### ISSUE TITLE
Excluding a negation in patterns

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#1002]
# Bug

There is this use case when you have analyzed a project with a lot of different file-endings like a common web-application using html, js and css and you want to exclude all building BUT the .js-buildings. This is still possible by excluding `*.html` and `*.css` but it should be possible by excluding `!*.js` 

## Expected Behavior

Excluding `!*.ts` in the web visualization for example should exclude everything BUT the ts-files.

## Actual Behavior

Nothing is excluded at all.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.49.0
- OS: MacOS
- Browser: Chrome

**Comment by BridgeAR** [comment]
This should be pretty straight forward to address by switching the globbing library.

**Comment by BridgeAR** [comment]
Even though `ignore` should support this.

**Comment by NearW** [comment]
> Even though `ignore` should support this.

Yes, ignore supports the negated patterns, but they're somehow not working in our code. I didn't check the code further, so I can't really tell if it's a tricky fix or not.
Nonetheless, having this feature enabled would be great though

**Comment by BridgeAR** [comment]
What about reworking our filtering in general? I think it would be nice to improve this by allowing notations that do not require to write globs. It's just a low priority though.

**Comment by BridgeAR** [comment]
This is already implemented :-)
