### ISSUE TITLE
Cut search / filter time into half

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1025]
# Bug / Feature

## Expected Behavior

__GIVEN__: A big cc.json is open in the visualizer

__WHEN__: Entering a search / filter string

__THEN__: It updates the map quickly

## Actual Behavior

It takes a significant amount of time to search. Most time is spend in few functions, e.g.,
`getNodesByGitignorePath`, `createTreemapNodes` and `buildMeshFromIntermediateVertexData`. A lot of time is spend on cloning as well and it's questionable if the cloning is indeed always necessary. It is likely, that the data structure could be cloned once and that it's all that is needed instead of multiple times. Some functions only have smaller optimization potential (~1%) while others provide significant potential e.g., ~10% of the total current time.

Reducing the total filter time by more than 1/3 is likely going to become more challenging, so try to focus on obvious gains. Often, the same structure is iterated upon multiple times doing one step at a time instead of iterating once and doing multiple steps on each iteration.

To have an actual starting point: use the current version and profile the performance with a big map (e.g., [Apache OpenOffice](https://maibornwolff.github.io/codecharta/showcase/aoo/)). That way you have a better comparison. It takes about 2.5 seconds to filter the file on my device (plus additional ~500 milliseconds that are spend after the actual search to render some color updates). The goal is to reduce that to 1.5 seconds or below. Split the work into small PRs that improve the performance of small areas per PR that all reference this issue and that outline how much gain the change provides.

This task has some overlap with #1024 and some gains will be noticeable for both, the loading and filtering time.

## Steps to Reproduce the Problem

1. Open the web visualizer
2. Load the AOO file
2. Start the browsers profiler
3. Search for e.g., `*cxx`.

## Specifications

- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.49.1
- OS: All
- Browser: Chromium

**Comment by ce-bo** [comment]
How is the current state of this issue? @BridgeAR

**Comment by BridgeAR** [comment]
`getNodesByGitignorePath` is already improved but the other two that I mentioned are not yet improved. Especially `buildMeshFromIntermediateVertexData` should be fixed.

**Comment by BridgeAR** [comment]
Closing as resolved. If there are new issues, let's address them in particular.
