### ISSUE TITLE
Right click to move the position causes node options to show

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1027]
# Bug

## Expected Behavior

GIVEN an open map

WHEN clicking with the right mouse button on parts of the map without releasing the cursor and moving the mouse

THEN the map moves without showing the node options of the node that was clicked upon

## Actual Behavior

GIVEN an open map

WHEN clicking with the right mouse button on parts of the map without releasing the cursor and moving the mouse

THEN the map moves but the node options of the node that was clicked upon are visible

## Steps to Reproduce the Problem

1. Open a map
1. Click with the right mouse button on a node without releasing the button
1. The node option is visible immediately

## Suggested fix

It should be enough to only trigger the node options in case the mouse button is _released_, not when clicked.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.49.1
- OS: All
- Browser: All

**Comment by NearW** [comment]
Regarding the suggested fix:
We should also check if the mouse moved since last right-clicked. If that's the case, we shouldn't show the context menu at all. To avoid bad user experience, we should also define a threshold in which the mouse has to move in order to not show the context menu. Something like 10 should be enough I guess.

**Comment by BridgeAR** [comment]
I very much agree. I missed to outline that in the suggestion! I would actually not accept any movement from the actual click to the release (but that might be to strict. In that case your suggestion would be the ideal way).
