### ISSUE TITLE
Node options not hiding on second mouse click

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1028]
# Bug

## Expected Behavior

GIVEN an open map

WHEN clicking with the right mouse button on parts of the map without and releasing the mouse button. Then clicking a second time with any mouse button e.g., outside of the map

THEN the former node options are hidden

## Actual Behavior

GIVEN an open map

WHEN clicking with the right mouse button on parts of the map without and releasing the mouse button. Then clicking a second time with any mouse button e.g., outside of the map

THEN the former node options are still visible

## Steps to Reproduce the Problem

1. Open a map
1. Click with the right mouse button on a node and releasing the button
1. Click with any mouse button outside of the map
1. The node option is still visible

## Suggested fix

It should be enough to hide any open node options as soon as there's a new mouse click.

## Specifications

- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.49.1
- OS: All
- Browser: All

**Comment by NearW** [comment]
> WHEN clicking with the right mouse button on parts of the map without and releasing the mouse button. Then clicking a second time with `any` mouse button e.g., outside of the map

I can only reproduce that when I try to hide the node context menu by clicking the `right` mouse button outside of the map.

**Comment by BridgeAR** [comment]
@NearW that is likely the case. The reason for that is probably that inside the map the mouse click would override the former event.

**Comment by ce-bo** [comment]
I think, this has been fixed already and the issue can be closed.

**Comment by BridgeAR** [comment]
This is indeed fixed :-) Thanks for the heads up!
