### ISSUE TITLE
House label not fully visible

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1029]
# Bug

## Expected Behavior

GIVEN an open map

THEN the tallest house label is fully visible, no matter from what angle

## Actual Behavior

GIVEN an open map

THEN the tallest house label is often not fully visible, depending from what angle

## Screenshots

![image](https://user-images.githubusercontent.com/8822573/86511509-437d9a00-bdfa-11ea-8e64-81547f5346b1.png)
![image](https://user-images.githubusercontent.com/8822573/86511537-7e7fcd80-bdfa-11ea-91ef-a112cd96d40d.png)
![image](https://user-images.githubusercontent.com/8822573/96259496-fa72df80-0fbd-11eb-9681-a8cbd195b0ab.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.49.1
- OS: Linux
- Browser: Chromium

**Comment by Richargh** [comment]
@RomanenkoVladimir I don't know if this is relevant for your task, but I researched algorithms to create non-overlapping labels in issue #334. I'm afraid it's not more than that though, it's just a possible starting point.

**Comment by RomanenkoVladimir** [comment]
Yeah we are trying with different startegies on how to improve labels right now, 
Thanks for the link, I see what we can do with it :)

**Comment by BridgeAR** [comment]
We have multiple other reports concerning the labels open. Thus, I am closing this. It is also already improved but there is still more work to do.
