### ISSUE TITLE
DetailPanel word wrap the shown path

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#103]
For large projects the path to a file might be very long. Too long for the detailPanel, when the Selected- and Hovered-field cover half the map. It also gets almost impossible to navigate through the map.
<img width="1440" alt="detailpanel long path covers map" src="https://user-images.githubusercontent.com/23529226/37893754-46e7a9f4-30dc-11e8-8570-810dcdabfe83.png">

**Comment by mrpatpat** [comment]
This is actually something that should be fixed. If you want to fix it, you can assign yourself to this issue.
