### ISSUE TITLE
Map gone / context lost

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1031]
# Bug

## Expected Behavior

GIVEN an open map

WHEN moving the cursor around hovering over the file percentage indicators

THEN the map should keep on being visible

## Actual Behavior

The map vanished / the context was lost and the following is printed in the browser's terminal: `THREE.WebGLRenderer: Context Lost.`

## Screenshots

![image](https://user-images.githubusercontent.com/8822573/86511829-fc44d880-bdfc-11ea-8d53-d65f0996536f.png)

## Steps to Reproduce the Problem

Unknown. I was not able to reproduce the error so far

## Specifications

- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.49.1
- OS: Ubuntu 20.04
- Browser: Chromium

**Comment by NearW** [comment]
I can't reproduce this either and I've never heard someone encountering this.

**Comment by BridgeAR** [comment]
It's likely difficult to trigger but we should keep an eye out for it.

**Comment by BridgeAR** [comment]
I am going to close this as it's not something that seems to be reproducible deterministically and it's only happening very rarely.

Please leave a note, if anyone else runs into this to reopen.
