### ISSUE TITLE
Loading the same map as currently loading does not reset the state

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1032]
# Bug

## Expected Behavior

GIVEN foobar.cc.json file is loaded

WHEN clicking on e.g., delta and then loading foobar.cc.json again

THEN the initial options should be set / all states should be reset to their defaults

## Actual Behavior

Nothing changes

## Specifications

- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.49.1
- OS: Ubuntu 20.04
- Browser: Chromium

**Comment by NearW** [comment]
accidentally linked the wrong issue in the PR
