### ISSUE TITLE
Convert colors only once / only when necessary (performance)

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1034]
Changing metrics triggers a huge amount of `convertHexToNumber` calls. In a big map this can easily add up to a significant time that is spend in that function. For the Apachge Open Office map it takes roughly 400 milliseconds on my device just in that function.

Ideally, the colors are precomputed and are only visualized for the user while clicking on a node / hovering above it, if necessary.

**Comment by NearW** [comment]
There are a few things I want to note here and that should be considered when implementing this:
- What's actually being called a lot is `colorToVector3()` which is necessary for every vertex in the scene
- There are 4 colors, green, yellow, red and grey (folders)
- When hovering over buildings their lightness changes resulting in a new color to be applied. Also the lightness of the building hovered is increased. This results in 3x4 = 12 possible colors for a building
- When hovering over buildings with presentation mode, the lightness is can be decreased in 5 ways based on distance. This results 7*4 colors => 28 that need to be tracked.
