### ISSUE TITLE
Indicate metric next to the number of the highest building

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1035]
# Feature request

## Description

As a regular user, I want to know what metric is highlighted on the tallest building so that I know what the number actually stands for.

## Acceptance criteria

- Add a second smaller line to the description of the tallest building that indicates what metric the number actually stands for

![image](https://user-images.githubusercontent.com/8822573/86512287-1aacd300-be01-11ea-8303-713f9d2459b1.png)

**Comment by RomanenkoVladimir** [comment]
@BridgeAR what do you think of adding the metric behind the number:
e.g. configure.in: 16 mcc

this seems most intuitive to me, as its an established notation for heights and similar items

**Comment by RomanenkoVladimir** [comment]
Or did you imagine one extra label on the heighest building only, like:

configure.in: 16
Metric: mcc

**Comment by BridgeAR** [comment]
I thought about using a separate line:

```
configure.in
16 mcc
```

I do in fact also think about removing this part alltogether, since it's taking up space that could be used to visualize other file names instead. But I want to give a separate line a go first.

**Comment by RomanenkoVladimir** [comment]
![keyword_EoL_highest](https://user-images.githubusercontent.com/25777197/94919674-25850b80-04b5-11eb-92e6-824dca947ddc.PNG)
![Keyword_new_line](https://user-images.githubusercontent.com/25777197/94919689-2ae25600-04b5-11eb-8c89-66c29bf18558.PNG)

It looks kinda bad in my opinion, if we only show it for the highest building, or what do you say?

**Comment by JaiJoPa** [comment]
- Add Checkboxes to toggle name and metric display
- Add another Checkbox to show all labels
- Improve design of labels

new Issue: 
- Show only labels of buildings according to a chosen color or only labels of buildings to a value

**Comment by ce-bo** [comment]
@JaiJoPa we cover your "new Issue" point on this new issue: #1347

**Comment by ce-bo** [comment]
> * Add another Checkbox to show all labels
>

This will implicitly be possible with #1347
