### ISSUE TITLE
Option not hidden when clicking on a node or other option

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1036]
# Bug

## Expected Behavior

GIVEN e.g., a metric option is open

WHEN clicking on a node on the map or on another option

THEN the metric option is collapsed

## Actual Behavior

The metric option is still visible

## Screenshots

![image](https://user-images.githubusercontent.com/8822573/86512237-abcf7a00-be00-11ea-9039-e51b19a0e605.png)
![image](https://user-images.githubusercontent.com/8822573/86512344-9e66bf80-be01-11ea-9556-40354a3aefc3.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.49.1
- OS: Ubuntu 20.04
- Browser: Chromium

**Comment by NearW** [comment]
![metric visible](https://user-images.githubusercontent.com/12533626/86521018-874cbf80-be4b-11ea-9efa-563ff19d8056.gif)

Works for me.

**Comment by BridgeAR** [comment]
@NearW what I meant is also visible in your example: the expanded mcc part should be hidden when clicking somewhere else.

**Comment by NearW** [comment]
@BridgeAR Oh, you mean the color-range-slider and the two checkboxes?
For now this was intentional design, but you're right. I don't see a reason for those to be open.
