### ISSUE TITLE
Responsive design: metrics not visible on smaller width

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1037]
# Bug

## Expected Behavior

GIVEN a map opened with the visualizer

WHEN minify the window to have a smaller screen / in case the width is small in general

THEN the metrics are all visible or better: it's possible to click to the other metrics

## Actual Behavior

The metrics are invisible and it's impossible to get there / know about the missing ones

## Screenshots

![image](https://user-images.githubusercontent.com/8822573/86520703-9fbadb00-be47-11ea-9408-3011d200de36.png)

## Specifications

- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.49.1
- OS: Ubuntu 20.04
- Browser: Chromium

**Comment by NearW** [comment]
Uh, responsive design... The last time we spoke about this with our previous PO we decided to not support screen resolutions less than 1440x900..? I'm not 100% sure at this point.

**Comment by BridgeAR** [comment]
Most parts seem to be responsive. This seems like a minor part that is missing and I would still fix that with a low priority.

**Comment by BridgeAR** [comment]
Text from #1423:

> * CodeCharta visualization is responsive, scaling to the screen size and behaving as expected on smaller screens.
> * However, the top bar features set heights and widths making it difficult to use on smaller windows, with some feature like edge settings being unreachable.
> * The size for components like the blacklist or the flattenend list might also be an issue in such cases.

> Making the website responsive for smaller devices, e.g. Pads and Phones might improve user experience and increase usability.

**Comment by BridgeAR** [comment]
This should also be fixed while being at it:

![image](https://user-images.githubusercontent.com/8822573/103100616-b3374980-4613-11eb-8721-d855a180a3f6.png)

The icon has some fixed space to the next part.
