### ISSUE TITLE
SettingsPanel labels

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#104]
Inside the settingsPanel the labels are too low and inside the dropdown-menus. 

<img width="415" alt="bildschirmfoto 2018-03-26 um 11 08 32" src="https://user-images.githubusercontent.com/23529226/37897540-ab9248fa-30e6-11e8-9ce1-9b0f5bc84865.png">

**Comment by mrpatpat** [comment]
This is indeed a visual bug but we won't fix it directly since we already fixed it on [this branch](https://github.com/MaibornWolff/codecharta/tree/frontend_refactoring).
