### ISSUE TITLE
Sorting not working

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1040]
# Bug

## Expected Behavior

GIVEN the search field is open

WHEN clicking on the sorting button

THEN the order changes according to the chosen order

## Actual Behavior

The behavior does not change

## Screenshots

![image](https://user-images.githubusercontent.com/8822573/86521832-fe875100-be55-11ea-9997-95dd6e27d1a7.png)
![image](https://user-images.githubusercontent.com/8822573/86521835-05ae5f00-be56-11ea-850e-472d3698f6a5.png)

## Specifications

- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.49.1
- OS: Ubuntu 20.04
- Browser: Chromium

**Comment by NearW** [comment]
Developer Note: It does sort, but you need to collapse and open the folder again in order to trigger a re-rendering.
