### ISSUE TITLE
Get sonarcloud quality gate to green

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1041]
This is meant as tracking issue to make sure the quality gate is green for the visualization part.

If I'm not mistaken there's mostly not a lot to do to fix the reported issues. This could be split into multiple small PRs that address this over time. It's good for filling small time buckets.

Refs: https://sonarcloud.io/dashboard?id=de.maibornwolff.codecharta%3Avisualization

**Comment by NearW** [comment]
note that both visualization and analysis had their last update on february 21st. We should adress this again once we get our results published to sonar again.

**Comment by RomanenkoVladimir** [comment]
I adressed the issue by sonar frontendside in a previous issue, although new ones might have been introduced in the meantime, the ones from february the 21st should be solved on master.

**Comment by BridgeAR** [comment]
Fixed by #1125
