### ISSUE TITLE
Use better cursor indicators for move / rotate

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1042]
# Feature request

## Description

As a user, I want to know what buttons trigger what behavior. Therefore it's important to implement cursor icons that indicate moves and rotating.

## Acceptance criteria

- When double clicking on the map with the left button, the [grabbing](https://www.w3schools.com/cssref/playit.asp?filename=playcss_cursor&preval=grabbing) icon should be visible to indicate it's possible to now rotate the map
- When clicking on the map with the right button, the [move](https://www.w3schools.com/cssref/playit.asp?filename=playcss_cursor&preval=move) icon should be visible to indicate it's possible to move the map
- When hovering over the minimap at the top right corner, the [pointer](https://www.w3schools.com/cssref/playit.asp?filename=playcss_cursor&preval=pointer) icon should be visible to indicate it's possible to click on the minimap
- The implementation is agnostic to switching the buttons with an potential future option

**Comment by NearW** [comment]
I don't think that rotating the map with double-clicking is the actual use case. Holding down left-mouse-button is enough already.

I'd change the goals:
- When clicking on the map with the left button, the grabbing icon should be visible to indicate it's possible to now rotate the map

Also: Why do we show the pointer cursor on the viewcube, but we don't show it on the map itself? Buildings and folders can be clicked. I'd expect the cursor to be a pointer when hovering over something.

**Comment by BridgeAR** [comment]
I believe we are actually aligned. If you click once with the left button and hold the button, you won't be able to move anything around (at least that's what I would expect - I mostly just use a touchpad and I would have to check again with a mouse but I expect the same to be true). If you click twice with the left button and hold the second click, it's possible to move the map.

> Why do we show the pointer cursor on the viewcube, but we don't show it on the map itself?

I wanted to have some initial cursor indicators and your suggestion sounds good as another addition.

**Comment by NearW** [comment]
@BridgeAR You can rotate the map by holding the left mouse button. Double clicking is not required. Double clicking is actually only used for opening the link of a building.
