### ISSUE TITLE
Different root for git log and sonar import

### ISSUE THREAD

**Issue by mrpatpat** [MaibornWolff/codecharta#109]
Sonar Importer and Git Log Parser produced a different root for the same project. 
TODO: provide example data

**Comment by ukinimod** [comment]
I do not understand this point. What does root mean? 

GitLogParser has the folder structure that is given in the git log. SonarImporter has the folder structure of SonarQube. If SonarQube is configured differently e.g. if it runs the analysis not in the root path of the git repository but a subpath then naturally the folder structure will defer.
The idea behind the MergeFilter in (beta) --leaf mode was to compensate for this difference by taking the best match from the end of the path.

**Comment by mrpatpat** [comment]
Thank you for your advice. 
--leaf mode should solve this issue. After taking your explanation why this happens into account I wouldn't call it a bug anymore. It's just how it has to work. 
I won't provide the sample data anymore since --leaf does exactly the thing needed.
