### ISSUE TITLE
Sort order in tree-view not applied correctly

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#1092]
# Bug

## Expected Behavior

When I open the tree-view, then I expect the folders and files to be sorted correctly by name. `ab.ts` should come before `Bc.ts`.

## Actual Behavior

When I open the tree-view, then the folders and files are not sorted correctly by name. `Bc.ts` comes before `ab.ts`.

## Screenshots

https://user-images.githubusercontent.com/23529226/87176436-64525d80-c2da-11ea-9bce-276a51dfeaa6.jpeg

## Steps to Reproduce the Problem
1. Open tree-view in demo

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.50.0
- OS: Mac and Windows 10
- Browser: Chrome

**Comment by BridgeAR** [comment]
To improve this even further: sorting should ideally sort numbers naturally and accent marks take are taken into account. This is easy to implement by using `localeCompare()`: `stringArray.sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))`.

E.g.:

```js
[
  '1',   '2',   '3',
  '10',  '11',  'abb',
  'abc', 'abC', 'Abc',
  'ábc', 'abd', 'bbc',
  'Bbc'
]
```

**Comment by RomanenkoVladimir** [comment]
@BridgeAR PTAL

I think you already implemented that change: current sorting uses custom comparator functions and not sort()
numerical sorting is done via substraction
alphabetical via a.name > b.name, I think this is the correct functionality?
