### ISSUE TITLE
FileChooser should only show .json files

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#1094]
# Feature request

## Description

As a user, I want to only want to be aple to open potential valid cc.jsons so that I don't accidentially select wrong files.

This also adds help to identify potential files in a folder, since all other are greyed out.

## Assumptions & Exclusions
- The user can only select .json files

## Development notes (optional Task Breakdown)
Please check out the accept attribute of input type file: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file

**Comment by RomanenkoVladimir** [comment]
This is one line of code, now that 'accept' is supported by all browsers, so I quickly added it.
However how would you test for that feature?

**Comment by NearW** [comment]
@RomanenkoVladimir Please take a look at the [e2e test](https://github.com/MaibornWolff/codecharta/pull/1083/files#diff-0b8f8eb70f729287dae2caa9aa3d3e5c) and the [page object](https://github.com/MaibornWolff/codecharta/pull/1083/files#diff-fd27f70ba6ca0a76f8ed06f5f8b35c6a) file.

You can simply add another e2e test that tries to select a non-json file. I don't know though if the application throws an error that we can catch then.
