### ISSUE TITLE
Number of incoming and outgoing edges not visible

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#1095]
# Bug

## Expected Behavior

When I hover over a building, then I expect the number of incoming and outgoing edges to be visible next to the edge metric, devided by a slash.

When I select a building, then I expect the number of incoming and outgoing edges to be visible next to the edge metric in the side-bar, devided by a slash.

## Actual Behavior

Bot are not visible.

## Screenshots

![image](https://user-images.githubusercontent.com/12533626/87253690-75879f80-c47d-11ea-8496-578640302219.png)

## Steps to Reproduce the Problem
1. Hover over or select a building

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.50.0
- OS: Windows
- Browser: Chrome

**Comment by kulasekp** [comment]
Same for me. 
I have found the temporary solution:
* link created to CC web app contains two "file" parameters: first one for merged sonar & git metrics, second for git metrics
* once CC app is opened use dropdown to switch to git metrics, then go back to sonar&git metrics

coupling numbers should be displayed from now on.
