### ISSUE TITLE
Flattening buildings broken

### ISSUE THREAD

**Issue by JaiJoPa** [MaibornWolff/codecharta#1098]
# Bug

## Expected Behavior

WHEN I flat a building

THEN I expect it to be flat

## Actual Behavior
The building is not flat, but it appears as flat in searchpanel

## Screenshots

![not_flattening](https://user-images.githubusercontent.com/50145538/87295442-7a903180-c505-11ea-8476-4b1814f1fd44.gif)

## Steps to Reproduce the Problem
1. Open Map
1. Flat a building

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes 
- CodeCharta Version: 1.50.0
- OS: Windows
- Browser: Chrome, Mozilla Firefox

**Comment by NearW** [comment]
This also happens when exlcuding something. Seems like it doesn't happen on larger buildings?
We really should look into this.

#vote high priority
