### ISSUE TITLE
Multiple cc.json in one view

### ISSUE THREAD

**Issue by mrpatpat** [MaibornWolff/codecharta#110]
A filter which aggregates multiple cc.json files in order to show them in a single view. 

e.g. combining a.json, b.json and c.json results in aggregate.json with a root node which has the children a.json, b.json and c.json with all the related data.

**Comment by ukinimod** [comment]
how does this compare to
ccsh merge --add-missing a.json, b.json, c.json
?

Have you tried this?

**Comment by mrpatpat** [comment]
using --add-missing adds missing nodes to the result. The suggested aggregation should make all given maps (a, b, c) siblings under the same parent (root of the new resulting map)

## Simplified Example (not the official json notation, but should be readable)

### a.json

`root
- childA1
- childA2
- ...`

### b.json

`root
- childB1
- childB2
- ...`

### a.json and b.json aggregated

```
root 
- childA       <--- this is the old root of a.json
-- childA1
-- childA2
-- ...
- childB       <--- this is the old root of b.json
-- childB1
-- childB2
-- ...
- ...
`

**Comment by ukinimod** [comment]
Hmm, I understand. That‘s something different.

Maybe it could be a work around in most cases, thought. If this is not such a imminent issue.

I am suggesting a workaround, as I think there is a whole concept lying underneath this request. It seems to be necessary to modify the path structure in one or multiple json by
a) merging multiple jsons 
b) filtering 
c) deleting subtrees
d) pushing down subtrees

I was fightinf with this while implementing the merge filter (especially with add-missing and lead). I‘m still thinking there should be a better way to do it than as I implementes it. But I can‘t think of none.

I was hoping you would come up with a clever idea that wouldn‘t add another feature flag on MergeFilter or such. But on the other side maybe that‘s the best solution at the moment.

**Comment by FernandoES** [comment]
- Side-by-side means something like in the picture or both in the same city as they were part of the same program?
![double](https://user-images.githubusercontent.com/14861502/39253803-04cede0e-48a9-11e8-8fea-497f4f1b7f0b.jpg)

 - In the same city option I have no other idea that adding a new feature flag on mergeFilter, but someone else can come up with one :) .
- the picture option it wouldn't require a change in the json file but a change in the website canvas. Btw this would make the loading slower that previously, we should take it into account.

**Comment by Richargh** [comment]
The idea is same city, part of the same program. Then you can load multiple cc.json files and display them at the same time. A concrete usecase requries four cc.json files but more is possible.

In the Treeview you can then toggle on or off the cc.json right under the root node.
