### ISSUE TITLE
Tokeiimporter throws Error root.asJsonObject.get(TOP_LEVEL_OBJECT) must not be null

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#1103]
# Bug

## Expected Behavior

WHEN running `tokei . --output json > tokei_results.json`
AND afterwards running `ccsh tokeiimporter -o tokei_results.cc.json tokei_results.json`
THEN no error occurs

## Actual Behavior

WHEN running `tokei . --output json > tokei_results.json`
AND afterwards running `ccsh tokeiimporter -o tokei_results.cc.json tokei_results.json`
THEN an error occurs: `root.asJsonObject.get(TOP_LEVEL_OBJECT) must not be null`

```
% tokei . --output json > tokei_results.json
% ccsh tokeiimporter -o tokei.cc.json tokei_results.json
 Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (de.maibornwolff.codecharta.importer.tokeiimporter.TokeiImporter@7ce6a65d): java.lang.IllegalStateException: root.asJsonObject.get(TOP_LEVEL_OBJECT) must not be null
	at picocli.CommandLine.execute(CommandLine.java:1016)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunAll.handleParseResult(CommandLine.java:1229)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1305)
	at picocli.CommandLine.parseWithHandler(CommandLine.java:1258)
	at de.maibornwolff.codecharta.tools.ccsh.Ccsh$Companion.main(Ccsh.kt:66)
	at de.maibornwolff.codecharta.tools.ccsh.Ccsh.main(Ccsh.kt)
Caused by: java.lang.IllegalStateException: root.asJsonObject.get(TOP_LEVEL_OBJECT) must not be null
	at de.maibornwolff.codecharta.importer.tokeiimporter.TokeiImporter$call$1.invokeSuspend(TokeiImporter.kt:73)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

## Example file

[tokei_results.json.zip](https://github.com/MaibornWolff/codecharta/files/4924389/tokei_results.json.zip)

## Steps to Reproduce the Problem
1. Install `tokei` according to the [README](https://github.com/MaibornWolff/codecharta/blob/master/analysis/import/TokeiImporter/README.md)
1. Run `tokei . --output json > tokei_results.json`
1. Run `ccsh tokeiimporter -o tokei.cc.json tokei_results.json`

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.50.0
- OS: macOS
- Shell: zsh

**Comment by RomanenkoVladimir** [comment]
Could you append the used tokei output?
The tokei Importer works fine on my machine, although it might be a macOS issue.

**Comment by alschmut** [comment]
The tokei file is already appended as a zip file above

**Comment by RomanenkoVladimir** [comment]
Ok I found the error, previous tokei files imported use: 
{"inner": {
    "Batch": {...}
}}
as the structure, this inner tag is also checked for as the entry point in our code.
The upload file is missing the entry point, starting with 
{"Bash":{
}}

The current implementation needs "inner" to construct the root.
To me this seems like a generation error on the tokei side, the file as Bash, Batch, Glsl.. lack an overarching encapsulation.
@alschmut you used CodeCharta to generate the tokei file right?

**Comment by alschmut** [comment]
@RomanenkoVladimir okey, well I was installing `tokei` with `brew install tokei` like mentioned on their projects [README.md](https://github.com/XAMPPRocky/tokei#package-managers) and then using it like mentioned in our codecharta Tokeiimporter [README.md](https://github.com/MaibornWolff/codecharta/tree/master/analysis/import/TokeiImporter).

I think I don't get your question. Tokei is another tool that exports a json file (the one above). And that json file is converted into a `cc.json` with the codeCharta `tokeiimporter`.

So it seems tokei updated their interface/output file structure. That's maybe worth thinking of adapting the CC `tokeiimporter`.

**Comment by RomanenkoVladimir** [comment]
Concerning the question, I just asked what project was analysed with tokei, as i wanted to try generating it myself.
I think Lukas and I were the last to use the Importer option a few weeks back and the generated files adhered to the structure, so I was wondering what could have caused it.

**Comment by alschmut** [comment]
yes, I was analysing the codeCharta project

**Comment by alschmut** [comment]
@RomanenkoVladimir I have installed the latest Tokei version 12.0.4 and I just checked, [Tokei 12.0.0](https://github.com/XAMPPRocky/tokei/releases/tag/v12.0.0) introduced some breaking changes to their format.

**Comment by RomanenkoVladimir** [comment]
Yeah just checked it as well, the change "The JSON Output and format of Languages has changed." is exaclty what breaks our current Importer.

**Comment by RomanenkoVladimir** [comment]
Should we file this as a feature request then?
Or change the Issue to Update the Tokei Importer to be able to parse tokei files generate with the newer 12.0 version.

**Comment by BridgeAR** [comment]
Ideally we are able to identify the version and parse both.

**Comment by alschmut** [comment]
Are you planning to fix that bug? I would really like to use this importer again, as it's the easiest way to get some simple metrics for non-java and non-sonar projects.

**Comment by NearW** [comment]
@alschmut Priorty has been set to [urgent](https://github.com/MaibornWolff/codecharta/labels/priority%3Aurgent). This will be fixed for our release on friday. :)
