### ISSUE TITLE
Assign custom colors to color range

### ISSUE THREAD

**Issue by mrpatpat** [MaibornWolff/codecharta#111]
## Description

Assigning custom colors to the color range spectrum would allow users to visualize edge cases where e.g. both edges can have the same color. 

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

* [ ] **All** requirements mentioned in the issue are implemented
* [ ] Does match the Code of Conduct and the Contribution file 
* [ ] Task has its own **GitHub issue** (something it is solving)
  * [ ] Issue number is **included in the commit messages** for traceability
* [ ] **Update the README.md** with any changes/additions made
* [ ] **Update the CHANGELOG.md** with any changes/additions made
* [ ] **Enough test coverage to ensure that uncovered changes do not break functionality**
* [ ] **All tests pass**    
* [ ] **Descriptive pull request text**, answering:
  + What problem/issue are you fixing?
  + What does this PR implement and how? 
* [ ] **Assign your PR to someone** for a code review
  + This person _will be contacted **first**_ if a bug is introduced into `master`
* [ ] **Manual testing** did not fail

**Comment by alschmut** [comment]
For the frontend view it were an idea to create a variable amount of colour-ranges like the following abstract example. I am not sure if or how we can adapt these multiple values (and maybe even the colours) to a single slider.

`<input startRangeNumber> <input pickColour> <button addNewRow>
<input startRangeNumber> <input pickColour > <button addNewRow>
...`

Two colourpicker examples are here:
A separated and rich colourpicker, fit to the AngularJS Material: https://github.com/brianpkelley/md-color-picker
A small and simple dropdown colourpicker: http://www.bestjquery.com/?xs5o4JUu

**Comment by alschmut** [comment]
Yes, I agree, splitting this in multiple issues is better. But to mention: the [NoUiSlider](https://refreshless.com/nouislider/slider-values/#section-handles-multiple) might work, but is not really usability-friendly and ugly as well.
