### ISSUE TITLE
Renew screenshots inside the CodeCharta project

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#113]
There are some old screenshots shown in the project to demonstrate the application. But we might want to take a nice-looking project. Screenshots are for example at:
https://github.com/MaibornWolff/codecharta/README.md
https://maibornwolff.github.io/codecharta/

Is it allowed, possible or desired to renew the images inside the online articles about CodeCharta as well?
https://www.maibornwolff.de/codecharta
https://www.maibornwolff.de/blog/code-visualisierung-mit-codecharta

**Comment by mrpatpat** [comment]
I think [https://www.maibornwolff.de/codecharta](https://www.maibornwolff.de/codecharta) should be updated since it is a static page. 
The one in the blog should not be updated since it is associated to a specific date and therefore to a specific version of CC.

**Comment by mrpatpat** [comment]
We could use a script with puppeteer (used in our e2e tests) to automatically generate a screenshot while building our docs. What do you think ?

**Comment by alschmut** [comment]
@mrpatpat That's actually a very nice idea!

**Comment by Richargh** [comment]
So far I have seen the screenshot folder updated a couple of times by hand. It might also be beneficial to do so by hand, because it allows you to show off what you find interesting.
