### ISSUE TITLE
Metric dropdown is closed when clicking on metric searchfield

### ISSUE THREAD

**Issue by JaiJoPa** [MaibornWolff/codecharta#1147]
# Bug

## Expected Behavior

When I click on the searchfield of the metric drop down 

Then the dropdown should be still visible for the search

## Actual Behavior

When I click on the searchfield of the metric dropdown

Then the dropdown is closed  

## Note
This bug does not exist when using Mozilla Firefox

## Screenshots
![metricSearchBug](https://user-images.githubusercontent.com/50145538/89636751-655eb680-d8a9-11ea-8ecc-52c30f381405.gif)

## Steps to Reproduce the Problem
1. Open a metric dropdown
2. Click on the searchfield

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.51.0
- OS: Windows
- Browser: Chrome, Edge

**Comment by JaiJoPa** [comment]
Closing this issue, because it is not existing anymore in CodeCharta Version 1.56.0.

**Comment by BridgeAR** [comment]
We might want to add a regression test?
