### ISSUE TITLE
List of project issues in visualization

### ISSUE THREAD

**Issue by mrpatpat** [MaibornWolff/codecharta#115]
# Feature request

## Description

Adding a list of issues into to the visualization would increase the incentive to look into CodeCharta.
An issue could be a sonarqube issue but it is not limited to them e.g. certain metrics can have limits which trigger an issue in the list. Hovering issues in the list should mark the correct buildings in the 3D scene.

**Comment by ChristianHuehn** [comment]
https://github.com/MaibornWolff/codecharta/issues/608 will research this first if needed and create an issue for it
