### ISSUE TITLE
Refactor beforeEach setup of angular tests 

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#1154]
# Description

Right now we devide our setup for angular tests like this 
```ts
beforeEach(() => {
	restartSystem()
	rebuildService()
	withMockedEventMethods($rootScope)
})
```

- restartSystem: initiate module, get services we need to inject, clone test data, setup initial state
- rebuildService / rebuildController: use injected service to call the constructor of the test objet
- withMocked (optional): Mock services 

As you can tell, we do a lot of things in `restartSystem`. Let's split this up.
- injectServices: initiate module, get services we need to inject
- buildService / buildController: use injected service to call the constructor of the test object
- setupTestData: clones test data from the data mocks
- setupState: resets the state to a given state
- withMocked... (optional): Mock services 

Please update the plop-templates as well.

**Comment by BridgeAR** [comment]
Are all of these steps always necessary? If yes, I'd just call all of these in a single preparation function. If not, let's make sure to only include necessary steps.

**Comment by NearW** [comment]
All of those should be necessary, except for the mocking which is optional. Well, the single preparation function is the `beforeEach`-block basically. Currently we just do way too much stuff in `restartSystem` and in a large test suite this can be confusing. I'd rather have dedicated functions to for each setup and call them in the beforeEach-block.

**Comment by shaman-apprentice** [comment]
In #2318 we are adopting best practise of this [Testing library](https://testing-library.com/docs/angular-testing-library/intro/), which will remove this flaw. So I think we can already close this as obsolete. @ce-bo @BridgeAR ?

**Comment by BridgeAR** [comment]
Sounds good to me.
