### ISSUE TITLE
Remove one-line-functions from plop-template and update files

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#1157]
# Description

We tend to write one-line functions instead inlining them. Take a look at this codeblock from a state-service:

```ts
public onStoreChanged(actionType: string) {
	if (isActionOfType(actionType, AreaMetricActions)) {
		this.notify(this.select())
	}
}

private select() {
	return this.storeService.getState().dynamicSettings.areaMetric
}

private notify(newState: string) {
	this.$rootScope.$broadcast(AreaMetricService.AREA_METRIC_CHANGED_EVENT, { areaMetric: newState })
}
```

The selection and the event broadcast are obvious and understandable without the wrapper. If a single line of code gets so complicated, that it might need a comment, either assign a variable with a understandable name or move it to a function with a name, that can describe what it does. This can be useful with some tricky if-conditions.

This specific block of code could be inlined to:

```ts
public onStoreChanged(actionType: string) {
	if (isActionOfType(actionType, AreaMetricActions)) {
		const { areaMetric } = this.storeService.getState().dynamicSettings
		this.$rootScope.$broadcast(AreaMetricService.AREA_METRIC_CHANGED_EVENT, { areaMetric })
	}
}
```

- [ ] Update all state-services using this pattern
- [ ] Update the template to avoid this anti-pattern from happening
- [ ] Check if there is more autogenerated one-line-functions like this and fix them

**Comment by shaman-apprentice** [comment]
Within #2318 the custom angular connection will be replaced through selectors, making all those services obsolete. Plop will be obsolete as well and in the long run be replaced through #2289. So I think we can close this issue in favour of #2289, can we? @ce-bo  @BridgeAR?

**Comment by BridgeAR** [comment]
@shaman-apprentice I guess this was meant a generic suggestion that does not apply to only the example above. I personally see this issue as a "refactor the codebase for clarity and understandability".

**Comment by BridgeAR** [comment]
I just looked at this again and I agree with your assessment @shaman-apprentice. Closing as obsolete due to not using plop anymore.
