### ISSUE TITLE
Changelog: Add missing sub-categories

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#1165]
# Description

The [CHANGELOG](https://github.com/MaibornWolff/codecharta/blob/main/CHANGELOG.md) does not include all sub-categories. We're missing Documentation and Breaking Changes.

```md
## [unreleased]

### Breaking Change ❌

### Added 🚀

### Changed

### Removed 🗑

### Fixed 🐞

### Documentation 🔎

### Chore 👨‍💻 👩‍💻
```

Keep in mind to update the release script, which actually updates this log and creates the empty template on top.

Do we want to remove Chore btw?

**Comment by BridgeAR** [comment]
I would like to rework the changelog by only including sections that actually contain entries instead of including everything each time.

**Comment by NearW** [comment]
> I would like to rework the changelog by only including sections that actually contain entries instead of including everything each time.

We already do that when we create the release posts. The empty sections are removed there, but we don't do that with the changelog yet. I'd say, we add the full template and once we release, we remove all empty sections.

**Comment by BridgeAR** [comment]
If there's a breaking change, we should definitely mark that prominently. Documentation only changes are likely either "changed" or "chore" depending on the type of documentation. I do not feel like it's important enough to change the structure at the moment. As such, I am closing this as won't fix.
