### ISSUE TITLE
Focus isolated map parts 

### ISSUE THREAD

**Issue by mrpatpat** [MaibornWolff/codecharta#118]
# Feature request

## Description

Clicking on a file or folder name in the treeview isolates the selected part in the 3D scene. Small isolated parts can be hard to find since you have to zoom into them without seeing them. 
It would be an enhancement if isolating a part would automatically zoom into the isolated part.

**Comment by alschmut** [comment]
Maybe it were useful to open a folder with its subfolders and files in a new browser-tab to only see this part of the project.

**Comment by mrpatpat** [comment]
Generally speaking tabs could become a part of CodeCharta e.g. for multiple loaded maps. The challenge will be to not use browser tabs since we publish CC for different environments (browser, native desktop). 
Another issue could be the loss of communication between tabs (although I think there will be some solution to this which will require some technical implementation).
For this particular request I do not think tabbing is the right solution because opening a new tab does break context from the user perspective. Tabs always feel like "something new and separate".
What do you think ?

**Comment by alschmut** [comment]
Self implemented tabs in CC is definitely a good idea and I fully understand the disadvantage of browser tabs. I just thought it might be easier to open a part of the map as a new file, where the camera focuses on the map by default.
