### ISSUE TITLE
File types not detected properly

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1188]
# Bug

## Expected Behavior

GIVEN a map consisting out of multiple programming languages, e.g. 50% `java` and 50% `javascript`

THEN the programming language indicator should be 50/50.

## Actual Behavior

The language indicator is far off and shows e.g., 95% javascript.

## Steps to Reproduce the Problem

Let's chat about it.

## Notes

I am if the `cc.json` already contains the percentages or if the frontend determines that from the file ending. Ideally it would be available in the `cc.json`, since it's possible to maybe even check the files. There are tools that determine the percentages properly and we should check what is off.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: v1.54.0
- OS: Ubuntu 20.04
- Browser: Chromium

**Comment by NearW** [comment]
That is only true, when you select unary as the distributionbar-metric. The distribution is based on a metric. I can't see what metric was selected, but it might be, that this metric is only available in java files?

**Comment by BridgeAR** [comment]
Good point. I was not aware that we handle our indicator like that 😆 It does indeed show the expected behavior when choosing lines of code. This behavior does seem very surprising though, that it does not just use the lines of code but also other metrics. I can not think of a use case for the file type indicator that uses other metrics than `loc`.

The default metric is bugged with that cc.json:

![image](https://user-images.githubusercontent.com/8822573/91366680-b7d62780-e804-11ea-8ea5-1d8b504fccf0.png)

I wonder what would be best to handle cases like these and what the actual bug is about.

**Comment by NearW** [comment]
Interesting. I've never seen a metric without a name in there before.
Can you .zip the cc.json and post it here for further investigation?

**Comment by ce-bo** [comment]
Bugfix needed: Please skip empty metrics in the select-box.

**Comment by ce-bo** [comment]
Improvements:
- Look for rloc, if it is present, choose it as the default metric.
- If no default metric could be found, choose the unary metric, so that the amount of files per programming language is visible.
