### ISSUE TITLE
Screenshot button

### ISSUE THREAD

**Issue by mrpatpat** [MaibornWolff/codecharta#120]
# Feature request

## Description

CodeCharta should offer a screenshot button which shows the scene (buildings), legend, logo (CC and MaibornWolff). The generated screenshots should always have the same size to achieve comparability.

**Comment by FernandoES** [comment]
Nice, I'll merge it

**Comment by Richargh** [comment]
To clean up the Inbox, we'll close this feature. We might add it again in the future, though.
