### ISSUE TITLE
Input-field in colourSettings doesn't work as expected

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#121]
# Bug

## Expected Behavior
When I change the numbers inside the input-fields of the colorSettingsPanel:
- the rangeSlider adapts to that value
- the map is supposed to adapt to the new colors as well

When lowering the "To"-number below the "From"-number:
- the "From"-number should lower as well (just like the slider does).

When raising the "From"-number above the "To"-number:
- the "To"-number should raise as well (just like the slider does).

## Actual Behavior
When I change the numbers inside the input-fields of the colorSettingsPanel:
- the rangeSlider adapts to that value
- the map DOES NOT adapt to the new colors

When lowering the "To"-number below the "From"-number:
- the "From"-number DOES NOT lower as well and just keeps as it is

When raising the "From"-number above the "To"-number:
- the "To"-number DOES NOT raise as well and just keeps as it is

### Screenshots

<img width="393" alt="bildschirmfoto 2018-04-05 um 16 16 12" src="https://user-images.githubusercontent.com/23529226/38371604-2aa5fe76-38ed-11e8-81a5-df806e7ad703.png">

## Steps to Reproduce the Problem

  1. checkout master or refactoring_frontend branch
  2. open the settingsPanel
  3. open the colorSettingsPanel
  4. raise or lower the input-fields

## Specifications

  - Version: 1.10.0
  - Branch: master and frontend_refactoring
  - Platform: ?
  - Subsystem: ?
  - Browser: Chrome and Safari

**Comment by FernandoES** [comment]
Solution developed in branch colorSettingCorrecture

**Comment by FernandoES** [comment]
Solution in Pull Request #132, please have a look and approve/reject modify it
