### ISSUE TITLE
SettingsPanels take 5 - 15 seconds to open in native app

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#123]
# Bug

## Expected Behavior
When clicking the panel-header of one of the panels inside the settingsPanel, they should toggle with a transformation of approximately 0.5 seconds.

## Actual Behavior
When clicking the panel-header of one of the panels inside the settingsPanel, the transformation takes way too long (around 5 - 15 seconds) to open/close.

### Screenshots

<img width="398" alt="bildschirmfoto 2018-04-11 um 10 30 21" src="https://user-images.githubusercontent.com/23529226/38605955-0dac1882-3d75-11e8-9299-2422728fea40.png">

## Steps to Reproduce the Problem

  1. `npm run start` opens the native app
  2. open the settingsPanel by clicking the lower left actionButton
  3. click on any Panel-Header to open the Panel-content

## Specifications

  - Version: 1.11.1
  - Platform: macOS 10.13.3
  - Subsystem: ?
  - Browser: Native App

**Comment by mrpatpat** [comment]
I can confirm this bug when running the visualization from the global installation `npm install -g codecharta-visualization && codecharta-visualization`
However running it with `npm run start` works as expected. After that I ran `npm link` in my visualization project (This basically symlinks your working directory npm package to your global packages, so you can run your dev version globally) and the problem reoccured.

I used the same OS as you. All instances used these NWJS versions.

```
{ platform: 'darwin',
  arch: 'x64',
  version: '0.27.3',
  flavor: 'sdk' }
```

It works fine in a windows 10 instance in parallels.

**Comment by Richargh** [comment]
Bug was no longer reproducable
