### ISSUE TITLE
Activate building labels to be shown by clicking a new option in the node options menu

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#1234]
# Feature request

## Description

As a software auditor, I want to activate a label of a building to be shown, so that I can keep track of the map and keep the view clear.

## Acceptance criteria
- A right click opens the node options (context) menu
- There, a new option "Show Label" is shown
- By clicking the new option, the corresponding label keeps displayed and the "Show Label" text toggles to "Hide Label"

## Open questions
It might be a good idea to provide some functionality to hide or show all labels with one click.

**Comment by NearW** [comment]
We currently have the slider to show the labels of the x highest buildings. I never really saw a good use-case for this and really appreciate the idea of this feature request!

Let's remove the slider and add the options to `Hide all labels` to the `AreaSettingsPanel` instead.
I don't think a `Show all labels` is needed, since it will just obfuscate the map.

**Comment by BridgeAR** [comment]
I thought about this before as well and I would like to show the label during hovering. After clicking on a building, I expect the label to be visible even after hovering away. That way there's no need to add an extra option and it's a tad more intuitive. Does that sound good to you two?

**Comment by NearW** [comment]
But this only allows a maximum of 2 labels being visible. The one you're hovering and the one you've selected.
Also the complete path is shown
![image](https://user-images.githubusercontent.com/12533626/92538193-5f5c4c80-f23e-11ea-9042-ee8c836f4b49.png)

I think that labels shouldn't be there automatically. I think that the user should actually enable them for specific buildings. Depending on the mapsize, you could have up to 10 of those.

**Comment by BridgeAR** [comment]
I guess we should chat about this feature request, as I am not completely certain I am able to follow.
