### ISSUE TITLE
Show number of files in the attribute-side-bar when selecting a folder on the map

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#1255]
# Feature request

## Description

As a user, I want see how many files are inside a folder after I selected the folder on the map.

## Acceptance criteria
- ~Remove UNARY-metric entirely~
- Number of files in folder should be displayed in the attribute-side-bar

**Comment by ce-bo** [comment]
The removal of the UNARY metric is handled in #1294. So this TODO can be skipped here.
Just show the number of files in a folder in the attribute-side-bar.
