### ISSUE TITLE
Show total Lines Of Code for a loaded project

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#1267]
# Feature request
Show total Lines Of Code for a loaded project.

## Description
It might be a good idea to visualize the total lines of code for a loaded map. Thus, it would be possible to get to know quickly how relevant a (sub) system is. It's an audit use case, when multiple projects are analyzed, you want to focus the relevant parts.

## Acceptance criteria
- to be discussed

**Comment by NearW** [comment]
You can select a folder in the map and you can see the `rloc` metric for that folder.

**Comment by ce-bo** [comment]
You are right. But I think, seeing the `rloc` immediately (without any challanging clicks and even seeing it all the time), is more intuitive. So even CodeCharta rookies can get this information. Additionally, you can keep `rloc` in mind all the time.

**Comment by NearW** [comment]
Sure, but how do you know what a sub-system is? Those can be the folders directly under root or some more nested structures.
I don't think there is a good way to detect those.

**Comment by ce-bo** [comment]
Sorry for that misunderstanding: A currently visualized cc.json/project can also be a sub-system of a bigger software ecosystem.
It would be totally fine to show the `rloc` of the visualized cc.json (root folder).

**Comment by BridgeAR** [comment]
It's likely a nice UX improvement. The question is where to visualize that part.

**Comment by abdelkaderlagha** [comment]
A very simple implementation is that I added rloc to the ribbonBar. For me this location is the most accurate. ![Capture.PNG](https://images.zenhubusercontent.com/6102ad06fd2e045c98188201/a1d53877-df2b-4fec-8002-15bbd4222d9f)

**Comment by BridgeAR** [comment]
@ce-bo what do you think about always visualizing the metric values up here: 

![image](https://user-images.githubusercontent.com/8822573/128086173-62cd8703-caa4-40f3-824b-ad5d456ef452.png)

During hovering, the numbers are going to change as they do right now. While clicking on a node, the value is "fixed" in a way that after hovering out of the map, the clicked upon values are visible again. If no node is clicked upon outside of the map, the total map values are visible.

**Comment by ce-bo** [comment]
@BridgeAR that's a good idea and a nice UI improvement. We also should take care of focused parts of the map (right click on sub folder -> focus).

I remember the original intention of this issue. We made screenshots of a map to visualize the system and it's sub-modules with corresponding RLOC numbers for every sub-module and the overall system. The reason for that was to get a feeling for the effort to refactor some of the most important sub-modules. This information was provided to the customer/client. Hence, a visualization of the RLOC number within the map (e.g. on the folder floors) would have been perfect for that use case.

**Comment by NearW** [comment]
That's sounds like a great solution.

Highly approved!

**Comment by ce-bo** [comment]
We could think/discuss about a new way on handling detailed settings.

**Comment by BridgeAR** [comment]
Please focus upon https://github.com/MaibornWolff/codecharta/issues/1267#issuecomment-892167501 at the moment. The other part should be discussed later.
