### ISSUE TITLE
EdgePreview on Map broken when selecting zero

### ISSUE THREAD

**Issue by JaiJoPa** [MaibornWolff/codecharta#1276]
# Bug

## Expected Behavior

<GIVEN>

WHEN I move the edgeMetric preview slider to zero

THEN no edgePreview should be visible on the map

## Actual Behavior

WHEN I move the slider to zero

THEN the map shows all edge previews on the map

## Screenshots

![image](https://user-images.githubusercontent.com/50145538/93750909-8af71380-fbfc-11ea-90df-6291428093d7.png)

## Steps to Reproduce the Problem
1. Select an edgeMetric
2. Move edgePreview slider to zero 

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes 
- CodeCharta Version: 1.57.3
- OS: Mac
- Browser: Chrome

**Comment by RomanenkoVladimir** [comment]
In the online demo this results in an infinte loading bug in firefox

**Comment by RomanenkoVladimir** [comment]
@BridgeAR do we want a slider that goes to 0 and shows no edges or should 1 be the minimum?
The second option would seem more intiuitive to me, as you can toggle the metric off, however its your choice.

**Comment by ce-bo** [comment]
> In the online demo this results in an infinte loading bug in firefox.

>EDIT: any change to the label slider now triggers an infinte loading for me, can anyone confirm it please @ce-bo @JaiJoPa @DmytroHutkin ?

There are TypeErrors present in the Console.
![image](https://user-images.githubusercontent.com/26900540/96848463-c16ebb00-1454-11eb-8643-7c8f0396a280.png)

**Comment by RomanenkoVladimir** [comment]
Yes, I fixed the issue
When I fix the bug in question as well it should all work as intended

**Comment by RomanenkoVladimir** [comment]
I detached my PR from this to release the fix this week, this will be done in a follow up PR

**Comment by BridgeAR** [comment]
I am going to reopen the issue as it's fixed for the zero case but not for other preview numbers.

![image](https://user-images.githubusercontent.com/8822573/100756547-94b3a900-33ed-11eb-8d95-2e3cde9f88eb.png)

**Comment by ce-bo** [comment]
@BridgeAR Could you please give us more details, so that we can understand the current issue better.
