### ISSUE TITLE
SourceCodeParser: Support Java 14

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#1277]
# Feature request

## Description

As a user, I want to parse Java 14 code so that I can get all available metrics and codesmells.

## Acceptance criteria
- Java 14 is fully supported
- The parser detects codesmells
- The parser creates at least the previously available metrics

## Assumptions & Exclusions
- Java 14 Support has been released with the Java-Plugin Version 6.6, we're on 5.14 right now

**Comment by Ookami86** [comment]
I experienced the same issue. A fix would be much appreciated.
