### ISSUE TITLE
Quick access for metrics

### ISSUE THREAD

**Issue by mrpatpat** [MaibornWolff/codecharta#128]
# Feature request

## Description

The metric selection dropdowns should be in the upper part of the 3D scene (side by side). They should show the values of the current hovered building and their corresponding dimension icon.
After implementing this, the current metrics in the legend panel can be removed.

**Comment by alschmut** [comment]
What's your opinion? The "quick metric access" [on top](https://github.com/MaibornWolff/codecharta/tree/metric_quick_access) or the one on the [left side](https://github.com/MaibornWolff/codecharta/tree/metric_quick_access_left)? 

<img width="1440" alt="bildschirmfoto 2018-04-13 um 16 40 09" src="https://user-images.githubusercontent.com/23529226/38741110-72eb8406-3f39-11e8-9742-79e2424951ce.png">

<img width="1440" alt="bildschirmfoto 2018-04-13 um 16 39 27" src="https://user-images.githubusercontent.com/23529226/38741113-75e20d1a-3f39-11e8-8a57-9632829c6bd2.png">

**Comment by mrpatpat** [comment]
I like the version on top. It somehow seems more "in order".

**Comment by alschmut** [comment]
try, I've just loaded a bigger map and the one on top definitely takes less space, when having long metric names.
