### ISSUE TITLE
Open code files locally

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1314]
# Feature request

## Description

As a user, I want to open files on my hard drive from the map in my default editor to easy accessing the correct file.

## Acceptance criteria

- All development notes are implemented

## Development notes (optional Task Breakdown)

- [x] Add a lazy loading mechanism that is triggered in case you double click on a file in a map and there's no remote link attached
- [x] Add the same lazy loading mechanism to the filename while having a file or folder open on the top right
- [x] As soon as the mechanism is triggered for the first time, a window is opened that asks for the directory of the file (ideally, a "open folder" window is opened to let the user find the correct folder)
- [x] The filename is now combined with the mentioned directory
- [x] The file is opened in the browser as `file://directory/file/path.extension`.
- [x] The mechanism is not triggered if the directory is already known. Instead, the file is opened as described before
- [x] On the standalone variation, validate that the folder does indeed exist as expected and print an error otherwise
- [x] Store the location of the repository in the local storage connected to the concrete map
- [ ] Update our cc.json to include the original path to the repository during creation. This path should be checked in the standalone variation. If it's still valid, use this value by default without asking the user.
- [x] (Optional, if more work than ~2 hours) The user should be able to update the path in case the folder is moved during development.

On top as another feature:

- [ ] Let the user choose to also add a link as directory instead
- [ ] The links are now all added to the current map
- [x] Double clicking behaves as it did before with links

## Open questions

- Check that the file is opened in the default editor
- We might want to let the user choose if the file should be displayed in the browser or in the default editor

**Comment by ce-bo** [comment]
For now the feature should only be implemented for the standalone version because it is not possible to open a file locally from the website.
