### ISSUE TITLE
Design a dedicated CodeCharta logo

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1316]
# Feature request

## Description

As a stakeholder, I want CodeCharta to be a unique brand so that it is identified easily.

## Acceptance criteria

- The logo should be intuitive and relate to the product

## Open questions

This task is for a designer, not for the developers. I'll check who could address this. Input is of course more than welcome!

**Comment by alpha2320** [comment]
i will like to work on this issue please provide more information

**Comment by BridgeAR** [comment]
@alpha2320 if you have a draft or concrete suggestion for one, please let me know :-)

**Comment by alpha2320** [comment]
@BridgeAR i am not able to understand the purpose of codecharta . please ellaborate so that i can draft accordingly!

**Comment by Richargh** [comment]
The issue is closed. Does that mean CC gets a new logo? :)

**Comment by BridgeAR** [comment]
Yes :-)

![Code Charta final](https://user-images.githubusercontent.com/8822573/111806586-6d1c1a00-88d2-11eb-8d4e-1f7921f20e2c.png)
