### ISSUE TITLE
Switching to delta mode with fixed folders cause infinite loop

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1341]
# Bug

## Expected Behavior

GIVEN a map with fixed folders

WHEN switching to delta mode

THEN the delta mode is rendered. Each folder is compared only with itself

## Actual Behavior

An infinite loop is triggered.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes | no
- CodeCharta Version: 1.58.1

**Comment by DmytroHutkin** [comment]
Bugfix check required. 
Scenario:
  - create .json with fixed folders
  - load .json in CodeCharta
  - switch to delta-mode
  - check if infinite loop is missing
