### ISSUE TITLE
Improve showing labels #2

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#1348]
# Feature request

Show only labels of buildings according to a metric value.

## Description

As an Auditor, I want to be able to show all labels that are within a given range of a metric value, so that I can control the displayed labels in detail.

## Acceptance criteria
- There is a new range slider to set a threshold where labels should be still shown
- There is a way to configure the condition of the threshold (show labels >= threshold or rather <=).
- Labels are shown accordingly.

## Open questions
- We should think about which metric makes sense to use as the basis for the range or should we enable the user to chose the appropriate area/height/color metric instead?

**Comment by BridgeAR** [comment]
I believe we implemented enough options that address the mentioned needs here. It is possible to invert the height and by doing so the range is inverted as well. We are also able to highlight labels by color and that is pretty powerful. As such, I am going to close this as being resolved.
