### ISSUE TITLE
Add SCMLogParserV2 documentation

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#1349]
# Feature request

## Description

As a Developer, I want to have a great documentation, so that I can read about all great features the new parser is providing.

## Acceptance criteria
- The documentation informs about the experimental status.
- There should be some words about resolving mutated files and gracefully handling modifications for unexisting files and so on.
- We should also add some words that we don't count the delete of a file if it is added again later on (revert).

**Comment by BridgeAR** [comment]
This should be addressed soon to also get the documentation on the website up to date.
