### ISSUE TITLE
SCMLogParserV2 parsing other projects except CodeCharta

### ISSUE THREAD

**Issue by RomanenkoVladimir** [MaibornWolff/codecharta#1351]
# Question
- Our tests ensures that CodeCharta is parsed correctly, however other projects might be different.
- We already noticed that parsing node.js might lead to issues, however, we are not sure if this is a logical error, or an unhandled edge case
- the old parser crashed way to early and therefore provides no good staging ground to compare against
- we would ask the potential users of the SCMLogParser to test the new feature and report any potential errors or anomalies

**Comment by BridgeAR** [comment]
Let's expect the parser to work appropriately for now. We may look into that later on again. Closing as won't fix for now.
