### ISSUE TITLE
E2E (end to end) tests could be false-positive

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#1362]
# Bug
36 matches in 11 files should be checked for the following bug:

If you use the following puppeteer code snippet:
`page.waitForSelector("#some-selector", { visible: true/false})`
to check, if an element is shown/visible currently (e.g. by `toBeTruthy()`)
then this can lead to a false-positive!
1) the returned value of `waitForSelector` is `truthy` in every case (a json is returned and evaluated as truthy).
2) Waiting for an element to be visible/not visible (option `visible: true/false`) seems to be unsafe in some cases.

There are a lot of existing e2e test, which are written using that snipped.
Therefore, action is required to find and fix those false-positive tests.

## Possible Fix
No fix is known yet

## Steps to Reproduce the Problem
1. To find those false-positive test, you can disable the interaction with the page object (e.g. disable a click on an element) before the relevant expectation is tried to be met.

**Comment by BridgeAR** [comment]
About the first issue: this is only critical for functions that return that value (which is rather uncommon in the tests). This should indeed be fixed (it's likely that the return value should be replaced with an await).

The second issue: the way how the test behavior works is to expect a timeout if something does not work as expected. Thus, I'm uncertain in what way it's unsafe to use this functionality.

**Comment by ce-bo** [comment]
> The second issue: the way how the test behavior works is to expect a timeout if something does not work as expected. Thus, I'm uncertain in what way it's unsafe to use this functionality.
This works only if you want to check if an element is present in the DOM and visible as well (no attributes like `visibility: hidden` or `display: none`). But the check does not guarantee, that the element is really shown to the user.
For example, the check is error-prone for elements that are shown/hidden by the aria-hidden attribute.

**Comment by ce-bo** [comment]
I checked some of the E2E tests by hand and could not find any false-positive tests. 
I close this issue.
