### ISSUE TITLE
Add deltas to to metrics quick access.

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#138]
# Feature request

Add deltas to to metrics quick access.

## Description

When the details panel is closed code deltas cannot be viewed. Since the details panel is often closed this is a problem.

The deltas should be seen in the quick access menu right next to the metrics. The deltas should have a + or - indicating if metrics increased or decreased. Their color should be the same as the delta indicator in the code city.

**Comment by FernandoES** [comment]
while deltas activated the color dimension is not used, right?
As a consecuente I'll suggest to add the delta horizontal window instead of the color one when deltas activated

**Comment by FernandoES** [comment]
Solved in the pull request #161
