### ISSUE TITLE
Add possibility to switch layouts

### ISSUE THREAD

**Issue by mrpatpat** [MaibornWolff/codecharta#141]
# Feature request

## Description

Add possibility to switch layouts in order to integrate other visualization methods

**Comment by ukinimod** [comment]
I don't get the necessity of this enhancement. Why not having multiple applications? Switching between TreeLayout and VilleLayout does not make any sense. What is the use case behind this?

**Comment by mrpatpat** [comment]
Hi @ukinimod,
We discussed this topic for quite some time. There are actually two reasons for this issue. 
Adding a layout switcher and ui routing in general adds the possibility to implement different views and layouts. E.g. if we want some charts, lists, menus or custom views other than the 3D scene. 
The second reason for this decision is a rather disputable one. We realized that testville is technically seen just another 3D view for the same file format. The layout itself reuses a lot of CC UI components. 
Maintaining a second application/fork for some small changes introduces a lot of problems in terms of updating and keeping up with origin changes. 
Please note that the testville layout is not yet officially visible. At this moment it is just a placeholder for possible layouts in the future (not necessary testville). This task just implements the technical layer for ui routing and layout management. If you want we can speak in person about the decisions that were made. 
I will close this issue since the feature is already implemented in PR #142.
