### ISSUE TITLE
Code Style formatting

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#1420]
# Feature request

Please ensure that the right code style is applied during development.
Some options:
- Add formatter script from CodeCharta root package.json to the git hooks
- Copy formatter script from CodeCharta root to visualization package.json
- Provide IDE config files to set the right coding style in the IDE

Do not forget the analysis part

**Comment by RomanenkoVladimir** [comment]
Analysis is handled by ktlint.
You run gradlew ktlintApplyToIde and it should set the formating rules (it should also say this somewhere in the docs...)
We don't apply those rules as a prehook, but we test for them during the build making it fail if they aren't applied

**Comment by RomanenkoVladimir** [comment]
Furthermore in my opinion and after talking to @NearW the prettier is always run at commit (also when only commiting to visualization) for the whole project, withthe analysis part is specifically excluded.
This seems to be an issue with your settings, you need to enable the pre-hook in the IDEA or commit via the command line.

I would consider the issue closed..
