### ISSUE TITLE
Disable building's highlight effect on moving the map

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#1432]
# Bug
I am not sure, if this is a bug:

## Expected Behavior

GIVEN
a loaded map

WHEN
moving the map with the pressed left mouse button in a way so that the courser hovers a building

THEN
the buildilng should not be highlighted.

## Actual Behavior

THEN
the building is highlighted.

**We think it will be a nice improvement because we don't have to check if the cursor hovers a building and thus, we don't have to fire the corresponding highlight event(s).**

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.60.2
- OS: Windows
- Browser: Chrome

**Comment by BridgeAR** [comment]
I thought about opening an issue about this a couple of times before but I decided against it after all. It's not really an issue and at least some users might prefer the current behavior?

**Comment by RomanenkoVladimir** [comment]
I don't know if the current behaviour is really preferable?
Imagine rotating a big map, this will light up a lot of random buildings, which does not help a user in my opinion.

Additionally this incurs a big event overhead as each hovered building will trigger a Highlighting Event.

In my opinion we should address this behaviour, maybe we can add an option to reenable it if someone really wants the feature.

Its fast and easy to do so it wouldn't eat needed development time.

What do you think?

**Comment by BridgeAR** [comment]
If it's fast to implement the change, I am good with that! I would not add an option to keep the old behavior.
