### ISSUE TITLE
Show folder names as labels on the floor

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#1491]
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As a an Auditor, I want to see the name of the folder on the floor on which a specific building is placed, so that I can see where a specific software module is placed without any clicks.

## Acceptance criteria
- The first 3 floor layers are labeled with the name of the folder that the individual layer represents.
- The label is fixed just like the floor geometric (just like the floor would be stamped).
- The deeper the layer the smaller the font size is.
- The folder name is centered vertically

## Development notes (optional Task Breakdown)
- We must expand the floor geometric on the front side to have enough space for the folder name to be placed.

## Example
Here you can find a 2D example of labeled floors: https://observablehq.com/@d3/nested-treemap?collection=@d3/d3-hierarchy

**Comment by Richargh** [comment]
@shaman-apprentice I don't know if this is relevant for your task, but I researched algorithms to create non-overlapping labels in issue #334. I'm afraid it's not more than that though, just a possible starting point.

**Comment by ce-bo** [comment]
Thank you @Richargh . That might be relevant for #1347. We are implementing another algorithm at the moment.
