### ISSUE TITLE
Labels do not take delta height into account

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1523]
# Bug

## Expected Behavior

GIVEN a map in delta mode that has a green or red part

WHEN looking at the label

THEN the label should start at the top of the building.

## Actual Behavior

The label clips into the red or green part as the top building height is calculated without the delta part.

## Screenshots

![image](https://user-images.githubusercontent.com/8822573/100616210-0cfc6a80-3319-11eb-8935-7a873157ddd4.png)
![image](https://user-images.githubusercontent.com/8822573/100616246-184f9600-3319-11eb-85fd-3c6ed1756763.png)

## Notes

I suggest to think about an abstraction for the building height in a way that delta mode does not need to be handled specially when changing e.g., the position where a label is positioned.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.63.0
- OS: All
- Browser: All

**Comment by RomanenkoVladimir** [comment]
I think the margin change might address that as @JaiJoPa fixed a height issue with labels. So maybe connected to #1490?

**Comment by JaiJoPa** [comment]
I just looked at it and sadly that bug also exists in in there. The delta height is seems to be not considered in the label height calculation.
