### ISSUE TITLE
Highlighted label while hovering over building

### ISSUE THREAD

**Issue by Gaugi28** [MaibornWolff/codecharta#1529]
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As a user, I want a highlighted label when I hover over the associated building so that I can see directly the name of the file.

## Acceptance criteria
- if the user hovers over a building, the label appears in the foreground and is highlighted

**Comment by RomanenkoVladimir** [comment]
A question: In case of hovering a building with label? Or in case of hovering any building?
So if the building has no label but is hovered do we create a label for the duration of the hover event?

**Comment by BridgeAR** [comment]
Good question. I personally would prefer the building to visualize the label during hovering as well, no matter if it's already visible or not.

But this specific issue was only about the hovering effect of the visible label:

Label hovered (highlights the label and building):
![image](https://user-images.githubusercontent.com/8822573/100758108-6cc54500-33ef-11eb-934b-a5482a012ecb.png)

Building hovered (highlights the building only. This should be fixed to also highlight the label):
![image](https://user-images.githubusercontent.com/8822573/100758135-75b61680-33ef-11eb-9581-92b86f0a48f8.png)

Not hovered. Nothing is highlighted.
![image](https://user-images.githubusercontent.com/8822573/100758184-84043280-33ef-11eb-9f0d-018f104df8ce.png)

**Comment by RomanenkoVladimir** [comment]
TODO: we also need to take into account constant highlighting and maybe add a tint to the label for a selected node
