### ISSUE TITLE
Labeling packages in legend

### ISSUE THREAD

**Issue by mrpatpat** [MaibornWolff/codecharta#153]
Original feature request was #119. Depends on #155.

## Description

The 3D visualization should show labeled packages in the legend on the left side.

Examples: If I mark a package as "pink" I expect the name to appear in the legend with the color indicator. If I mark two packages "pink" I expect both to be in the legend. Package names should be shortened so they fit the legend. At minimum I expect the leaf package name to be seen. 
That means, if the marked package is de/maibornwolff/codecharta then the minimal package name to be seen is codecharta. If there is enough room parts of the other packages can be displayed, too. F.ex. ...nwolff/codecharta.

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

* [ ] **All** requirements mentioned in the issue are implemented
* [ ] Does match the Code of Conduct and the Contribution file 
* [ ] Task has its own **GitHub issue** (something it is solving)
  * [ ] Issue number is **included in the commit messages** for traceability
* [ ] **Update the README.md** with any changes/additions made
* [ ] **Update the CHANGELOG.md** with any changes/additions made
* [ ] **Enough test coverage to ensure that uncovered changes do not break functionality**
* [ ] **All tests pass**    
* [ ] **Descriptive pull request text**, answering:
  + What problem/issue are you fixing?
  + What does this PR implement and how? 
* [ ] **Assign your PR to someone** for a code review
  + This person _will be contacted **first**_ if a bug is introduced into `master`
* [ ] **Manual testing** did not fail

**Comment by ukinimod** [comment]
Maybe labeling a number of packages in a certain level by size, analogous to the labeling of buildings, would be more sensible.
