### ISSUE TITLE
Default metric is preselected

### ISSUE THREAD

**Issue by Gaugi28** [MaibornWolff/codecharta#1532]
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As user who don’t know the metrics and their meaning, I want a default metric which fits to the file so that I don’t have to select the right metric by myself.

## Acceptance criteria
- if a user loads his/her data the right metric is pre-selected.

## Open questions
- How do the system know which metric is the right/default one?

**Comment by BridgeAR** [comment]
@ce-bo and me discussed this a few times recently and we thought about implementing a heuristic for known metrics based upon frequently used metrics in audits. We also thought about using machine learning. To do so we might need to ask users to transfer some statistics anonymously about their used metrics, the map size and a few more things.

**Comment by BridgeAR** [comment]
Specified requirements:

1. In our cc.json we add a new property that includes the information what three (or four with the edge metrics) metrics should be chosen as default metrics while loading the map.

![image.png](https://images.zenhubusercontent.com/5e995c73efe923788cbf2771/b8230248-4bcb-48a2-951e-6996043e195d)

1. Check our parsers/importers what metrics they generate and try to chose a logical frequently used combination that seems useful to most people.

1. Update our parsers/importers to always include the default metrics in the generated file.

1. Create a fallback mode in the frontend for older cc.json files that do not yet include the default metrics in. This may be done by using the well defined combinations already known from our parsers/importers and to check if any of those apply. If neither applies, use the first entry in the metric list.

1. Update our cc.json file merge tool to use the "best" default set from the provided ones. This may be done by prioritizing some metrics above others. If neither applies or a file has no defaults, just use the first entry in the metric list.

**Comment by BridgeAR** [comment]
I updated the requirements to simplify the issue:

1. Check our parsers/importers what metrics they generate and try to chose a logical frequently used combination that seems useful to most people. 

2. Create a default mode in the frontend for cc.json files. This may be done by using the well defined combinations already known from our parsers/importers and to check if any of those apply (as full metric combination). If neither applies, use the first entry in the metric list.

**Comment by ce-bo** [comment]
Example:

**Known combination 1:**
Size / Complexity / Complexity

Category Size: rloc, loc, number_of_statements, etc.
Categroy Complexity: mcc, complexity, sonar_cognitive_complexity, etc.

**Comment by jannikr** [comment]
Basic functionality was implemented with PR #2862. In the further process, the list of metrics will be extended. To evaluate the metrics, here is an overview (not complete).

| Metric | Category | Relevance | Done |
|:-----|:------|:------|:------|
| branch_coverage |      |      |      |
| bug   |      |      |      |
| classes   |      |      |      |
| code_smell   |      |      |      |
| cognitive_complexity |  complexity    |   2   |   ✓   |
| comment_lines   |      |      |      |
| commented_out_code_blocks   |      |      |      |
|  functions   |      |      |      |
|  max_nesting_level   |      |      |      |
|  line_coverage   |      |      |      |
|  loc   |   size   |   2   |   ✓   |
|  mcc  |   complexity   |   1   |   ✓   |
|  rloc   |   size   |   1   |   ✓   |
|  security_hotspots   |      |      |      |
|  sonar_blocker_violations  |      |      |      |
|  sonar_bugs  |      |      |      |
|  sonar_classes  |      |      |      |
|  sonar_code_smells  |      |      |      |
|  sonar_cognitive_complexity  |      |      |      |
|  sonar_comment_lines_density  |      |      |      |
|  sonar_conditions_to_cover  |      |      |      |
|  sonar_confirmed_issues  |      |      |      |
|  sonar_critical_violations  |      |      |      |
|  sonar_duplicated_blocks  |      |      |      |
|  sonar_duplicated_files  |      |      |      |
|  sonar_duplicated_lines  |      |      |      |
|  sonar_duplicated_files_density  |      |      |      |
|  sonar_false_positive_issues  |      |      |      |
|  sonar_file_complexity  |      |      |      |
|  sonar_files  |      |      |      |
|  sonar_generated_ncloc  |      |      |      |
|  sonar_info_violations  |      |      |      |
| sonar_issue_other   |      |      |      |
|  sonar_lines_to_cover  |      |      |      |
|  sonar_major_violations  |      |      |      |
|  sonar_minor_violations  |      |      |      |
|  sonar_open_issues  |      |      |      |
|  sonar_public_documented_api_density  |      |      |      |
|  sonar_public_undocumented_api  |      |      |      |
|  sonar_reopened_issues  |      |      |      |
|  sonar_security_hotspots  |      |      |      |
|  sonar_security_hotspots_reviewed_status  |      |      |      |
|  sonar_security_hotspots_to_review_status  |      |      |      |
|  sonar_skipped_tests  |      |      |      |
|  sonar_sqale_debt_ratio  |      |      |      |
|  sonar_test_errors  |      |      |      |
|  sonar_test_failures  |      |      |      |
|  sonar_test_success_density  |      |      |      |
|  sonar_uncovered_conditions  |      |      |      |
|  sonar_uncovered_lines  |      |      |      |
|  sonar_violations  |      |      |      |
|  sonar_vulnerabilities  |      |      |      |
|  sonar_wont_fix_issues  |      |      |      |
|  statements  |      |      |      |
|  unary  |      |      |      |
|  vulnerability   |      |      |      |

**Comment by ce-bo** [comment]
Hi @jannikr, thank you very much for creating this list of metrics.
I edited the list in your comment and mapped the metrics to size and complexity category.
The Relevance means the order in which we should choose a metric as a default. So cognitive_complexity and sonar_cognitive_complexity have the same order because I think they are synonyms. And I think we only calculate/import sonar_cognitive_complexity. I've never seen the metric cognitive_complexity in our parsers.

**Comment by charlotteKehm** [comment]
@ce-bo In metric-gardener exists the metric "real_lines_of_code"? How shall we handle this? In my opinion it is more relevant than "lines_of_code.

**Comment by ce-bo** [comment]
Yes, thats correct. The corresponding acronym is "rloc" and "rloc" has highest priority.
