### ISSUE TITLE
Add color picker to change color

### ISSUE THREAD

**Issue by Gaugi28** [MaibornWolff/codecharta#1533]
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As a color blind person, I want a color picker in the legend, at the metric color settings and at the edge metric settings so that I can choose other color to see the difference between red and green better and so that I can personalize the look of CodeCharta. 

## Acceptance criteria
Color metric settings:
- for each color (currently green, yellow, red and orange) there is a clickable color icon and a description, what the color represent, under the color range.
- if a user hover over a color icon, a brush icon appears
- if a user select a color icon, a colorpicker opens on the left side (the image shows an example).
- in the colorpicker the user can pick an color or set an hexadecimal color code to change the selected color.
- the color will be updated in the legend once the user has chosen the color
- function `white positive buildings` is deleted
![colorpicker_color metrics](https://user-images.githubusercontent.com/12883714/100848001-cfb2ec80-3480-11eb-8d95-e629f2cea9e6.png)

Edge metric settings:
- for each color there is a clickable color icon and a description, what the color represent, under the height slider.
- if a user hover over a color icon, a brush icon appears
- if a user select a color icon, a colorpicker opens on the left side (the image shows an example).
- in the colorpicker the user can pick an color or set an hexadecimal color code to change the selected color.
- the color will be updated in the legend once the user has chosen the color
![edgeMetricColor](https://user-images.githubusercontent.com/12883714/100847044-8910c280-347f-11eb-8f76-5152d5414bb0.png)

Legend:
- each color icon is a clickable icon
- if a user hover over a color icon, a brush pen appears
- if a user select a color icon, a colorpicker opens on the left side (the image shows an example).
- in the colorpicker the user can pick an color or set an hexadecimal color code to change the selected color.
- the color will be updated in the other color settings once the user has chosen the color
![legend_color](https://user-images.githubusercontent.com/12883714/100848334-43ed9000-3481-11eb-882a-f0bba324ee79.png)

## Assumptions & Exclusions
The image shows only an example of a colorpicker how it could look. If you find an already developed color picker, which fits to CodeCharta and your code, take it.

**Comment by BridgeAR** [comment]
Example color picker: https://www.npmjs.com/package/angularjs-color-picker

We should re-evaluate the `White Positive Buildings` button: we could just remove the button in favor of letting the user use such color picker. The button might be more convenient though?

We should also allow the "active" color (orange at the moment) to be configured.

**Comment by Gaugi28** [comment]
Yes, the "active" color configuration will be another issue. Or should I add it here? 

If `white positive building` is obsolete, how important is `Invert Colors`?

**Comment by BridgeAR** [comment]
I'd say our comments are sufficient for the "active" color?

I would keep `Invert Colors` as convenience button. This is likely the most frequent change and would require all colors to be manually changed, not only one.

**Comment by BridgeAR** [comment]
We might also allow to adjust the edge metric colors:

![image](https://user-images.githubusercontent.com/8822573/100756832-ea885100-33ed-11eb-8ab2-f2b7836638d2.png)
![image](https://user-images.githubusercontent.com/8822573/100756866-f542e600-33ed-11eb-83b7-5b6d8629aa6d.png)

We should allow the colors of the edge metrics to be adjusted in the edge metric configuration part. I would keep the "active" color adjustment in the color metric part as discussed while I am not totally sure if it's the most suitable place to adjust that color of if that would be in the general configuration. @Gaugi28 do you have an opinion about that?

The acceptance criteria should also include the legend to be updated accordingly.

**Comment by BridgeAR** [comment]
We could also allow the user to change the colors in the legend. That might be convenient to allow the color to be changed in multiple places?

**Comment by Gaugi28** [comment]
After a discussion with Ruben we decide to allow the user to change the color in the legend. The issue is now updated.

**Comment by Richargh** [comment]
@BridgeAR #565 might also match what you are looking for. Or you might want to close that issue now.

**Comment by BridgeAR** [comment]
@Richargh thanks, I had a look at that issue as well and it's definitely connected. I would like to keep both open as this implements the possibility to change colors but it's not yet a focus on any shorthand configurations for accessibility reasons and we could use the old issue for that. I would for example be interested in adding a `colorblind safe` option as well.

**Comment by shaman-apprentice** [comment]
@BridgeAR  @Gaugi28: Quick question regarding "Invert Colors": I suggest to switch the colors instead of the metric mapping. Meaning in below screenshot the 0 to < 60 stays at top position, but color-icon becomes red, instead of current behavior seen on screenshot

![image](https://user-images.githubusercontent.com/3596742/101892727-0a650500-3ba4-11eb-8cb4-3a57dfa1196b.png)

**Comment by BridgeAR** [comment]
@shaman-apprentice I agree, especially with the new UI, since we allow to change the colors of the specific range.

**Comment by Gaugi28** [comment]
@shaman-apprentice I agree too, a good idea!
