### ISSUE TITLE
Image Sharpening

### ISSUE THREAD

**Issue by Med-H** [MaibornWolff/codecharta#1534]
# Feature request

Improve text label and overall image quality.

## Description

As a user, I want to have clean text and sharp geometry borders.

Current
![Current](https://user-images.githubusercontent.com/74670211/100776686-224ec300-3405-11eb-9e0e-1b6e4b122390.PNG)

Expected
![expected](https://user-images.githubusercontent.com/74670211/100776774-43afaf00-3405-11eb-8f04-ac04f10400a3.PNG)

## Acceptance criteria

- There is an option to activate/deactivate the optimization.
- There is a List-box or step progress-bar with quality options (ex : normal/medium/high).

## Assumptions & Exclusions

- The used GPU fill rate will be higher therefore an optional quality selection might be needed.
- It might be needed to have some GPU performance metric (FPS, RAM usage, Frame time, …) 

## Open questions

- Is it feasible to improve the Fill-rate by optimizing the fragment shader?
- Is it feasible to adjust the quality based on the Frame rates ?

**Comment by RomanenkoVladimir** [comment]
The problem is that due to the performance of the folder label feature we reduced the number of pixels, we should optimize performance so that we can get high-resolution images again, without overloading the users GPU.
Related to #1541, I think a general change is required to accomplish both
