### ISSUE TITLE
Focus on selected building or area

### ISSUE THREAD

**Issue by Gaugi28** [MaibornWolff/codecharta#1538]
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As user I want that the selected building or area is in the center of my view so that I can see the selected better.
![NoFocusOnSelectedAreaOrBuilding](https://user-images.githubusercontent.com/12883714/100850055-89ab5800-3483-11eb-93ca-e7f1e82141c3.png)
![FocusOnSelectedAreaOrBuilding](https://user-images.githubusercontent.com/12883714/100850045-87e19480-3483-11eb-80c3-89bd9b70d406.png)

## Acceptance criteria
- if a user clicks on a building or an area the selected should be positioned in the center of the user's view

**Comment by RomanenkoVladimir** [comment]
Should we also rotate the map or move it closer if the building is too far away on the view ray, maybe as an extra feature?
I think it would improve navigation on very big maps.

**Comment by BridgeAR** [comment]
I gave this another thought. It might in fact be disrupting to the users as it's more difficult to find other buildings in case the map moves each time we click on a building. Clicking on buildings is done frequently and therefore it's not a priority. We could in add a button that would center the map to that building. @Christian-Eberhard you might have a look at this. I would let you decide upon this being a useful feature or not.

**Comment by ChristianHuehn** [comment]
I like the idea to center the attention on it. But it's a building, without details there is nothing to see there, not like it has any windows. 

On search it would be a lot better. Still not planed right now
