### ISSUE TITLE
Add visible zoom function

### ISSUE THREAD

**Issue by Gaugi28** [MaibornWolff/codecharta#1539]
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As user I want a visible zoom function so that I can zoom in and out and I can see the zoom factor. 

## Acceptance criteria
- under the cube there is a slider, with it the user can zoom in and out:
  - at the left side there is a minus
  - at the right side of the slider there is a plus
  - the user can pull the slider to the left and the view is zooming out
  - the user can pull the slider to the right and the view is zooming in
- at the right side of the slider there is the zoom factor
- the zoom factor and the slider show always the current zoom factor no matter if the user zooms by mouse, by touch or by using the slider
![ZoomDisplay](https://user-images.githubusercontent.com/12883714/100855866-f83fe400-348a-11eb-8508-7f8cb7ae7969.png)

**Comment by BridgeAR** [comment]
This is blocked on the padding improvements.

**Comment by BridgeAR** [comment]
This is now unblocked due to #3077 :partying_face:

**Comment by ce-bo** [comment]
Not sure, why this was blocked by the padding improvements...

**Comment by IdrisLaabidi** [comment]
PR reverted by this [commit](https://github.com/MaibornWolff/codecharta/commit/13a1875ff35d2c460056f860f36c6b04f40ce487)
