### ISSUE TITLE
Automatic highlighting

### ISSUE THREAD

**Issue by mrpatpat** [MaibornWolff/codecharta#154]
Original feature request was #119. Depends on #155 #152 #153 

## Description

The 3D visualization should allow automatic/intelligent package highlighting (by right clicking the tree view element or 3d element and then selecting intelligent highlighting in a context menu).
This will highlight and label the top Z (at most Z) descendants by a simple rule like:
"If the current block's area is bigger than X % and smaller than Y % of the global area then highlight and label this block" where X and Y are values which work for most projects.

**Comment by ukinimod** [comment]
1. Highlighting and labeling should be considered independently as is done with the buildings and their coloring and labeling. It is e.g. common to use labeling only in one view for an overview slide, for orientation, and using only highlighting thereafter and depending on the previously established orientation.
 
2. Concerning labels I agree with the issue. That would definetly be a helpful feature.

3. As developer and architect I disagree that highlighting should be dependent on the size of something in something other. This disagrees with the principle of "same level of abstraction". The highlighting should highlight modules, components or other vastly different higher level parts of the system. Highlighting them only if they are of a particular size would be misleading. Labeling on the other hand should not symbolize anything but convey the name of the considered part of the system.

**Comment by Richargh** [comment]
While really interesting, we'll probably not get to this feature this year. So we'll close it for now.
