### ISSUE TITLE
Reduce memory usage

### ISSUE THREAD

**Issue by Gaugi28** [MaibornWolff/codecharta#1541]
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As user I want a reduction of memory usage so that the message as shown in the image doesn't appear anymore.

![Single Multiple Delta](https://user-images.githubusercontent.com/12883714/100871186-20860d80-34a0-11eb-98e2-a3e9c66a521a.png)

## Acceptance criteria
- the message doesn't appear anymore
- the notebooks do not heat up too much when CodeCharter opens

**Comment by BridgeAR** [comment]
This is likely related to https://github.com/MaibornWolff/codecharta/issues/1547 as well as #1024 and #1025.

**Comment by Med-H** [comment]
I would also add #1710.

**Comment by BridgeAR** [comment]
This is partially addressed by now.

**Comment by BridgeAR** [comment]
I am going to close this as mainly resolved. If this comes up again, please open a new issue, thanks!
