### ISSUE TITLE
Show the whole node context menu within the viewport responsively

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#1546]
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As a CodeCharta user, I want to open a responsive node context menu even in the near of the boarders of the viewport, so that I am still able to see and click all node options. The node context menu may not be hidden because it runs out of the viewport.

## Acceptance criteria
- If I open the node context menu by right clicking a building, the node context menu is responsively placed arount the current cursor position, so that the node context menu is visible in every case.

In this case the node context menu disappears on the right and I am not able - for example - to exlucde the building.
![image](https://user-images.githubusercontent.com/26900540/101050452-b5623700-3584-11eb-9e1d-230726069dad.png)

**Comment by shaman-apprentice** [comment]
I already implemented this during migration. See [this changelog entry](https://github.com/MaibornWolff/codecharta/blob/main/CHANGELOG.md?plain=1#L260)
