### ISSUE TITLE
Spike: Automatic performance measures

### ISSUE THREAD

**Issue by shaman-apprentice** [MaibornWolff/codecharta#1550]
# Spike / Feature request

## Description

As an user I want a responsive / performant visualization of the buildings.

As a developer I want to catch unwanted performance drawback without huge manual testing. As a developer I also want to have a quick way to assess performance optimizations.

As far as I know performance analysis is done via manual testing and by feeling so far.

## Acceptance criteria / scope of this issue
- Proposals how to run automatic performance tests / which metrics to analyse are documented
- Proposals how to understand those metrics quickly are documented
  - regarding automatic evaluation
  - regarding visualization

## Assumptions & Exclusions
- Chrome (and Electron as well) expose a [performance api](https://chromedevtools.github.io/devtools-protocol/tot/Performance/) which can capture metrics. I know that you can start and control electron via a node script for automatic performance analysis via this api. I guess in chrome or nw this is possible as well

**Comment by Med-H** [comment]
would this close it ?

![devMetrics](https://user-images.githubusercontent.com/74670211/107639217-dde76b00-6c70-11eb-98d8-12b5eff33bd7.gif)
