### ISSUE TITLE
Quick city navigation

### ISSUE THREAD

**Issue by shaman-apprentice** [MaibornWolff/codecharta#1554]
# Feature request

## Description

As a user I want a lean main screen, to minimalise distraction. I also want a nice way to navigate to special views. 

Currently there is a cube in the upper right, which moves with the whole city. I find that distracting and I am not sure what the value for the user is. 

If you click on a site of the cube, you can change the view on the city.
- If you click on the top, you get a view from the top, which is very nice e.g. for screenshots. But I think the view should be turned 90deg, so that the floor labels are readable
- I am not sure, if all other views, you can get through clicking on the cube, are useful

![image](https://user-images.githubusercontent.com/3596742/101366244-020b8200-38a5-11eb-9cd6-0c19cb699f14.png)

## Suggestion:
- Remove the cube
- make the compass a dropdown menu with the 2 options to
  - reset the view
  - get to the top view

**Comment by BridgeAR** [comment]
It is already possible to move the cube in a way that the labels are turned by 90 degrees. The map will likely get a different default view angle at some point and it will be more intuitive from then on.

I am going to close this as the cube should stay as it is for now. On top of the new angle there's a plan to add labels to better indicate the cube's behavior.
