### ISSUE TITLE
Add color picker to NodeContextMenu

### ISSUE THREAD

**Issue by Gaugi28** [MaibornWolff/codecharta#1556]
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As a user, I want a color picker to the NodeContextMenu so that I can choose individual colors.

## Acceptance criteria
- the sixth color is replaced by a brush icon
- if the user clicks on the brush icon the color picker opens (shown in image)
- the user can also change the color in the legend~
- legend colors change with the selection of color in the NodeContextMenu

![ColorPickerHighlightFarben](https://user-images.githubusercontent.com/12883714/101373643-7a764100-38ad-11eb-9d8b-d125331c68f7.png)

**Comment by BridgeAR** [comment]
@shaman-apprentice is this already implemented in your color PR? This would otherwise be a good addition right afterwards :)

**Comment by shaman-apprentice** [comment]
> @shaman-apprentice is this already implemented in your color PR? This would otherwise be a good addition right afterwards :)

Not part of #1533 but should not be hard to implement right afterwards with the same reusable introduced color-picker

**Comment by shaman-apprentice** [comment]
@BridgeAR @Gaugi28 Should we keep the 5 other colors, or just put the actual color there, which opens the color picker like in the legend?

**Comment by Gaugi28** [comment]
We should keep the 5 other colors. So users with little time have not to think which color they prefer.

**Comment by shaman-apprentice** [comment]
Does an entry in the legend make sense? It is not a global setting but customizable per folder layer:

![image](https://user-images.githubusercontent.com/3596742/104169102-56070a80-53ff-11eb-87d3-da802c9342d9.png)

If we should add a label (for the root folder?), what would be a good label text? My first intuition would be "**floor**". But that might be confusing as you can change it in the node context menu. So maybe "**node**"? Or "**folder**" as the tooltip is "colorize folder"?
![image](https://user-images.githubusercontent.com/3596742/104169318-a7af9500-53ff-11eb-821b-7e96b49ea7f2.png)

**Comment by BridgeAR** [comment]
I would not add an entry for the root folder or any "default" floor color. It would be relatively verbose without providing significant benefit.

It should be fine to add the newly created custom color to the legend as well, just as any other color. They should be distinguishable due to the individual hex code of the color.
