### ISSUE TITLE
Creating a scenario with changed colors

### ISSUE THREAD

**Issue by Gaugi28** [MaibornWolff/codecharta#1557]
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As a user, I want to save my set colors so that I can use them in other CC projects.

## Acceptance criteria
- The user can select also the colors by adding the scenario
- If the user switch to the scenario the map is colored in the saved colors.

**Comment by RomanenkoVladimir** [comment]
I would propose adding this to custom configs as well, aka, when I create a custom config the colors picked in the color picker are saved as part of the config

**Comment by BridgeAR** [comment]
This should ideally be implemented as follow-up to changing the colors. CC @shaman-apprentice
