### ISSUE TITLE
Small map is cut off when combining with a really big map in multiple mode

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#1566]
# Bug

## Expected Behavior

GIVEN
A quite big and a small map has been uploaded

WHEN
activating the multiple mode

THEN
both maps are rendered next to each other or let's say together 

## Actual Behavior
the smaller one is cut off

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.63.0
- OS: Windows
- Browser: Chrome

**Comment by BridgeAR** [comment]
AFAIK this is blocked by the margin issue and is likely resolved as soon as that's fixed.

@ce-bo if that is indeed the case, let's maybe close this?

**Comment by ce-bo** [comment]
Yes, I agree.
