### ISSUE TITLE
Excluding in delta mode is broken

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1578]
# Bug

## Expected Behavior

GIVEN two maps in delta mode

WHEN excluding parts

THEN the excluded part is not visible anymore

## Actual Behavior

The excluded part is still visible

## Screenshots
![image](https://user-images.githubusercontent.com/8822573/101919779-43fd3680-3bcb-11eb-8101-494e419f84d9.png)

## Steps to Reproduce the Problem
1. Try to exclude any data

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.63.0

**Comment by RomanenkoVladimir** [comment]
This issue only exists when excluding buildings via the search bar and not using a star "*".
Whne excluding "*.ts" for example the map is excluded correctly. Same for excluding by nodes/folders manually.
Do you think we should also exclude all folders when not using a *selector(this also doesn't work in single mode currently).

**Comment by RomanenkoVladimir** [comment]
If this isn't the issue this seems to have been fixed already, @BridgeAR could you take another look?

**Comment by RomanenkoVladimir** [comment]
Addition: Blacklist/Flatten tracking by index is bugged as well, we should adress this issue as part of the PR, now that the scope is changed to address *(wildcards).
