### ISSUE TITLE
Fixed folders map in delta mode causes errors

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1579]
# Bug

## Expected Behavior

GIVEN a fixed folder map

WHEN switching to delta mode

THEN no errors occur

## Actual Behavior

Errors occur.

## Screenshots
![image](https://user-images.githubusercontent.com/8822573/101920245-dd2c4d00-3bcb-11eb-91c4-a10642832f09.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.63.0

**Comment by DmytroHutkin** [comment]
Delta Mode:
1. If there is a single map, find true root folder.
2. If there are multiple maps with a single root folder, use that folder.
3. If there are multiple maps with multiple root folders, use "root" as new main root folder.

Singe Mode:
Find true root folder.

Multiple Mode:
...see delta
