### ISSUE TITLE
Visualization Data in cc.json

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#158]
# Feature request

Visualization data, aka. settings, for single maps (vs. delta etc. maps) in cc.json.

## Description

I'm using codecharta maps with our customer to give them the possibility to have a look at their system. Usually, I present slides containing pictures of maps and give them the cc.json files for having their own look at the maps with the visualization demo in the internet. It would be extremely helpful if the maps he is viewing with their cc.json resemble, at least in the key aspects, with the maps they have seen in my presentation. Therefore, it would be great if these key aspects for the  visualization of this project, could be saved in one file alongside with the other visualization data and loaded into the application.

One key value of codecharta maps is as in any map the overview and support in orienting in the system. Therefore, these value actually never change. These are the values I mean by key aspects of the visualization. Examples for them are, if customizable:
* filter rules to some degree
* camera position
* margins
* scenerios
* coloring for areas
* maybe labeling
* maybe scaling

In delta maps one usually uses the "configuration" of one of the "single case" maps. But, ATM i don't know how this relates to aggregation maps that are only parts of a whole visualization or other such completely different visualizations.

This issue is related and possibly in opposition to issue #156.

**Comment by alschmut** [comment]
In my opinion this is a very good issue! What would you think about the idea to also be able to save all currently used settings inside the same cc.json file? Especially the client had less effort to import another file. In the visualization we could give the option to save the settings or reset to default.

**Comment by mrpatpat** [comment]
I like the idea. I also like the idea to use the cc.json for saving settings.

**Comment by mrpatpat** [comment]
@ukinimod What do you think is a good representation of the highlighting data ? In #152 I just used a color code. I think that adding another layer of abstraction is not necessary. This would also make it possible to use all available web safe colors from cc.json.

**Comment by Richargh** [comment]
This discussion has moved to #182
