### ISSUE TITLE
Delta mode with non-matching entries cause errors

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1580]
# Bug

## Expected Behavior

GIVEN two maps that do not have the same nodes

WHEN entering delta mode

THEN one part of the map is 100% "positive" and the other is 100% "negative" without any errors.

## Actual Behavior

Errors occur.

## Screenshots
![image](https://user-images.githubusercontent.com/8822573/101921105-e538bc80-3bcc-11eb-9be4-a52d39ad3bc3.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.63.0

**Comment by DmytroHutkin** [comment]
@BridgeAR I'm trying to reproduce the case and I've got a following question:

> GIVEN two maps that do not have the same nodes

Does this mean two 100% divergent maps (incl. root folder)?

**Comment by BridgeAR** [comment]
@DmytroHutkin I have to check that again, I can't remember it right now :)

**Comment by BridgeAR** [comment]
This might be resolved due to another fix. Let's test this locally and update the issue accordingly.

**Comment by DmytroHutkin** [comment]
@BridgeAR **It seems to be solved by other issues and released already:**

![solved.gif](https://images.zenhubusercontent.com/5f8990b3edce07acb450c1fb/28f58322-bb69-4afa-acfc-14936d5811e4)
