### ISSUE TITLE
Imrove UI of slider

### ISSUE THREAD

**Issue by shaman-apprentice** [MaibornWolff/codecharta#1588]
# Feature request

## Description

As an user I want an intuitive ui without duplicated information nearby.

![image](https://user-images.githubusercontent.com/3596742/102095064-5c678e00-3e23-11eb-958e-25231378e8c8.png)

## Acceptance criteria
- Marked numbers to the left and right are removed
- Optional: If not to much effort, it would be nice, if the slider would take use of all available space

**Comment by BridgeAR** [comment]
@shaman-apprentice the numbers indicate that they may be changed while hovering. We should at least keep that feature:

![image](https://user-images.githubusercontent.com/8822573/103173745-4b743f00-485d-11eb-9548-24ab7a9c91d1.png)

It's probably enough to just keep the up and down arrows and always visualize them. @Gaugi28 what do you think?

**Comment by Gaugi28** [comment]
Entering the text has the advantage for the users that they can enter exact numbers. With a slider it's more difficult to get a certain number depending on the number range.
If you only keep the arrows, it must be clear what the user changes with these arrows. There should be labels which indicate which value the user changes with the arrows.

**Comment by BridgeAR** [comment]
I would be fine with a slider similar to [rSlider](https://www.cssscript.com/demo/animated-customizable-range-slider-pure-javascript-rslider-js/).

![image](https://user-images.githubusercontent.com/8822573/141878251-a2a8af72-564e-4e73-b22e-d80a46162cea.png)

I would however not want to invest a lot of energy into improving the slider at the moment. There is just too little benefit by it.

I am therefore going to close this for now. We might come back to this at a later point.
