### ISSUE TITLE
Hiding ColorChooser when in delta mode

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#159]
Hiding ColorChooser when in delta mode

# Feature request

The color chooser on top is misleading when in delta mode and should be hidden or replaced by something else.

**Comment by mrpatpat** [comment]
This is partly implemented in #161. Color settings in the side menu are still available and should be hidden.

**Comment by Richargh** [comment]
We chose not to hide the color choser, because it is useful to see the value of a metric, even if it has no influence on the color. We might remove the icon though or black it out at a later point in time.
