### ISSUE TITLE
Slider not initialized correctly

### ISSUE THREAD

**Issue by shaman-apprentice** [MaibornWolff/codecharta#1592]
# Bug

## Expected Behavior

<GIVEN>

WHEN I open the map and its color option

THEN the slider is initialized correctly

## Actual Behavior
Sometimes (most often in small maps) the max slider is on the min slider

## Screenshots
![image](https://user-images.githubusercontent.com/3596742/102195848-650da200-3ebf-11eb-8edf-9d0fb81df98d.png)

## Steps to Reproduce the Problem
Most often can be seen in local developed chrome with standard small sample1.cc.json

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes 
- CodeCharta Version: 1.6.4
- OS: Windows
- Browser: Chrome

**Comment by shaman-apprentice** [comment]
Dev notes: https://github.com/angular-slider/angularjs-slider#common-issues looks kind of related and the following code does indeed fix it. But we should come up with a better solution than the hardcoded timeout.

_rangeSlider.component.ts:_
```js 
	$postLink() {
		this.$timeout(() => {
			this.$scope.$broadcast('rzSliderForceRender')
		}, 3000);
	}
```

**Comment by BridgeAR** [comment]
@shaman-apprentice it's described as a single millisecond timeout in the module. Does that suffice as well?

**Comment by shaman-apprentice** [comment]
@BridgeAR it is described as a millisecond timeout after it has become visible. In the current implementation the slider doesn't know when it becomes visible. So it might be enough to integrate that in an onOpen method somewhere.

**Comment by shaman-apprentice** [comment]
What also makes me wonder is, that the timeout 3000 worked, even if the slider has not become visible in the meantime. So I am not sure, where the race condition is, but at some point firing `this.$scope.$broadcast('rzSliderForceRender')` will probably fix it.

**Comment by BridgeAR** [comment]
If I am not mistaken, it's possible to determine when the parent becomes visible (due to e.g., listening to the correct event or triggering a JS function on show)?
