### ISSUE TITLE
Cannot upload compressed .gz files

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#1593]
# Bug

## Expected Behavior

WHEN
Uploading a compressed .gz file

THEN
the file will be unziped and if the map is valid it is loaded properly.

## Actual Behavior
an error message appears "File invalid or empty"

## Steps to Reproduce the Problem
1. Click the "load map" button on the upper left
1. Upload a .gz file

## Developer Notes
- The fileChooser component tries to unzip the compressed file.
- Then a `Uint8Array` is returned from the `zlib` library.
- We then mistakenly assume that the `Uint8Array` is a Json string which we can parse with `JSON.parse(content)`.
- This results in the aforementioned error message.
- I think we must handle a buffer array differntly, converting it to string and then parse it as a JSON.
- We have to add tests for that.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.64.0
- OS: Windows
- Browser: Chrome

**Comment by BridgeAR** [comment]
Do we know why our tests did not cover this case?

**Comment by ce-bo** [comment]
This is because we do not have any tests for uploading .gz files. Neither unit tests nor e2e tests.

**Comment by BridgeAR** [comment]
😕 we should really only land PRs that are fully covered (or at least fully test the main features).

**Comment by Shivan-997** [comment]
Import procedure works so far. but only with a certain compression method.

**Comment by ce-bo** [comment]
We should support more ZIP-Algorithms -> Change this issue to a feature request with low priority.

**Comment by Shivan-997** [comment]
look at Issue #1702. the implementation is handled there.
