### ISSUE TITLE
Bug collections concerning map rendering and margins

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#1609]
# Bug

- When changing the margins, the height of the building should not change.
- Refactor how we zoom the map. Currently we move the "Kegel" to zoom in and out but threejs can do that by its own (pass the zoom to threejs).
- treeMapGenerator.js: Do not estimate the map size, calculate it: read the view port size substract some pixels to have space between the view port and the drawn map and consider the current zoom factor. The resulting numbers should be passed to threejs, so that the map fits perfectly into the view port.
- By default all buildings should be visible (this can be achived by modifying the zoom level)

@RomanenkoVladimir @BridgeAR 

## Open TODOs before merge:
- [x] Re-enable Floor Labels
- [x] Add/Expand Unit Tests for area calculation
- [ ] #3146

## Bugs (currently in main):
- Fix "floor labels next to the maps" after changing height scaling #2611 .
- [ ] #3145

**Comment by Med-H** [comment]
I think the margin problem could be solved when using the d3 hierarchy padding property 
https://github.com/d3/d3-hierarchy#treemap_padding

in this page you can check it in action
https://observablehq.com/@d3/animated-treemap

**Comment by ce-bo** [comment]
I will check the open tasks after the next release. For now, I decrease the priority because the urgent tasks have been addressed.

**Comment by ce-bo** [comment]
I close this issue since the main (urgent) parts have been solved. 🥳 
Open issues are tracked by #3145 and #3146 .

**Comment by ce-bo** [comment]
Thank you @BridgeAR. I just added two new issues #3148 and #3147 with different priorities to track point 2 and 4.
