### ISSUE TITLE
Labels are placed at the wrong height

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#1618]
# Bug
Temporary labels are placed at the wrong height if the buildings are height-scaled 

## Expected Behavior

GIVEN
A map with height-scaled buildings

WHEN
hovering a building which has no visible label

THEN
a temporarily drawn label should be shown on top of the scaled building

## Actual Behavior
the label is shown at the wrong height

## Screenshots
![image](https://user-images.githubusercontent.com/26900540/102988503-47ba8280-4514-11eb-923b-6153e776ec1d.png)

## Steps to Reproduce the Problem
1. Open the Height Metric Options and scale the buildings to lets say a factor of 3
1. Hover a building with no visible label

**Comment by BridgeAR** [comment]
Let's try to fix all our open bugs and write lots of tests for them.

**Comment by BridgeAR** [comment]
Seems like it's also an issue for big maps:

![image](https://user-images.githubusercontent.com/8822573/103174016-06e9a300-485f-11eb-8370-64efdb25e155.png)

The height was not changed manually. This is just the default case loaded.

**Comment by Gaugi28** [comment]
This bug occurs also in the delta mode.

**Comment by RomanenkoVladimir** [comment]
Ok, I investigated that issue.
The problem is current scaling is only applied to all drawn labels at the moment of scaling the building.

This is a problem because another bug stemming from this is resetting labels to 0 and then reenabling them on a scaled map will also result in labels disappering inside buildings.

**Comment by BridgeAR** [comment]
Reopening as it's still an issue.

![image](https://user-images.githubusercontent.com/8822573/104927197-6724be00-59a1-11eb-86a0-170027e60b39.png)

Just switch to delta mode with the default map.

**Comment by RomanenkoVladimir** [comment]
I think its a problem with the delta mode of the map(height is 84, delta height is also 84 = 168)
I tested it  with our smal maps as delta and it works, furthermore when switching the two maps in delta mode in the online demo it works as well. Maybe we should take a look at that

**Comment by RomanenkoVladimir** [comment]
@BridgeAR I tested it some more and its indeed an error with the deltaHeight calculation for this map, the label is placed "correctly", the values are just wrong.
Should I open an issue for that?

**Comment by BridgeAR** [comment]
@RomanenkoVladimir please feel free to do so and ideally already open a PR to fix it?
