### ISSUE TITLE
Visible labels will disappear or placed lower

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#1619]
# Bug
for scaled bulidings only!

## Expected Behavior

GIVEN
A map with height-scaled buildings

WHEN
changing the margin or the labels to be shown

THEN
visible labels will be placed correctly above the bulidings

## Actual Behavior
visible labels will placed lower or they will disappear within a 3D Building

**Comment by BridgeAR** [comment]
Let's try to fix all our open bugs and write lots of tests for them.

**Comment by RomanenkoVladimir** [comment]
Same issue as #1618, the scaling logic does not support scaling newly drawn buildings, it never did. When we change the amount of labels they will get redrawn and therefore loose the scaling.
