### ISSUE TITLE
The "maximum treemap files" is always visible

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1624]
# Bug

## Expected Behavior

GIVEN a user has opened the global settings

WHEN not using the "TreeMapStreet" layout

THEN there should not be an option to specify the maximum treemap files as it has no functionality on those layouts.

## Actual Behavior

The option is always visible.

## Screenshots

![image](https://user-images.githubusercontent.com/8822573/103099790-263ec100-4610-11eb-8397-9f4fe807f0a7.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.65.0

**Comment by ce-bo** [comment]
I think this bug has not been fixed correctly. The option should be visible for "TreeMapStreet" only and not for "Squarified TreeMap"

**Comment by ce-bo** [comment]
@Med-H could you please have a look at it?
