### ISSUE TITLE
Folders and files to highlight can be described in the cc.json

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#165]
Still needs to be evaluated if presentation and data should be in the same file. It might also be a good idea to even place the general configuration in the cc.json. We also need to evaluate how the new structure should look like.

**Comment by mrpatpat** [comment]
This feature is "allowed" since #186. This means that it is possible to use the cc.json to mark folders but it won't be officially supported/removed until this issue here is resolved. 
Reason for this decision is that reading the marking color from the cc.json needs to be forbidden explicitly.

**Comment by Richargh** [comment]
This discussion has also moved to #182
