### ISSUE TITLE
Change dependabot update policy

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1650]
Please update our dependabot settings to use a new versioning-strategy. We should only receive a PR if a change to our `package.json` is necessary, not if it only changes the `package-lock.json`

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#versioning-strategy

**Comment by shaman-apprentice** [comment]
If I am not mistaken [versioning-strategy](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#versioning-strategy) describes how the _package.json_ is updated related to changes in _package-lock.json_ or allows to disable PR for changes, which update only _package-lock.json_.

With [allow](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#allow) we can set it to direct dependencies only (`allow: direct`), which I believe is described in this FR.

Maybe it is interesting to set it to `allow: production`, to skip updates of all _devDependencies_ like eslint? My first intuition would be to keep them as updates in webpack can make a huge different in build time, or I want to use latest TypeScript features.

**Comment by Jacob-Kirimi** [comment]
@shaman-apprentice Hi, are you still working on this issue?

**Comment by BridgeAR** [comment]
@Jacob-Kirimi Torsten removed his assignment, it should be free to grab :)

**Comment by Jacob-Kirimi** [comment]
I Have created the branch again as it was deleted the last time it was merged into main.We can revert the changes that removed config.yml from the main branch and wait to see if pull requests will be created. When this functions then we can automerge the changes that only affect package-lock.json.
