### ISSUE TITLE
wrong reset icon position when using color picker

### ISSUE THREAD

**Issue by Med-H** [MaibornWolff/codecharta#1682]
# Bug

## Expected Behavior

WHEN opening the color picker

THEN the reset button should be properly positioned

## Actual Behavior

the reset button is positioned in the wrong place

## Screenshots

![image](https://user-images.githubusercontent.com/74670211/105011572-65103d00-5a3d-11eb-8427-d0e729db062e.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.6.6
- OS: windows
- Browser: chrome

**Comment by RomanenkoVladimir** [comment]
This is the case for all of the top bar components, not only for the color picker
I'm going to look if we can quickly fix this
