### ISSUE TITLE
Branch and commit naming conventions

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#170]
# Branch and commit naming conventions

## Description
We should use the same language for naming branches (underscore, hyphen, camel case, ...) and commits (updating, update, rewriting, correcting, ...).

See branch [docs/naming-conventions](https://github.com/MaibornWolff/codecharta/blob/docs/naming-conventions/CONTRIBUTING.md#naming-conventions)

**Comment by alschmut** [comment]
@mrpatpat @Richargh @ukinimod @FernandoES please have a look inside the changed doc. Is this a possible solution for unified naming? If not, what would you like to change?

**Comment by mrpatpat** [comment]
I like the suggestions. @Richargh and me also discussed our branching model. My first suggestion was to use git flow but Richargh suggested to use the more lightweight github flow. I think github flow combined with your changes should be a good solution

**Comment by FernandoES** [comment]
Read. I agree with everything but the structure "If applied, this commit will blah...", I would write directly the blah, in order to reduce unnecesary length of committing

**Comment by Richargh** [comment]
Can we change "internal" to "tech", as in technical story? 

Can we remove "tests" and "release". A pure test commit seems strange to me, a release commit as well. If I remember correctly we tag our releases instead. 

And finally, can we change <type>/<name> to also include the issue id? That would be immensly helpful for me to find the branch a feature is being developed on.

**Comment by alschmut** [comment]
solved with #183
