### ISSUE TITLE
Switch parser compression default

### ISSUE THREAD

**Issue by Shivan-997** [MaibornWolff/codecharta#1702]
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As User, I want to save space on my device and only want zipped files by default.

## Acceptance criteria
Our internal parsers all generate gz files by default.

**Comment by BridgeAR** [comment]
I had another look at it and it should actually be sufficient to load our own compressed files as long as we are certain they are able to be loaded.

We should switch the default for our parsers to gzip the files.

Otherwise we ship things that are not essential.

**Comment by BridgeAR** [comment]
I changed the description of the task accordingly.
