### ISSUE TITLE
Infinite Loading of Maps in Firefox / Blank map in Chrome

### ISSUE THREAD

**Issue by alexhunziker** [MaibornWolff/codecharta#1710]
# Infinite Loading in Firefox / Blank map in Chrome

Hello, I noticed the following behavior when I was trying to analyze some of our projects with CodeCharta:

## Actual Behavior

When I try to open larger maps (~3-5MB, about 20k files) generated by the Tokei importer, loading the map into the visualization does not terminate.
In Chrome, the map can be loaded and displayed, however it sometimes crashes and then the map disappears (see screenshot attached). It seems to be reproducible when trying to flattening buildings in large maps. On my system the window flashes black quickly and then the map is gone, the console shows just a warning from WebGL, see screenshot.

## Screenshots
![empy_cc](https://user-images.githubusercontent.com/20796577/106491479-32435b80-64b7-11eb-8829-945bc16f67b2.png)
![cc_crash_console](https://user-images.githubusercontent.com/20796577/106492568-5ce1e400-64b8-11eb-95ae-1f6af7b297d0.PNG)

## Steps to Reproduce the Problem
1. Load a larger file (>3MB, 20k nodes) in the visualization in Firefox / Chrome
1. Observe that it loads forever

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.67.0
- OS: Windows 10
- Browser: Firefox 84 / Chrome 88

**Comment by alexhunziker** [comment]
Oh i forgot to post the error message of firefox, here we go: 
![image](https://user-images.githubusercontent.com/20796577/106566668-e59c6680-6530-11eb-8e30-e38c37aa4893.png)

**Comment by Med-H** [comment]
> Oh i forgot to post the error message in the console of firefox, here we go:
> ![image](https://user-images.githubusercontent.com/20796577/106566668-e59c6680-6530-11eb-8e30-e38c37aa4893.png)

@alexhunziker can we have access to the cc file ?

**Comment by alexhunziker** [comment]
Hi @Med-H 

Thank you for the quick response. Attached you find the file that caused the issue. I just had to alter the names of files and folders for confidentiality reasons.
[anon.cc.json.zip](https://github.com/MaibornWolff/codecharta/files/5919471/anon.cc.json.zip)

**Comment by Med-H** [comment]
It does in deed load crash under firefox, It is most probably caused by the canvas textures which consumes a fairly big amount of GPU ram. We might want to investigte on another approach for rendering the text.

**Comment by Med-H** [comment]
this is definetly due to the usage of a large amount of textures for the text
![image](https://user-images.githubusercontent.com/74670211/108719283-a9509a80-751f-11eb-8814-35cd9157cce7.png)
>700 MB of used textures !

**Comment by RomanenkoVladimir** [comment]
@BridgeAR this seems connected/ to be the same issue as the one discussed in teams

**Comment by BridgeAR** [comment]
This issue is likely already resolved?

**Comment by ce-bo** [comment]
I can load the anon.cc.json map relatively quickly in Chrome (Win64).
