### ISSUE TITLE
Labels and lines are not connected

### ISSUE THREAD

**Issue by Med-H** [MaibornWolff/codecharta#1716]
# Bug

Labels and lines are not connected

## Expected Behavior

GIVEN 

A ccjson file ( ex the AM sonar one )

WHEN

Zooming in the map and hovering on the buildings.

THEN

The labels and lines are connected.

## Actual Behavior

![image](https://user-images.githubusercontent.com/74670211/106585671-dd9bf100-6547-11eb-9ba0-044f9bbb8454.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes 
- CodeCharta Version: 1.67.0
- OS: Windows
- Browser: Chrome

**Comment by RomanenkoVladimir** [comment]
Here we need to get the new center point of the label after popup(threeJS can do that for us) and pass it to the line to change its draw height, maybe account for offsets. Should be easy to fix.
