### ISSUE TITLE
Add temporal coupling to ccsh and visualization

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#172]
parent of #210, parent of #211, parent of #212, parent of #213, parent of #214, parent of #215, parent of #216, parent of #217, parent of #218, parent of #219

Use [feature/172/visualizing-edges](https://github.com/MaibornWolff/codecharta/tree/feature/172/visualizing-edges) to checkout a branch.

## Description
1. Build an Importer for the SCM metric tool CodeMaat https://github.com/adamtornhill/code-maat. Check out http://www.adamtornhill.com/code/crimescenetools.htm to download an executable codemaat.jar file.

    ![codemaatimport-modell](https://user-images.githubusercontent.com/23529226/45157514-4ba62780-b1d9-11e8-801f-fd79cf40d072.jpg)

    The command takes a CSV table with the coupling data provided by CodeMaat and returns a cc.json schema conform JSON file. The `coupling.cc.json`-file will not have any Treemap-Metric data and therefor needs to get merged with another file, which contains usual metric data for every file.

    `ccsh codemaatimport coupling.csv -o coupling.cc.json`

2. Visualize the temporal coupling data inside the CodeMap. Other Issues how to implement in concrete terms follow.

## Issues still to create:
- by @ukinimod: Personally I would map the pairing rate to the colour. I find this more intuitive than the height, although the height could be better to keep the overview. Nevertheless I don`t figure displaying hierarchy, coupling and three metrics at the same time is sensible in any way (yes, I'm always for a minimal feature set), therefore this feature could imho be deleted.
- by @richargh: It might also be interesting to see coupling between large packages. No clue how to visualize that however.
- by @richargh: I wonder if it makes sense to color the buildings that are paired together in the same color. In addition to the arrows. Or maybe give them "hats" that are the same color.
- by @ukinimod: It's probably only vaguely related to this pr, but I guess this context is good enough to answer an offline question of @Richargh.

    what I and some collegues, including @silasg, would find very interesting (mostly in the analysis use case) to be able to display the (especially temporal) coupling for certain hotspots. I'm not quite able to put it in good words, but I would describe it as the degree the "foulness" of this class / file is spread across the project.

    One possible visualization that we discussed for this, is a way to select the file, that is considered as hotspot. Then something like the pairing rate for all (temporal) coupled (with a possibly configurable limit) are coloured by their degree (e.g. pairing rate) of dependency.

**Comment by alschmut** [comment]
@Richargh check out the current version of [feature/172/visualizing-edges](https://github.com/MaibornWolff/codecharta/tree/feature/172/visualizing-edges). See updated [CHANGELOG.md](https://github.com/MaibornWolff/codecharta/blob/master/CHANGELOG.md). The Edges-Panel is not yet updated to be more generic!
```
- CodeMaatCouplingImport to Analysis #172
- Option to show and hide dependent edges from node-context-menu #218
- Select edge-attributes in MetricChooser #217
- See edge-attributes inside detailPanel #217
```

**Comment by Richargh** [comment]
I just had a good discussion with @silasg and we had some questions. Let's say Node A --(avgCommits=5)-->Node B and Node A --(avgCommits=3)-->Node C. Which pairingRate is used as height for NodeA? Which one is used for nodes B and C? 

Our feedback is this:

* Please remove avgCommits and pairingRate from the MetricChoser. Same for the detailPanel.
* *Create a filter* that sums all nodes attributes (avgCommits_sum), means all percentage attributes (pairingRate_mean) and adds it to the nodes in the cc.json. An example interface is this: `ccsh edgeFilter edgesin.cc.json -o edgesout.cc.json` Then we can use the MetricChooser to select pairingRate_mean for color and find foul classes.
* Show the edges with arrows of each selected building (currently we can only select one building but we might change that in the future) 
* Remove the table from the edges panel, same for the commit slider. We do not need it, if we can use the pairingRate_mean as color to found the foul classes.
* The edges panel should then only contain a checkbox for *show arrows*.

**Comment by Richargh** [comment]
I am on the fence, should we place the logic in the UI or in the filter: 

I wouldn't say it's less work for the user to have it in the UI. You always need something like `ccsh sonarimporter -o sonar.cc.json`, `ccsh codemaatimporter -o coupling.cc.json` and `ccsh merge sonar.cc.json coupling.cc.json -o merge.cc.json`. Now we are talking about adding another `ccsh edgeFilter -o couplingedges.cc.json`. One more step is not the issue.

It's annoying if someone forgot to include the edgeFilter. *That's what I am concerned about*. I think we can conquer that by referencing the edgeFilter from the the codeMaatImporter in the help. 

The **benefit** is that we can see the result even in older versions of CodeCharta, we can easily throw away the filter if we don't like it and our visualization code stays dumber, which is always a plus :) And, since I have different opinions about other pieces of logic, placing it in the analysis/edgefilter matches the workflow of the user.

* place it in the ccsh, separate from the codemaatimporter
* in the future I want to select multiple buildings, for this feature we only need to select one building
* and finally on the topic of aggregation:

With a good nights sleep, let's not use "aggregation". Let's instead describe the type of the attributes instead. Our code then selects how to aggregate. It's a small change but I think it makes more sense to describe the type. Currently there are two types we can think of: absolute and relative attribute numbers. But [Wikipedia lists](https://en.wikipedia.org/wiki/Aggregate_function) 8 common aggregation functions. Thus I think "attributeTypes" is more future proof:

```json
"attributeTypes": {
  "nodes": [
    {"loc": "absolute"},
    {"testcoverage": "relative"}
  ],
  "edges": [
    {"pairingRate": "absolute"}, 
    {"averageRevs": "relative"}
  ]
}
```

**Comment by Richargh** [comment]
@alschmut we probably need the separation as `nodes` and `edges`. Let's take the metric *loc*. *loc* for a node is **absolute**. Another tool could create an edge to describe what percentage of lines in a class couple to another class and also represent that as *loc*. Here *loc* would be **relative**. It's a hypothetical example for sure but it does show that we have no mechanism to ensure that attributes  are unique in nodes and in edges.

What do you think? Does it cost us anything to have attributeTypes for nodes and edges? Do you see any downsides?

**Comment by alschmut** [comment]
@Richargh no it will definitely work with nodes and edges, I just thought to have it as generic as possible ;) btw: in the ccsh we have the power to rename every attribute.

**Comment by Richargh** [comment]
@alschmut What is the current progress on this item? Also does it make sense for other developers to help you out?

**Comment by alschmut** [comment]
@Richargh I've finished the edgefilter to aggregate the edge-attributes and add them to the appropriate node as node-attributes. Now as I merged the master branch into it, there is a bug in the visualization. Hovering a building flickers and selecting isn't possible... At the moment I really don't know where that comes from. @mrpatpat @felixherbst @FernandoES do you have any ideas?

**Comment by mrpatpat** [comment]
@alschmut I did not yet check out the branch so I may be wrong. My first guess in terms of flickering 3D scenes would be multiple faces on the same coordinates or at least faces which are too close. This would explain the hover problems, too. 

I will look into this as soon as possible.

**Comment by Richargh** [comment]
The flickering is really annoying. Also I do not see a single arrow in the default map with three buildings. Can you include more sample data so I can see how the visualization looks?

**Comment by Richargh** [comment]
I just checked out the version. Looks good to me.
