### ISSUE TITLE
Try out another ray intersection algorithm

### ISSUE THREAD

**Issue by Med-H** [MaibornWolff/codecharta#1737]
# Feature request

when hovering a building we trigger https://github.com/MaibornWolff/codecharta/blob/eeebfa2ebffba8ee64ea17df59a0bbcff0bdb8ca/visualization/app/codeCharta/ui/codeMap/codeMap.mouseEvent.service.ts#L208 leading to the call of https://github.com/MaibornWolff/codecharta/blob/eeebfa2ebffba8ee64ea17df59a0bbcff0bdb8ca/visualization/app/codeCharta/ui/codeMap/rendering/codeMapGeometricDescription.ts#L31-L58

this is a potential cpu consumer.

## Some Ideas

- Try out to optimize the raycasting using [octree](https://www.i-programmer.info/programming/theory/1679-quadtrees-and-octrees.html)

- Maybe implement a bounding view hierarchy [bvh](https://github.com/gkjohnson/three-mesh-bvh)

**Comment by ChristianHuehn** [comment]
Performance is an issue but not a focus at the moment, will keep in mind when getting to this in the future
