### ISSUE TITLE
Fix e2e Visualisation 'Node is either not visible or not an HTMLElement'

### ISSUE THREAD

**Issue by Med-H** [MaibornWolff/codecharta#1785]
# Bug

## Expected Behavior

e2e test should always pass

## Actual Behavior
at least this example will fail 

   > FAIL app/codeCharta/ui/fileChooser/fileChooser.e2e.ts (42.877 s)
      FileChooser › should keep the old map if opening a file was cancelled
      Node is either not visible or not an HTMLElement

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes | no
- CodeCharta Version: 1.68.0
- OS: windows 10
- Browser: chrome

**Comment by JaiJoPa** [comment]
fixed
