### ISSUE TITLE
changing display or color settings resets zoom

### ISSUE THREAD

**Issue by silasg** [MaibornWolff/codecharta#18]
when I change (at least) invert colors or toggle delta cubes, (at least) the z axis zoom is reset. however, the UI control for this zoom is not updated.

**Comment by mrpatpat** [comment]
When I invert the colors or toggle the delta cubes after i changed the zoom level, the z-axis zoom is not reset. Can you specify the problem and add your browser version ?

**Comment by silasg** [comment]
Sorry I meant y axis scaling, not z axis zoom ;) using chrome 58 on mac os, but I think I’ve also ween this using the windows electron container.





__________________________________________________

Blockchain: Euphorie oder Schockstarre – mehr in den
Praxis-Tipps https://www.maibornwolff.de/newsletter/1-2017
__________________________________________________

Silas Graffy
Senior IT Architect


Mobil +49 151 544 22 047
silas.graffy@maibornwolff.de
Baseler Straße 10, 60329 Frankfurt am Main

MaibornWolff GmbH, Theresienhöhe 13, D-80339 München
http://www.maibornwolff.de, Telefon +49 89 544 253 000
USt-ID DE 129 299 525, Amtsgericht München HRB 98058, GF:
Volker Maiborn, Holger Wolff, Jens Rieger, Alexander Hofmann

__________________________________________________

On 9. Jun 2017, at 12:03, mrpatpat <notifications@github.com<mailto:notifications@github.com>> wrote:


When I invert the colors or toggle the delta cubes after i changed the zoom level, the z-axis zoom is not reset. Can you specify the problem and add your browser version ?

**Comment by mrpatpat** [comment]
Thank you for the contribution. I was able to reproduce this issue. I will fix it as soon as possible.

**Comment by mrpatpat** [comment]
fix is merged. It will be part of the next release.
