### ISSUE TITLE
Standalone tool that wraps the analysis part and the visualization part.

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#180]
<img width="1406" alt="standalone-edited" src="https://user-images.githubusercontent.com/28268662/41784764-fd50d43c-7640-11e8-97c6-02c104f18c11.png">

**Comment by ukinimod** [comment]
I don`t really know what's the intention and use-case behind this issue. At the moment codecharta is an expert tool, at least what the analysis part is concerned, what in my opinion matches the main two user of the tool, analysis experts and architects. I think something that makes codecharta more accessible to a broader user group by adding a layer for non-expert user would be great. Actually I would suggest to go even another layer on top. I would hide all the interna concerning analysis tools, like Sonar, Understand... and only takes links to repositories and does the whole analysis. I personally think a visual representation of the analysis steps is not neccessary.

**Comment by Richargh** [comment]
I would say "CodeCharta is a communication tool for people with different backgrounds to be able to discuss the important issues". But it has a high entry barrier.

Currently the process if someone wants to try codecharta is: npm install codecharta-analysis and then ccsh import [etc]. To a non-technical user those steps are cumbersome and reduce the motivation to try CodeCharta to almost nothing. 

> I would hide all the interna concerning analysis tools, like Sonar, Understand... and only takes links to repositories and does the whole analysis.

--> I agree to that statement fully. That is the intention of this issue. One program that makes it as easy as possible to try and use codecharta with my own software.

**Comment by ukinimod** [comment]
My opinion is probably of no matter, but I would say that it is highly questionable for a non-technical user to make an analysis, even for trial. Using the terminal via ccsh import ... should be just as easy for a technical user as clicking some buttons in a ui (that's exactly what the screenshot shows) and is furthermore repeatable and programmable. Yes, I know, that is disputable, but it's also an existing and working implementation. I would question your opinion, that the motivation is thus reduced by having to use the terminal.
As a current and high user of codecharta I would be very glad, if you would concentrate on things like implementing or integrating codecharta with a good metric tool, saving visualization and highlighting data in the cc.json, more sensible scenarios, various ui quickwins like summary of number of items / rloc in layer or for special color, filtering out parts in the cc.json etc. That's the kind of features I and probably every one that earnestly wants to use CodeCharta with real data dearly misses. Yes, the user interface is an entry barrier, but missing the latter features are potentially fatal for longterm usage.

The key question is, do we want to open operating all of CodeCharta to people "with different backgrounds" / "non-technical users" or only usage of the visualization and leave operation of the analysis to skilled user that can handle a terminal or possibly gradle... As of now, the focus was clearly on the latter for various reasons. I think if you want to broaden the focus there should at least be a discussion as to what the consequences are etc.

**Comment by mrpatpat** [comment]
I really like this suggestion. 

I get two kinds of feedback: From "experts" who mostly understand the process and others who are overwhelmed by the entry barrier. Honestly, I myself would love to just enter a repo url and get a result. 

Although I like the idea of simplifying things we must not forget that the command line tools are necessary for applications in CI or building custom scripts for analyzing. They should always come first. 

Keep in mind that analyzing requires a jvm and therefore cannot be easily started from a browser. This standalone version must be running on a desktop or some kind of server with a jvm.

**Comment by Richargh** [comment]
We haven't gotten around to this and #683 might be the better solution anyway
