### ISSUE TITLE
A filter to remove unneeded parts from the cc.json

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#181]
## Context

Source code sometimes contains vendor code (angular, hibernate, etc.) which shows up in the cc.json and then in the visualization. We do not need that code, because it is beyond our scope and frankly out of our control. 

## Description

We want to permanently remove vendor code from our cc.json, even if it is placed on some form of sublayer. 

The interface should be the one suggested by @ukinimod below:

`ccsh filter -exclude "src/main/de/**/*Test.java" test.cc.json > filtered_test.cc.json`

**Comment by ukinimod** [comment]
What would be practical for me is an integration in ccsh via regex (e.g. ant-style regex), e.g. via
ccsh filter -exclude "src/main/de/**/*Test.java" test.cc.json > filtered_test.cc.json
or 
ccsh filter -f filter.txt test.cc.json > filtered_test.cc.json

Consequently, these filtered nodes should be treated, at least by default, as non-existant in the visualization.

Usually I try to already filter out these files with the analysis tools, e.g. understand, by setting the filters there, but in case we no longer have the sources it is not possible to redo the analysis with the correct filters. Therefor it's probably a non-standard use-case for me.

**Comment by mrpatpat** [comment]
I like this feature. What do you think about a flag for something like a soft and hard filter? The hard filter removes the nodes completely from the file and the soft filter just presets the visibility.

**Comment by alschmut** [comment]
@mrpatpat I like the idea of a flag!

**Comment by ukinimod** [comment]
@mrpatpat I personally have no need for a soft filter in my analysis. If needed one could use the filter in the visualization. If someone needs the soft fiter it could maybe implemented later?

**Comment by Richargh** [comment]
Reopenend because there are many cases where items should not be in the cc.json at all. node_modules, vendor librararies or similar significantly slow down the `ccsh mergefilter`. To combat this issue we want to permantenly remove them from the cc.json.
