### ISSUE TITLE
Place to collect additions to the cc.json

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#182]
Please add data that you consider adding to the followng bullet point list:

* an id for each "File" so can realibly compare files that have been moved (data might come from version control system)
* user settings (camera angle, position, selected metrics)
* metric description (long text that describes what each metric means, will be created by the corresponding importer)
* markingColor for highlighted packages, marked packages, pinned buildings
* exclude tag, which can treat the node, at least by default, as non-existant #181 
* different types of dependencies/edges

## Current cc.json top-structure
```json
{
    "projectName": "codecharta",
    "nodes": [],
    "apiVersion": "1.0",
    "edges": []
}
```

**Comment by Richargh** [comment]
@alschmut can you explain your critique in a different way? I don't understand it.

**Comment by Richargh** [comment]
New cc.json idea. Look out for all the comments with `// NEW`

```json
{
    "projectName": "rojectName",
    "apiVersion": "1.0",
    "createdOn": "9.8.2018", // NEW some form of timestamp with date and time
    "nodes": [{
        "name": "root",
        "type": "Folder",
        "attributes": {},
        "link": "",
        "children": [{
            "name": "src",
            "type": "Folder",
            "attributes": {},
            "link": "",
            "children": [{
                "name": "de",
                "type": "Folder",
                "attributes": {},
                "link": "",
                "color": 1, // NEW, can be a specific id, that maps to our default color
                // OR a string with a hex code "color": "#123"
                "children": [{
                    "name": "Foo.java",
                    "type": "File",
                    "attributes": {
                        "mcc": 39,
                        "lines_of_code": 212,
                        "rloc": 182
                    },
                    "fractionAttributes": {
                        "coverage": 100 // NEW
                    },
                    "link": "",
                    "children": [{
                        "name": "maibornwolff",
                        "type": "Folder",
                        "attributes": {},
                        "link": "",
                        "children": [{
                            "name": "codecharta",
                            "type": "Folder",
                            "attributes": {},
                            "link": "",
                            "children": [{
                                "name": "Bar.java",
                                "type": "File",
                                "attributes": {
                                    "mcc": 39,
                                    "lines_of_code": 212,
                                    "rloc": 182
                                },
                                "fractionAttributes": {
                                    "coverage": 50 // NEW
                                },
                                "link": "",
                                "children": []
                            }]
                        },
                        {
                            "name": "Blub.java",
                            "type": "File",
                            "attributes": {
                                "mcc": 39,
                                "lines_of_code": 212,
                                "rloc": 182
                            },
                            "fractionAttributes": {
                                "coverage": 70 // NEW
                            },
                            "link": "",
                            "children": []
                        }]
                    }]
                }]
            }]
        }]
    }],
    "timeTravel": [
        {
            "nodeName": "root/src/de/maibornwolff/Blub.java"
            "previousNodeNames": [
                {
                    "timestamp": "2018-10-12:10:15", // IMPROVEMENT: should have the name and timestamp as the one on top
                    "name": "CoolStuff.java"
                }
            ]
        }
    ]
    "edges": [{ // NEW 
        "fromNodeName": "/root/src/de/Foo.java",
        "toNodeName": "/root/de/maibornwolff/codecharta/Bar.java",
        "attributes": {
            "averageRevs": 9
        },
        "fractionAttributes": {
            "pairingRate": 100
        }
    }],
    "blacklist": [{ // NEW - ANT-style path
        "exclude": "Blub.java"
    }],
    "attributeDescription": [{ // NEW
            "name": "coverage",
            "displayName": "Code Coverage"
            "description": "The code coverage measures blah blah and is calculated by blah blah"
        },
        {
            "name": "mcc",
            "displayName": "Code Complexity",
            "longDisplayName": "Complexity by McCabe",
            "description": "The code coverage measures blah blah and is calculated by blah blah"
    }],
    "userSettings": { // NEW
        "camera": {
            "angle: 110.5,
            "position": {"x": 5, "y": 7, "z": 12}
        },
        "size": {
            "selectedAttribute": "rloc",
            "margin": 15,
            "autoMargin": true
        },
        "height": {
            "selectedAttribute": "mcc"
        },
        "color": {
            "selectedAttribute": "coverage",
            "firstColor": "#red",
            "secondColor": "#red",
        }
    }
}
```

**Comment by alschmut** [comment]
Inside the cc.json schema the Treemap is stored inside the variable `nodes`
```
{
    "projectName": "codecharta",
    "nodes": [
        {
            "name": "root",
            "type": "Folder",
            "attributes": {},
            "link": "",
            "children": []
        }
    ],
    "apiVersion": "1.0"
}
```

Inside the visualization the Treemap is stored inside the variable `root`
```
export interface CodeMap {

    fileName: string,
    projectName: string,
    root: CodeMapNode,
    dependencies?: CodeMapDependency[]
}
```
And I would prefer to change (probably the visualization one), so its the same. It is especially confusing when writing test-cc.json-files inside the visualization, using the CodeMap interface, while using the variable name `nodes` so it gets read correctly as a real cc.json file.

**Comment by alschmut** [comment]
The following is just my opinion and not necessarily the correct one:
- I would use at least the full date (with zeros) and preferably formatted like this: `"createdOn": "2018-09-08"`
- I think the color hex code is more flexible than using a separate list of predefined variables
- As said I like the difference between `attributes` and `fractionAttributes`
- Do you prefer a separate blacklist or could we add an attribute to the existing `node`?
- How would you like to use the `timeTravel` information?
- `edges` 👍
- `attributeDescription` 👍
- `userSettings` 👍

**Comment by Richargh** [comment]
* Fine by me: `export interface CodeMap {nodes: CodeMapNode, /...`
* Let's use *ISO 8601* `"createdOn": "2009-01-01T12:00:00+01:00"`
* I like the numbers more, if we decide to use a different color scheme, it will be updated automatically. And we will change the color scheme, since we want to support color-blindness.
* I think a separate blacklist makes more sense. Then the merging gets easier. You only create the blacklist once and you can apply it to all future cc.json for that project. 
* *timetravel* is a cute name for a concept that I have no good name for yet :) I want to use it to map nodes in one cc.json to nodes in another cc.json. So you can see what nodes were renamed or similar.

**Comment by Richargh** [comment]
I just added `scenarios` to the previous example

**Comment by alschmut** [comment]
@Richargh Looks good!

**Comment by ukinimod** [comment]
- I didn't follow the issue. What came into my mind concerning aggregation of values, i.e. the discussion concerning attributes and fractionAttributes, from different nodes. One could also save the way of aggregation (sum or average or ...) in an additional section as a hash value.
- due to the pipes and filters architecture of the backend one could consider some kind of log inside the json file

**Comment by alschmut** [comment]
@ukinimod @Richargh do you think of something like this? Where did you want the hash value?

```
{
  "projectName": "codecharta",
  "createdOn": "2018-10-12:10:15...",
  "nodes": [...],
  "apiVersion": "1.0"
  "scenarios": [...],
  "timeTravel": [...],
  "edges: [...],
  "blacklist" = [...],
  "attributeDescription": [...],
  "userSettings": {...}
  "aggregation": [
    {"pairingRate": "average"}, 
    {"averageRevs": "sum"},
    {"loc": "sum"},
    {"testcoverage: "average"}
  ]
}
```

**Comment by mrpatpat** [comment]
@ukinimod mentioned an interesting fact in #247. What do you think about it ? Do attribute types solve it ?

**Comment by Richargh** [comment]
#247 says that we used to be able to parse attributes that are not numbers. Today we are only able to parse number attributes. That is a regression. Honestly I was not aware that we were ever able to parse non-number attributes nor that we currently can't. 

Attribute types can be used to tell CC how to display string attributes. It does not solve this regression. @mrpatpat or @ukinimod do we even have an importer in the analysis that generates non-number attributes? What would be an example for that?

**Comment by ukinimod** [comment]
@Richargh as of my knowledge there is no importer that creates non-number attributes. There was once, but no longer. It was only coincidence that I found that there is a slightly different approach in analysis and visualization. I would only suggest to unify them, one way or the other.

**Comment by Richargh** [comment]
Can you think of a scenario where non-number attributes make sense? I can think of *tagging* a File with java/c# or something. But that would only be an attribute key, not a value.

**Comment by ukinimod** [comment]
> Can you think of a scenario where non-number attributes make sense? I can think of _tagging_ a File with java/c# or something. But that would only be an attribute key, not a value.

There could of course be situations where non-number attributes for nodes make sense. Implementation language would be another, quite important. Not that important are the former usage to put authors of the specific files there. Creation date, modification date could be interesting, especially in legacy systems, but this could be handled differently. One convenience function in other tools is to put the method name and line number for the max metrics there. We often search for the most interesting spots in audits. That would help a lot. Sonarqube and many other tools are using ratings (A-...), but that could be mapped to numbers.

Of course, you can think of all of them as tags.

**Comment by Richargh** [comment]
Discussion continues in #350
