### ISSUE TITLE
memory leaks when hovering the labels

### ISSUE THREAD

**Issue by Med-H** [MaibornWolff/codecharta#1825]
# Bug

when hovering the labels, the geometries and textures are leaking quite quickly

<GIVEN>

WHEN hovering between the labels

THEN the used memory should not increase

## Actual Behavior
![devMetrics](https://user-images.githubusercontent.com/74670211/108965974-e59a0d00-767d-11eb-83b9-92bcd3acd6ee.gif)

## Steps to Reproduce the Problem

hover the buildings on any map

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes | no
- CodeCharta Version: 1.69
- OS: windows
- Browser: chrome

**Comment by ce-bo** [comment]
Closed in #1828
