### ISSUE TITLE
Huge performance differences between Sonar and SourceMonitor Parser 

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#1829]
# Bug

A project has been parsed by Sonar and SourceMonitor parsers. 
They have nearly the same count of total files (~5800).
However, the file sizes are different.
The size of the Sonar map is ~8MB and can be rendered qutie fast.
The size of the other SourceMonitor map is  ~4MB and causes performance issues on rendering.

## Expected Behavior
I would expect that the rendering behaves roughly similar in both cases.

## Steps to reproduce
Please contact me to get the appropriate test files and to reproduce the rendering.

**Comment by BridgeAR** [comment]
It's difficult to compare the maps without looking closely at their metrics. The complexity highly depends on those and if medians have to be calculated or sums, etc.

**Comment by ce-bo** [comment]
Ok, this could hide the actual reasons for that.
Should we have a look at it anyway? Maybe we can identify and improve some parts easily.

**Comment by BridgeAR** [comment]
I would rather not prioritize it before we address other aspects :)

**Comment by BridgeAR** [comment]
I guess this is resolved due to our recent improvements to the floor labels. Closing.
