### ISSUE TITLE
SonarImporter imports wrong folder names

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#1830]
# Bug
The SonarImporter imports wrong folder names.
The folder names seem to be replaced by some kind of UUIDs.

## Expected Behavior
The folder names will be imported correctly.

## Steps to Reproduce the Problem
Please contact me to get the appropriate test file and to reproduce this behavior.

**Comment by BridgeAR** [comment]
Is the behavior something that happens frequently?

**Comment by BridgeAR** [comment]
Ping @ce-bo

**Comment by ce-bo** [comment]
Currently, I am not able to reproduce it. SonarImporter works fine (e.g. importing CodeCharta from SonarCloud).
@silasg do you remember this case? I think we tried to import some C# metrics from Sonar.

**Comment by ce-bo** [comment]
Let's reopen it, if the issue still occurs.
