### ISSUE TITLE
Small UX improvements

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1881]
# Feature request

## Description

As a user, I want to have a smooth UX so that it's a nice feeling handling the application.

![image](https://user-images.githubusercontent.com/8822573/111795307-58865480-88c7-11eb-87ae-e02e80d04227.png)
![image](https://user-images.githubusercontent.com/8822573/111795453-8075b800-88c7-11eb-84f3-59264bb3b26d.png)
![image](https://user-images.githubusercontent.com/8822573/111795478-87042f80-88c7-11eb-91e1-cec8d45a61d1.png)
![image](https://user-images.githubusercontent.com/8822573/111795597-a4d19480-88c7-11eb-8e99-7c9320490b5d.png)
![image](https://user-images.githubusercontent.com/8822573/111795849-dea29b00-88c7-11eb-8630-b1afb23c3723.png)
![image](https://user-images.githubusercontent.com/8822573/111795876-e6fad600-88c7-11eb-9450-5b5cbbad3d32.png)

## Acceptance criteria

- ~~Add a line in the legend between `selected` and the other colors above that correspond to a metric (see picture one)~~
- ~~Always show the center map button at the top right navigation globe. Also, if the map has not yet moved (see picture 2 + 3)~~
- ~~Add tooltips the the functionality of the top right navigation globe (see picture 4)~~
- ~~Align buttons in the color and edge metric options. They should all have an identical padding etc. The `Invert colors` button should be  (see picture 5 + 6)~~ Resolved
- Update Logo as defined in the internal MaibornWolff Channel

**Comment by Christian-Eberhard** [comment]
What exactly do you mean with "Add tooltips the the functionality of the top right navigation globe (see picture 4)" Do you want the highlighted rectangle to have a generic tooltip for example "Align view"?

**Comment by BridgeAR** [comment]
Let's imagine the cube with it's six sides. We could name then e.g., `top`, `right`, `bottom`, `left`, `foreground` and `background`. That way it would be possible to describe what side to focus upon. We might also add a short description upon the cubes surface but for now it should be enough to just add a tooltip. Each vertex  would now indicate what would be focused. E.g., `Center foreground - top` would be:

![image](https://user-images.githubusercontent.com/8822573/116104133-7e65fc80-a6b0-11eb-833f-f0f85d2addf2.png)

And `Center foreground - top - right` would be printed here:

![image](https://user-images.githubusercontent.com/8822573/116104254-963d8080-a6b0-11eb-958e-e014c8cac25b.png)

We might also indicate angles but just showing the names is likely the most intuitive way?

**Comment by Christian-Eberhard** [comment]
Larger part split off into seperate issue, see https://github.com/MaibornWolff/codecharta/issues/2302 for that

**Comment by BridgeAR** [comment]
Closing as resolved. There's another issue for the logo.
