### ISSUE TITLE
Switching metric calculations seems broken

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1883]
# Bug

## Expected Behavior

GIVEN a map with a metric calculated as sum or median

WHEN switching the metric type

THEN the map is rerendered with the recalculated metric

## Actual Behavior

The type changes but the map looks identical as before.

## Screenshots

![image](https://user-images.githubusercontent.com/8822573/111805767-a1430b00-88d1-11eb-9848-a5da7e859a5e.png)
![image](https://user-images.githubusercontent.com/8822573/111805811-abfda000-88d1-11eb-8177-712e0feefa85.png)
![image](https://user-images.githubusercontent.com/8822573/111805836-b15aea80-88d1-11eb-83c8-bb20bffa2dd4.png)

## Steps to Reproduce the Problem

1. Open any metric option and choose the metric type for the currently chosen metric
1. Change the type

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.71.2

**Comment by RomanenkoVladimir** [comment]
Adressed in https://github.com/MaibornWolff/codecharta/pull/2069, closing the PR as the issue resulted from a misunderstanding due to confusing implementation
