### ISSUE TITLE
add slider controls for color thresholds

### ISSUE THREAD

**Issue by silasg** [MaibornWolff/codecharta#19]
I loved the old feature in an earlier version that allowed me to adjust the two neutral color thresholds using slider controls because you could do a kind of "interactive sensitivity analysis" (how save are my thresholds? how much turns red if i move the slider a little? is there a discrete limit to make the whole map red or is it continuous? etc).

I'm aware that this is not an easy feature request because we would need to now min and max for each metric. So I won't be too disappointed if it gets rejected but please at least have a look at it, thanks! ;)

**Comment by mrpatpat** [comment]
I started implementing this feature on this [branch](https://github.com/MaibornWolff/codecharta/tree/colorslider). The easy interactivity will definitely help finding the correct values for the desired analysis.

**Comment by mrpatpat** [comment]
The next release will include the desired feature. You can already see it in the online demo.
