### ISSUE TITLE
Loading a new map should add that map to known ones instead of replacing the former one

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1954]
# Feature request

## Description

As a user, I want to keep old maps so that I safe time when comparing maps in multiple mode.

## Acceptance criteria
- Loading a new map does not remove already existing maps anymore
- The new maps are the only "active" maps (as implemented currently)
- The map dropdown list receives a garbage bin icon to remove loaded maps to safe memory

**Comment by ngormsen** [comment]
> ## Acceptance criteria
> * Loading a new map does not remove already existing maps anymore
> * The new maps are the only "active" maps (as implemented currently)
> * The map dropdown list receives a garbage bin icon to remove loaded maps to safe memory

@BridgeAR could you further specify the feature request for me? This is my understanding so far:
1. Maps A and B are loaded.
2. User loads the files for Maps C and D.
3. Map C is now "active" (selected?) in single view / Map C and D are "active" in multiple view.
4. The other maps remain in the dropdown list (deselected). 
5. New button that removes all(?) maps in the list.

Is this correct? Thanks!
