### ISSUE TITLE
SonarImporter: Correctly named modules in multi module projects

### ISSUE THREAD

**Issue by mrpatpat** [MaibornWolff/codecharta#196]
# Feature request

When importing multi module projects with the sonar importer I get project keys and hashes in paths and names. They should be replaced with the correct module name. --merge-leaf does the job, but it merges all modules into one (as intented).

**Comment by alexhunziker** [comment]
Which project(s) can be used to reproduce this error? And what are the steps required to get this behaviour?

**Comment by BridgeAR** [comment]
@mrpatpat PTAL

**Comment by mrpatpat** [comment]
I took a look into this again and unfortunately my original report was not very detailed. I am not sure if this still is a bug but I will at least report the current behaviour here, so you can decide if the behaviour is expected and intended. 

1) try importing a multi module sonar project 
`ccsh sonarimport https://sonarcloud.io com.amsidh.mvc:MultiModuleSonarQube`

we get this result: 
![image](https://user-images.githubusercontent.com/2622069/111807308-1d8a1e00-88d3-11eb-85f5-4a67515749e2.png)

2) with --merge-modules we get this behaviour

![image](https://user-images.githubusercontent.com/2622069/111807569-5924e800-88d3-11eb-9a6b-3322c24c1b66.png)

Now I think in my original issue there were some folders like "com.amsidh.mvc:MultiModuleSonarQube#1234324234" which seemed weird. When I look at the result now this seems to be not the case anymore. 
I am asking myself though if --merge-modules did the expected thing here and if com.amsidh.mvc should be seen in the path. 
Sorry for not describing it better back then.

**Comment by BridgeAR** [comment]
Thanks a lot for the update! I expect it's solved and I'll close the issue as such. If it does come up again, please feel free to leave a comment to reopen this or just create a new issue instead.
