### ISSUE TITLE
Sonarcloud action always fails on first attempt

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#1966]
# Bug

## Expected Behavior

GIVEN a triggered dependabot pipeline

WHEN the sonarcloud task runs for the first time

THEN it succeeds 

## Actual Behavior

GIVEN a triggered dependabot pipeline

WHEN the sonarcloud task runs for the first time

THEN it fails no matter what

**Comment by BridgeAR** [comment]
This should also be useful for renovate.
