### ISSUE TITLE
Auto-Merge and Auto-Approve are not triggered anymore

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#1967]
# Bug

## Expected Behavior

GIVEN a green pipeline

WHEN triggered by depandabot

THEN it should be auto approved and then auto merged

## Actual Behavior

GIVEN a green pipeline

WHEN triggered by depandabot

THEN auto approve and auto merge are never triggered

**Comment by BridgeAR** [comment]
Supersedes by #2027. We could check if renovate supports auto merging but if we use their grouping function, it's ideal to merge that single PR on our own.
