### ISSUE TITLE
Nice looking Ribbon bar

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#198]
Create a nice looking ribbon with the existing metrics. Move **existing** settings from the burger menu on the right side to an expandable ribbon bar on the top

<img width="70%" src="https://user-images.githubusercontent.com/23529226/44479918-d9124500-a639-11e8-9c8b-d9accdd09310.jpg">

#### Done:
* That is one huge ribbon bar :) I expected the heigh to be about half that height, probably a third of that height. 
* Can we align everything at the top? 
* Can we remove these huge labels "area options", "height options" etc.?
* "White background" is not a detail of "Color" and should not be in the ribbon
* The regular "Options" (Maximize Detail panel) etc. don't need to be part of the ribbon. 
* Options->Labels belongs to the height metric
* Links is a good idea but it should not be in the ribbon bar, we can put that in the sidebar
* Scenarios should be selectable inside a small select-dropdown, also when the ribbon bar is minified.
* Crop long filenames to need less space
* Let's make the ribbon bar the default and remove the "use ribbon bar"
* Can we put labels with a small font right under the categories? File, Scenarios, Size, Height, Color.
* selecting delta mode for two cc.json files creates problems with the size. How about we only allow the user to change the map, when the ribbon bar is expanded? And when it's expanded it can look similar to the ribbonbar-vertical where Single, Delta, Aggregate is in the same line.

#### TODO:
* Can we use the other color selector we talked about that shows the color directly?
* The color slider has some weird delay currently.
* Can we reduce the length of the ribbon bar quite a lot as well?
* Can we change the ribbon bar to no longer be an overlay? The CodeMap should stop right under the ribbon bar, even if it is expanded.

**Comment by mrpatpat** [comment]
@felixherbst I experimented a little bit on [this branch](https://github.com/MaibornWolff/codecharta/tree/experiment/ribbon_bar). Please take a look and see if you find the solution or parts of it fitting.

**Comment by mrpatpat** [comment]
I added some new additions on experiment/ribbon_bar and experiment/ribbon_bar _with_buttom.

@Richargh  thank you for the contribution. I also got the feedback that automatic opening is not good. 

I also added first settings into it and realized, that they take up a lot of space.

**Comment by mrpatpat** [comment]
One thing we realized while looking at our experiments is that the expanded ribbon bar should be as small as possible. A good visual experience is achieved by changing $heightExpanded to 200 in in the ribbonBar.component.scss file.
This would require a compact design of our most important options.

![image](https://user-images.githubusercontent.com/2622069/44155039-8334c672-a0ac-11e8-8ad2-608a9dc6813d.png)

It is important to see the map itself so we can explore values like color ranges. We could open sections separately. This would prevent us from quick changes in different sections at once.

I also experimented with opacity, but it makes the view a bit confusing. 

![image](https://user-images.githubusercontent.com/2622069/44155288-2dfcf8f4-a0ad-11e8-9fb6-df059e333180.png)

Generally speaking, we should talk about which options should appear up there and which not.

**Comment by alschmut** [comment]
Yes, I agree the ribbon bar should be as small as possible. I don't know what you have in mind to do next, but wouldn't it be cleaner to implement something similar to this and always only open one "field"

<img width="70%" src="https://user-images.githubusercontent.com/23529226/44155547-e6a60e4a-a0ad-11e8-8ea9-ba78e6d6b24d.jpg">

**Comment by Richargh** [comment]
@alschmut we discussed this. We thought that users would probably change the details of each metric together and that's why you want to see more than one open "field". 

So if you change height to mcc, you might want to change how many labels are shown, which is a height detail. Then change color to coverage, while you then also change the color sliders in the detail view.

**Comment by Richargh** [comment]
@mrpatpat Let's try the clickable=expandable version first. No expand on hover, no transparency. 

@alschmut, @felixherbst, @FernandoES how about we merge the clickable version to master but deactivate it. Most people see the current version. But by setting a flag in experimental willing users can try the new design and give us feedback?

**Comment by alschmut** [comment]
@Richargh yes, I understand what you mean, but after all I see no big difference between the stuff on top or on the side. When we remove unnecessary Panels in the sidebar, we get it faster to change as well.

Giving the User the option to try it out is good, but first we should get a nicely working version

**Comment by Richargh** [comment]
@alschmut I'm not sure I understand the criticism. "When we remove unnecessary Panels in the sidebar, we get it faster to change as well." The ribbon design was the result of our design workshop where we decided to move all the metric details from the side bar into the ribbon bar. Which will leave the ribbon bar empty except for the treeview. Has your opinion changed? Shouldn't we move the details to the ribbon? 

I am not suggesting throwing a broken version at users. It should be functional, even if it is opt-in using an experimental flag.

**Comment by alschmut** [comment]
@Richargh oh true the sentence is difficult to understand. I meant to take out the settings for Maps and Metrics e.x. and put them on top of the sidebar. So just without the expandable panel-boxes.

But I probably got it wrong: I thought you want to move everything from the sidebar to the ribbon bar. Thats not the case, is it? Because this would be too much ;)

**Comment by mrpatpat** [comment]
Our experimental implementation 52682d9 depends on #220

**Comment by alschmut** [comment]
I ve tried to implement the [experiment/ribbon-bar-vertical](https://github.com/MaibornWolff/codecharta/tree/experiment/ribbon-bar-vertical). Actually its just the settingsSidebar without the expandable panels. I ve used the table layout to set the headers to the left of the setting-boxes. How do you think about that? Problem: I had to use a mininum-height for the table-cells, to fit the rotated header inside the box. Thats why some of the boxes are a bit bigger than they need to.

![bildschirmfoto 2018-08-19 um 19 59 47](https://user-images.githubusercontent.com/23529226/44311595-7e36de80-a3ea-11e8-956c-b72731cf8453.jpg)

**Comment by Richargh** [comment]
@alschmut we sketched a version of codecharta where most of the items in the sidebar have moved to the ribbon. 

The sole survivor is the TreeView. Which is good, because the TreeView needs most of the space of the sidebar. The [experiment/ribbon-bar-vertical](https://github.com/MaibornWolff/codecharta/tree/experiment/ribbon-bar-vertical) does not achieve this goal. 

Also the settings for changing the metrics are not located where the metric is located which I find bad from a usability perspective. F.ex. the metric height is located at the top. And completely unrelated, there is the *Display* area in the side bar which contains the settings labels, height and invert height. As an alternate example the metricChooser for size is at the top. But inside "display" are the settings margin and dynamic margin.

Thus we decided to move the metric settings to the metric location and our solution was the ribbon bar. I don't understand why that creates controversy now?

**Comment by Richargh** [comment]
![Screen Shot 2018-08-20 at 16.44.00.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b45ff04882b29001104eeca/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456f36b7191a379e90c2f55415f4ebe5d4a1f06a3a3dc78e2a436628f0e0fb987695a7dc56c15a5bbd61fbf00e8718a1a8cb3ef9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecb5cf14ce74e55a3113063f43b.png)

* That is one huge ribbon bar :) I expected the heigh to be about half that height, probably a third of that height. 
* Can we align everything at the top? 
* Can we remove these huge labels "area options", "height options" etc.?
* "White background" is not a detail of "Color" and should not be in the ribbon
* When I open a cc.json  with a long name or when I have a regular sized-window, it can happen that color metric or even height metric disappears.
* Scenarios should be selectable even when minified.
* Scenarios can use a space-saving dropdown
* The regular "Options" (Maximize Detail panel) etc. don't need to be part of the ribbon. 
* Can we use the other color selector we talked about that shows the color directly?

**Comment by alschmut** [comment]
@Richargh yes I understand. We have planned it differently, thats why it also was just an idea/experiment to use the space on the right (because fact is: displays are wider compared to their high). But for sure, we just need to work on the "normal" ribbon bar 👍

**Comment by Richargh** [comment]
"Displays are wider compared to their height": that is a **very** good point, we'll come back to that with future enhancements which will probably use the left side of the display :)

**Comment by alschmut** [comment]
I have reduced the size of the ribbon bar and put the options into the sidebar. I have merged the Color- and DisplayPanel into the codeMap-Panel, which is only visible when not using the RibbonBar. Feel free to reorder the settings. E.x. "Show Edge Arrows", or "Labels"-slider.

![bildschirmfoto 2018-08-22 um 13 14 33](https://user-images.githubusercontent.com/23529226/44463407-8885f200-a60f-11e8-9824-f40021887b73.jpg)

![bildschirmfoto 2018-08-22 um 13 25 20](https://user-images.githubusercontent.com/23529226/44463416-8de33c80-a60f-11e8-80e9-54c420ad5e79.jpg)

![bildschirmfoto 2018-08-22 um 13 34 31](https://user-images.githubusercontent.com/23529226/44463593-2b3e7080-a610-11e8-926f-b7f7f631095e.jpg)

**Comment by alschmut** [comment]
Current version:
![bildschirmfoto 2018-08-24 um 23 11 16](https://user-images.githubusercontent.com/23529226/44610483-45d13f00-a7f4-11e8-8ea5-d0f101848c26.jpg)

![bildschirmfoto 2018-08-24 um 23 11 27](https://user-images.githubusercontent.com/23529226/44610486-479b0280-a7f4-11e8-813d-291334964e8d.jpg)

- the slider still does weird things
- the transition of choosing single, delta or aggregation is weird as well

**Comment by alschmut** [comment]
![bildschirmfoto 2018-08-25 um 14 36 36](https://user-images.githubusercontent.com/23529226/44618800-0565d580-a875-11e8-92bb-1c2e8926305b.jpg)

![bildschirmfoto 2018-08-25 um 14 36 54](https://user-images.githubusercontent.com/23529226/44618801-07c82f80-a875-11e8-80b3-8af3c61f3794.jpg)

- The ribbonBar uses less height (smaller font-size)
- Updated section-title places directly under the select field
- The scenario select is currently inside the File-section
- the fileChooser button is in the top left corner. It might not be visible enough, but it fits nicely into the icon-schema. How do you think about that?
- fixed long metric names to be shortened 
- fixed delta compare filename to be too long

Question:
- Do you want to keep the large button on the top right? Or would you also consider a smaller button-version inside the ribbon bar (still in the top right corner)

btw: i am pretty proud of how it looks now, as I had some scepsis with the ribbonbar itself :D

**Comment by Richargh** [comment]
It's progressing very nicely. :)

* All the sliders have a huge lag problem. It feels completely different compared to regular version. We need to fix that.
* I like the section titles. Can we center them and use a grey font? Right now it's too dominating.
* I think we can leave the scenario select in the file-section. Let's see what our users say. But we should probably renamed it to "metric scenario".
* I like the fileChooser button where it is and with that size. It should definitely be a button. Right now I wouldn't know to click on it. 
* The large button on the top right can be smaller. Whatever looks good. Maybe keep it floating on the edge though. That is probably a good indicator that you can expand the ribbon.
* Can we change the ribbon bar to no longer be an overlay? The CodeMap should stop right under the ribbon bar, even if it is expanded.

**Comment by alschmut** [comment]
![screen shot 2018-08-28 at 15 45 02](https://user-images.githubusercontent.com/23529226/44731565-5c6ce400-aadb-11e8-92b7-b6f2c6753c4f.jpg)

![screen shot 2018-08-28 at 15 45 10](https://user-images.githubusercontent.com/23529226/44731568-5ecf3e00-aadb-11e8-990b-d810bf44e01b.jpg)

I just implemented the above mentioned points.
- What do you think of the toggle-button on the right? When hovering it highlights as in the second image
- Is the fileChooserButton noticeable and still nice enough?


#### Todo
- the color slider doesn't adapt the range when loading the page, but does when changing any other setting.
- The codeMap needs to be centered again, when the ribbonbar was expanded and the canvas has less height available. At the moment the complete canvas just slides down.

**Comment by Richargh** [comment]
* The toggle button looks good to me
* fileChooserbutton should probably be a round button with shadow, like the burger menu button and the center button

**Comment by mrpatpat** [comment]
TODO: We should reactivate the e2e tests in 2592a942f8e459c82243302178b442205afc5675. I deactivated them since we need this version for review

**Comment by Richargh** [comment]
@felixherbst @mrpatpat @alschmut This is done right? It's no longer in progress?

**Comment by alschmut** [comment]
Yes, i would say so.
