### ISSUE TITLE
company logo for screen shots

### ISSUE THREAD

**Issue by Shivan-997** [MaibornWolff/codecharta#1990]
# Feature request

## Description

As a end user, I want company logo to be visible on exported screen shots to increase reach.

## Acceptance criteria
- Logo is visible

**Comment by abdelkaderlagha** [comment]
I did some adjustments first of all to the background color of the screenshot from black to white. I think white is a better color to match with the logo. This is sample of a screenshot![single_sample1.cc (5).png](https://images.zenhubusercontent.com/6102ad06fd2e045c98188201/7fafa777-43d2-477c-ac96-fb01a85284d1)

**Comment by abdelkaderlagha** [comment]
This is how the screenshot looks like after the modification : ![single_sample1.cc - 2021-08-12T134308.185.png](https://images.zenhubusercontent.com/6102ad06fd2e045c98188201/13a3ab13-9e1d-4b1e-8355-7c2c1b21efb8)

**Comment by ce-bo** [comment]
I am not really sure, if we want to include the Logo in every case (e.g. if we want to have company neutral screenshots). What do you think @BridgeAR?
