### ISSUE TITLE
Expandable Ribbon bar for area

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#200]
# Feature request

## Description
move **existing** area settings from the burger menu on the right side to an expandable ribbon bar on the top
![IMG_3850.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b45ff04882b29001104eeca/125516c66e82c728ace21e0d46c1b9bd1cd1dbfcdfabf301b44fff9e2c4533317346f6292481e57cea1b28005b564df841585e16adf8dc22a3e52e6c981e5ab38532022d8c6853beb2901eb80bbb25884c87b7b5884cc0e13524f5c6.JPG)

**Comment by alschmut** [comment]
@Richargh do we need this issue anymore?

**Comment by Richargh** [comment]
Probably not, we did all of this on the experiment branch.
