### ISSUE TITLE
Switch to renovate

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#2027]
We had quite a few issues with dependabot and it seems like there's no ideal solution to e.g., reduce the amount of PRs incoming.

Renovate supports grouped updates and it's possible to open a PR e.g., each one, two or four weeks. That way it's much easier to update everything and we spend less time solving problems around dependabot.

**Comment by RomanenkoVladimir** [comment]
This would require us to authenticate renovate from the MW organisation, even if we allow it for CodeCharta only.

**Comment by RomanenkoVladimir** [comment]
We should discuss if we really want this and if we decide to perform the switch contact organisation managment

**Comment by ce-bo** [comment]
We should have a look on that to finalize the issue.

**Comment by jannikr** [comment]
After the partitioning by groups like npm, gradle and others worked, I assume we can close this issue?
