### ISSUE TITLE
Feature/Show max number in MetricChooser select-list

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#204]
# Feature/Show max number in MetricChooser select-list

## Description

Show the max of each metric in braces behind the metric's name in the metric selection drop down. this way you could easily identify interesting and noticeable metrics in a (still) unkown code base. You can also identify metrics that are not interesting, because the maximum is low.

**Comment by alschmut** [comment]
@silasg 
Do you think of something like this?
![bildschirmfoto 2018-08-09 um 15 29 59](https://user-images.githubusercontent.com/23529226/43902113-88e6fb34-9be9-11e8-862b-1a05d5138550.jpg)

**Comment by Richargh** [comment]
I like helping/suggesting features like this. I just don't understand how a meaningless number like rloc(400) should help me. 

Perhaps it makes more sense with averages/deviations of fractional attributes? coverage (50) for the whole code base would be pretty bad. Or coverage (80 SD 20).

**Comment by Richargh** [comment]
I got an explanation. This way we won't select a metric that is not present in the map from the drop-down. If there are no `sonar_bugs` we don't have to select it to find out it's not interesting.
