### ISSUE TITLE
Exclude items and store in cc.json

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#205]
In the Ui we can **exclude** or **hide** packages or buildings. This makes sense for vendor libraries (jquery, Lucene etc), generated code or similar. Exclude means that the package/building is removed and the structure is reordered. Hide means that package/building is removed but the space where it used to be is now empty.

This information needs to be **permanently stored in the cc.json**, because it is unfeasable to reselect all excluded items every time the cc.json is reopened. We  talked about a button to "Save as". The NW.js version additionally provides a "Save" button, because it can access the local file system. 

Internally in the cc.json .gitignore or ANT-style exclusions probably make the most sense to represent the exclusions. The exclusions in the cc.json should be inspired by the discussion in #182

**Comment by alschmut** [comment]
Ist this the same or at least a part of #181?

**Comment by Richargh** [comment]
It might very well be. I created this issue because it is THE core feature for our lead auditor. Some form of persistent exclusion of files.

**Comment by alschmut** [comment]
Requested meeting-changes:

#### TODO
- change blacklist format in cc.json to following:
    ```
    "blacklist": [
      {
        "path": "/root/file",
        "type": "File"
      },
      {
        "path": "/root/folder",
        "type": "Folder"
      },
    ]
    ```
- Blacklist in visualization as list items like 
    ```
    <file/folder-icon> <path> <exlude-icon>
    <file/folder-icon> <path> <exlude-icon>
    ...
    <add-list-item-icon>
    ```
- Remove userSettings when downloading json
- "download  json" button in ribbonBar as "save"-icon next to filechooser
- add timestamp to filename when saving the cc.json

#### Done
...

**Comment by felixherbst** [comment]
I edited your comment, blacklist format and list are functional, but need to get some css
Atm, when a user manually adds a path to the blacklist, there is no feedback if that path has typos/ is available in the map.

**Comment by Richargh** [comment]
I edited the comment as well and added the "save" and "save as" option for the standalone CC.

**Comment by mrpatpat** [comment]
I added the timestamp to the file name. Currently it is not the real unix timestamp but the current date in the dd_mm_yyyy format. Is this ok or should it really be the milliseconds?

**Comment by Richargh** [comment]
@mrpatpat the date format seems better to me. But I did not make the suggestion to add it so someone else might chime in?

**Comment by Richargh** [comment]
Hi everyone, I updated the description in the beginning to reflect a lot of the conversations we have had. Please note, that now both **excluded and hidden** buildings are stored in the cc.json. That is different than before. Also @mrpatpat mentioned to me that the "type" : "Folder"/"File" is not necessary if we use *.gitignore* style matching. Together we discussed changing the cc.json format to:

```
"blacklist": [
  {
    "path": "/root/package1/package2/",
    "type": "hide"
  },
  {
    "path": "/root/package1/package2/",
    "type": "exclude"
  }
]
```

What do you guys think?

**Comment by alschmut** [comment]
Sounds good for me!

**Comment by mrpatpat** [comment]
I added a proposal branch with the gitignore style pattern (feature/205/proposal)
