### ISSUE TITLE
Make CodeCharta Reload save

### ISSUE THREAD

**Issue by ollio** [MaibornWolff/codecharta#2056]
# Feature request

It would be nice, if I have to reload the browser page, all configs, filters, color settings and camera position are stored and the view is the same state after a page reload.

## Acceptance criteria
- Loaded cc.json file is restored
- After page reload the camera position, settings and filters are restored

## Development notes (optional Task Breakdown)
- [ ] 
- [ ] 
- [ ]

**Comment by ce-bo** [comment]
Hi @ollio, great suggestion, thanks!

**Comment by ce-bo** [comment]
@fritschldwg Could you please explain the reason why it is blocked?

**Comment by fritschldwg** [comment]
Sorry for not including this in the ticket (it was only mentioned in the PR). A dev-dependency I added needs Node version 18 or higher, so this issue will be resolved once we upgrade from Node v16 to v18.

**Comment by ce-bo** [comment]
Sorry, I have overseen the infos in the PR. I was blind.

**Comment by ce-bo** [comment]
@fritschldwg i move this to backlog since it is not blocked when we use an older version of the mentioned library (see comment in linked PR).

**Comment by fritschldwg** [comment]
> @fritschldwg i move this to backlog since it is not blocked when we use an older version of the mentioned library (see comment in linked PR).

I will finish this as soon as I am done with the ticket I am currently working on.
