### ISSUE TITLE
Add a screenshot button

### ISSUE THREAD

**Issue by ollio** [MaibornWolff/codecharta#2057]
# Feature request

Add a screenshot button. 

## Description

If the button is pressed, the actual view is copied into the intermediate storage to paste it into a target.

## Acceptance criteria
- Screenshot of the actual view is in the intermediate storage
- legend and company logo are at the correct position
- the view is full filled in the center of the screenshot
- Optionally: a save modal dialog to store the screenshot in a file exists

## Development notes (optional Task Breakdown)
- [ ] 
- [ ] 
- [ ]

**Comment by BridgeAR** [comment]
@ollio I believe this is already included? (besides the bug with the brackets)

![Screenshot from 2021-07-30 12-18-33](https://user-images.githubusercontent.com/8822573/127640159-9278b2e9-74dd-4c72-a8df-9af5dc05b7fa.png)

**Comment by BridgeAR** [comment]
Please reopen in case I miss something!
