### ISSUE TITLE
Show list of top n files for each selected metric

### ISSUE THREAD

**Issue by silasg** [MaibornWolff/codecharta#2062]
New button or tooltip for each metric to show the top 5 or top 10 files for the selected metric including the actual value.

eg next to the size metric with selected rloc the top 10 largest files can be shown. next to heigt with selected complexity the most complex files are shown. next to color for coverage the 10 most red files can be listed. be careful here: for test coverage lower values are hotspots, so the selected color scheme is of importance.

bonus if the list can be copied to clipboard by button press :)

**Comment by fritschldwg** [comment]
@ce-bo For now I'll consider the direction when calculating the list. @Nereboss has already designed some UI mockups to enhance this feature. However, I plan to update this feature's UI along with a complete menu UI overhaul, rather than separately.
