### ISSUE TITLE
Unusable component

### ISSUE THREAD

**Issue by shaman-apprentice** [MaibornWolff/codecharta#2074]
# Bug

## Actual Behavior

`colorSettingsPanel.component.html` has an unusable  `reset-settings-button-component`

## Screenshots
![image](https://user-images.githubusercontent.com/3596742/123663348-96840480-d836-11eb-8ac7-d2b0aa83471e.png)

![image](https://user-images.githubusercontent.com/3596742/123663683-efec3380-d836-11eb-81ef-7b3a7f7ed01b.png)

## Specifications
- is currently released in Main only
- Assumption: This element was added by accident and can be removed again

**Comment by ngormsen** [comment]
Results from diverting changes in #2041 and #2040. The two components differ regarding their style and behaviour. Which one do you want to keep @RomanenkoVladimir @Christian-Eberhard ?

**Comment by RomanenkoVladimir** [comment]
Seems like merging #2040 accendentaly overwrote the changes from #2041
