### ISSUE TITLE
Evaluate use of Angular Material

### ISSUE THREAD

**Issue by shaman-apprentice** [MaibornWolff/codecharta#2107]
# Do we need Angular(JS) Material?

Currently we use [AngularJS Material](https://material.angularjs.org/latest/), which cannot be easily migrated. We have the following two options:

1. Utilize [Angular Material](https://material.angular.io/)
2. Simply use some own CSS / Sass

## Advantages of Angular Material
- Theming (do we need it?)
- Accessibility (do we need it?)
- Responsive Design (do we need it?)
- It comes with pre-build components like `mat-select`, directives like `cdkPortal`, ect

## Disadvantages of Angular Material
- New framework to learn
- Additional dependency (to maintain and build time)

**Comment by shaman-apprentice** [comment]
As discussed on weekly on 09.09.2021 we don't use Angular Material for now. If necessary, we can re-add / utilize it later on.

**Comment by BridgeAR** [comment]
I would rather not use own CSS. This is already causing quite a lot of issues and it would be good to default to a good standard. This standard might be something else than Angular Material but it could definitely be part of that.

**Comment by shaman-apprentice** [comment]
Given it some further thoughts I agree. Standards are a cool thing and it gives us a component library for free. It seems also to be very broadly adopted by Angular developers. So I will introduce it when migrating `sorting-option-component`, which needs a select component.

**Comment by jannikr** [comment]
Last week we talked about how we could use Angular Material to further improve our frontend and prevent too many dependencies in the code. In the process, the issue https://github.com/maibornwolff/codecharta/issues/2470 was created, which could replace this issue.

**Comment by shaman-apprentice** [comment]
I like the idea of reducing dependencies and better scoping of styles. I think using Angular Material as component library is a stand alone task. #2470 is a further enhancement and we should keep both tickets. (This ticket will be already resolved with #2472 )
