### ISSUE TITLE
Update AggregateService to summarize edges

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#213]
Original feature request was #172.

Use [feature/172/visualizing-edges](https://github.com/MaibornWolff/codecharta/tree/feature/172/visualizing-edges) to checkout a branch.

## Description
Add the possibility to use aggregation of Maps inside visualization with edges. The visualization will not be able to give a completely new analysis result, but we can summarize all edges just like the merge filter does in `ccsh merge`. Because until now it would just delete the edges/dependencies and thats definitely worse.

**Comment by FernandoES** [comment]
Just implemented in #172
