### ISSUE TITLE
revision chooser does not react to url params/given settings 

### ISSUE THREAD

**Issue by mrpatpat** [MaibornWolff/codecharta#220]
# Bug

Single Map is selected even though I expect delta to be selected when parameter delta is set via url.

## Expected Behavior

delta is chosen when url parameter delta is set

## Actual Behavior

delta is not chosen when url parameter delta is set

### Screenshots

![image](https://user-images.githubusercontent.com/2622069/44269893-1d66a500-a236-11e8-8500-07b004af0a2c.png)

## Steps to Reproduce the Problem

  1. set url param delta to true
  2. open revision chooser

**Comment by FernandoES** [comment]
Correcture on work in branch  Bug220ShowDeltasOnURLLoading. 
The value deltas: boolean of settings was changed to kindOfMap, which has the value KindOfMach, a new added enum with the values {Single, Delta, Aggregate}. Note that the value delta:boolean of viewModel was not changed, only of Settings.
Already done:
-Refractor
-Test Correcture
-Part of the failure correcture.

Still to do:
- Find out which failure makes the file/file to aggregate/deltas selector does not appear in the ribbon bar.
- Same for color selector
-Do Manual-visual testing of the UI

Reason of the values change: It does sense to have a boolean value when only two kind of views are available (single and delta) but its neither safe or elegant when having three ( aggregate ). The try to make the selector work with boolean values was not bidirectional, being that the reason of the original bug described in  this issue. Although this change/refractor brings many changes in the code, it makes it simpler and more understable.
