### ISSUE TITLE
Add edgeFilter to ccsh to set node-attribute from aggregate edge-attributes

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#222]
Child of #172.

Use [feature/172/visualizing-edges](https://github.com/MaibornWolff/codecharta/tree/feature/172/visualizing-edges) to checkout a branch.

## Description
*Create a filter* that sums all **edge** attributes (avgCommits_sum), means all percentage attributes (pairingRate_mean) and adds it to the **nodes** in the cc.json. An example interface is this: 
`ccsh edgeFilter edgesin.cc.json -o edgesout.cc.json` 
Then we can use the MetricChooser to select pairingRate_mean for color and find foul classes.

Using attributesType to separate sum and average attributes.
```json
"attributeTypes": {
  "nodes": [
    {"loc": "absolute"},
    {"testcoverage": "relative"}
  ],
  "edges": [
    {"pairingRate": "absolute"}, 
    {"averageRevs": "relative"}
  ]
}
```

**Comment by Richargh** [comment]
I changed the description a bit. Previously it said: "Create a filter that sums all node attributes" and now it says "Create a filter that sums all edge attributes"

**Comment by alschmut** [comment]
solved and merged into  [feature/172/visualizing-edges](https://github.com/MaibornWolff/codecharta/tree/feature/172/visualizing-edges)
