### ISSUE TITLE
Create a guide for setting up a sonar and scmlogparser

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#227]
As a user, I want an easy guide that explains how to create a cc.json with Sonar and Scmlogparser and Mergefilter.

The guide should show others how to create cc.json maps with sonarparser, scmlogparser and mergefilter. The example project should be our own CodeCharta. Important NOTE: This might require fixing our sonarcloud installation. 

An example article in german can be found here: https://maibornwolff.de/blog/code-charta-fuer-ethereum 

The article does not mention the mergefilter and uses two files. As a user I want only one cc.json so please use mergefilter to combine sonar.cc.json and scmlog.cc.json.

**Comment by mrpatpat** [comment]
I have documented it [here](https://github.com/MaibornWolff/codecharta/wiki/Using-Sonarqube-and-Git-data-to-visualize-Codecharta's-own-Code). I also moved detailed documentations to the wiki and referenced it in the Readme file. Is this ok ? These detailed guides dont seem to fit into a Readme file.

**Comment by felixherbst** [comment]
I tested this tutorial and everything worked fine! To provide a better overview of the necessary steps, I would suggest using a markdown console view, like
```console
ccuser:~$ npm i -g codecharta-analysis
foo
```

**Comment by Richargh** [comment]
I would be awesome if we could have a flowcharta that shows the analysis process.

**Comment by felixherbst** [comment]
I added a flowchart

**Comment by Richargh** [comment]
1)Can we change the flowchart a bit and add a legend? Sonarqube and Git repository should be metric sources with their own color. sonarimport, scmlogparser and merge should be cc filter. cc.json should be an artifact.

I also changed the wording a bit (is it a change for the better?) and added one thing to the scmparser. The scmparser takes the Project name as a cmd line flag `-p de.maibornwolff.codecharta:visualization`.
