### ISSUE TITLE
Create a guide for setting up Gitlab CI with sonar and .NET

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#228]
Same as #227 but this time for a .Net project with GitLab CI.

**Comment by mrpatpat** [comment]
Please see my comment in #231

**Comment by Richargh** [comment]
I modified the issue to also include Gitlab-CI.

**Comment by mrpatpat** [comment]
[Documented here](https://github.com/MaibornWolff/codecharta/wiki/Integrating-CodeCharte-into-a-Gitlab-CI-on-Windows-for-.net-projects)

**Comment by Richargh** [comment]
I would be awesome if we could have a flowcharta that shows the analysis process.

**Comment by FernandoES** [comment]
IMO the guide is clear, I would close this issue
