### ISSUE TITLE
Check for unused Services

### ISSUE THREAD

**Issue by shaman-apprentice** [MaibornWolff/codecharta#2288]
As new Angular components will be directly connected to redux store, a lot of services will likely become obsolete and can be removed.

**Comment by BridgeAR** [comment]
Is this a necessary issue right now? It seems like it's too early for this?

**Comment by shaman-apprentice** [comment]
As all services are injected by AngularJS, migration cannot be complete with some unused obsolete service. Therefore we can safely close this issue.
