### ISSUE TITLE
Migrate or remove plop

### ISSUE THREAD

**Issue by shaman-apprentice** [MaibornWolff/codecharta#2289]
As a Developer I want to reason about as less code as possible. Each code not present reduces the changes of breaking something, having to upgrade something, ect. 

We currently have plop templates for AngularJS development. I think we don't use them anyway and can make our repository a little bit leaner through removing them. If they provide value for us, we have to migrate them to reflect Angular Development.

**Comment by BridgeAR** [comment]
@RomanenkoVladimir I guess you know better in what way they are used?

**Comment by RomanenkoVladimir** [comment]
Right now we use them to generate services and components.
Component generation will be natively supported by angular: `ng generate`
If we were to drop plop for ngRX we could also use ng generate to generate reducers, however, as of now we would need to write them by hand if we remove plop

**Comment by BridgeAR** [comment]
We should not use plop anymore. As such, let's go ahead and remove it.
