### ISSUE TITLE
Migrate custom dispatch

### ISSUE THREAD

**Issue by shaman-apprentice** [MaibornWolff/codecharta#2292]
Our **store.service.ts** has some custom `dispatch` logic, which needs to be migrated.

For now we can monkey patch redux dispatch to this logic.

After the divorce of `$rootScope` and redux store, we can move the custom logic into the redux store, or utilize something like [redux-thunk](https://github.com/reduxjs/redux-thunk).

**Comment by BridgeAR** [comment]
@shaman-apprentice please elaborate a bit more about the issue. I would definitely not want to monkey patch redux and it would be good to know what the actual problem is. Do we need our custom dispatch logic?

**Comment by shaman-apprentice** [comment]
@BridgeAR  I absolutely agree, that we don't want to monkey patch redux. My idea is to replace the already previous existing custom dispatch logic (and the hacky monkey patch), after the divorce of `$rootScope` and `redux`. Then it should be easy to replace it through something like [redux-thunk](https://github.com/reduxjs/redux-thunk)

**Comment by shaman-apprentice** [comment]
> Do we need our custom dispatch logic?

Maybe we can even remove the custom dispatch logic completely. To be honest, I wanted to get started with the migration before my holiday. Therefore I did not spent much time into reverse engineering and refactoring... After the divorce of `$rootScope` and `redux` it should be easier and I should have a better understanding of why the custom logic is there in the first place :)

**Comment by BridgeAR** [comment]
@shaman-apprentice does this depend on angular being fully migrated? If so, let's move this into the angular migration issue. If not, let's address this sooner.

**Comment by shaman-apprentice** [comment]
I will add it to the angular issue
