### ISSUE TITLE
Create guide for analyzing Junit5 with CodeCharta sourcecodeparser and csvparser+code-maat

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#230]
Create a guide that explains how to create a cc.json for [Junit5](https://github.com/junit-team/junit5). The tools to use are this time the sourcecodeparser, csvparser (with a csv generated by [code-maat](https://github.com/adamtornhill/code-maat))

Ideas for code-maat metrics are:

java -jar code-maat-0.9.0.jar -a revisions -c git2 -l project.git.log 

java -jar code-maat-0.9.0.jar -a entity-churn -c git2 -l project.git.log

blocked by #236

**Comment by felixherbst** [comment]
blocked by  #236

**Comment by Richargh** [comment]
if we integrate code-maat metrics into ccsh we don't need this guide specifically.
