### ISSUE TITLE
Create a guide for integrating CC into Gitlab-CI build server, with sonar and for a Java project

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#231]
See #229 but this time for Gitlab-CI

**Comment by mrpatpat** [comment]
I actually started writing it up [here](https://github.com/MaibornWolff/codecharta/blob/master/gh-pages/ci-gitlab-dotnet.md) a few days ago but it is a full guide. It is not only limited to Gitlab CI specific configurations, but also for .net projects mentioned in #228.
Is it ok to leave it merged or should we split it ?

**Comment by Richargh** [comment]
@mrpatpat this is very close to the guide we have for .Net. Can we also add the java-variation to the wiki?

**Comment by mrpatpat** [comment]
Yes, I looked into it and it *should* be very similiar. Only the project building part should differ.

**Comment by Richargh** [comment]
We'll leave it a Jenkins https://maibornwolff.github.io/codecharta/how-to/jenkins_sonarqube/ and  Gitlab-Ci for windows https://maibornwolff.github.io/codecharta/how-to/gitlab_ci_windows_net/
