### ISSUE TITLE
Limit maximum legend width

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#2329]
# Bug

## Expected Behavior

GIVEN a map with nodes that have long folder / node names

WHEN opening the legend panel

THEN the legend panel should have a maximum width of ~15-20% of the view and a minimum size so that "Outgoing Edge" is always fully visible. 

## Actual Behavior

The legend panel may increase it's size so that a lot of the screen is not readable anymore.

## Screenshots

![image](https://user-images.githubusercontent.com/8822573/127677894-f3e25218-5886-4dfc-9b35-7b273e248670.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.77.0

**Comment by luelista** [comment]
What are we going to do with the long labels? 

Cut them off?
<img width="541" alt="grafik" src="https://user-images.githubusercontent.com/388142/168556351-0af3e698-eade-4fdb-a6bf-a9e7e5611ff6.png">

Or word wrap?
<img width="544" alt="grafik" src="https://user-images.githubusercontent.com/388142/168556476-bb1ec1d3-3289-4955-a72a-6ca940c8ac9d.png">

I think first looks better, but second is more usable...

**Comment by BridgeAR** [comment]
I agree that the first looks better and I also tend to use that with a tooltip showing the full label with one difference: cut off the start of the label, not the end. The end is often the most important part.

**Comment by luelista** [comment]
direction: rtl; is only recommended to use on text which is actually in a RTL language. See https://developer.mozilla.org/en-US/docs/Web/CSS/direction#examples

If I'd set our file paths to RTL, it's displayed incorrectly: the first forward slash is moved to the end (same behaviour with the full stop in the example above).

**Comment by luelista** [comment]
<img width="596" alt="grafik" src="https://user-images.githubusercontent.com/388142/168795500-41690729-f9a0-43c3-aef7-14bfb42ee7bc.png">

**Comment by luelista** [comment]
Okay, I found a kind-of hacky workaround for that, not sure if we should really do this, but it seems to work...

https://github.com/MaibornWolff/codecharta/pull/2804/files#diff-50667783b76530e0fe16fe24035dfe4c6c004b0e5aea0c190c3e53becdb9d845R86-R93

**Comment by BridgeAR** [comment]
Interesting!

The question for me is, if we actually want to have a trailing slash instead of a leading one. A leading slash indicates an absolute path. In CC that's a difficult to answer question. It's absolute from the frontends perspective but on the device that the file was generated on, it's a relative path.
The trailing slash mainly indicates that it's indeed a path and not a file, which is always going to be the case for these entries, so it does help as a visual reminder (even though it's also valid to omit the slash).

Opinions?
