### ISSUE TITLE
Legend improvements

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#2330]
# Feature request

## Description

As a user, I want the legend to be as useful as possible so that I have all necessary information without any information that is not needed or being distracted by anything.

## Acceptance criteria

- Change the background color of the legend to be identical to the background of the map (it should be 100% transparent)
- Remove the bounding box of the legend so that the content is visible without anything distracting the user
- Remove "Outgoing" and "Incoming" Edge from the legend in case there is no such metric available
- Add all used metrics to the legend and add a description in case we know what the abbreviation stands for

![image](https://user-images.githubusercontent.com/8822573/127678325-76957b55-37bc-4075-aa8b-991dd1dc7eac.png)
![image](https://user-images.githubusercontent.com/8822573/127679683-8ea9c488-83f0-496a-8b15-3829f380ca8a.png)

## Development notes (optional Task Breakdown)

- [x] Remove the bounding box and changing the background color
- [x] Remove "outgoing" and "incoming" edges from the legend, if not applicable
- [x] Add all used metrics to the legend
- [x] Add a list of known metric descriptions to the frontend and show a translation next to the entry

**Comment by jannikr** [comment]
@BridgeAR 
Could you specify which browser has a bounding box? I don't see a bounding box on Chrome (Version 93.0.4577.63). 

Should the background of the legend be like in the image?

![legend-background-color.png](https://images.zenhubusercontent.com/6131edf54db704a4b262f4b8/8ac382cf-7c04-4839-bd64-793396979fa5)

**Comment by BridgeAR** [comment]
This is how I would like it to look like (regular background and white background):

![image](https://user-images.githubusercontent.com/8822573/132403318-0fedf48a-0452-4011-acb2-bdeff0145606.png)
![image](https://user-images.githubusercontent.com/8822573/132403431-cfa372be-295d-4e58-ae2d-c65e3c3ad34f.png)
