### ISSUE TITLE
DRAFT: Map jumping when switching e.g. metric templates

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#2332]
# Bug

## Expected Behavior

GIVEN a map is loaded

WHEN 

THEN

## Actual Behavior

TBD

## Steps to Reproduce the Problem
1.
1.
1.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes | no
- CodeCharta Version:
- OS:
- Browser:

**Comment by ChristianHuehn** [comment]
Closing unfinished draft. Feel free to reopen if needed.
