### ISSUE TITLE
DRAFT: Inconsistent local storage settings / label settings incorrect

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#2333]
# Bug

## Expected Behavior

GIVEN

WHEN

THEN

## Steps to Reproduce the Problem
1.
1.
1.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes | no
- CodeCharta Version:
- OS:
- Browser:

**Comment by ChristianHuehn** [comment]
Closing unfinished draft. Feel free to reopen if needed.
