### ISSUE TITLE
Wait for Sonarqube to finish analysis

### ISSUE THREAD

**Issue by mrpatpat** [MaibornWolff/codecharta#235]
# Feature request

## Description

Sonarqube analysis can take some time. When writing a CI script which triggers an analysis we need a mechanism to wait for the server-side  Sonar analysis to finish. This is the only way to ensure that the sonar importer does pull the latest analysis and not the penultimate.

In a project where this problem occured I used a powershell script as a workaround to wait for sonar. This script is just a workaround and has some minor problems. e.g. It does not check for a specific task to finish. It waits until all analysis on this project are finished.

```
$user = $env:SONAR_USER
$pass = $env:SONAR_PW

$pair = "$($user):$($pass)"

$encodedCreds = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($pair))

$basicAuthValue = "Basic $encodedCreds"

$Headers = @{
    Authorization = $basicAuthValue
}

$Polling = $TRUE

while ($Polling) {
    Start-Sleep 5
    Write-Host "Polling sonarqube server"
    $Response = Invoke-WebRequest '<SERVER_URL>/api/ce/component?component=<PROJECT_KEY>' -Headers $Headers | ConvertFrom-Json
    
    if (($Response.current.status -eq "PENDING") -Or ($Response.current.status -eq "IN_PROGRESS")) {
        $Polling = $TRUE;
    } else {
        if ($Response.queue.Length -eq 0) {
            $Polling = $FALSE;
        } else {
            $Polling = $TRUE;
        }
    }
}

exit $LASTEXITCODE
```

In my opinion we need a mechanism like this in the sonar importer or at least a collection of workaround scripts for each system (Although this would be user-unfriendly and propably more complex than just implementing it into the importer)

**Comment by ukinimod** [comment]
could this be done with Sonarqubes Webhooks (https://itc-20.com/sonarqube/documentation/webhooks)?

**Comment by mrpatpat** [comment]
I do not think webhooks are good in this scenario. Hooks call a given url with a json payload. In this case we want a CI stage to wait for the analysis. This problem can also occur when run locally. 
Another possible scenario would be triggering a visualization build pipeline when an analysis has finished. Here webhooks would be great.

**Comment by Richargh** [comment]
@mrpatpat I think we should close this issue, or finally tackle it. What's your view?
