### ISSUE TITLE
Mark SCMLogParserV2 as stable and deprecate SCMLogParser

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#2350]
# Feature request

## Description

As a user, I want to use the best parser so that I am able to get the most stable, fast and reliable experience.

## Acceptance criteria
- `SCMLogParserV2` should be marked as stable for git repositories. SVN is not yet implemented!
- `SCMLogParser` should be marked as deprecated (recommending `SCMLogParserV2`) for git repositories.
- Maybe rename the parsers to include `git` and `svn`.

**Comment by IhsenBouallegue** [comment]
The docs should also be updated to reflect these changes 👍
