### ISSUE TITLE
Higher margin kills readability of labels

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#237]
# Bug

## Expected Behavior

Labels should be readable also in big maps with margin > 1 and overview mode.

## Actual Behavior

When having big maps with auto-margin (or margin > 1) zooming out to see the whole map will render the labels on files etc. non-readable.

### Screenshots

![dynamic margin (36)](https://user-images.githubusercontent.com/16349180/46069980-0a23ef00-c17d-11e8-8345-5a605d5c95cb.png)

![margin 1](https://user-images.githubusercontent.com/16349180/46070016-1e67ec00-c17d-11e8-8464-65abf6caf326.png)

## Steps to Reproduce the Problem

  1. Load big map
  2. Use margin > 10
  3. Zoom out to see full map
  4. Label more than one item

## Specifications

  - Version: 1.17.0
  - Platform: Mac
  - Browser: Firefox

**Comment by Richargh** [comment]
Solution looks good from my perspective. Please merge
