### ISSUE TITLE
Fix the drawing distance.

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#238]
# Bug

## Expected Behavior

Using dynamic margin I would expect that it is still possible to see the map when clicking auto-adjust and that dynamic margin is not higher than a value so that the whole map is still visible on a standard screen.

## Actual Behavior

When loading a bigger map, with higher dynamic margin (40 in my case) and clicking auto-adjust I no longer see the map at all. After zooming in I can again see the map in full if I carefully set a relatively high perspective. When using a more sensible perspective the map partially disap

### Screenshots

![auto-adjust map](https://user-images.githubusercontent.com/16349180/46070964-49ebd600-c17f-11e8-8034-59ba2ce524fe.png)

![carefully set perspective](https://user-images.githubusercontent.com/16349180/46070943-39d3f680-c17f-11e8-8803-002e7131d909.png)

![partially disappeared](https://user-images.githubusercontent.com/16349180/46070901-23c63600-c17f-11e8-87e8-dd35c24df991.png)
pears.

## Steps to Reproduce the Problem

  1. Load a moderately big map
  2. Keep dynamic margin or some moderately high margin
  3. Click Auto-Adjust
  4. Zoom in 

## Specifications

  - Version: 1.17.0
  - Platform: MacOS
  - Browser: Firefox (Fullscreen)
  - Resolution: 1920x1200

**Comment by Richargh** [comment]
This happens a lot if  there are more than a million lines of code. We need to fix the drawing distance.

**Comment by FernandoES** [comment]
The minimal and maximal drawing distance can be modified in:
app/codeCharta/ui/codeMap/threeViewer/threeCameraService.ts

**Comment by felixherbst** [comment]
explore options in priority:
option 1: determine if three.js can identify objects behind render distance
option 2: let user define render distance in experimental, when loading new maps above certain size, inform user that if he can't see his map, render distance needs to be adapted (manual way of option 3)
option 3: auto adapt render distance for large maps, inform user about possible performance lacks and the option to disable that feature (opt out checkbox)

**Comment by FernandoES** [comment]
This could be useful for option 1: https://threejs.org/docs/#api/en/math/Frustum

**Comment by FernandoES** [comment]
The solution is being developed in branch feature/238/Fix-the-drawing-distance

**Comment by mrpatpat** [comment]
> This could be useful for option 1: https://threejs.org/docs/#api/en/math/Frustum

Maybe we can check all vertices of the maps bounding box with the containsPoint method of the frustum. After that use something like doubling/dividing the near and far plane values until the map is fully included in the frustum. This should not be too heavy on the resources I think.

**Comment by FernandoES** [comment]
Something similar is implemented in this branch in ThreeOrbitControlsService.autoFitTo() but with boundingsphere instead of box to compute distanceToCamera, wich allows to compute the distance from camera to bottom, now stored in ThreeOrbitControlsService.DISTANCE_CAMERA_BOTTOM

**Comment by FernandoES** [comment]
Just to summarize group decisions:
 - FAR value multiplied by 10, not for big maps but hardcoded
 - Render distance no more checked
 - No more pop-up shown to the user, since nothing is changed when the map is big
 - Should be found out how could be rendering optimized for far objects

**Comment by FernandoES** [comment]
The rendering optimization theme is moved to a new issue, so this one focus only in drawing distance fixing, as expect initially

**Comment by FernandoES** [comment]
After testing in a middle class 7 year old computer this change produces no remarkable change in user experience when it comes to performance.

**Comment by Richargh** [comment]
How big was the map? I consider moving #266 way down the inbox.

**Comment by FernandoES** [comment]
the map had an area of 1 100 millions.
I agree with your consideration
