### ISSUE TITLE
Better default perspective

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#239]
# Feature request

## Description

The standard perspective should not be "diamond", but parallel on the border of the square. 

Using the current view takes much space and makes problems with visability on huge maps. Therefore I always manually shift the perspective to the above, which is cumbersome. Having to do it manually has also the effect that it is always slightly non-parallel and looks bad when having to re-adjust it as the perspectives of several screenshots are slightly different.

**Comment by Richargh** [comment]
@felixherbst you had an idea to visualize the perspective right? One of your tools uses a small cube symbol (in the top right corner I think). You can click the cube to rotate 45/90 degrees, view birds-eye perspective etc. Can you perhaps show an example for that?

**Comment by mrpatpat** [comment]
![image](https://user-images.githubusercontent.com/2622069/48257506-f83b9a00-e412-11e8-9ff7-bab15cde85fa.png)
This is the Unity 3D perspective gizmo (right upperhand corner, ignore the arrows in the middle). It represents the current view on the project. Clicking on sides/arrows in it turns the camera to the selected face. e.g. clicking the green axis arrow rotates into a top down view. Clicking on the "Persp." label switches between "perspective" and "isometric" camera. 

![image](https://user-images.githubusercontent.com/2622069/48257942-4604d200-e414-11e8-914d-5023a4ed62d1.png)
The unreal engine solves it a little bit more minimalistic. 

We could also implement something like snapping to nice angles (45,90,...) while rotating to ensure they are easily selected.

**Comment by Richargh** [comment]
I modified @ukinimod's original request so that the original persepective is "parallel on the border" and added #274 in which we explore a new way to select a good perspective.

**Comment by Richargh** [comment]
This is rather well handled by the viewcube and by the custom scenarios
