### ISSUE TITLE
Risk Profiles: Total Sum of percentages exceeds 100%

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2393]
# Bug - Risk Profiles: Total Sum of percentages exceeds 100%

## Expected Behavior

GIVEN loaded codecharta.cc.json sample map

WHEN opening Suspicious Metrics Panel

THEN the sum of percentages should be 100%

## Actual Behavior

THEN the sum of percentages exceeds 100%

## Screenshots
![image](https://user-images.githubusercontent.com/26900540/134864482-bee12bb7-cdfa-4754-b36c-9aa5556ed41c.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.79.0
- OS: Windows
- Browser: Chrome

**Comment by Hall-Ma** [comment]
We already fixed this problem in commit 3bdc263a585cdb92b63bfdca329b869aee822caa from PR: fix/2376/improve-ui-of-suspicious-metrics-feature https://github.com/MaibornWolff/codecharta/pull/2496.
But maybe we should write an additional test to check the risk calculation.
