### ISSUE TITLE
Describe how a City Map is visualized

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2407]
# Feature request

## Description

As a CodeCharta Contributor, I want to have a description on how City Maps are visualized and how D3 and Three.js is used for that, so that I am able to understand the project better.

## Acceptance criteria
- The description is added under Visualization section in [New to this code?](https://maibornwolff.github.io/codecharta/docs/new-to-code/)
- The description explains the collaboration of Three.js and D3
- The description explains how 2D coordinates are mapped to be 3D

## Development notes (optional Task Breakdown)
- [ ] Check if we can reflect the mapping from 2D to 3D coordinates within the code (e.g. as a clear method name `map2dTreeMapNodeTo3d `) and introduce a method accordingly.

**Comment by BridgeAR** [comment]
I would argue this mainly requires our code to be restructured / refactored for better readability? I would not document the behavior would try to change the code itself accordingly.

**Comment by ChristianHuehn** [comment]
I agree, closed
