### ISSUE TITLE
Integrate logging framework to analysis for turning of certain logs

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#243]
# Feature request

In order to be able to switch between log levels in the analysis we introduce a logging framework.

**Comment by Richargh** [comment]
What is the use case for this? I assume it's to be able to add a `-log` command line switch and that switch is useful if a filter has trouble with a file: produces errors or similar.

**Comment by ukinimod** [comment]
Yes, that's the use case. There was a problem with the understand importer and I needed logs to be able to debug it. As it is a common use case I included a logging framework in all analysis parts (see https://github.com/MaibornWolff/codecharta/pull/244) before using it for the understand importer alone. As there must be an issue for all PRs I created this issue. After the review by @alschmut I merged the PR. 
Maybe we could therefore interpret the feature request as done.

**Comment by Richargh** [comment]
Logging works rather differently now due to the pipe support
