### ISSUE TITLE
Suspicious Metrics calculations cause performance issues

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2435]
# Bug
The feature calculates which metrics seem to be suspicious. For those, a Custom Config will be added (e.g. Suspicious MCC Files, Very High Risk RLOC Files).
![image](https://user-images.githubusercontent.com/26900540/136380714-3e8d1105-fd30-42f0-a1c3-62d721fc05f6.png)

Every Custom Config is created by cloning the current state using `klona(state)`. I assume, this becomes to be very expensive, if a lot of metrics are suspicious and a lot of clone-calls have to be made.

## Screenshots
![image](https://user-images.githubusercontent.com/26900540/136380102-cf318a4a-95b0-49de-bef9-f6198db65cbe.png)

**Comment by Hall-Ma** [comment]
This Issue is already fixed in https://github.com/MaibornWolff/codecharta/pull/2564. The state is not cloned anymore.
