### ISSUE TITLE
Suspicious Metrics UI Bug

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2437]
# Bug

If more than two or three metrics are inconspicuous, the `<ul>` overlaps with following DOM elements.

## Screenshots
![image](https://user-images.githubusercontent.com/26900540/136384685-3ffd7a82-d541-47b7-9162-5a4f94f1036e.png)

## Steps to Reproduce the Problem
1. Load `codecharta_analysis.cc.json`

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.80.0
- OS: Windows
- Browser: Chrome 94

**Comment by IhsenBouallegue** [comment]
Fixed by issue #2376 
![grafik](https://user-images.githubusercontent.com/48621967/141097752-d67b3b3a-569b-44b5-bfac-9a87b8ab7827.png)

**Comment by IhsenBouallegue** [comment]
Fixed by #2376 
![grafik](https://user-images.githubusercontent.com/48621967/141097927-1365052d-6274-4bbe-b37a-8525385d1d27.png)
