### ISSUE TITLE
Showing "yellow" Labels not working on "Weighted Gradient"

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2455]
# Bug

## Expected Behavior

<GIVEN>

WHEN clicking "show labels" for the yellow buildings

THEN the labels should appear

## Actual Behavior

THEN no label pops up

## Screenshots
![image](https://user-images.githubusercontent.com/26900540/137688887-fbb96e5d-5d0a-465b-9075-4321c93b1f8e.png)

## Steps to Reproduce the Problem
1. Load Demo Map
1. Click "Show Labels" next to yellow color setting

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.81.0
- OS: Windows
- Browser: Chrome

**Comment by BridgeAR** [comment]
This does not work with either gradient.

**Comment by IhsenBouallegue** [comment]
@BridgeAR Should we move it back to the Backlog if no one is actively working on it? Because it will block the pipeline otherwise
