### ISSUE TITLE
Global component style

### ISSUE THREAD

**Issue by jannikr** [MaibornWolff/codecharta#2470]
# Bug

## Expected Behavior

GIVEN

Component like filePanel

WHEN

editing the styling of the component in the scss-file

THEN

new style is showing up

## Actual Behavior

- The parent component like toolBar is affecting to style of child component

- Different kind of sytling-Frameworks compete with each other

## Steps to Reproduce the Problem

1. Coupling and cohesion principle

1. Select only one global styling-Framework like Angular Material (If further frameworks are needed, then only as few as possible. These must also be compatible with Angular Material)

**Comment by shaman-apprentice** [comment]
This is quite a generic issue and I added a lot of component selectors in the styles during migration. Are you fine with closing this issue (and if needed create more specific ones)? @jannikr @ce-bo

**Comment by ChristianHuehn** [comment]
Can be closed for now. Will create a new issue when switching to the new angular syntax. 
Would be a great opportunity to change some of the styling too.
