### ISSUE TITLE
Suspicious Metrics - Choose programming language for calculation

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2474]
# Feature request

Calculate (merged) percentages for the risk profile for every present programming language. At the moment it is calculated for the most frequent programming language in the map.

![image](https://user-images.githubusercontent.com/26900540/140302268-b25abd4d-8853-4d99-958e-dbafce78fe8f.png)

## Acceptance Criteria
- Percentages are calculated for every programming language that is present in the cc.json.
- The displayed percentages are composed of the risk category percentages of every programming language.
- Textual descriptions have been updated.

**Comment by BridgeAR** [comment]
I personally would like to calculate the risk profiles for all used languages and to use a combined (merged) percentage.
