### ISSUE TITLE
Mobile building view not visible

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#2482]
# Bug

## Expected Behavior

GIVEN a map open on a mobile device

WHEN clicking on a building / file

THEN the detail view should open

## Actual Behavior

The sidebar does not open

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.82.0
- OS: android
- Browser: chrome

**Comment by Christian-Eberhard** [comment]
Can you specify the mobile device and operating system you used to produce this behaviour?
Long clicks (on my device [Galaxy S10, Android 10]) cause the sidebar to open.

**Comment by ce-bo** [comment]
Not working on IPhone Devices

> Can you specify the mobile device and operating system you used to produce this behaviour? Long clicks (on my device [Galaxy S10, Android 10]) cause the sidebar to open.

**Comment by IhsenBouallegue** [comment]
Did a bit of testing and investigation
Does **not** work on:
- iPhone 11, iOS 15.3.1, Safari
- OnePlus 8T, Android 11, Firefox 98.1.1 and Chrome 99.0.4844.58

Something to note, when enabling desktop mode (which actually looks exactly the same) on the mentioned devices it works just fine, so it's probably not a browser issue.
