### ISSUE TITLE
Url parameters do not load properly

### ISSUE THREAD

**Issue by FernandoES** [MaibornWolff/codecharta#249]
You can select one of these templates to file an issue
# Bug

## Steps to Reproduce the Problem

CodeCharta is loaded, then in the side bar "url parameters" button is pressed and the values shown there are copied.
Then this text is added to the name of the website, which online is 

https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json

(it should be taken into account that here the first symbol ? of the url parameters should be substituted by & since there is already a first parameter)

or locally depends on the localhost used, for example by me it is http://localhost:3000/

(It should be taken into account that by localhost that  http:// should be added before  and / should be added after localhost to allow parameter inputs.)

## Expected Behavior
The browser opens the new website with the indicated parameters, which happen to be the same than before.

## Actual Behavior
Firefox opens the website properly, chrome and Safari do not open the proper website.

The copied url parameters contains a line break (ASCII decimal value 10) and a carriage return ( ASCII decimal value 13 ) between every two parameters, those two chars are translated into %20 %20 when pasted in the url. If they are deleted manually before pasting it in the url everything works as expected.

Please check these resources first before posting a question

* [x ] I searched for answers in [older issues](https://github.com/MaibornWolff/codecharta/issues?utf8=%E2%9C%93&q=)
* [ x] I looked into the [README.md](https://github.com/MaibornWolff/codecharta)
* [ x] I read the [website](https://maibornwolff.github.io/codecharta/)

## Question

Could we somehow achieve to avoid that problem while keeping the cleanness of showing every parameter in a single line when opening the url parameters window?

**Comment by alschmut** [comment]
@Richargh I feel like this issue is outdated, as we do not show the url parameters for settings properties anymore.

**Comment by Richargh** [comment]
Agreed. I'm closing it.
