### ISSUE TITLE
WIP: Auto detect good metric limits for yet unknown metric types for the suspicious metrics

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#2491]
# Feature request

## Description

As a user, I want the suspicious metrics to handle metrics that are yet unknown so that I am able to identify extreme values faster.

## Acceptance criteria

- Check historic data and filter for 
- 
- 

## Development notes (optional Task Breakdown)
- [ ] 
- [ ] 
- [ ]

**Comment by ChristianHuehn** [comment]
Right now I'm cleaning up all draft/wip issues. Closed as it is in wip since 2021.11. But the idea is good, I take it on my notes and re-add if necessary.
