### ISSUE TITLE
ThreeJs Dependency Update

### ISSUE THREAD

**Issue by jannikr** [MaibornWolff/codecharta#2492]
# Bug

During the migration of renovate we decided to exclude the dependency check of ThreeJs because the new major updated causes problems with our default colour palette. Therefore we create this issue to have a separate place to fix this problem. 

Additionally, we should move away from the no longer maintained ThreeOrbitControls, which we still use. A good replacement could be the builtin Orbit- or ArcballControls https://threejs.org/docs/index.html#examples/en/controls/OrbitControls https://threejs.org/docs/#examples/en/controls/ArcballControls

When this issue is fixed we should add ThreeJs to our Renovate Pipeline.

## Expected Behavior

WHEN

updating to ThreeJs and @types/three to newest version eg. 0.134.0.

THEN

default colours should be the same as before

## Actual Behavior

default colours are completely different. But changing the colour with the colour picker works fine.

## Screenshots

![Bildschirmfoto 2021-11-09 um 14.03.52.png](https://images.zenhubusercontent.com/6131edf54db704a4b262f4b8/a3d07240-3887-4c78-a827-12a0a20cddaf)

## Specifications
- CodeCharta Version: 1.83.0
- OS: MacOS
- Browser: Firefox 93.0

**Comment by ce-bo** [comment]
PR for bumping version of three.js #2503

**Comment by ChristianHuehn** [comment]
Updated threejs, we dont switch to arcball for now
