### ISSUE TITLE
Show garbage bin next to the loaded maps

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#2499]
# Bug

## Expected Behavior

GIVEN codecharta is opened

WHEN you open the list of the loaded maps

THEN it's possible to remove individual maps to allow for a better overview and less memory usage

## Actual Behavior

The button to remove a map is not visible anymore. That was planned for the [current implementation](https://github.com/MaibornWolff/codecharta/pull/2065).

## Screenshots

![image](https://user-images.githubusercontent.com/8822573/141348499-069903b4-2462-40a0-93e1-8467c3de77c9.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.83.1
- OS: all
- Browser: all

**Comment by cschild** [comment]
Can a user delete all maps?

**Comment by ce-bo** [comment]
I am not sure what @BridgeAR thinks about that.
But in the original implementation the remove button was only visible if at least 2 files are loaded:
https://github.com/MaibornWolff/codecharta/commit/489c62a0ed825a4d03aeb5d75efff56f154a54d4

Therefore, I would do it like back then.
