### ISSUE TITLE
Combine single and multiple mode

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#2506]
# Feature request

## Description

As a user, I want to have an intuitive UI so that it's straight forward to use the application.

## Acceptance criteria

- Remove "single" mode. This is in fact identical to the "multiple" mode with only a single map being used
- Migrate the component to the new Angular

## Assumptions & Exclusions

Check problems around black list entries as described here: #476

## Checklist

- [x] Migrate component to new angular

- [x] Remove all occurrences of "Single" mode in the code

**Comment by IhsenBouallegue** [comment]
If I understand correctly, this means a major update?

**Comment by jannikr** [comment]
We might consider updating the screenshot in the Readme.md because it no longer matches the current state of the system.

**Comment by Christian-Eberhard** [comment]
Has been split into:
https://github.com/MaibornWolff/codecharta/issues/2546

**Comment by BridgeAR** [comment]
@Christian-Eberhard are you certain you meant this issue is split into smaller chunks? I guess you meant to reference the other issues as being related to the modes in general?

**Comment by Christian-Eberhard** [comment]
Both in a way. I feel like all of the mentioned issues need to be adressed to make this feature feel good

**Comment by BridgeAR** [comment]
I agree that the modes feature itself would benefit from these changes but they do not seem required to address this issue and the other issues seem independent to me, no?

**Comment by Christian-Eberhard** [comment]
Yes

**Comment by jannikr** [comment]
Currently I have continued to work on the standard branch for this issue. We should close this issue after the adjustments of the modes and the migration and work on the related issues at a later time. Otherwise, this issue would block us too much.

**Comment by Christian-Eberhard** [comment]
This is why i choose to remove some weight from the issue.
