### ISSUE TITLE
Add "code quality default metric behavior"

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#2507]
# Feature request

## Description

As a user, I want to change as little as possible so that I have to do less work to achieve my goal.

It is often difficult to understand a map if all three metrics show different things. Mostly people want to change the color and height together and keep the size metric fixed as rloc (with a fallback to loc).

## Acceptance criteria

- Add a button (checkbox) that indicates the "program code" default behavior. In case it's set "bind" the height and color metric together and always use the preselected size metric like `rloc` or `loc` (done by #1532) for the size metric. 

## Open questions

- Define where to place the checkbox. Any suggestions are appreciated.

**Comment by Hall-Ma** [comment]
@BridgeAR Which behavior should be the standard now? The linked or unliked behavior? 
Also, would you like (when the coupling is enabled) the color metric chooser to be disabled in the panel so that the user cannot select a color metric until it is unlocked again?

**Comment by BridgeAR** [comment]
> Which behavior should be the standard now? The linked or unliked behavior?

I suggest we start by implementing the feature and keeping it disabled for now. Let's get some user feedback about it after a while to check if we want to enable it by default. It should also be disabled for cases where `rloc` and `loc` can not be found.

> would you like (when the coupling is enabled) the color metric chooser to be disabled in the panel so that the user cannot select a color metric until it is unlocked again?

Yes, that would be ideal.
