### ISSUE TITLE
Weird metric description

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#2508]
# Bug

## Expected Behavior

GIVEN a map is loaded

WHEN clicking upon the metric type

THEN the types are visible and the description for the search bar is properly readable

## Actual Behavior

`fl Metric` is shown in the search bar.

## Screenshots

![image](https://user-images.githubusercontent.com/8822573/141859457-2bb8420e-aa93-412c-b68b-90ce247329ce.png)

## Steps to Reproduce the Problem

1. Click on the metric type

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.83.0
- OS: all
- Browser: all

**Comment by ce-bo** [comment]
I cannot reproduce it in the web demo.

**Comment by BridgeAR** [comment]
I am able to reproduce it on Firefox and Chromium in the web demo on Ubuntu.

**Comment by jannikr** [comment]
We saw this problem on Kali Linux system too. It is very hard to find a solution that renders icons properly inside the input tag. Therefore we tried to insert the icon inside an i tag. With this solution the icon displays correct on every system. It is a very unpleasant solution, maybe we should research for other options. Keywords: Unicode, FontAwesome, Ubuntu

**Comment by BridgeAR** [comment]
I am going to reopen it even though it's more like a new issue:

Ideally, the placeholders contain the metric name (Color Metric, Edge Metric, Height Metric, Size Metric).
