### ISSUE TITLE
Deltamode Pictogram does not update when new colors are selected

### ISSUE THREAD

**Issue by Christian-Eberhard** [MaibornWolff/codecharta#2513]
# Bug

## Expected Behavior

The user is in deltamode and wants to change the colors of the deltas.

When changing the colors in the color settings

Then the pictogram next to the selected map should update

## Actual Behavior

The pictogram only updates when changing to a different cc.json

## Screenshots
![Delta.JPG](https://images.zenhubusercontent.com/6076b0525fa0ae9470963a22/1cd8c86e-7a15-4b0e-aa1f-dd82eaddcd5f)

## Steps to Reproduce the Problem
1. Open delta mode
2. Change colors
3. To update the colors in the pictogram, change the selected cc.json in the delta view

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes

**Comment by ce-bo** [comment]
Let's close it: Fixed in #2864.
