### ISSUE TITLE
Label line height does not get reset

### ISSUE THREAD

**Issue by Shivan-997** [MaibornWolff/codecharta#2518]
# Bug

## Acutal Behavior

a visualized cc.json is opend. after increasing the height:
Labels line still has the last height  (Screenshot 1)

## Expected Behavior

a visualized cc.json is opend. after increasing the height:
Labels height is reset

## Screenshot
![Screenshot 2021-11-19 at 16.20.29.png](https://images.zenhubusercontent.com/5ffed4e0d883b3484758dac9/b325d808-26da-4c31-a68f-bf678a22c0eb)

**Comment by ce-bo** [comment]
Seems to be fixed. If it reoccurs, please open a new issue with a concrete description and example.
