### ISSUE TITLE
Importers accept files without .cc.json 

### ISSUE THREAD

**Issue by IhsenBouallegue** [MaibornWolff/codecharta#2522]
# Feature request

## Description

As a user, I want to write commands without file extensions so that it is easier.

## Acceptance criteria
- The importers will check if a the presented output file has an extension
- They make sure it is .cc.json
- If not they add it

## Example
csvimport  -nc -o outputFile File
will export outputFile.cc.json and not outputFile

## Open questions
To keep the change consistent, all importers must be changed. Let's discuss if this is something we want/need

**Comment by ce-bo** [comment]
Duplicate: #2800
