### ISSUE TITLE
"Know more" button in What's new section doesn't work

### ISSUE THREAD

**Issue by Hall-Ma** [MaibornWolff/codecharta#2523]
# Bug

## Expected Behavior

When "Know more" button is clicked then news page should open a new tab.

## Actual Behavior

"Know more" button doesn't link to news page

## Screenshots

![Bildschirmfoto 2021-11-24 um 12.08.18.png](https://images.zenhubusercontent.com/615eb4f76331b83ced10ffe0/2f345f49-8468-4d79-90d7-0f1420621128)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes 
- CodeCharta Version: 1.84.0
- OS: all
- Browser: Chrome

**Comment by Hall-Ma** [comment]
My suggestion is to use 
`a href="#" onClick="window.open('https://maibornwolff.github.io/codecharta/news/', '_blank')" class="md-primary">Know more</a>` in dialog.changelog.component.ts

**Comment by ce-bo** [comment]
I would be very suprised, if the `<a>` tag does not work without JavaScript in this case.
Adding `target="_blank"` works for me.

I just noticed that in the current implementation the link does not work but the URL has changed.
(Windows, Chrome)

**Comment by Hall-Ma** [comment]
I wonder that the current implementation works local but not in the deployed version. Furthermore it would be more convenient when a new tab would open the news page.
