### ISSUE TITLE
Compressed files (.gz) with API version 1.3 are no longer loaded into visualization

### ISSUE THREAD

**Issue by Hall-Ma** [MaibornWolff/codecharta#2524]
# Bug

## Expected Behavior

Given cc.json.gz with **API version 1.3**

When choosing a cc.json.gz file (made by our parser) to load into visualization then a map should appear.

## Actual Behavior

Map doesn't load. Validation Error says "API version is empty or invalid".

## Steps to Reproduce the Problem
1. Parse a project with source code parser with default settings.
2. Load cc.json.gz into visualization.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.84.0
- OS: Mac
- Browser: Chrome

**Comment by ce-bo** [comment]
There was a bug some time ago (#1593) that had led to the same consequences. 
We should write a regression test for this crucial feature to ensure the general functionality of a new released CodeCharta Version
Test Scenario: Generate zipped and unzipped .cc.jsons -> upload them in the visualization -> map loaded properly

**Comment by ce-bo** [comment]
As described in the PR, we should generate .gz files during build pipeline to ensure the functionality of CodeCharta (current parsers are working with current visualization).
