### ISSUE TITLE
Create zipped CodeCharta cc.json files during pipeline build

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2538]
# Feature request

In build_gh_pages.sh we create unzipped cc.json files. The default case is, that parsers are creating compressed (.gz) files.
Let's build compressed files during the build pipeline.
Then, to ensure the functionality of CodeCharta (current parsers are working with current visualization), the created and zipped files should be used in our e2e tests to test the behaviour automatically.

## Acceptance criteria
- During Build Pipeline .gz and unzipped files are generated
- When loading CodeCharta the zipped files should be loaded instead of unzipped ones to reflect the default case.
- E2E Test to test uploading compressed files is using the continuously updated compressed sample files.

## Development notes (optional Task Breakdown)
- Modify build_gh_pages.sh to generate unzipped and zipped files.

**Comment by ce-bo** [comment]
@BridgeAR please have a look on this issue and feel free to adjust acceptance criteria.

**Comment by jannikr** [comment]
This issue is not closed, because the merge and patch was just for testing.

**Comment by Hall-Ma** [comment]
Still not working on our Website. We have to figure it out where we have to change the url.
