### ISSUE TITLE
Show deleted buildings in delta view

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#254]
In the delta view two cc.json (`file` and `compare to`) can be compared. If a building existed in `compare to` but no longer in `file` it is not visible in the visualization, if I select a metric like *rloc*. This needs to change.

**Given** a building exists in  `compare to ` but no longer in `file`
**and** I open the delta view
**When** I select the metric *rloc* for size and *mcc* for height
**Then** I see a red building (or green if colors are inverted) and use the metrics from `compare to`.

**Comment by alschmut** [comment]
So with other words: For deleted files in delta view, use the metrics from the deleted file and color it by default red

**Comment by Richargh** [comment]
Yes. Also, that is a great and uncomplicated summary :)
