### ISSUE TITLE
Ribbon looks strange in delta mode

### ISSUE THREAD

**Issue by shaman-apprentice** [MaibornWolff/codecharta#2544]
# Bug / Question

What is the intendet behavior of the ribbon bar in delta mode? The ribbon bar looks broken?

![image](https://user-images.githubusercontent.com/3596742/144638232-df2d2c9e-a7a9-4e16-b206-8b197765300c.png)

**Comment by BridgeAR** [comment]
It is not possible to change the colors in delta mode. Therefore it's not visible in the UI. Do you have a suggestion how to improve something? Otherwise this could probably be closed again?

**Comment by shaman-apprentice** [comment]
We can still click on color settings. Maybe we should hide the color settings. Dropdown for edge metrics are hidden as well - I assume because we don't calculate deltas for edge metrics?

**Comment by BridgeAR** [comment]
> Maybe we should hide the color settings.

We still have settings that the user should be able to configure:

![image](https://user-images.githubusercontent.com/8822573/144992987-c5b43fa4-8132-4680-89ac-6a8b53b69256.png)

> Dropdown for edge metrics are hidden as well - I assume because we don't calculate deltas for edge metrics?

Yes

**Comment by shaman-apprentice** [comment]
Thanks for the clarifications.

**Comment by BridgeAR** [comment]
@shaman-apprentice there is something that we could hide though: 
![image](https://user-images.githubusercontent.com/8822573/145264020-dc326eb1-f022-4a64-b5ac-88898be4a0f6.png)

This part won't have an effect.
