### ISSUE TITLE
Clearer behaviour when switching between map modes

### ISSUE THREAD

**Issue by Christian-Eberhard** [MaibornWolff/codecharta#2546]
# Feature request

## Description

As a user, I want to have a consistent behaviour when switching from map modes so that i dont get confused.

When currently switching map modes between "Multiple Mode" and any other mode, the preselected maps in 
"Multiple Mode" are the last maps i uploaded together. It would be a clearer behaviour to preselect the last maps that have been selected by the user before switching modes.

## Acceptance criteria
- Multiple mode "remembers" which maps have been selected last
- Multiple mode selects the last selected maps when switching to it

**Comment by ce-bo** [comment]
Fixed by #2892
