### ISSUE TITLE
Fully transparent and online parsing

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#2570]
# Feature request

## Description

As a user, I want to focus on the data visualization and not on the data parsing so that I have to invest less time using CodeCharta.

The new (experimental) file API (so far Chromium based browsers only) allows to open directories and files on a local computer in the browser and also allows to edit those files.
We should be able to use a pure JS parser to allow opening a folder on the local machine of the user and to auto parse the data in the browser. That data could then be saved by the user and immediately be visualized without having to install anything or to enter any command/information in a shell. Everything could be done right away in the browser.
If we require to load e.g., C code or similar, we could compile those file to WASM by using Emscripten.

## Acceptance criteria

- Figure out if the idea might actually work

**Comment by ChristianHuehn** [comment]
We will change our approach. Doing all this from browser will take a lot of work, which we are not doing in the near future. Instead we will provide better ways to parse projects via docker so users can easily parse locally and use our web demo for analyzing their code.
