### ISSUE TITLE
Improve multiple mode

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#2574]
# Feature request

## Description

As a user, I want all features to work identical in single or multiple mode so that it feels like having a single file, no matter what.

This is for example important for the suspicious metrics that currently only work on a single dataset, even while being in multiple mode. The internal implementation would be much simpler that way and there's no implementation overhead checking all maps that are used for multiple mode.

## Acceptance criteria

- Rework the current internal implementation combining files in multiple mode. It should behave as a single dataset instead of multiple sets.

## Notes

This is kind of a feature and bug fix at the same time.

**Comment by ce-bo** [comment]
I think the fix for the suspicious metrics feature was already done in #2721.
