### ISSUE TITLE
Sonarqube issues

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#258]
You can select one of these templates to file an issue

# Technical Issue

There are many sonarqube issues in codecharta and quality gates are not passed:
https://sonarcloud.io/dashboard?id=de.maibornwolff.codecharta%3Avisualization

**Comment by Richargh** [comment]
#265 will increase code coverage. Most sonar issues are not issues at all. Sonar simply does not like the way angular works. We'll have to update the profile for this.

**Comment by Richargh** [comment]
Closed because we tackled many issues already and try to get even better.
