### ISSUE TITLE
Easier switching between the delta mode direction

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#2581]
# Feature request

## Description

As a user, I want to be able to switch which file is the first one and which is the second one so that I am able to switch the delta direction.

## Acceptance criteria

- Add a button between the delta mode to switch the position.
- Make sure all setting are identical, just the directions are switched

**Comment by ce-bo** [comment]
@knoffi any open questions/things to discuss or was the switch to further inquiry not intentional?

**Comment by knoffi** [comment]
Thank you for asking. I guess, after some fiddling around every question was more or less answered.
