### ISSUE TITLE
Suspicious Metrics - Broken menu

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2589]
# Bug

## Expected Behavior

<GIVEN>

WHEN
loading firefox.cc.json with kind of exotic metrics

THEN
Suspicious Metrics menu should be grayed out (it should not be clickable) and show a message on hover (a regular title behavior, showing the message after a short delay) that it's not available, if no metrics have been calculated due to not matching any known metric types. Show a short message that no suspicious metrics have been found if that's the case (only inconspicuous metrics were found).

## Actual Behavior
Suspicious Metrics menu is broken

## Screenshots
![image](https://user-images.githubusercontent.com/26900540/147918662-5c42568f-d5d7-4f03-896a-40f7e6598244.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.86.0
- OS: all
- Browser: all

**Comment by BridgeAR** [comment]
I updated the above to behave a bit different depending on two different scenarios.

**Comment by Hall-Ma** [comment]
Solved in #2721
