### ISSUE TITLE
Unhandled promise rejection when uploading custom configs

### ISSUE THREAD

**Issue by Hall-Ma** [MaibornWolff/codecharta#2613]
# Bug

## Expected Behavior

When a configuration is uploaded, it happens without errors.

## Actual Behavior

When uploading a custom config then we get an error in the console. Nevertheless, we can use the config as usual.

## Screenshots

<img src="https://images.zenhubusercontent.com/615eb4f76331b83ced10ffe0/962c0815-0fef-415b-a43c-c2b3d2b6c31e" width="700">

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.87.1
- OS: Mac
- Browser: Chrome

**Comment by shaman-apprentice** [comment]
Is this still the case? Could you @Hall-Ma  please provide a not working example?

**Comment by Hall-Ma** [comment]
No, I couldn't reproduce it. I close this issue.
