### ISSUE TITLE
Import GameObjects File

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2617]
# Feature request

## Description

As a User, I want to import the attached Game Object Json File ([gameObjectPositions.zip](https://github.com/MaibornWolff/codecharta/files/7906328/gameObjectPositions.zip)), so that I can explore them in the 3D visualization.

## Acceptance criteria
- [x] A prototype script can import the game objects of the attached file: [gameObjectPositions.zip](https://github.com/MaibornWolff/codecharta/files/7906328/gameObjectPositions.zip)
- [x] The prototype creates and exports a valid .cc.json file
- [x] The .cc.json file can be imported and visualized in CodeCharta Visualization
- [x] The prototype can import the dependencies included in the attached file

## Assumptions & Exclusions
- Dependency Information will be attached soon.
- The GameObject JSON Files will include Java Classes only
- Class Names do not have dots included

## Development notes (optional Task Breakdown)
- It would be sufficient to write a prototype script (e.g. written in Node.js) to import the data
- The x, y and z coordinates and the scaling must be transformed into our format

## Screenshots from GameObject Tool
![image](https://user-images.githubusercontent.com/26900540/150517703-94f6e911-fdcb-4e54-bb33-a18ea988ccf0.png)
![image](https://user-images.githubusercontent.com/26900540/150517709-d09a3a8d-081a-47c1-b9ec-2ba820038827.png)

**Comment by IhsenBouallegue** [comment]
What are the dependencies? Can anyone clarify that a bit?

**Comment by IhsenBouallegue** [comment]
Should it be called GameObject? Or should we find a more descriptive name?

**Comment by ce-bo** [comment]
@IhsenBouallegue The dependencies list will be a from-to list. This relationships are used to draw the Edges/Arrows in CodeCharta. E.g. it is used to depict that two buildings are coupled due to any reason. As soon as the JSON strucutre and one example for the list is provided, we can start to implement this as a second step.

The naming of GameObject is not final yet. It could change in the future but for the Prototype I would keep it, because it is a known term.

**Comment by IhsenBouallegue** [comment]
Another question about the coordinates. The x, y and z are in relation to what? Where is the origin point of the map. And do they tell us the position of the middle of the buildings or the corner?

**Comment by IhsenBouallegue** [comment]
Yet another question,
Because we don't have file extensions. We can't know if a building is a file or a folder. However, all folders have scale.y = 1. Can we assume that only folder have that? Or is it also possible for files to have a height of 1?

**Comment by ce-bo** [comment]
I would make an assumption for now, so that names include file extensions and the path is separated by `/`.

The coordinates are Unity world positions: https://docs.unity3d.com/ScriptReference/Transform-position.html
Scalings are Unity local scales: https://docs.unity3d.com/ScriptReference/Transform-localScale.html

Buildings can be scaled in any direction:
Height Scaling to express how often the file/building/component is used by others (incoming direction).
Area Scaling to express how many other compontens are used by the component (outgoing direction).

**Comment by ce-bo** [comment]
The dependency export is available. One Example with Edges/Dependencies for dependency cicles:
[gameObjectsAndCycles.zip](https://github.com/MaibornWolff/codecharta/files/7971020/gameObjectsAndCycles.zip)

**Comment by ce-bo** [comment]
Open TODOs fo finalize this issue:
- Currently, the buildings look a bit compressed compared to the buildings in the screenshots. Let's try to improve the aspect ratio to be less squared and more like the aspect ratio depicted in the screenshots.
- Finalize and improve the import script, so that we are able to upload the Game Objects structure, transform it to our cc.json structure and visualize it accordingly.

**Comment by IhsenBouallegue** [comment]
A fellow up question to this point,
>     * Finalize and improve the import script, so that we are able to upload the Game Objects structure, transform it to our cc.json structure (on upload) and visualize it accordingly.
By on upload, is it meant that we do it on the fly? Should the frontend detect which JSON structure was uploaded and create a CC.JSON if needed? Should a backend handle? Simply put, how should the "pipeline" look like? Any tips would be appreciated.

Also, it would be really helpful to have a couple more  files for testing. Files that only include java classes (how this parser was meant to be used). So far we have been making theories and assumptions and that's confusing.

**Comment by ce-bo** [comment]
Yes, on the fly. If you upload a json file in the visualization, the frontend should detect the GameObject structure and transform it to a valid cc.json file.
