### ISSUE TITLE
Import Metrics of MetricGardener

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2619]
# Feature request

Before this can be done, the release of MetricGardener must be planed (e.g. publish on npm.js).

## Description

As a User, I want to import [MetricGardener ](https://github.com/MaibornWolff/metric-gardener/)imports, so that I am able to visualize standard metrics (e.g. complexity, size, etc.) and dependency metrics (e.g. outgoing/incoming coupling) for a lot of languages.

## Acceptance criteria
- [x] A new importer in CodeCharta Analysis can be called from the User to run and import MetricGardener files (execute MetricGardener as a terminal command via npm).
- [x] MetricGardener needs to be published to the npm repository. [Try me](https://www.npmjs.com/package/metric-gardener)
- [x] The importer provides interactive CLI usage.
- [x] The outcomming structure of MetricGardener is transformed to our .cc.json structure
- [x] The importer exports .cc.json files in zipped format per default.

## Development notes (optional Task Breakdown)
- Use the npm package https://github.com/MaibornWolff/metric-gardener/ to parse source code in lots of programming languages
- MetricGardener files are volatile, the structure is not stable and will most likely change
- The file pathes must be transormed appropriately to match .cc.json structure

**Comment by MW-Friedrich** [comment]
We still need to find a way to elegantly execute npm cli commands from within our Kotlin code. So far we have looked into:

- Java's Runtime.exec
- Turtle (https://github.com/lordcodes/turtle)
- Running a shell script via Runtime.exec or Turtle
- Gradle Node Plugin (https://github.com/node-gradle/gradle-node-plugin)
- Kotlin Multiplatform (https://kotlinlang.org/docs/multiplatform.html)

For release 1.101 our focus was more on the parsing from a metric-gardener json to our cc.json, so we only tried out these solutions experimentally.

**Comment by BridgeAR** [comment]
@MW-Friedrich please do not use something like the Gradle Node Plugin. It is specific to Node.js but what, if we want to use something else? Then we need another individual solution. The command should just be executed as any other shell command. Using turtle for it is probably fine.

**Comment by ce-bo** [comment]
I had a look on this. I ended up running metric-gardener npm binary using Turtle. This worked for me. But I am not sure if it is a good idea. @BridgeAR what do you think?
```    @Test
    fun `should run metric gardener help`() {

        val userDir = System.getProperty("user.dir")
        println(userDir)

        val os = System.getProperty("os.name")

        var binaryPath = userDir + "/../../node-wrapper/node_modules/.bin/metric-gardener"
        if (os.contains("Windows")) {
            binaryPath += ".cmd"
        }

        val realPath = Path(binaryPath)
        println(realPath)

        val output = shellRun(realPath.toString(), listOf("--help"))
        println(output)

        Assertions.assertThat(output.toStr()).contains("app.js <command>") // Current branch name, e.g. master
    }```

**Comment by ce-bo** [comment]
I will check if we can use this without turtle.

**Comment by BridgeAR** [comment]
The question is, if we ship CC with metric gardener or without. If we ship it, then the above would work. I thought we did not ship it and in that case, it would be:

1. Check if metric-gardener is installed locally or globally
  a. No: Ask if it should be installed.
      i. No: Stop with an error message
      ii. Yes: run install command and go to 2.
  b. Yes: go to 2.
2. Run metric-gardener

**Comment by Chrisp485** [comment]
I think it would be easier to ship metric-gardener with CC. Just checking if metric-gardener is installed is not gonna be easy, espically across different OS and since people might even change their default node modules directory.

**Comment by ce-bo** [comment]
Let's ship it with CC. I will open a new issue for asking the user to install it.

**Comment by MW-Friedrich** [comment]
Should I close this issue then? Also thanks for the insight on how to best integrate something like this :)

**Comment by ce-bo** [comment]
No, the task to call/run metric gardener by a terminal command is still open. So let's ship MetricGardener with CC (install it via npm as a dependency in the analysis node-wrapper) and run it similar like I suggested in this [comment](https://github.com/MaibornWolff/codecharta/issues/2619#issuecomment-1195316807).

**Comment by MW-Friedrich** [comment]
Ah, I see! I think I just misunderstood you then, thank you for clarifying 👍

**Comment by ce-bo** [comment]
Are there any open questions?
