### ISSUE TITLE
Attribute Sidebar: Change to Median no longer possible in Secondary Metrics

### ISSUE THREAD

**Issue by Hall-Ma** [MaibornWolff/codecharta#2630]
# Bug

## Expected Behavior

<GIVEN>
When attibute sidebar is open then I can change from Sum to Median in Secondary Metrics list.

## Actual Behavior

When attibute sidebar is open I only can change global aggregation to Median in Primary Metrics. In Secondary Metrics I can choose Median but nothing is changed including the button.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes 
- CodeCharta Version: 1.88.0
- OS: Windows
- Browser: Chrome

**Comment by shaman-apprentice** [comment]
During fixing I noticed, that edge metrics are not taken into account by secondary Metrics. Is that on purpose? Should We create a feature / bug request for that? (@BridgeAR )
