### ISSUE TITLE
Unify root node

### ISSUE THREAD

**Issue by shaman-apprentice** [MaibornWolff/codecharta#2674]
# Feature request / Question

## Description

As an user I find the "root" node quit confusing. When switching between single <-> multiple file mode the file name gets added / removed as second node. 

Wouldn't it be more consistent to have the label of "root" node removed and to always show the file name as second node?

![image](https://user-images.githubusercontent.com/3596742/154859999-e868101b-f2ed-484d-9707-c4d70fa0ce0b.png)

Would fix #2673

**Comment by BridgeAR** [comment]
This should ideally be done by our merging tool and not by the frontend. The reason is that the frontend is not able to decide this on its own. It should be something specific that the user does.
