### ISSUE TITLE
Loading gif is always visible in ribbon bar

### ISSUE THREAD

**Issue by Hall-Ma** [MaibornWolff/codecharta#2680]
# Bug

## Expected Behavior

When open CodeCharta, the loading gif is only visible while a file is loaded.

## Actual Behavior

When starting CodeCharta the loading gif is always visible.

## Screenshots
![image](https://user-images.githubusercontent.com/72517530/155133792-2d6d775e-e5ff-4a7a-a7b9-86b07b500afe.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes 
- CodeCharta Version: 1.91.0
- OS: Windows
- Browser: Chrome

**Comment by shaman-apprentice** [comment]
##First analyse:

With 4ad684e the following scenario stopped working / before this commit it worked with the local dev app:
1. `npm run dev`
2. Load latest version of released CodeCharta demo app (v1.91.0)
3. Open file selections and select *sample2.cc.json*

Loading Gif stays **AND sample2.cc.json isn't displayed in the map.**

## To be further analysed:
Is the cause for this the same bug as in the demo app or is this another bug?
