### ISSUE TITLE
Add changelog to releases

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#2684]
Please add the changelog entries to our release entry during publishing.

![image](https://user-images.githubusercontent.com/8822573/155725466-7b13b56c-dd75-4726-a6db-9e3cda4a8a3c.png)

**Comment by BridgeAR** [comment]
@IhsenBouallegue thanks for adding that. The issue was not meant as a one of thing but a request to implement this to automatically do that on each publishing process.

**Comment by BridgeAR** [comment]
I believe it's added manually at the moment, right?

**Comment by phanlezz** [comment]
Closed via #2916

**Comment by BridgeAR** [comment]
The last release had a wrong version number and it might work but so far there has nothing been added to the changelog. I am going to reopen until it's definitely fixed :)

**Comment by MW-Friedrich** [comment]
With the release of 1.103.1, this now works, although the formatting differs slightly from before (The word "Release" is missing before the version number and the date isn't explicitly stated again).
We (@phanlezz @jannikr and I) think this is acceptable though. If not please reopen this ticket.
