### ISSUE TITLE
Fix hiding Nodes in Blacklist and TreeView eye-click does not work

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#271]
# Bug

## Expected Behavior
- Toggle visibility when clicking on the eye in the Treeview next to the node name
- Show the node again, when removing the hide-item in the blacklist.

## Actual Behavior
- Clicking on the dashed eye does not reshow the node.
- When removing a hide-item in the blacklist the node doesn't show up in the Codemap

### Treeview:
  1. Open Sidebar and TreeView Panel
  2. click on any eye to hide the node
  3. click on the same dashed eye to show the node again
  4. the node visibility keeps hidden

### Blacklist:
  1. Open Sidebar and BlacklistPanel
  2. right click on any codeMap-node and click HIDE
  3. the hide item shows up in the blacklist
  4. click the trash can icon to remove that hide-item
  5. the hide-item is deleted, but the codemap doesn't show the node again

## Specifications

  - Version: 1.19

**Comment by alschmut** [comment]
As I talked to @ukinimod in the short term its okey to switch off the Isolate functionality to remove the Hide bug. We can then have more time to discuss #268.

**Comment by Richargh** [comment]
We moved further work to #273.

**Comment by alschmut** [comment]
@Richargh shouldn't we at least "fix" the bug for the audit/review tomorrow (Friday)?

**Comment by Richargh** [comment]
Yes. I guess my comment was confusing. Please review and merge this bug. As for a Review. I won't be there but that does not mean you can't hold one.
