### ISSUE TITLE
Changelog tool

### ISSUE THREAD

**Issue by IhsenBouallegue** [MaibornWolff/codecharta#2722]
# Changelog Tool

## Description

As a developer, I want to easily be able to correctly update the CHANGELOG.md each time so that PRs don't get stuck for days because of silly changelog mistakes.

We have [Changelog Guidelines](https://github.com/MaibornWolff/codecharta/blob/main/CONTRIBUTING.md) on how to add entries to the Changelog. But humans are error-prone, and I noticed that sometimes issues stay longer in review column than needed because of simple mistakes in the changelog. Or worse they go unnoticed (which is from experience a pain to fix)

A possible way to solve this is not to change the changelog manually, but to create a tool with a configuration of the current guidelines. So that we input the relevant information (Change type/Description/PR number…) and the tool does the needed formatting. 

We already do this as part of our release pipeline (we don't change the Changelog manually to avoid mistakes)
So it only seems natural to do this also for development.

Furthermore, the changelog parser (used to display the new changes since the last visit) assumes that the changelog is correctly formatted (according to our guidelines). By using a tool that consistently updated the changelog, we ensure that the changelog parser won't randomly break because of a random, unnoticed mistake.

A plus side is that such a tool/script can be used across projects (or maybe there is already a library for it)

## Acceptance criteria
- It should be able to receive change type, description, PR numbers as input.
- It should be able to parse the input into the changelog format that we use (to be compatible with our changelog parser) (Also check [keep a changelog](https://keepachangelog.com/en/1.0.0/))
- it should consistently update the changelog and eliminate the need for manual updating.
- it should display the formatted entry for confirmation before updating the changelog

## Development notes (optional Task Breakdown)
TBD
- [ ] 
- [ ] 
- [ ]

**Comment by ChristianHuehn** [comment]
So far i didnt hear any problems with this. Will ask in team how much they need this 👍
