### ISSUE TITLE
Tech: Activate Strict Type Checkings

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2728]
Tech: Activate strict type checkings according to https://www.typescriptlang.org/tsconfig#strict in `tsconfig.json` to prevent unexpected errors.

**Comment by shaman-apprentice** [comment]
duplicate of https://github.com/MaibornWolff/codecharta/issues/2460?

**Comment by ce-bo** [comment]
Duplicate to #2460
