### ISSUE TITLE
Remove all 'FileSelectionState Single' entries

### ISSUE THREAD

**Issue by Hall-Ma** [MaibornWolff/codecharta#2735]
## Description
- When the 'multiple' mode was introduced as a standard file selection, not all side effects of the previous 'single' mode were removed.

## Development notes (optional Task Breakdown)
- [x] Find and delete all `FileSelectionState: Single` entries
- ~~[ ] Fix #2656~~
- [x] Clarify what should happen if only one map is selected -> Should the file also be aggregated like in the other modes? **Answer:** Access decorated map data, no distinction between standard/multiple mode.

**Comment by ce-bo** [comment]
- Check SingleState references
- Access decorated map data, no distinction between standard/multiple mode.

**Comment by IhsenBouallegue** [comment]
Should we also fix #2656 as part of the new milestone? https://github.com/MaibornWolff/codecharta/milestone/19

**Comment by BridgeAR** [comment]
@shaman-apprentice is https://github.com/MaibornWolff/codecharta/issues/2656 directly related in a way? It being broken seems orthogonal to the FileSelectionState (besides maybe including some information about it in there)? I would separate the two issues, if possible.

**Comment by ce-bo** [comment]
The Tracking collects map specific data and dumps it to a tracking file. If I remember correctly, this does not work currently with the multiple mode changes. One option would be to fix this, so that the tracking is working with aggregated data. Another one would be to delete the tracking module since we just do not need it.

**Comment by BridgeAR** [comment]
There is another story for gaining further analytical data. We'll have to look into this again when we address that issue. Until then, I'd just keep it broken as changing it takes time.

**Comment by ce-bo** [comment]
I think this is related to #2574.
