### ISSUE TITLE
Font blurry before clicking on export screenshot

### ISSUE THREAD

**Issue by Christian-Eberhard** [MaibornWolff/codecharta#2741]
# Bug

## Expected Behavior

When i load a map in CodeCharta the font should always be readable

## Actual Behavior

The font is blurry until i click on the export screenshot button

## Screenshots
Before:
![Before](https://user-images.githubusercontent.com/42114276/159266936-2cc086f9-edd4-480a-a95a-b851754d897b.JPG)
After:
![After](https://user-images.githubusercontent.com/42114276/159266963-8b8c726e-221f-44f5-b6ab-1da282eaa6d2.JPG)

## Steps to Reproduce the Problem
1. Open CodeCharta
2. Click on the export screenshot button

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.93.0
- OS: Windows 10
- Browser: Firefox & Chrome

**Comment by BridgeAR** [comment]
@Christian-Eberhard please check your quality in the global settings. I can imagine that the image sets this to high or best and before that it's on low.

While I understand that this is not ideal, I do not think we should invest the time into it currently as there are other things that are more substantial. I am therefore going to close this as a "let's postpone this".
