### ISSUE TITLE
Reload map in delta mode only when both maps are selected

### ISSUE THREAD

**Issue by Christian-Eberhard** [MaibornWolff/codecharta#2743]
# Feature request

## Description

As a user i want to only reload the map when necessary to reduce my GPU/CPU usage.
The map in delta mode should only reload when both reference and comparrison are selected.

## Acceptance criteria
- Map only reloads when comparrison and reference map are selected in delta mode
- Map does not reload when only one of the two is selected

**Comment by BridgeAR** [comment]
Duplicate of #2707
