### ISSUE TITLE
SCMLogParserV2/GitLogParser - Bug during Git parsing

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2749]
# Bug

An exception occurs during parsing:
![image](https://user-images.githubusercontent.com/26900540/183442940-b5bb8cbc-cc63-44cf-a809-6367b6d85cb4.png)

Please contact me to get access to the used  git logs.

**Comment by MW-Friedrich** [comment]
@ce-bo The error was in the anongit script, not in the parser itself. In your specific case the gitlog would need to be regenerated unfortunately (in case this is still relevant)
