### ISSUE TITLE
SonarQube Plugin

### ISSUE THREAD

**Issue by MarcoHei** [MaibornWolff/codecharta#2780]
# Feature request

As a developer using CodeCharta, I want a SonarQube Plugin that allows me to generate the .cc file automatically during project analysis.

## Acceptance criteria
- I receive the .cc file after the analysis finished successfully

**Comment by BridgeAR** [comment]
@MarcoHei thank you for the suggestion. To fully grasp the required functionality: you mainly require a way to run an application that returns a .cc file automatically, right? It is probably independend from SonarQube?
We currently mainly work on being completely independent from third-party software and adding a plugin is diametral in this case.

**Comment by MarcoHei** [comment]
@BridgeAR  Sorry for my late response.

> you mainly require a way to run an application that returns a .cc file automatically, right?

Yes. 

>  It is probably independend from SonarQube?

Not really. I can see, why you want to keep CodeCharta independent, but i would be very convenient to trigger Codecharta inside SonarQube. For what I heart, CodeCharta works best with SonarQube anyway and adding an easy way to use both together in one application (that is SonarQube) would be a nice feature.

Currently we have to automate this with a Bash Script which, I admit , is not that compilcated to do.

**Comment by BridgeAR** [comment]
I see. Due to priorizing not relying on SonarQube for good metrics in the future, I'd not implement this in CC for now. If you do want to have such a plugin, it's always possible to work on that as a R&D project. I hope that helps.
