### ISSUE TITLE
Can I fix the file/node explore menu?

### ISSUE THREAD

**Issue by sparkyqin** [MaibornWolff/codecharta#2788]
# Feature request

## Description

when I check code city, I want fix the file/node explore menu, so that I switch file or module while exploring code city.
![image](https://user-images.githubusercontent.com/10319552/165057404-14601b28-a630-454f-85ca-6b1606411b33.png)

## Acceptance criteria
- I can use a pin in the menu to fix it or not
- when fixed, the explore menu still display while clicking the code city
- when not fixed, the explore menu collapse while clicking the code city

**Comment by BridgeAR** [comment]
This is accepted. I suggest suggest to add the checkbox between the numbers and the sorting options.

@sparkyqin do you mind working on this? :)

**Comment by sparkyqin** [comment]
> This is accepted. I suggest suggest to add the checkbox between the numbers and the sorting options.
> 
> @sparkyqin do you mind working on this? :)

No, not mind, thank your acceptance. :)
