### ISSUE TITLE
Analytics for CodeCharta

### ISSUE THREAD

**Issue by Ann-CathrinKlose** [MaibornWolff/codecharta#2794]
# Feature request

I discussed the idea of analytics tooling for this project with Richard Gross yesterday. There seems to be a need for understanding better how users are interacting with CodeCharta, however, there are also data protection issues to be kept in mind. I suggested looking into whether Matomo might be a good choice for this, because it is generally more GDPR compliant than Google Analytics. I can also point you to some MW colleagues who are already working on Matomo and have an internal instance up and running if you like. 

## Open questions
- I don't know if it is possible to use Matomo analytics on GitHub Pages, we need to check that 
- What gdpr requirements are relevant to adding a analytics tool to a project like this?
- ...

**Comment by ChristianHuehn** [comment]
We wont focus on this for a long time. We reopen or create a new issue later if this is ever planed.
