### ISSUE TITLE
Improving CLI output name handling by adding file extensions if necessary

### ISSUE THREAD

**Issue by phanlezz** [MaibornWolff/codecharta#2800]
If given an output file name like `-o fileName` the output file name should be `fileName.json` compressed in `fileName.json.gz`. 
If `fileName.gz` is given, the file name should be `fileName` compressed into `fileName.gz`.

=> If the user gives a file extension, it should be used if it fits (`.json`, `.json.gz`, or `.gz`). If no extension is given it will be added.

**Comment by MW-Friedrich** [comment]
Just as a heads up, json files generated by CodeCharta should still end as .cc.json, not .json

**Comment by ce-bo** [comment]
Moving issues from in progress back to backlog is mostly not ideal. They are likely to be forgotten but we already started work on in.
