### ISSUE TITLE
Metric number for occurence of certain keywords in comments

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#281]
# Feature request

## Description

There is the saying that wtf's per minute is the most precise code metric. Sometimes they can even be found in the code. It would be great to have a parser for the occurence of comments including a configurable set of keywords (e.g. "todo", "hack", "wtf", "bug",...).

**Comment by ce-bo** [comment]
Yes, it's simple to add it to the generic parser. Let's put it back into Backlog.

**Comment by BridgeAR** [comment]
@ce-bo I would like to prioritize this as soon as the metric-gardener is ready for it.

**Comment by ChristianHuehn** [comment]
Went into MetricGardener.
