### ISSUE TITLE
More space in toolbar for hovered file path

### ISSUE THREAD

**Issue by shaman-apprentice** [MaibornWolff/codecharta#2818]
# Feature request

## Description
As a user, I want important information not to be overlapped by not important information, so that I can see all important information  as quickly as possible.

To have more place for the hovered file path, we should move the toggle for the presentation mode into the global configuration. In addition we can remove the text "Global Configuration", as the icon should be self explaining and has also an explaining title on hover.

![image](https://user-images.githubusercontent.com/3596742/169886137-a7d2e81f-63d3-487b-bd60-d4d7bd5ac724.png)

## Acceptance criteria
- Presentation mode toggle is removed from toolbar
- Presentation mode toggle is added to global configuration
- Text "Global Configuration" is removed from toolbar

## Development notes (optional Task Breakdown)
- [ ] As the global configuration dialog is already migrated we need to add a `IsPresentationModeServiceSelector`
- [ ] We can remove `IsPresentationModeService` afterwards as it will become unused
- [ ] Mark `presentationModeButton.component.ts` and `isPresentationMode.service.ts` as migrated in #2318

**Comment by BridgeAR** [comment]
So far the presentation mode button is meant for live audit situations and a quick access is important in that case.
I do not know if the feature itself is frequently used so far but I would not want to hide it without further data. We could change "Global Configuration" to "Configuration". There are likely possibilities in providing a better placement for multiple options and as soon as that's the case, I would be fine to remove the description. Before that, it's a way to make them more prominent to look at.

Something that we could do is to cut off the start of the entries with dots if it does not fit into the line. For now, it's not really important as it's only one of three ways to see the actual path.

**Comment by shaman-apprentice** [comment]
I think the buttons with the icons are enough to be recognized as something to click on and configure something with it. So I would leave both buttons with icons there but remove the text. When hovering you get a description, which should be enough for new users.

But on second thought I agree, that the information is not important. I would be fine with closing this as won't fix as well.

**Comment by BridgeAR** [comment]
Closing as won't fix for now.
