### ISSUE TITLE
--not-compressed flag acts as compressed in CLIs

### ISSUE THREAD

**Issue by IhsenBouallegue** [MaibornWolff/codecharta#2829]
# Bug

## Expected Behavior

WHEN
executing a parser with flag --not-compressed=true 
THEN
the output file won't be compressed
## Actual Behavior
the output file gets compressed

## Steps to Reproduce the Problem
1. `ccsh edgefilter codecharta.cc.json output.cc.json --not-compressed=true`
(this is true for other parsers too)

## Solution
It is clear that the variable or flag was inverted at some point and the other was not. Current we have
```
@CommandLine.Option(names = ["-nc", "--not-compressed"], description = ["save uncompressed output File"])
private var compress = true
```
Wanted default behavior is to compress the output per default. So the variable compress should be changed to not_compressed and everything updated accordingly

**Comment by BridgeAR** [comment]
After @luelista looking into it further, I remembered the reason for the flag being renamed (it was only tested without arguments). Now that the arity is set to zero, I am fine to keep it as is.
