### ISSUE TITLE
Update GitHub Pages for Users & READMEs for Developers (CodeCharta Documentation)

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2834]
Update GitHub Pages ([CodeCharta Documentation](https://maibornwolff.github.io/codecharta/))
Update README's (Github)

### Split the general documentation for CodeCharta into two parts for `Developers` & `Users`

> Some parts need to be modified [ New: 🚀 Changing: 🔨 Keep: ✔️ Discuss: ❓ ] 

- GitHub Pages
- - 🔨 User focused documentation
- - ✔️ How-to's and specific use cases
- - 🔨 User installation guide
- - ✔️ Release Posts
- - ❓ ADR
- - ✔️ Versioning / Price / Feedback
- - 🚀 Auto copy of technical README's (if possible) or links to README's
- READMEs (Github)
- - ✔️Technical documentation (CLI usage, flags)
- - 🚀 Developer setup guide 
- - 🔨 Introductory README's

The entry point in both sections should have a strong link/reference for users/developers to switch to the (more) appropriate documentation

**Comment by phanlezz** [comment]
I will move this to 'further inquiry' until @Nereboss is back. I'm not sure if there is anything that needs to be added.

**Comment by Nereboss** [comment]
This is ready for review, nothing more needs to be added in this ticket
