### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by jannikr** [MaibornWolff/codecharta#2844]
# Feature request

Enable / disable dark mode for better visibility in dark environments.

## Description

As a user, I want dark mode so that I habe better visibility in dark environments. The map background and the control panels have a darker colour tone.

## Acceptance criteria
- Enable / disable dark mode automatically based on display mode / time.
- Manuel switch for dark mode

**Comment by BridgeAR** [comment]
I don't think we should implement this anytime soon. The map is used for slides during daytime. If we have the requirement to change the theme, it's possible to do so with plugins in the browser or by changing a screenshot.

**Comment by felixakiragreen** [comment]
Soon has passed. Perhaps it's time now that it can be prioritized?
