### ISSUE TITLE
Tech: Swap from Dependabot to Renovate for Security Patches

### ISSUE THREAD

**Issue by phanlezz** [MaibornWolff/codecharta#2911]
# Security Patches: Dependabot -> Renovate

For updating dependencies we use Mend:Renovate. But security patches based on dependabot alerts are still generated by dependabot. It is possible to also swap this behavior to Renovate too. 

[RenovateDoc-vulnerabilityalerts](https://docs.renovatebot.com/configuration-options/#vulnerabilityalerts)

## Assumptions & Exclusions

If renovate is unreliable for this generation, this issue can be dismissed.

**Comment by BridgeAR** [comment]
I don't we should invest time into this as it works as it is, right?

**Comment by ce-bo** [comment]
I agree @BridgeAR, although I prefer to have only one tool for this. But it is working at the moment, so it has a very low priority.
