### ISSUE TITLE
Upgrade github-pages gem to latest version to avoid problematic dependencies

### ISSUE THREAD

**Issue by phanlezz** [MaibornWolff/codecharta#2912]
## Upgrade github-pages gem to latest version to avoid problematic dependencies

To avoid future [security alerts](https://github.com/MaibornWolff/codecharta/security/dependabot/24) for old dependencies from gh-pages, it should be updated to the latest version.

Current Version: 219

**Comment by BridgeAR** [comment]
Please do not open issues for these things. Thanks.
