### ISSUE TITLE
Improve UI of add custom scenario dialog

### ISSUE THREAD

**Issue by shaman-apprentice** [MaibornWolff/codecharta#2926]
# Feature request

## Description

As a user I want to know, why I cannot add a custom scenario.

As a user I want all options, which I cannot influence, not to be present, for having a lean ui, which enabled me to do my work faster.

## Acceptance criteria
- Error message is shown, when scenario name is empty
- Error message is shown, when no property is selected
- Edge-Metric is not shown, when there are no edge metrics

## Screenshot
![image](https://user-images.githubusercontent.com/3596742/182380923-c5940834-4dc8-4050-9f50-fade124e566a.png)

**Comment by BridgeAR** [comment]
We already deactivate out the `Add` button in case something is wrong. Yes, indicating the name is not there is a nice to have but I would not want time to be invested into implementing this as it does not seem really necessary. An error on not selecting a metric does not seem to be required either, as it does not make sense to do that. I don't think users are actually going to have an issue with that (it does work with the deactivated button).

The edge metric should still be possible to activate, no matter if it's applicable to the current map. Scenarios are meant as a "general" thing and may apply to _any_ map. We could rework that a scenario with edge metrics also applies to maps that do not have any (as it does not hurt to apply it).

**Comment by shaman-apprentice** [comment]
I will create another FR for a more generic selection as discussed
