### ISSUE TITLE
color settings are not set back to standard mode

### ISSUE THREAD

**Issue by shaman-apprentice** [MaibornWolff/codecharta#2936]
# Bug

## Expected Behavior
Given the map is open in Standard mode
Then color metric is choseable and color metric options are editable

## Actual Behavior
Color settings for delta mode are still displayed

## Screenshots
![image](https://user-images.githubusercontent.com/3596742/182786121-243a6810-c541-418e-bb02-914beef5e7bd.png)

## Steps to Reproduce the Problem
1. Switch to delta mode
2. Switch back to standard mode

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.101.1

**Comment by BridgeAR** [comment]
This was AFAIK an intentional change as the options available were not applicable to the delta mode. We could in theory let the users change `green`, `red` and `nothing changed` but I wonder if we need this?
