### ISSUE TITLE
Show tooltip with explanation for every metric

### ISSUE THREAD

**Issue by MariusMaibornWolff** [MaibornWolff/codecharta#2944]
# Feature request

## Description

As a user, I want to have tooltips for every area, height and color metric so that I can understand what the metric represents and understand more about the product in the first glance.

## Acceptance criteria
- Tooltip with explanation of the metric is shown for every metric in Area Metric Options
- Tooltip with explanation of the metric is shown for every metric in Height Metric Options
- Tooltip with explanation of the metric is shown for every metric in Color Metric Options

## Development notes (optional Task Breakdown)
- [ ] 
- [ ] 
- [ ]

**Comment by jannikr** [comment]
As a next step, we want to provide users with links to the individual metrics that contain more detailed information: [2958](https://github.com/MaibornWolff/codecharta/issues/2958)
