### ISSUE TITLE
Create educational YouTube series

### ISSUE THREAD

**Issue by shaman-apprentice** [MaibornWolff/codecharta#2947]
# Feature request

## Description
As a Developer I want to know about issues within my source code, so I can improve the source code. 

Finding the right metrics and right spots to look at, for revealing issues is not trivial. A source of education regarding metrics and regarding best practices how to analyse with CodeCharta, would be appreciated a lot. 

A YouTube series with 3-10 minutes video each about example usages and finding would inspire me and get me a better idea about best practices. In addition it would be a good promoting channel for CodeCharta and MaibornWolff.

## Open questions
Marketing will probably love to support us :)

**Comment by ChristianHuehn** [comment]
Not planed atm. Nevertheless it's a good idea 👍
