### ISSUE TITLE
Rewrite Documentation for using SonarQube

### ISSUE THREAD

**Issue by Hall-Ma** [MaibornWolff/codecharta#2949]
# Feature request

## Description

As a user, I want to know which tech stack I need to start CodeCharta analysis and visualization so that I can start immediately.
Additionally, I don't want to find more than 2 different instructions to do the same thing (e. g. start to analyse with SonarQube (https://maibornwolff.github.io/codecharta/docs/step-by-step/, https://maibornwolff.github.io/codecharta/how-to/analyze_projects_with_local_sonarqube/)

## Acceptance criteria
- Only one page that addresses the same issue
- more explicit command examples (for e.g. for sonarimport)

**Comment by ce-bo** [comment]
Let's concentrate only on the rewrite of the docu for SonarQube usage and create follow up issues to cover the other tasks.
