### ISSUE TITLE
Show links with explanation for every metric

### ISSUE THREAD

**Issue by jannikr** [MaibornWolff/codecharta#2958]
# Feature request

Add links for each metric in the legend panel.

## Description

As a  user, I want to read articles with descriptions about the selected metric in the legend so that the purpose of each metric is easier to understand.

## Development notes (optional Task Breakdown)
- [ ] Refactor metricDescriptions.ts and change Map to Class in order to access descriptions and links more intuitive
- [ ] Search for metric descriptions on wikipedia, sonar, ...
- [ ] Add data to the new metricDescriptions class
- [ ] Update legendPanel to show links

**Comment by ce-bo** [comment]
Ideally every parser/importer is providing it's own descriptions and also appropriate "read-more" links within the `cc.json` structure for every metric.
This way, the frontend can simply use and display this data.

**Comment by ce-bo** [comment]
I found a very similar issue. So I am going to close this as the ideal way is already described there #1066.
