### ISSUE TITLE
Make GitLog Test File Smaller

### ISSUE THREAD

**Issue by MW-Friedrich** [MaibornWolff/codecharta#2972]
# Feature request

## Description

As a developer, I want the "root/analysis/import/GitLogParser/src/test/resources/codeCharta.log" to be smaller (than it's current ~21MB) so that tests using that file will complete faster.

## Acceptance criteria
- The File under analysis/import/GitLogParser/src/test/resources/codeCharta.log is as small as possible

## Development notes (optional Task Breakdown)
- [ ] 
- [ ] 
- [ ]

**Comment by ce-bo** [comment]
Please address such issues immediately instead of opening an issue for that. Thank you!
However, I think having an Integration Test for the GitLogParser like this is a good idea.
