### ISSUE TITLE
Update package list before install wine

### ISSUE THREAD

**Issue by jannikr** [MaibornWolff/codecharta#2975]
# Bug

## Expected Behavior

GIVEN

GitHub Release pipeline uses release_gh_pages.yml to build project

WHEN

it should run `sudo apt-get install -y wine-stable`

THEN

packages getting installed.

## Actual Behavior

the package list might by outdated and throws error:

`E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/gstreamer1.0-x_1.16.3-0ubuntu1_amd64.deb  404  Not Found [IP: 40.81.13.82 80]`

## Screenshots

<img width="1029" alt="Screenshot 2022-08-10 at 16 31 00" src="https://user-images.githubusercontent.com/31436472/183927923-e0ba0fcc-f2cb-4fc8-aacf-e81f93d4bb4b.png">

**Comment by ce-bo** [comment]
Closed by #2976
