### ISSUE TITLE
loading indicator isn't working

### ISSUE THREAD

**Issue by shaman-apprentice** [MaibornWolff/codecharta#2977]
# Bug

## Expected Behavior
Given a huge map
When I load it
Then a loading indicator is displayed on the map while it is loading

## Actual Behavior
The page becomes unresponsive until the map is loading

## Steps to Reproduce the Problem
1. Load a huge map, which needs several seconds to load
2. Wait until it gets loaded and see that there was no loading indicator

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes 
- CodeCharta Version: 1.103.1

## Developer notes
Without checking I assume that:
- Parsing of file is probably done on main thread, which would block animation of loading give anyway.
- Rendering is probably done on main thread, which would block animation of loading give anyway.

## TODOs
- [ ] Check if we still need `isLoadingMap` and `isLoadingFile` within store/appSettings

**Comment by ce-bo** [comment]
This issue is included in our current milestone. Please do a first analysis of the bug and see how much effort it is to fix it. If a lot of effort is needed, I would like to exclude it from the milestone, as it is not a critical bug.

**Comment by shaman-apprentice** [comment]
With a very quick look, I don't know at which point in time it broke. I am currently [migrating / reworking the render process](https://github.com/MaibornWolff/codecharta/pull/2980). I recommend to postpone this ticket until then and volunteer to take over it afterwards.
