### ISSUE TITLE
Upload Release Files

### ISSUE THREAD

**Issue by jannikr** [MaibornWolff/codecharta#2978]
# Bug

## Expected Behavior

GIVEN

Release pipeline script `release_gh_pages.yml

WHEN

Releasing

THEN

Release assets are being uploaded

## Actual Behavior

Socket hang up

## Screenshots
<img width="1252" alt="Screenshot 2022-08-11 at 09 56 44" src="https://user-images.githubusercontent.com/31436472/184088976-478dbb92-c6f6-4d41-81b6-4894baa2c931.png">

Possible solution: https://github.com/alexellis/upload-assets/issues/5

**Comment by phanlezz** [comment]
Closed, reopen if there are still problems after the next release.

**Comment by phanlezz** [comment]
Permissions unknown in github action
