### ISSUE TITLE
Create blacklist entry for Treeview search term

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#298]
# Feature Request
depends on #225

## Description
I some cases, after seeing the result of a search term I want to blacklist these items. 

This makes sense when I search for all `designer.cs` files. First I want to see if my query matches any files and then I want to exclude them. 

This feature would link blacklist and treeview. Maybe we should combine both things into one view then as well.

**Comment by alschmut** [comment]
@Richargh I don't think that one Panel should contain both the ThreeView with its search-field and the blacklist. Imagine a long list of blacklisted entries and huge opened treeview. What do you think about the following UI option? The "blacklist"-button opens the small menu and when selecting a blacklistType a blacklist-entry will created instantly.

What else we could:
- Remove the adding field inside the balcklisftpanel
- put the blacklistPanel beneath the TreeviewSearchPanel to show the user it is kinda connected
- I am not 100% sure, if the `fa-list`-icon is the correct one for a blacklist association, but to be honest its pretty difficult to find on

**Comment by Richargh** [comment]
I like how it works and I agree that we should probably not remove the blacklist panel for the reason you mentioned. But can we link this search field and the blacklist even more? 

* Can we add a label "blacklist" to the small menu at the bottom or top? 
* Or can we add a counter, like iPhone apps, to the blacklist icon in the panel that shows how many items are blacklisted? Then that counter would increase if we add sth to the blacklist? 
* Or maybe when we add something to the backlist the text fades away towards the blacklist? Currently it just kind of stays there and I think the search field should be cleared after adding it to the blacklist.
* definitely put the panel beneath the treeviewsearchpanel.
* let's use the ban for the blacklist icon. Maybe even use it instead of the x for excluded items?
* let's use the three dots for the treeview search.
* also how about, when the blacklist is empty, we tell the user to "Exclude or hide items with the treeview search"?

**Comment by alschmut** [comment]
When a node was excluded (so not anymore shown in the codeMap and not shown in the TreeView. Is it still supposed to be found (see "Found: 1 file" in the screenshot)? Should we just skip excluded nodes or do you have any ideas how to show that the searchPattern found excluded nodes?
<img width="50%" src="https://user-images.githubusercontent.com/23529226/51441566-e0ae4680-1cca-11e9-96f7-7d2b122121f8.jpeg">

**Comment by Richargh** [comment]
Can we add two more symbols next to "Found"? One for excluded and one for hidden files?

Also let's remove the folder icon. I don't find that usefull because only the buildings are interesting to us.
