### ISSUE TITLE
Flickering surfaces

### ISSUE THREAD

**Issue by Ookami86** [MaibornWolff/codecharta#3]
Hey,

looks like there are issues with occlusion, when values are very low. When you rotate the treemap in space the surfaces of some of low valued blocks start flickering.

![unbenannt](https://cloud.githubusercontent.com/assets/859551/24603738/4fab5330-1862-11e7-8d92-db7b06cfcfbc.PNG)

This kind of "flickering" usually happens when two polygons share points in space or are very very close to each other and the occlusion culling algorithm cannot determine which surface is in front of the other (see https://en.wikipedia.org/wiki/Hidden_surface_determination)

Regards
Johannes

**Comment by mrpatpat** [comment]
Hey Johannes,

thank you for your contribution. Two possible approaches to this problem are mentioned in [this Stackoverflow thread](http://stackoverflow.com/questions/29020613/three-js-issue-to-render-objects-using-canvasrenderer). They could fix this bug without alternating the existing visualization logic. 
Drawing buildings with a height value of 0 is necessary to ensure that its color and area informations are not lost. Therefore we assume that those buildings have a height of 1px. Based on this assumption a third way to fix this bug would be to increase the minimum height of a building. This approach would lead to an inaccurate visualization.
I will try those solutions and implement the most fitting one. Additional suggestions are always welcome.

Regards
Adrian

**Comment by mrpatpat** [comment]
WebGLRenderer was already in use and tessellation only minimized the issue. After researching the issue in greater detail, changing the near plane of the viewing frustum solved the problem. 

[Stackoverflow](http://stackoverflow.com/questions/17786723/flickering-planes)
[Wikipedia](https://en.wikipedia.org/wiki/Viewing_frustum)
