### ISSUE TITLE
Sonarcloud badge 

### ISSUE THREAD

**Issue by jannikr** [MaibornWolff/codecharta#3006]
# Bug

There are two quality gate badges in README.md for analysis and visualization. The alt description does not work to make clear the differences between both badges.

## Screenshots

<img width="501" alt="Screenshot 2022-08-31 at 08 51 28" src="https://user-images.githubusercontent.com/31436472/187612591-5c8ffb4e-c2f0-4a8d-9c3e-38b7713a74cf.png">

## Steps to Reproduce the Problem
1. Open README.md in root directory

**Comment by MW-Friedrich** [comment]
While we're at the the SonarQube-Links under "Further Information" link to outdated projects.
They should link to https://sonarcloud.io/project/overview?id=maibornwolff-gmbh_codecharta_visualization and https://sonarcloud.io/project/overview?id=maibornwolff-gmbh_codecharta_analysis respectively.

**Comment by MW-Friedrich** [comment]
This has been adressed with #3076 as we had to touch the readme there anyways. :)
