### ISSUE TITLE
Can't load CC.JSON files on Safari

### ISSUE THREAD

**Issue by RomanenkoVladimir** [MaibornWolff/codecharta#3017]
# Bug

## Expected Behavior

GIVEN
A valid cc.json file

WHEN
the user attempts to load the cc.json file on Safari

THEN
the file is loaded and visualized or an explanatory error message why it can't be loaded is displayed.

## Actual Behavior
The file is not loaded, no error message is displayed to the user.

## Steps to Reproduce the Problem
1. Open the visualization in Safari
2. Attempt to load a cc.json file
3. Nothing happens 

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes 
- CodeCharta Version: 1.104.1
- OS: Mac OS
- Browser: Safari

**Comment by ce-bo** [comment]
Does this apply to all cc.json files? Otherwise, could you please provide an example file?

**Comment by RomanenkoVladimir** [comment]
All .cc.json files are not loadable when using Safari on Mac OS
Other browsers are working fine
