### ISSUE TITLE
Remove redundant dependencies in analysis

### ISSUE THREAD

**Issue by MW-Friedrich** [MaibornWolff/codecharta#3036]
# Feature request

## Description

As a developer, I want fewer dependencies in my projects so that redundant functionality is removed and attack surface is minimized.
For example, we have a lot of dependencies/libraries for handling json files and content, maybe we can switch to one single library and use all of its functionality.

## Acceptance criteria
- 
- 
- 

## Assumptions & Exclusions
In our Weekly on the 13th of September 2022 we decided that this should be an ongoing task, rather than one "big" issue. 

## Development notes (optional Task Breakdown)
- [ ] Check if we need Wiremock and if yes, switch to the new https://github.com/wiremock/wiremock repository
- [x] Switch from Spek and JUnit4 to JUnit 5 #3202 
- [ ] Decide on one assertion plugin (  jsonassert and assertJ, ... ) are currently in use)
- [ ] Decide on one JSON plugin (JSON, GSON, Jackson and jsonassert are currently in use)
- [ ] Unify/Verify which mockking library we use (io.mockk // mockito-core // com.nhaarman.mockitokotlin etc.)
- [ ] Update ADR to write down these decisions for future reference

**Comment by ChristianHuehn** [comment]
I will pull this out and look for a better place to store it, so that we will keep in in mind when developing CC further.
