### ISSUE TITLE
Removing a cc.json is not going to rerender the map

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#3038]
# Bug

## Expected Behavior

<GIVEN>

WHEN
removing codecharta.cc.json in Standard mode (in demo)

THEN
the map should be rerendered with the remaining cc.json files.

## Actual Behavior
the map still displays codecharta and codecharta_analysis.cc.json.

## Screenshots
![image](https://user-images.githubusercontent.com/26900540/189823535-7dcea5fc-62af-49a5-aa20-69e529abcfe9.png)

## Steps to Reproduce the Problem
1. Open Demo
1. Remove codecharta.cc.json file

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes
- CodeCharta Version: 1.105.0
- OS: all
- Browser: all

**Comment by shaman-apprentice** [comment]
@ce-bo I think this is already fixed.

**Comment by ce-bo** [comment]
Thank you @shaman-apprentice. It seems to be fixed.
