### ISSUE TITLE
Deselecting a file with more than one focussed node breaks the app

### ISSUE THREAD

**Issue by shaman-apprentice** [MaibornWolff/codecharta#3069]
# Bug

## Expected Behavior
Given a map with multiple focussed nodes
When deselecting a file
Then the app doesn't crash

## Actual Behavior
The app chrases

## Open questions
What is the expected behavior? Should we
- always unfocus all nodes when deselecting a file
- or keep focus in case a map with no focussed nodes was deselected?

## Screenshots
![image](https://user-images.githubusercontent.com/3596742/193458433-35bef517-de80-4a78-9a24-d91b0fde63dc.png)

## Steps to Reproduce the Problem
1. Open demo app at https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json
2. Right click on chodecharta.cc.json/app folder and focus it
3. Right click on chodeCharta folder and focus it
4. Deselect codecharta map in file chooser

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes
- CodeCharta Version: 1.108.1

**Comment by shaman-apprentice** [comment]
When loading a new file, all nodes are unfocussed within `UnfocusNodesOnLoadingMapEffect`. Therefore I think we should also unfocus all nodes when deselecting a file.

**Comment by ce-bo** [comment]
This case should not be normal. Let's just unfocus in case the user deselects a map.
