### ISSUE TITLE
Screenshot Improvements #2

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#3080]
# Feature request

## Description

As a user, I want to export a screenshot of my map which is not extended to the whole screen size, so that screenshots are as small as possible.

## Acceptance criteria
- [ ] There is an option to do a cropped screenshot of the whole map, so that the complete map fills the complete screenshot with a tiny edge (edge size of up to 3% on each side).
    - [ ] Current view angle and zoom is respected

**Comment by fritschldwg** [comment]
@ce-bo I remember us discussing this issue a while back. However I'm not certain anymore what came of that discussion. Is this feature still relevant, now that the legend panel is part of the screenshot? Should it be possible to do a cropped screenshot only when the legend panel is collapsed? If you could leave me a quick comment on what exactly we want to do

**Comment by fritschldwg** [comment]
@ce-bo I recall us discussing this issue previously, but I'm unsure of the outcome. With the legend panel now included in the screenshot, is this feature still necessary? Should we enable cropped screenshots only when the legend panel is collapsed? I'd appreciate a quick update on our plans for this feature.

**Comment by BridgeAR** [comment]
The feature sounds really useful for audits to improve the overall workflow. I would definitely like to get this in. The cropping should ideally happen no matter if the legend is included or not. If the legend is included, it would be considered the outer bounds.
