### ISSUE TITLE
Update user controls documentation

### ISSUE THREAD

**Issue by jannikr** [MaibornWolff/codecharta#3087]
# Update user controls documentation

## Description

Update the screenshot of the user controls and refer to the [Custom View Buttons](https://github.com/MaibornWolff/codecharta/pull/3085#discussion_r993228164).
## Development notes (optional Task Breakdown)
- [x] Update user controls documentation (Custom Views and Suspicious Metrics)
- [x] Add link to user controls in the Custom View article in order to show the user the Custom View Buttons

**Comment by ce-bo** [comment]
I changed the priority as this is needed to provide a proper Custom Views documentation (#2489).

**Comment by ce-bo** [comment]
Yes, you are right. That's fine.

**Comment by phanlezz** [comment]
Closed via #3117
