### ISSUE TITLE
Excluding all folders of a map leads to an endless loop in the browser

### ISSUE THREAD

**Issue by Hall-Ma** [MaibornWolff/codecharta#3108]
# Bug

## Expected Behavior

GIVEN: A map

WHEN I exclude all folders THEN I want to be able to include all folders again.

## Actual Behavior

WHEN I exclude all folders THEN I cannot include all folders again, because the browser gets stuck due to an endless loop.

## Screenshots

![image](https://user-images.githubusercontent.com/72517530/198556933-1669488f-aa3f-438f-a0fe-c9a5452df218.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes
- CodeCharta Version: 1.109.1
- OS: Windows
- Browser: Chrome

**Comment by shaman-apprentice** [comment]
I haven't guarded against that, as excluding all folder should not be possible. Is this still the case? In that case I would fix the logic, that it is possible to exclude all folders. @ce-bo?

**Comment by ChristianHuehn** [comment]
As this is no longer possible ![Image](https://github.com/user-attachments/assets/ea167645-5dbd-4513-99f3-e647402a94b1)

we close it for now
