### ISSUE TITLE
Add white color instead of green

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#311]
requires #318

Currently the UI is rather busy because of so many colors. As an experiment we want to replace the green color with white for the buildings.

Please also add a switch to revert back to the original green color in the color ribbon.

**Comment by alschmut** [comment]
What actually happened to #111 and the colorpicker, which @felixherbst started to implement (once upon a time)?

**Comment by Richargh** [comment]
No clue how far he got. 

The thing that is visually useful is to have a color slider that actually shows what part is red/yellow/white (or green). 
The thing that one user specifically wanted is to be able to select the default scenarios using a single-select box: Green/red/Green, Red/Yellow/Green etc. 

We can talk about all these possibilities in future iterations, especially if you have some idea. Let's see where this issue goes first.
