### ISSUE TITLE
Custom config collapsable dialogue is expanded for minimal time span

### ISSUE THREAD

**Issue by LuisGuenther** [MaibornWolff/codecharta#3142]
When opening the custom view menu by clicking the "Open your saved custom views" button, the collapsable menu for the individual custom view is expanded for a minimal time span, then it collapses.

<img width="1481" alt="Bildschirmfoto 2022-11-23 um 13 03 51" src="https://user-images.githubusercontent.com/93578491/203542387-d80c4883-95b9-41d5-b56f-cd4462012fb3.png">

**Comment by fritschldwg** [comment]
This problem no longer seems to exist in the current version (1.124.1).
