### ISSUE TITLE
Risk-Profile throws erros when programming language is undefined

### ISSUE THREAD

**Issue by MW-Friedrich** [MaibornWolff/codecharta#3143]
# Bug

This was discovered in #3077 but had a different origin.

## Expected Behavior

GIVEN a heavily anonimised cc.json file

WHEN the file does not contain a programming language

THEN the risk profile and suspicious metrics should show that no calculations could be made.

## Actual Behavior
GIVEN a heavily anonimised cc.json file

WHEN the file does not contain a programming language

THEN the programming language is left at undefined and the risk calculation fails with an error.

## Steps to Reproduce the Problem
1. Upload a .cc.json file where no programming language is specified or can be inferred

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes 
- CodeCharta Version: 1.111.0
- OS: Windows
- Browser: Firefox

**Comment by ce-bo** [comment]
I would add something:
If no programming language could be inferred, all files should be assessed based on default threshold values.

@MW-Friedrich is it possbile to include this requirement in the scope of this issue?

**Comment by MW-Friedrich** [comment]
> I would add something: If no programming language could be inferred, all files should be assessed based on default threshold values.
> 
> @MW-Friedrich is it possbile to include this requirement in the scope of this issue?

I would say something like this would be best to handle as a new feature request. At the moment both the Risk-Profile and Suspicious Metrics feature just "turn off" when no programming language is given, so adding this behaviour would be a bigger undertaking. Should I maybe open a new feature request for this?

**Comment by ce-bo** [comment]
I will keep track of it and I will open the issue, thank you.
