### ISSUE TITLE
Refactor how we zoom the map

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#3147]
Refactor how we zoom the map.
Currently we move the "Kegel" to zoom in and out but threejs can do that by its own (pass the zoom to threejs).

**Comment by IdrisLaabidi** [comment]
It appears that label scaling is malfunctioning; the label sizes are not adjusting based on zoom level. This issue is particularly problematic for larger code maps.

**Comment by IdrisLaabidi** [comment]
This issue will be addressed and closed by PR #3693 

The fix now relies on the MapControls module from Three.js to handle zoom functionality more effectively. Please review the PR for more details on the implementation.
