### ISSUE TITLE
Added Custom Views is non-applicable but should not

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#3151]
# Bug

## Expected Behavior

<GIVEN>

WHEN
adding a custom view

THEN
it should appear as an applicable view

## Actual Behavior
it is shown under the "non-applicable" views.

## Screenshots
![image](https://user-images.githubusercontent.com/26900540/203951441-4b51cb14-387e-4e2d-adcd-2bc6eec2ba0e.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes | no
- CodeCharta Version: 1.112.0
- OS: all
- Browser: all

**Comment by Hall-Ma** [comment]
@ce-bo Unfortunately I cannot reproduce it. Neither in the released version nor on the main branch are newly added custom configs displayed as unclickable. Please, can you double-check this?

**Comment by ce-bo** [comment]
It is working, sorry my mistake. It was a cache issue.
