### ISSUE TITLE
Loading a custom config is considered as changing map

### ISSUE THREAD

**Issue by LuisGuenther** [MaibornWolff/codecharta#3194]
# Bug

## Expected Behavior

Camera changes to custom view when custom view is loaded

## Actual Behavior

Camera perspective of custom view is being ignored because of the active settings flag "reset camera when changing map". 

## Steps to Reproduce the Problem
1. Load a map.
2. Change the camera perspective.
3. Save the custom configuration.
4. Restart codecharta.
5. Activate the "reset camera" flag in settings.
6. Load the map.
7. Load the custom configuration.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes
- CodeCharta Version: 1.113.0
- OS: Windows 11
- Browser: Firefox

**Comment by phanlezz** [comment]
Closed as completed through #3698
