### ISSUE TITLE
Migrate to Angular Material v15 MDC components

### ISSUE THREAD

**Issue by IhsenBouallegue** [MaibornWolff/codecharta#3225]
# Feature request

In the context of upgrading to Angular 15 #3116 we need to migrate away from materials legacy components.
But what should have been a straightforward migration is now a full on construction site. 

This is the result after upgrading. (UI completely broken)
![ui after upgrade)](https://user-images.githubusercontent.com/48621967/217210592-8a0be032-42ba-4255-9316-c092a08dabff.png)
Sadly, the update brings a lot of braking changes which affect almost every component. A lot of refactoring needs to be done.

[Material v15 MDC Migration](https://material.angular.io/guide/mdc-migration)

**Comment by shaman-apprentice** [comment]
I noticed another styling issue (now in main) (@IhsenBouallegue ?)

![image](https://user-images.githubusercontent.com/3596742/223539642-f95b8642-4086-4466-bc40-3c500332cf95.png)
vs now
![image](https://user-images.githubusercontent.com/3596742/223539710-00a6b649-dd4f-47ec-9fe7-7147340838af.png)

**Comment by IhsenBouallegue** [comment]
> I noticed another styling issue (now in main) (@IhsenBouallegue ?)
> 
> ![image](https://user-images.githubusercontent.com/3596742/223539642-f95b8642-4086-4466-bc40-3c500332cf95.png)
> vs now
> ![image](https://user-images.githubusercontent.com/3596742/223539710-00a6b649-dd4f-47ec-9fe7-7147340838af.png)
> 

Oh missed that one, will take a look if find the time this week.

**Comment by ce-bo** [comment]
@valenfx also had a look. After merging main into #3234 the custom view list could not be uncollapsed anymore.

**Comment by Hall-Ma** [comment]
What still needs to be done for this?

**Comment by ce-bo** [comment]
Will be closed by #3251.
