### ISSUE TITLE
Usage of analysis docker file

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#3259]
# Bug

## Expected Behavior

WHEN

I ran the analysis docker image via

docker run -v $(pwd):/src --workdir /src codecharta/codecharta-analysis:1.114.0 csvimport some.csv

THEN

It should run ccsh csvimport in the docker container

## Actual Behavior

It starts a docker container with entrypoint "tail -f /dev/null" and hangs

## Additional Info

* There is a workaround for this: fixing the entrypoint to use "ccsh" instead of the config of the docker image.
* Using docker run -v $(pwd):/src --workdir /src codecharta/codecharta-analysis:1.114.0 ccsh csvimport some.csv amounts to the same result.

## Steps to Reproduce the Problem
1. docker run -v $(pwd):/src --workdir /src codecharta/codecharta-analysis:1.114.0 csvimport some.csv

## Specifications
- CodeCharta Version:  1.114.0
- OS: Windows 11 WSL
- Browser: not relevant

**Comment by ce-bo** [comment]
@ukinimod The image provides more commands than just ccsh. Thus, the entrypoint should not prevent the usage of the other commands. I guess the way to go then is `docker run -v $(pwd):/src --workdir /src codecharta/codecharta-analysis:1.114.0 ccsh csvimport some.csv`.
