### ISSUE TITLE
Delta Mode not working anymore

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#3268]
# Bug

The delta mode does not show any deltas anymore

## Expected Behavior

<GIVEN>

WHEN
loading two maps in delta mode

THEN
there should be deltas even if the two cards do not share any code files

## Actual Behavior
no deltas are shown.

## Screenshots
![image](https://user-images.githubusercontent.com/26900540/231660489-6eb544ed-db54-4443-b6d3-39e86da0efb5.png)

## Steps to Reproduce the Problem
1. Open Web Demo
1. Switch to delta mode
1. select comparison file

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes
- CodeCharta Version: 1.115.1
- OS: Windows
- Browser: Chrome

**Comment by phanlezz** [comment]
Broken since `1.115.0`, works in `1.114.0` and lower.

**Comment by shaman-apprentice** [comment]
interesting. I suspect / guess some racing in the calculation / dispatching of events. 

In [this PR](https://github.com/MaibornWolff/codecharta/pull/3271) I replace redux through ngrx and I had to debug some racing issues. With this branch it works again, right? The PR is almost ready, "only" missing migration of most UI tests.
