### ISSUE TITLE
Improve developer documentation

### ISSUE THREAD

**Issue by moritz-suckow** [MaibornWolff/codecharta#3276]
# Feature request
## Description

As a developer, I want to have a centralised documentation with information for getting started so that I do not have to search through multiple files at multiple locations for all needed information.

## Acceptance criteria
- There is a getting started page in the documentation with all needed information for starting development in one place
- From there I can navigate to more specific getting started pages for the analysis and visualisation parts of the project

## Background
Right now the documentation for developing is scattered around multiple files in the repository and rather small. A more extensive and centralised developer documentation would help new developers get started faster in the project.

**Comment by ce-bo** [comment]
Let's address this soonish as long as the difficulties are still known.

**Comment by moritz-suckow** [comment]
closed via #3289
