### ISSUE TITLE
Automatically suggest useful parsers for the given codebase (2/2)

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#3279]
# Feature request

Follow up issue for #1884 

## Description

As a user, I want CodeCharta to let me know what parsers I might want to use so that I get most insights from all parsers relevant for the codebase.

## Acceptance criteria
- [x] After executing all parsers, the individual cc.json files are merged into one compressed result cc.json
  - [x] Duplicated metrics are removed (due to the usage of multiple parsers)
- When executing ccsh, the CLI suggests useful parsers for the codebase
  - [x] For Java codebases, the SourceCodeParser is suggested.
  - [x] For multi language codebases, MetricGardener is suggested as long as it supports the found languages.
    - [x] A hint is shown that this one is a experimental parser that may take a long time to parse the code.
  - [x] The SVN Log Parser is suggested, if the local path is a SVN controlled repository.
  - [x] The RawTextParser is suggested if there are code files present.
  - [x] The documentation section for Parser Suggestions is updated

## Future Outlook
1. Further suggestions to be defined....
1. This can be improved to also automatically trigger these by a default command

**Comment by moritz-suckow** [comment]
Why do we not always suggest all applicable parsers for the given project/file?
If someone is interested in using one of the parsers but unsure which ones make sense, I think we should give the user all information which parsers can generally be used and then let the user decide on what he wants to execute.
We already introduced the possibility to execute all suggested parsers at once, so we can give more suggestions to try out without executing a lot of commands manually.

I think if a parser can generally be used we should put it into the list of recommendations.

If that is too many parsers and might overwhelm the user, we could order them by specificness and usefulness for the given project, so more specialised parsers like the SourceCodeParser or MetricGardener are ranked above more generalised parsers like the RawTextParser.

**Comment by ce-bo** [comment]
Thanks for the feedback! Let's do it like you said. I will adjust the ACs.

**Comment by moritz-suckow** [comment]
closed via #3287
