### ISSUE TITLE
Detect invalid file input

### ISSUE THREAD

**Issue by moritz-suckow** [MaibornWolff/codecharta#3307]
# Feature request

## Description

As an Auditor, I want to be warned if the files I specified for input do not exist so that I can adjust the files names or correct paths.

## Acceptance criteria
- For each parser with files as input, if one or more input file do not exist, execution is stopped and an error message is output.
  - The same applies to invalid file paths
- Execution is also stopped if the user does not provide any file paths (if applicable)
- Execution is also stopped if the input file paths do not provide any files
- For each parser, with only files and no folders as input, execution is stopped and an error message is output if user specifies a folder as input.

## Development notes (optional Task Breakdown)
Since this is part of many parsers and to avoid duplication and inconsistent behaviour, we should solve this in one place for all parsers like the model.

**Comment by ukinimod** [comment]
I also encountered this for gitlogparser, e.g. with specifying "--repo-path" for a repo path that doesn't exist.

**Comment by phanlezz** [comment]
While it is important to stop the execution of any parser/filter/etc. when a users provides a **wrong** file/-path;
 we need to **continue** if a users does not provide any `0` input files, because the input could be piped in. This may only applicable to certain parsers.

**Comment by ce-bo** [comment]
@moritz-suckow I guess this can be closed.
