### ISSUE TITLE
gitlogparser doesn't work with docker file

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#3308]
# Bug

## Expected Behavior

GIVEN a git repository

WHEN

I run 

`docker run -it -v $(pwd):/src --workdir /src ccsh ccsh gitlogparser repo-scan --repo-path /src`

in this git repository

THEN

it doesn't run the git-log and filename-list  creation 
and puts out an almost empty cc.json

EXPECTED

it should run the git-log and filename-list creation
it should put out the same cc.json when running ccsh directly

WORKAROUND

the first problem about running the git commands can be solve by specifying the correct user for running the docker container:
`docker run -it -v $(pwd):/src --workdir /src --user 1000:1000 ccsh ccsh gitlogparser repo-scan --repo-path /src`
This should probably be specified correctly in the Dockerfile and not at execution time.

nevertheless specifying the above still results in an almost empty cc.json. 

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes | no
- CodeCharta Version: 1.116.0
- Env: Windows WSL2, Rancher Desktop

**Comment by phanlezz** [comment]
> nevertheless specifying the above still results in an almost empty cc.json.

I produced the `cc.json` via a NPM install and via the docker compose setup. Both files were equal.
Regarding the first part:
I need to do some more investigation why this command is required `--user 1000:1000`.
