### ISSUE TITLE
Add parser name before configuration start in multi parser usage

### ISSUE THREAD

**Issue by moritz-suckow** [MaibornWolff/codecharta#3320]
# Feature request

## Description

As an Auditor, I want to directly know which parser I am configuring while using the multi parser configuration setup so that this feature is more easily usable. Right now, you have to look at the order of parsers during selection to guess which parser you are currently configuring.

## Acceptance criteria
- Before the interactive configuration of a parser starts during parser suggestions, the name of the parser the user is about to configure is printed

**Comment by phanlezz** [comment]
Closed by #3335
