### ISSUE TITLE
CCSH - Parsing getting stuck when running configured parser suggestions

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#3337]
# Bug

## Expected Behavior

GIVEN
running `ccsh` command for codecharta visualization codebase

WHEN
selecting and configuring rawtextparser and metricgardenerimporter

THEN
both parsers are supposed to run successfully

## Actual Behavior
parsing gets stuck after rawtextparser has been executed successfully

## Screenshots
![image](https://github.com/MaibornWolff/codecharta/assets/26900540/a5d8b91c-bd31-4fb0-872e-25189deba573)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): -
- CodeCharta Version: 1.117.0
- OS: Windows
- Browser: -

**Comment by phanlezz** [comment]
Same as #3321 ?

**Comment by ce-bo** [comment]
Yes, thank you. Will be resolved by #3321. Closed.
