### ISSUE TITLE
Parser suggestions - Improvements

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#3338]
# Feature request

## Description

As a User of the Parser Suggestions (running ccsh command without arguments):
- [x] I want not to be asked to merge output files, if only one parser was executed
- [x] I want to see a description of the individual parser that was suggested to me in this dialog:
  - ![image](https://github.com/MaibornWolff/codecharta/assets/26900540/79cbf34a-81ec-48a2-9578-489d2f6337ab)
- [x] I want to see the full path of the file(s) that has/have been created at the end

## Developer Notes
- Open a separate PR for the individual points.

**Comment by phanlezz** [comment]
If I selected >no< before the execution, it would be nice if the command line equal call would be printed out, so that it can be copied for later.
(only if not too complicated)
