### ISSUE TITLE
CCSH Parser Suggestions Stuck if output on terminal

### ISSUE THREAD

**Issue by phanlezz** [MaibornWolff/codecharta#3340]
# Bug

When executing a single or multiple parsers via the suggestions the tool gets stuck before the last step (merge prompt) if one of the executed parsers printed on StdOut. 

## Screenshots

<img width="548" alt="image" src="https://github.com/MaibornWolff/codecharta/assets/65733509/9c0a2be6-2464-4f9d-a70c-0b23994de5ca">

## Steps to Reproduce the Problem
1. Start ccsh somewhere
1. Execute a parser (tested with sonar and gitlog) with no output file specified
1. Last step does not pop up

## Specifications
- CodeCharta Version: 1.118
- OS: Windows
- Shells: CMD (Screenshot), Bash in CMD

**Comment by phanlezz** [comment]
I think this still occurs outside of the parser suggestions, it's just not noticeable, because there is no more terminal output/control-elements when a parser is done.

**Comment by ce-bo** [comment]
Same as #3328 ?

**Comment by phanlezz** [comment]
Closed. Same as #3328
