### ISSUE TITLE
Deselected buildings with green/red roof in delta mode do not reset their color roof

### ISSUE THREAD

**Issue by knoffi** [MaibornWolff/codecharta#3348]
# Bug

## Expected Behavior

GIVEN I recently clicked on a buildings with a green or red roof in delta mode so that it gets an orange roof

WHEN clicking on another building

THEN the previously selected building regains the green/red roof it had before

## Actual Behavior

The previously selected building keeps its orange roof, I loose the information whether it was green or red before and it still looks like a selected building

## Screenshots

![image](https://github.com/MaibornWolff/codecharta/assets/46388280/d9fec78c-f78e-4ebe-9abb-630456f73c79)

## Steps to Reproduce the Problem
1. Upload two cc.json-files in delta mode
2. Click on a building with a green/red roof
3. Click on another building so that the first building gets deselected

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes
- CodeCharta Version: 1.119
- OS: Windows, Mac
- Browser: Microsoft Edge, Google Chrome

This bug does not appear on buildings with a black roof.

**Comment by ce-bo** [comment]
Thank you @knoffi for this bug report. I can confirm it.
Can you support and fix it, please?
