### ISSUE TITLE
Sonar not working with old Java versions

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#3357]
> warning The version of Java (11.0.14) you have used to run this analysis is deprecated and we will stop accepting it soon. Please update to at least Java 17.
Read more [here](https://docs.sonarcloud.io/appendices/scanner-environment/)

https://github.com/MaibornWolff/codecharta/pull/3353#issuecomment-1663900072

**Comment by phanlezz** [comment]
Closed via #3359 #3370
