### ISSUE TITLE
Document development prerequisites for analysis

### ISSUE THREAD

**Issue by moritz-suckow** [MaibornWolff/codecharta#3383]
# Feature request

## Description

As a developer I want to have instructions, exactly which tools I have to install before being able to develop in the analysis part. Currently the only things documented needed for developing are Node/NPM and Java, while to build the analysis you also need additional tools.

## Acceptance criteria
- For Mac and Windows there is a documentation page on the exact software/tools you need to install before being able to **build** the analysis.

**Comment by moritz-suckow** [comment]
For Windows:
- Install Java (I used Version 17)
- Install Node/NPM (I used Version 18)
- Install Metric-Gardener

To install Metric-Gardener you need to be able to use node-gyp as it seems (you do not need to install it manually, just need to fulfill the prerequisites). 
Prerequisites for node-gyp, summarized from here: https://github.com/nodejs/node-gyp#installation
- Python (I used Version 3.12.0)
- Some kind of C/C++ Compiler  toolchain and make => I downloaded the Visual Studio Build Tools 2022 with "Desktop development with C++" selected

If you are using Python version 3.11.6 or 3.12.0 or something even newer, you additionally need to install the python package 'setuptools'. The 'distutils' module was deprecated and the functionality moved to the 'setuptools' package in version 3.12.0. 'distutils' is used by node-gyp and if you do not install while using Python 3.12.0+ you will run into an error. See https://peps.python.org/pep-0632/

**Comment by ce-bo** [comment]
It is not acceptable that an install of analysis is not possible at the moment due to the mentioned dependencies.

**Comment by Nereboss** [comment]
Setup on Mac:

- Install Java (Version 20.0.2 was preinstalled on my machine but usually Java is not preinstalled on new Macs)
- Install node/npm (I used versions 18.18.2 / 9.8.1)
- No need to install python, it comes preinstalled on all Macs (Version 3.11.5 for me)

Otherwise executing `npm i` was sufficient for me. 
Note that there were no problems with installing metric-gardener, it is only installed locally inside npm.

**Comment by moritz-suckow** [comment]
> Setup on Mac:
> 
> * Install Java (Version 20.0.2 was preinstalled on my machine but usually Java is not preinstalled on new Macs)
> * Install node/npm (I used versions 18.18.2 / 9.8.1)
> * No need to install python, it comes preinstalled on all Macs (Version 3.11.5 for me)
> 
> Otherwise executing `npm i` was sufficient for me. Note that there were no problems with installing metric-gardener, it is only installed locally inside npm.

You probably also installed XCode-Command tools on Mac right? These also deliver the needed C/C++ Compiler Toolchain.

**Comment by phanlezz** [comment]
> It is not acceptable that an install of analysis is not possible at the moment due to the mentioned dependencies. In my opinion we must not ship metric-gardener as a dependency asap to solve the problems on install.

I told you that it is a requirement for ccsh usage, but I have to correct myself:
As far as I'm concerned we **do not require** metric-gardener in any way, if someone want to use the ccsh. Metric-gardener automatically gets installed when someone tries to execute the metricgardenerimporter, does not have a metric-gardener produced json and does not have a metric-gardener installation (globally or locally), as expected.
I'm not 100% sure how the `npm i` command plays into this, but I don't think we actually install metric-gardener via `npm i` for _usage_ or for _development_. 
The important part is the call here: 
https://github.com/MaibornWolff/codecharta/blob/6bab0bb152facc3f4d2ce48628aef8ce4fc6b23b/analysis/import/MetricGardenerImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/metricgardenerimporter/MetricGardenerImporter.kt?plain=1#L65
 via `-y` flag `npm exec` installs metric-gardener inside the npm-cache folder. 
 
 -> So at least we don't have a hidden requirement
