### ISSUE TITLE
Condense console output of MetricGardenerImporter

### ISSUE THREAD

**Issue by moritz-suckow** [MaibornWolff/codecharta#3386]
# Feature request

## Description

As a user, I do not want to have a lot of unnecessary console output which does not help me, when executing the MetricGardenerImporter.

Currently when creating a cc.json with the MetricGardenerImporter, after processing of the project is finished, I simultaneously receive one line of console output for each processed node. In case of Codecharta, I get 1200+ lines of console output at once after processing is completed. This is not helpful and should be condensed so that we do not clog a users terminal as much.

## Acceptance criteria
- MetricGardenerImporter no longer outputs one line for each node processed at the same time

## Open questions
Is the generated output meant to be printed during execution as some kind of progress indicator ? Then we should not print all output simultaneously at the end

**Comment by ce-bo** [comment]
Thank you @moritz-suckow . I think the output it is not ment as a progress indicator and was just not cleaned up yet. So let's do this improvement :-)
