### ISSUE TITLE
Progressbar breaks when it can't fit in one line

### ISSUE THREAD

**Issue by Nereboss** [MaibornWolff/codecharta#3416]
# Bug

## Expected Behavior

<GIVEN>

WHEN

Using a parser that implements the progresstracker

THEN

The progresstracker always correctly displays its progress in one self-updating line

## Actual Behavior

When the commandline is too small, so part of the tracker gets put into a new line or other printlns happen during execution, it doesn't update the one line but prints a new one 

## Screenshots
![image](https://github.com/MaibornWolff/codecharta/assets/105795397/c131226a-c89a-41e5-b439-40d5349e0442)

## Steps to Reproduce the Problem
1. Make the commandline where you execute the ccsh small
2. Execute a parser that implements the progresstracker (e.g. RawTextParser)

## Specifications
- CodeCharta Version: 1.120.1
- OS: Mac OS

**Comment by ChristianHuehn** [comment]
Good finding, but not relevant enough to be planed in the near or far future.
