### ISSUE TITLE
Prettify usage help

### ISSUE THREAD

**Issue by fritschldwg** [MaibornWolff/codecharta#3432]
# Feature request

## Description

- As a first-time-user, I want the usage help to be simple and easily understandable

## Acceptance criteria
- The help output is consistent with the actual usage (file or folder is specified first)
- The help output is consistent accross parsers
- The help output is cleanly formatted

## Development notes
- Docker help can serve as reference for a well structured help output

## Screeenshots
<img width="611" alt="ccsh vs docker help" src="https://github.com/MaibornWolff/codecharta/assets/149768491/ced7baec-08cc-4348-a6b1-55a1adc10245">

**Comment by ce-bo** [comment]
Let's have a short session to check the current issues here together please.

**Comment by ChristianHuehn** [comment]
We will only do this when we are done with the kotter migration. Which is still on hold. Until then I see no point in changing it as it would cost way more resources to change that, right now.
