### ISSUE TITLE
GitLogParser - NumberOfAuthors updated on merge commits?

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#3443]
# Bug

## Expected Behavior

WHEN using GitLogParser to calculate number_of_authors metric

THEN
the metric should be increased accordingly for files that have been modified by a merge commit 

## Actual Behavior
it could be the case that merge commits are not considered for this metric.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): -
- CodeCharta Version: 1.121.1
- OS: -
- Browser: -

**Comment by BridgeAR** [comment]
Merge commits are always tricky. You always have to do a compromise in this case.
The merge commit itself should however not count, just the commits that it references.

**Comment by BridgeAR** [comment]
Theoretically, the merging person could be counted but they might not have changed any code. That is the reason why I would not count them.

**Comment by ce-bo** [comment]
Thats true. However, there is an issue that a lot of files have number_of_authers = 0.
That's confusing to the users.

**Comment by ce-bo** [comment]
I am not sure whether we can fix this.
Maybe this is due to files that are added by squashed merge commits.

**Comment by ce-bo** [comment]
What about changing the default value of an existing file for number_of_authors from 0 to 1?

**Comment by ce-bo** [comment]
I checked the code quickly. The merge commit parser is not increasing the number_of_authors metric. 
But let's verify that by some examples to understand the problem at first.

**Comment by phanlezz** [comment]
The current state of the repository does not produce any `number_of_authors = 0` values.
Can you provide me an example repository where this issue occurs?

**Comment by ChristianHuehn** [comment]
As there is no more activity and we cannot recreate it, we will simply close it. If the problem persists please contact us again.
