### ISSUE TITLE
Output Handling - Enable compression for data written to stdout

### ISSUE THREAD

**Issue by fritschldwg** [MaibornWolff/codecharta#3444]
# Feature request

## Description

As a user of codecharta, I want the option to compress codecharta JSON data not only when writing to files but also when outputting to stdout. This will allow me to use compressed output in further steps.

## Acceptance criteria
- Running any parser with the compression flag set, applies compression to both file and stdout output

**Comment by BridgeAR** [comment]
I don't think it's something really necessary at the moment. Suggestion: let's only log a warning about the flag being ignored with other options together or throw an error and abort. That would be sufficient.

**Comment by BridgeAR** [comment]
After discussing it briefly with @fritschldwg we came to the conclusion that it's not possible to confuse the option as the user can only opt-in to uncompressed output and there is no need for a warning.
I don't think we need the other behavior right now, so let's close this for now @ce-bo?
