### ISSUE TITLE
Can't rotate map in mobile view

### ISSUE THREAD

**Issue by Nereboss** [MaibornWolff/codecharta#3449]
# Bug

When opening the web version on a mobile device, the map cannot be rotated

## Expected Behavior

WHEN

I swipe across the screen in the main area

THEN

Both the map, as well as the top right cube that shows the rotation get rotated

## Actual Behavior

Only the cube in the top right rotates. The main map only rotates once the user makes an additional click or the page is refreshed e.g. by changing the rotation of the device

## Steps to Reproduce the Problem
1. Open CodeChartas web version on a mobile device (chromes toggle device toolbar works too when its in mobile mode)
2. Swipe across the screen over the main map
3. Click somewhere on the main view to see the map rotate

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes
- CodeCharta Version: 1.121.1
- OS: IOS
- Browser: Safari, Chrome

**Comment by ChristianHuehn** [comment]
For now I will close all the mobile related issues. We have to rethink if we even want to support mobile or not
