### ISSUE TITLE
Codecharta version does not get automatically increased

### ISSUE THREAD

**Issue by Nereboss** [MaibornWolff/codecharta#3451]
# Bug

## Expected Behavior

<GIVEN>

WHEN

Making a release

THEN

The codecharta version in the package.json files gets updated correctly

## Actual Behavior

Only the package.json in visualisation gets update, the one in the main folder is stuck at 0.0.2

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): no
- CodeCharta Version: 1.121.1
- OS: Mac
- Browser: -

**Comment by BridgeAR** [comment]
The main folder is not published on npm. It's a kind of monorepo used here.
