### ISSUE TITLE
Applicable custom view is shown in "non-applicable custom views" section

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#3455]
# Bug

## Expected Behavior

GIVEN
added custom view for current map

WHEN
opening custom views menu

THEN
custom view is shown in "applicable custom views" section

## Actual Behavior
custom view is shown in "non-applicable custom views" section

## Screenshots
![image](https://github.com/MaibornWolff/codecharta/assets/26900540/2a42f6bf-8c15-4318-9916-6f49297cfb16)

## Steps to Reproduce the Problem
1. open web demo with default maps
1. add custom view
1. open custom view menu

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes 
- CodeCharta Version: 1.121.1
- OS: -
- Browser: -

**Comment by Nereboss** [comment]
Could not be reproduced, if someone can reproduce this issue please add the steps in a comment and reopen this issue
