### ISSUE TITLE
MCC name is incorrect

### ISSUE THREAD

**Issue by Nereboss** [MaibornWolff/codecharta#3456]
# Bug

## Expected Behavior

<GIVEN>

WHEN

Looking at the legend

THEN

The MCC is described with the correct words (likely McCabe Complexity or Cyclomatic Complexity)

## Actual Behavior

The MCC is described as Maximum Cyclomatic Complexity

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes
- CodeCharta Version: 1.121.1
- OS: Mac
- Browser: Yes

**Comment by phanlezz** [comment]
[Some notes to cc, mcc](https://arxiv.org/pdf/2003.00399.pdf )

**Comment by phanlezz** [comment]
Two ideas:

- CC : Cyclomatic complexity : Total number of paths through the code as defined by McCabe.
- MCC: McCabe Cyclomatic complexity; Total number of paths through the code as defined by McCabe.

**Comment by ce-bo** [comment]
The two mentioned metrics are the same, no?

I am used to also count && and || operators for a complexity metric.
According to the [docs](https://docs.sonarsource.com/sonarqube/latest/user-guide/metric-definitions/), Sonar is doing the same. I suggest to stick to this approach.

**Comment by phanlezz** [comment]
> The two mentioned metrics are the same, no?
> 
> I am used to also count && and || operators for a complexity metric. According to the [docs](https://docs.sonarsource.com/sonarqube/latest/user-guide/metric-definitions/), Sonar is doing the same. I suggest to stick to this approach at least for metric gardener. I think the mcc in Codecharta is the same than the complexity metric of Sonar, or is it the "real" McCabe Complexity?

I thought (wrongly), that sonar uses MCC, but it is a modified version as you say. 
As sonar is our primary source of complexity metrics, I would agree with your position and stick to the same definition.
That would be:
CC : Cyclomatic complexity : Total number of paths through the code.
Correct?

**Comment by ce-bo** [comment]
Yes, I think that is fine. It is unfortune that the acronym is `mcc`. But in the sope of this issue I would keep it. An update would require some more changes and would also be a breaking change that we should communicate to the users. 

I will create an issue for renaming `mcc` to e.g. `sonar_complexity` when it is imported or generated by sonar. For me it doesn't make sense to translate sonar imported metrics to a not understandable metric like `mcc` with a missing are deviating definition. It can coexist with the sonar_cognitive_complexity. Thus, there might be other complexity metrics that can be imported but would be named differently then.

I think there are a lot of hard references to `mcc` in the code. We must evaluate on how to get rid of those.

**Comment by Nereboss** [comment]
Update/conclusion on the current situation for this issue:

Our mcc metric is the complexity metric from sonar but renamed. 
Currently we define it as "Maximum cyclomatic complexity" where the Maximum does not make much sense and can easily be confused for "McCabe cyclomatic complexity".

The first idea was to not rename it anymore which would result in us having a 'new' sonar_complexity metric but no mcc metric anymore. As mcc is one of the most used metrics, this change should not be done before informing/discussing it with the stakeholders.

This issue will be blocked until we decide on how to continue with this problem

**Comment by ChristianHuehn** [comment]
Yes we can stop renaming it to mcc and use the default name instead. In that specific case: sonar_complexity
