### ISSUE TITLE
Performance issues for files >5MB

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#346]
Files that are larger than 5MB feel very laggy. Rotation is smooth but the following are visually laggy and stutter.

* typing in Treeview Search (very slow)
* hiding/excluding files
* comparing two big maps in delta mode
* selecting a scenario
* changing metrics
* changing margin
* changing labels
* changing height
* using the color slider
* invert colors

That is pretty much all intersting interaction. We need to address this issue. 

Maybe some code is slow, maybe we just need to add some debouncing or **make the UI more fluid by delaying some other stuff and not reacting immediately**. This might also be a good point to work with async/await.

**Comment by mrpatpat** [comment]
> * typing in Treeview Search (very slow)
> * using the color slider

Debouncing should definetly help here 👍 These are actions that get repeated a lot on change. Still the action itself could have some improvement potential, too.

> * changing height
> * comparing two big maps in delta mode

These two points are linked to our number of 3D objects in our scene.  We had this problem a long time ago, made it better (rendering rework!) and saw further improvements (less geo, merge everything into one, etc). 

The other issues are propably linked to the fact, that the map needs to be rebuilt on change. This is associated with  the map size. Maybe we can make changes more selective. Only change specific parts of the map. 

Especially the number of objects and partial geo updates are very interesting but challanging tasks. Before implementing the solution, we should have a meeting and talk a little bit about this topic and maybe start a spike. 

These are just some notes and definetly not all possible solutions :)
