### ISSUE TITLE
Clicking on a Folder/File in the File/Node Explorer / (searchPanel) should select the corresponding Folder/File on the map

### ISSUE THREAD

**Issue by phanlezz** [MaibornWolff/codecharta#3470]
## Clicking on a **Folder/File** in the _File/Node Explorer_ / (`searchPanel`) should select the corresponding **Folder/File** on the map

Like the title describes, the function should be identical to a click on a building on the map.

### Description

As a user, I want to quickly highlight a certain building so that I can evaluate it visually. 

## Acceptance criteria
- OnClick on a File or Folder in the `searchPanel` should highlight it on the map (like a direct click on the map would)

**Comment by ce-bo** [comment]
We discussed to highlight the building that was clicked in the file explorer and to show the sidebar as well. Are there any other questions remaining @fritschldwg?
