### ISSUE TITLE
Rethink edges in delta mode

### ISSUE THREAD

**Issue by Nereboss** [MaibornWolff/codecharta#3472]
# Feature request

Currently in delta mode it is not clear which edges belong to the comparison map and which belong to the reference map. This should be change. 
Three possible approaches for this are:
- Only showing edges of the comparison map (as this is the 'newer' map) [dev note: look at edgeVisibility.selector.ts]
- Showing edges of the comparison and the reference map in different colors
- Do not show edges in delta mode

## Description

As a user, I want edges in delta mode to behave so that i can more clearly see changes from the comparison to the reference map.

## Acceptance criteria
- 
- 
- 

## Assumptions & Exclusions
**Before implementing any of this, we should decide on an approach and update the acceptance criteria**

## Development notes (optional Task Breakdown)
- [ ] 
- [ ] 
- [ ]

**Comment by ChristianHuehn** [comment]
Will be reworked. As truc worked on this.
