### ISSUE TITLE
Create CodeCharta Maven plugin

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#348]
CodeCharta is currently not available in a maven repository. That makes it harder to include in a build pipeline than it needs to. Let's change that.

One big change from ccsh is that there should be automerge, which adds -p and -o to all filters.

Proposed interface, 1:1 mapping from ccsh, but adding automerge:
```
<plugin>
                <groupId>de.maibornwolff.codecharta</groupId>
               <artifactId>analysis-maven-plugin</artifactId>
                <version>same as all of codecharta</version>
                <configuration>
                   <automerge>
                        <mergeFile>projectName.cc.json</mergeFile>
                        <projectName>projectName</projectName>
                   </automerge>
                    <filters>
                    <filter>
                       <name>sonarimporter</name>
                       <params>url proj</params>
                    </filter>

                    <filter>
                       <name>scmlogparser</name>
                       <params>src/main/java -o scmlog.cc.json</params>
                    </filter>

                     <filter>
                       <name>scmlogparser</name>
                       <params>src/main/java -o scmlog.cc.json</params>
                    </filter>
                    </filters>
                </configuration>
            </plugin>
```
                
Proposed maven artifact names:
```
<groupId>de.maibornwolff.codecharta</groupId>
<artifactId>analysis-ccsh</artifactId>

<groupId>de.maibornwolff.codecharta</groupId>
<artifactId>analysis-maven-plugin</artifactId>
```

**Comment by Richargh** [comment]
A lot has happened here as well. We can release a maven plugin if we want. 

There are a couple of issue though.

* Ccsh is not available in maven central
* Getting a library and plugin into maven central involves about 16 steps including creating a jira issue. It's rather involved and I have no idea if we can automate it as part of our release script.
* It might be a lot easier to create  gradle plugin.

**Comment by BridgeAR** [comment]
I am closing this as a low priority for now. If someone wants to add CodeCharta to the build pipeline, it's possible to do so with `npm`.
