### ISSUE TITLE
Decouple CodeCharta from fixed metrics like MCC

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#3485]
# Feature request

Resulted from https://github.com/MaibornWolff/codecharta/issues/3456

## Description

Some complexity metrics (e.g. from sonar) are imported and renamed into `mcc`, so that CodeCharta does know the most important complexity metric. But...

**As** a User, **I want** to preserve the source metrics names and definition, **so that** I can use exactly these metrics in CodeCharta.

At the moment, some metrics are mapped during import on custom acronyms that nobody can understand.

We need to put further thoughts into this on how to get rid of the fixed core metrics in CodeCharta.

## Acceptance criteria
- 
- 
- 

## Development notes (optional Task Breakdown)
- [ ] There are hard references to `mcc`, `rloc` and maybe others in the code
- [ ] 
- [ ] 

## Open questions
- How to be able to identify the main complexity metric, that is available from the cc.json file, so that features like Suspicious Metrics can work with it.

**Comment by ChristianHuehn** [comment]
Is planed for the future but will be split into multiple smaller issues.
