### ISSUE TITLE
Add option to reset saved state

### ISSUE THREAD

**Issue by fritschldwg** [MaibornWolff/codecharta#3498]
# Feature request

## Description

After #3486 will have been merged, users will no longer be able to reset their workspace to default. A button which resets the entire workspace back to default (including sample maps) is therefore necessary, since resetting every setting manually is too cumbersome. 

## Acceptance criteria
- A button is added which allows to reset the current workspace back to default.
- The button could be placed in the global settings menu.

**Comment by ce-bo** [comment]
I would like to show the new button in the upper menu bar next to the global settings button. It should be quick and easy to reset CodeCharta. We should make sure that it is hard to accidentally click the reset button e.g. when a user actually wants to open the global settings.

**Comment by fritschldwg** [comment]
I'm clsoing this issue, as I have implemented the reset-button as part of #2056. I placed the reset-button in the upper left corner (next to the upload-button, screenshot-button etc.). Once the reset-button is clicked, a dialog asking for confirmation is opened.
