### ISSUE TITLE
CodeCharta json 2.0

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#350]
A place to design the new **codecharta.cc.json**. This issue description should always contain all commented ideas and be up to date!!!

- **`analysis`** is data from the ccsh importer. This will never be updated!
- **`settings`** can be updated by the user. Enriches the analysisData
- The `color`'s value can either be a ID number, which matches to our default color scheme or a hex-string value

### In short
``` json
{
  "fileMeta": {},
  "analysis": {
    "map": [],
    "edges": [],
    "attributeTypes": {},
    "timeTravel": [],
    "attributeDescription": [],
  },
  "settings": {
    "fileSettings": {
      "excludedNodes": [],
      "flattenedNodes": [],
      "markedPackages": []
    }
  },
  "scenarios": [{
    "name": "Complexity",
    "settings": {
      "dynamicSettings": {},
      "appSettings": {}
    }
  }]
}
```

### In detail
``` json
{
  "fileMeta": {
    "apiVersion": "1.1",
    "createdOn": "2019-02-21T19:50:10+00:00",
    "updatedOn": "2019-03-01T19:50:10+00:00"
  },
  "analysis": {
    "map": [{
      "name": "root",
      "type": "Folder",
      "attributes": {},
      "link": "",
      "children": []
    }],
    "edges": [{
      "fromNodeName": "/root/src/de/Foo.java",
      "toNodeName": "/root/de/maibornwolff/codecharta/Bar.java",
      "attributes": {
        "averageRevs": 9,
        "pairingRate": 100
      }
    }],
    "attributeTypes": {
      "edges": [{
        "name": "pairingRate",
        "type": "average"
      }, {
        "name": "averageRevs",
        "type": "sum"
      }],
      "nodes": [{
        "name": "loc",
        "type": "sum"
      }, {
        "name": "testCoverage",
        "type": "average"
      }]
    },
    "timeTravel": [{
      "nodeName": "root/src/de/maibornwolff/Blub.java",
      "previousNodeNames": [{
        "timestamp": "2018-10-12T12:10:15+00:00",
        "name": "CoolStuff.java"
      }]
    }],
    "attributeDescription": [{
      "name": "mcc",
      "displayName": "Code Complexity",
      "longDisplayName": "Complexity by McCabe",
      "description": "The code coverage measures blah blah and is calculated by blah blah"
    }],
  },
  "settings": {
    "fileSettings": {
      "excludedNodes": ["/root/Foo.java"],
      "flattenedNodes": ["/root/Bla.java"],
      "markedPackages": [{
        "path": "/root/Foo.java",
	"color": 1,
	"attributes": {
          "name": "My foo class"
	}
      }]
    }
  },
  "scenarios": [{
    "name": "Complexity",
    "settings": {
      "dynamicSettings": {
        "colorRange": [{                
          "color": 1,
          "from": 0
        }, {
          "color": 2,
          "from": 70
        }]
      },
      "appSettings": {}
    }
  }]
}
```

#### Ideas by @Richargh regarding `userSettings`
```
"userSettings": {
  "camera": {
    "angle": 110.5,
    "position": {"x": 5, "y": 7, "z": 12}
  },
  "size": {
    "selectedAttribute": "rloc",
    "margin": 15,
    "autoMargin": true
  },
    "height": {
    "selectedAttribute": "mcc"
  },
  "color": {
    "selectedAttribute": "coverage",
    "sections": [{
      "color": 0,
      "from": 0
    }, {
      "color": 1,
       "from": 70
    }, {
      "color": 2, 
      "from": 85
    }]
  }
}
```

**Comment by Richargh** [comment]
It's a great idea to move meta-information to a separate space. `createdOn` should also be very helpful, just please also add a time-zone. I suggest adding a `modifiedOn` as well. That way the original timestamp can be preserved during merge and only modifiedOn is changed.

I don't understand scenarios.json. What is that one for? Is it a separate file that can also be added using the UI? That brings me to another thought I have had for a while: Wo could create a codecharta.cc.proj file. In reality the proj file could just be a compressed archive of a cc.json and one scenarios.cc.json and some more. The proj file would be something only the standalone version understands and it could include even more user-specific information.

I like where this rough idea is going. I am missing things such as edges, blacklist, historic information such as commits, authors, language version.

**Comment by alschmut** [comment]
- The timestamp is the (ISO_8601)[https://en.wikipedia.org/wiki/ISO_8601] and the `+00:00` includes the timezone changes.
- The `scenarios.cc.json` file I currently a hard coded file in the project and could possibly be imported in the future
- Which advantage would a `codecharta.cc.proj` give us? Or is it "just" supposed to contain different files...?
- All other objects will be added as well, I just wanted to think about the settings object in more detail first and collect impressions from #178

**Comment by Richargh** [comment]
1. You are right. My mistake. I expected the Z (zero or UTC) because I see that all the time in my current project.
2. Does it require a lot of effort to build a scenario importer?
3. The cc.proj would a) give us the compression. We can go from 13MB files to 702kb. b) we can include specific user settings in the cc.proj. F.ex. it would be beneficial to store where the source code is for the cc.json. But you don't want that in the cc.json because it is system/user specific.
4. I thought so. It looked like a rough idea.

**Comment by alschmut** [comment]
@Richargh 
2. As we already have an importer for our `project.cc.json` files, it shouldn't be too much effort
3. Alright, yea for those use cases that made sense

**Comment by alschmut** [comment]
I just updated the `cc.json` schema. What do you think about the `analysisData`? It holds all the information, which only comes from the `ccsh` analysis. As we can not re-analyze inside the visualisation this is intended to not be updated!

Currently we store the edge-visibility inside the edges object. Like doing it with the blacklist we could store such information in the `fileSettings`.

**Comment by alschmut** [comment]
> I just updated the `cc.json` schema. What do you think about the `analysisData`? It holds all the information, which only comes from the `ccsh` analysis. As we can not re-analyze inside the visualisation this is intended to not be updated!
> 
> Currently we store the edge-visibility inside the edges object. Like doing it with the blacklist we could store such information in the `fileSettings`.

Back to the topic after many weeks: Would you like to comment? :)

**Comment by Richargh** [comment]
A couple of things:

* analysisData is a great idea! Only question is, should it just be analysis without the data? :)
* What does edge-visibility mean? 
* Do you want to rename nodes: [{}] to map: [{}]?

My ideas:
* Should we rename `"name": "root"` to `"name": "/"`? I find it confusing to see "/root" in the file path.
* I added "updatedOn" in case we merge files. UpdatedOn reflects the createdOn data from the last merged file. So "updatedOn" is a bad name, I just couldn't find a better one.
* The scenarios should be storable in the cc.json as well.
* Human readable attribute descriptions should also be in the cc.json: `{"attribute: "rloc", "name": "Real Lines of Code", "description": "This metric is calculated by ..."}` --> and we might want to make this editable by the user :)

**Comment by alschmut** [comment]
I just updated the above issue description with the content of #182. So we can potentially close #182?

**Comment by Richargh** [comment]
I closed #182. Things that I could not find but were in #182 

* non-number attributes like author names or implementation language
* method name and line number for the max metrics

We should also move `attributeTypes` and `attributeDescriptions` out of the analysis block and into a new user-supplied block. It might be useful for the user to be able to change these and supply them from after cc.json creation. What do you think.

**Comment by alschmut** [comment]
- Why should the user change `attributeTypes`? The metrics have a in fact one behaviour, `relative` or `absolute`, no matter what we want. `rloc` will always be an absolute number..? If the user wants to change that behaviour, we should rather think about adding a settings checkbox to treat all metric values as relative for example.
- I am fine with moving the `attributeDescriptions`, if it really makes sense to change that description, although I don't really know how to name that block/object.

**Comment by Richargh** [comment]
* not all importers generate an `attributeTypes`. The CSVImporter in particular. But we could also add a filter to ccsh for chaning the attributeTypes.
* That filter could we could also for `attributeDescriptions`. 

You know what, I changed my mind, let's not make them user changable but provide that option from the `ccsh`. Most importers should be well-behaved and generate the right descriptions and types.

**Comment by alschmut** [comment]
btw: one thing that came into my mind.
1. Do we have to stop supporting the cc.json 1.x scheme, while starting to support a cc.json 2.0? 
1. Why don't we just do it incrementally and add a separate layer to convert from 1.x to 2.0? Or the other way around, which means we will never export any 2.0 cc.json in production code, but would potentially be able to import a 2.0 cc.json
1. We probably have to do that nevertheless, as we won't implement everything in one PR. Of course we need that layer in the analysis, as well as the visualization.
1. But I also get that this is more like a strategy decision and depends on what codecharta is supposed to be in 2 years...
