### ISSUE TITLE
PRs based on branches in repository forks do not run GH-Actions 

### ISSUE THREAD

**Issue by phanlezz** [MaibornWolff/codecharta#3500]
# Bug: PRs based on branches in repository forks do not run GH-Actions 

## Expected Behavior

GIVEN A branch from someone who want to participate in this repository

WHEN opening a PR on said branch (on a fork)

THEN the applicable GH-actions like test.yml asks for a maintainer to be started or start themselves if possible.

## Actual Behavior

They don't start and are forever stuck in _"Waiting for status to be reported"_,
 
## Steps to Reproduce the Problem
1. Create fork
1. Create branch
1. Open PR

## Specifications

It must be checked whether this behavior is still occurring.

**Comment by BridgeAR** [comment]
It's actually a security aspect by github. Github actions were for example misused to do bitcoin mining and people tried to steal secrets from the github actions.

**Comment by ChristianHuehn** [comment]
Would be great, but we currently dont need it as there aren't many people supporting CC from outside of our organization anyway. 👍
