### ISSUE TITLE
Merging Metric Templates and custom views

### ISSUE THREAD

**Issue by Nereboss** [MaibornWolff/codecharta#3503]
# Feature request

Metric Templates are basically Custom views that are independent of the map
This could be integrated into custom views by making a new non-map-specific section, where the current Metric Templates will be placed, and a map-specific section, where the current Custom Views are placed.

This would allow to create custom views that are not dependent on the map, which will make it easier for use cases where different maps (or different version of the same map) are compared.

## Description

As a user, I want these two features combined so that it is easier to apply specific scenarios because both features serve similar purposes.

## Acceptance criteria
- The buttons in the UI are merged into one (The one of custom views)
- Inside the Custom views there are two sections for map specific and non map specific views
- When creating a custom view the user has the option to make it map specific or not

## Development notes (optional Task Breakdown)
- [ ] 
- [ ] 
- [ ]

**Comment by ChristianHuehn** [comment]
We need both atm
