### ISSUE TITLE
Dragging/Rotating the map does not work when mouse is near viewcube

### ISSUE THREAD

**Issue by mrpatpat** [MaibornWolff/codecharta#353]
# Bug

Dragging/Rotating the map does not work when mouse is near viewcube. The right events need to be propagated to the codemap and/or the three orbit controls

## Expected Behavior

Dragging the map near the viewcube rotates the map.

## Actual Behavior

Dragging the map near the viewcube does nothing.

**Comment by NearW** [comment]
https://stackoverflow.com/questions/46667197/three-js-orbitcontrols-not-working-when-dom-element-is-positioned-over-the-scene

**Comment by RomanenkoVladimir** [comment]
@DmytroHutkin this currently breaks any user interactions PTAL
