### ISSUE TITLE
Exclude should also update maxValue of colorRange

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#355]
# Bug

## Expected Behavior
When excluding nodes the possible colorRange should adapt to the metrics new maxValue of visible nodes.

## Actual Behavior
Currently the colorRange's maxValue just stays the same when excluding nodes, although the maxValue actually should be much lower.

## Question
Should the colorRange's maxValue also be updated when hiding nodes? (no!)

## Specifications

  - Version: 1.21.0

**Comment by Richargh** [comment]
* Don't change the maxValue when hiding nodes. Hiding nodes also does not affect the metric summation for example.
