### ISSUE TITLE
Indicate Top10 per metric

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#362]
When selecting a metric, should Codecharta explicitely display or marc the top 10 buildings for that metric? 

If yes: why and how?
If no: why not?

**Comment by alschmut** [comment]
Do you think of a functionality similar to the labels (which only show up for the top N buildings regarding the heightMetric), but displaying it in another way than "labels"?

**Comment by Richargh** [comment]
I forgot about the labels :) That's already a way to show the top x metrics.

But yes, I was looking for a new way to show the top 10 for the area and color metric.

**Comment by Richargh** [comment]
We'll close this for now, because we can already see a top-10, like @alschmut remarked, for various metrics.
