### ISSUE TITLE
Show the sum symbol next to the metric sum

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#364]
Currently CC sums the metrics for the buildings, when hovering over folders. It would be nice to also see a sum symbol to know what it does.

**Comment by NearW** [comment]
> attributeTypes is an optional entry in the cc.json.
> If it's there CC has information about the attributeType and can theoretically display the arithmetic mean for relative attribute types.
> If it's not there CC will assume an absolute type for all metrtics and generate a default representation.
> We added this a while back to CC but so far I think code does not react to different attribute types and almost no importer sets this information. It's an oversight, because over things took priority.

We will display the sigma-icon based on that information. In order to profit from that in the future, we should work on settings the attributeTypes in the analysis correctly for future cc.jsons though.
