### ISSUE TITLE
Presentation mode

### ISSUE THREAD

**Issue by Nereboss** [MaibornWolff/codecharta#3640]
# Question

It is currently not clear to me what the presentation mode does and there is no documentation about it.
Is this a feature that was once working and we need to fix?
Is this not functional and we can just remove this button?
Is this a feature that should be added?

## Preparation

Please check these resources first before posting a question

* [x] I searched for answers in [older issues](https://github.com/MaibornWolff/codecharta/issues?utf8=%E2%9C%93&q=)
* [x] I looked into the [README.md](https://github.com/MaibornWolff/codecharta)
* [x] I read the [website](https://maibornwolff.github.io/codecharta/)

**Comment by ChristianHuehn** [comment]
There is a functionality, it looks like a small spotlight around your cursor.
See codeMapMesh and presentationModeButton.component.html
