### ISSUE TITLE
Visual Bug with the Button that shows hidden/flattened buildings

### ISSUE THREAD

**Issue by Nereboss** [MaibornWolff/codecharta#3646]
# Bug

## Expected Behavior

<GIVEN>

WHEN

The button is pressed

THEN

Only its color changes to show that its activated

## Actual Behavior

Additionally to the color change, a checkmark appears which makes the button larger and shifts the UI

## Screenshots

Button not pressed:
<img width="358" alt="image" src="https://github.com/MaibornWolff/codecharta/assets/105795397/120bcd7d-99e6-49c5-9c6b-582d5d4432ac">

Button pressed
<img width="389" alt="image" src="https://github.com/MaibornWolff/codecharta/assets/105795397/34ff4812-39e3-4f7a-a60c-a354d9e306c0">

## Steps to Reproduce the Problem
1.
1.
1.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes
- CodeCharta Version: vis 1.126.0
- OS: MacOS
- Browser: Chrome

**Comment by ChristianHuehn** [comment]
Agree, we will remove the checkmark.
