### ISSUE TITLE
Make name of metric templates/scenarios consistent

### ISSUE THREAD

**Issue by Nereboss** [MaibornWolff/codecharta#3648]
# Feature request

Our metric templates/scenarios menu has the label `metric templates` in the main UI. However when clicking on it, the top bar says `metric scenarios` and when adding one scenario is also the used name. 

In the code the word `metric template` is found 13 times and `metric scenario` is found 9 times.

We should decide on one name and stick to it. 

## Description

As a user, I want the naming to be consistent so that i dont get confused by the changing names throughout the program and the documentation.

## Acceptance criteria
- 
- 
- 

## Development notes (optional Task Breakdown)
- [ ] 
- [ ] 
- [ ]

**Comment by ChristianHuehn** [comment]
We will rename it to scenarios
