### ISSUE TITLE
Add LoC Metrik to Gitlog Parser

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#3666]
# Feature request

Make the Gitlog Parser also calculate lines of code (LoC).

## Description

As an Auditor, I want LoC in the gitlog parser so that the generated .git.cc.json is useful by itself.

When visualizing a `cc.json` we usually put RLoC (real lines of code) on the area metric and keep that constant for all views. That means it's currently pointless to visualize a `.git.cc.json`, because it has no useful area metric. You always have to merge the `.git.cc.json` with another file that includes real lines of code (like a `.sonar.cc.json`). It would be much better if the `.git.cc.json` would already by useful by itself. 

Note that I am suggesting that the gitlogparser calculate the lines of code, not the real lines of code. The lines of code is much simpler. It's just the lines in the file. If a file has 200 lines, then LoC is equal to 200. The gitlogparser does not have to know anything about code to know that. 

## Acceptance criteria
- the gitlogparser calculates loc

## Assumptions & Exclusions

The gitlogparser should not try to count real lines of code.

## Development notes (optional Task Breakdown)
- [ ] 
- [ ] 
- [ ]

**Comment by ChristianHuehn** [comment]
When I read this I see a problem with git not having a RLoC metric and therefor is not useful by itself. LoC would just be a workaround here. Actually it would be much better to combine different parsers (instead of, parser1, parser2, merge both). I reject this for now, until we come up with a better solution for this.
