### ISSUE TITLE
Add RLoC metric to rawtextparser

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#3667]
# Feature request

Add real lines of code (RLoC) to rawtextparser.

RLoC = count only the lines that have actual code in them. Ignore blank lines and ignore comments. 

## Description

As an auditor, I want the rawtextparser to calculate rloc so that I have a fallback in case sonar cannot calculate metrics or is not available. 

Sonar + `ccsh sonarimport` is a great source of metrics. But it's cumbersome to setup for parsing and not always available (not all clients have a sonar setup and the free sonar does not support all languages). It would be great if we had a parser that gave us both real lines of code for the area metric and nesting level for the height metric.

There is another tool that gives us the real lines of code, tokei + tokeiimporter, but that requires the user to also install tokei. It would be great to have a shortcut here. Simply call `ccsh rawtextparser` and you have some base metrics. 

I think it would relatively easy to add real lines of code to the rawtextparser. Take the language file that tokei uses, https://github.com/XAMPPRocky/tokei/blob/master/languages.json, and use that to identify what tokens are single-line and what are multi-line comments and don't count them. Support only the programming languages that are somewhat know and for which the language.json is simple to understand.

Tokei and its languages file is dual licensed under Apache and MIT. 

## Acceptance criteria
- rawtextparser calculates real lines of code (RLOC)

## Development notes (optional Task Breakdown)
- [ ] 
- [ ] 
- [ ]

**Comment by ChristianHuehn** [comment]
We are currently thinking about different ways to do this for RLOC/LOC/COMMENTS/MCC/IDENTATION_LEVEL and some more, so we dont have to use sonar for everything. Therefor I will delete this issue, to clean up a bit :) thanks for the idea
