### ISSUE TITLE
View encapsulation causing component style problems in Global Configuration Dialog

### ISSUE THREAD

**Issue by polina-schoenfeld-mw** [MaibornWolff/codecharta#3671]
# Bug

## Expected Behavior

WHEN

Some components (i.e. GlobalConfigurationDialog component) are being displayed

THEN

Component styles aren't displayed correctly due to view encapsulation being disabled.

## Actual Behavior

Component's should be using view encapsulation and have their styles displayed as expected.

## Screenshots

![Image](https://github.com/user-attachments/assets/76ee11b1-683f-4d41-b507-abd2ba8527ad)

![Image](https://github.com/user-attachments/assets/c7bb37e8-cdfc-43c4-a93e-047973f83096)

![Image](https://github.com/user-attachments/assets/0890f8ed-a772-4039-9cb4-6151d3e075b8)

![Image](https://github.com/user-attachments/assets/8b8f12ab-bc6d-4b1f-98f7-c174122629b3)

## Steps to Reproduce the Problem
1. Open the Global Configuration Dialog.
2. Click on one of the Dropdown Menus.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes
- CodeCharta Version: 1.126.0
- OS: Windows 10 Pro
- Browser: Google Chrome 123.0.6312.122 (Official Build)

**Comment by phanlezz** [comment]
Closed via #3712
