### ISSUE TITLE
Changing Camera zoom seems to change field of view 

### ISSUE THREAD

**Issue by Nereboss** [MaibornWolff/codecharta#3678]
# Bug

## Expected Behavior

<GIVEN>

WHEN

Zooming in or out

THEN

The proportions of the map stay the same

## Actual Behavior

The map seems to be "warped" when zoomed in or "flattened" when zoomed out. To me this looks like the field of view (FOV) of the camera somehow changes

## Screenshots
Map on 100% zoom:
![image](https://github.com/user-attachments/assets/9f26494a-72c4-4989-943d-6119afa19a26)

Map on 225% zoom:
![image](https://github.com/user-attachments/assets/05bf2a7e-ed1f-4960-b558-385fa2943e10)

Map on 25% zoom:
![image](https://github.com/user-attachments/assets/82bdcfa0-4fd8-42a4-b01c-a7918ed7c20a)

## Steps to Reproduce the Problem
1. Zoom in/out
2. Use right click to move the map around so its nearer/further away
3. 

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): no
- CodeCharta Version: current main
- OS: MacOS
- Browser: Chrome

**Comment by Nereboss** [comment]
Yes, as the feature causing the bug is reverted, this issue can be closed

**Comment by phanlezz** [comment]
Re-opened as #3665 did not get reverted, which changed the camera behavior. 
It will be determined if a revert action and fix release need to be done.  
@IdrisLaabidi

**Comment by phanlezz** [comment]
#3665 got reverted via fac09469cc03d30c22ebd6ebbae437939110f534
