### ISSUE TITLE
Old mcc maps can be migrated to new metric names

### ISSUE THREAD

**Issue by ChristianHuehn** [MaibornWolff/codecharta#3685]
# Feature request

## Description

As a user who has an old codecharta map with mcc, I want a script that allows me to migrate it in the repository with a documentation in the docs, so that I can migrate and compare them easier

## Acceptance criteria
- we have a script that migrates old mcc metrics into our new format. Located in our repo 
- There is an documentation for it

## Development notes (optional Task Breakdown)
- [ ] 
- [ ] 
- [ ] 

## Open questions

**Comment by Nereboss** [comment]
I think the acceptance criteria for this issue should be adjusted a little for two reasons:

About the migration script: We already have the StructureModifier which can adjust the structure of an existing cc.json. 
I propose that we do not provide a script to update the mcc but add it as an option in the StructureModifier.

For making the user aware: When the user imports a map, to give them the options to abort or import anyway we would need some kind of popup. This can get annoying for several reasons (popups are annoying in general; it would reappear for every new map, even when the user already knows what will happen; if someone has the visualisation in a pipeline somewhere the popup could mess with that; etc.). 
I propose we handle it more like a notification that is out of the way but still makes the user aware and would tell them how to update the map with the StructureModifier. Similar to how IntelliJ shows notifications in the bottom right that are noticeable, but not invasive like a popup.

**Comment by Nereboss** [comment]
The script that can rename mcc to complexity or sonar_coplexity has been implemented into the structureModifier, so the first part of this issue is done
What is left is to notify the user in the frontend when they load multiple maps with some containing mcc and some the new names

**Comment by phanlezz** [comment]
Closed via #3728 and #3773

**Comment by ChristianHuehn** [comment]
I took an old map https://github.com/user-attachments/files/17414626/old.cc.json and it failed 

java.lang.NullPointerException: Input file contains null value for an attribute type! Please ensure the input is a valid cc.json file.
