### ISSUE TITLE
View encapsulation causing component style problems in File Panel Component

### ISSUE THREAD

**Issue by polina-schoenfeld-mw** [MaibornWolff/codecharta#3695]
# Bug

## Expected Behavior

WHEN

Some components (i.e. FilePanelComponent) are being displayed

THEN

Component styles aren't displayed correctly due to view encapsulation being disabled.

## Actual Behavior
Components should be using view encapsulation and have their styles displayed as expected.

## Screenshots
![Image](https://github.com/user-attachments/assets/1bf13aec-99fb-4361-b306-5c2abff8d840)

![Image](https://github.com/user-attachments/assets/31ee284d-30d5-4f4c-8f2f-46531d39aff4)

![Image](https://github.com/user-attachments/assets/e661bd40-77e6-472d-894e-a73487de2be6)

![Image](https://github.com/user-attachments/assets/e19c2370-dbb3-4a47-8b9d-32dc867ff7ab)

## Steps to Reproduce the Problem
1. Select Standard or Delta.
2. Click on one of the dropdown menus.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes
- CodeCharta Version: 1.127.1
- OS: Windows 10 Pro
- Browser: 123.0.6312.122 (Official Build)

**Comment by phanlezz** [comment]
Closed via #3712
