### ISSUE TITLE
View encapsulation causing component style problems in Slider Component

### ISSUE THREAD

**Issue by polina-schoenfeld-mw** [MaibornWolff/codecharta#3713]
# Bug

## Expected Behavior

WHEN
Some components (i.e. Slider component) are being displayed

THEN
Component styles aren't displayed correctly due to view encapsulation being disabled.

## Actual Behavior
Component's should be using view encapsulation and have their styles displayed as expected.

## Screenshots
![Image](https://github.com/user-attachments/assets/9d7ba989-83f4-4838-b414-2acbfe71426f)

![Image](https://github.com/user-attachments/assets/df3c27d4-560d-47ce-86d2-d3e1e3cf4903)

![Image](https://github.com/user-attachments/assets/dc4e10f6-475f-4a1b-af70-1d83c6ec49a0)

## Steps to Reproduce the Problem
1. Open i.e. the Global Configuration Dialog (or other components that contain a slider)
2. Select TreeMapStreet.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes
- CodeCharta Version: 1.127.1
- OS: Windows 10 Pro
- Browser: Google Chrome 123.0.6312.122 (Official Build)

**Comment by Jvascs** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by phanlezz** [comment]
Closed via #3714
