### ISSUE TITLE
Enable View Encapsulation in the Legend Panel and the components inside

### ISSUE THREAD

**Issue by polina-schoenfeld-mw** [MaibornWolff/codecharta#3718]
# Bug

## Expected Behavior

Component's should be using view encapsulation and have their styles displayed as expected.

## Actual Behavior
Some components styles aren't displayed correctly due to view encapsulation being disabled.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes
- CodeCharta Version: 1.127.1
- OS: Windows 10 Pro
- Browser: Google Chrome 123.0.6312.122 (Official Build)

**Comment by phanlezz** [comment]
Closed via #3720
