### ISSUE TITLE
Limit camera rotation under map

### ISSUE THREAD

**Issue by IdrisLaabidi** [MaibornWolff/codecharta#3730]
# Bug

## Expected Behavior

WHEN the map is being tilted so it would be visible from below

THEN the camera stops the tilt when the 'floor' is reached

## Actual behaviour

The camera goes below the map, showing a black square 

> NOTE: This issue has been changed from a previous bug we won't address, the original issue is preserved below
---

# Bug

## Expected Behaviour

GIVEN the map is tilted and buildings are visible

WHEN zooming in

THEN the camera should dolly towards the mouse pointer position.

## Actual Behavior

The camera appears to be rotating, following an arc trajectory towards the mouse coordinates instead of dollying straightforward.

## Steps to Reproduce the Problem
1. Tilt the map as much as possible while still being able to see the buildings. 
2. Attempt to zoom in.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): no
- CodeCharta Version: main branch
- OS: Windows 11
- Browser: Microsoft Edge

**Comment by ChristianHuehn** [comment]
We will try to just remove the rotation 👍

**Comment by Nereboss** [comment]
I tried to address this issue but was not lucky so far. It seems to be a bug within ThreeJS when using the zoomToCursor functionality that can also be observed on their demos e.g. [here](https://threejs.org/examples/#misc_controls_map). 

While there is an option to disable camera rotation and it did disable the user being able to rotate the camera, the rotation of this arc was unaffected.

As this issue does not happen often and theres no easy fix we can do, id suggest closing this and to hope threeJS fixes it in an upcoming version
