### ISSUE TITLE
No Edge Metric in AttributeSideBar for multiple selected Files

### ISSUE THREAD

**Issue by LisaWalter90** [MaibornWolff/codecharta#3746]
# Bug

## Expected Behavior

<GIVEN>
There is more than one file selected
WHEN
The AttributeSideBar is opened
THEN
The amount of incoming/outgoing edges is shown

## Actual Behavior
The amount of incoming/outgoing edges is empty

## Screenshots
![Image](https://github.com/user-attachments/assets/b2946309-48a4-456e-bcad-5fca674cc93f)

## Steps to Reproduce the Problem
1. Select two files
2. Click on a Node so that the AttributeSideBar opens
3. See the empty values for indoming/outgoing Edges

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes 
- CodeCharta Version: 1.127.1
- OS: all
- Browser: all

**Comment by polina-schoenfeld-mw** [comment]
Closed via #3753
