### ISSUE TITLE
Removing a map that is not shown, should not reload the map

### ISSUE THREAD

**Issue by ChristianHuehn** [MaibornWolff/codecharta#3747]
# Bug

## Expected Behavior

GIVEN a map is toggled off and not visible on the view
WHEN deleting the map

THEN no reload should occur

## Actual Behavior
The whole view gets reloaded.

## Screenshots
![Image](https://github.com/user-attachments/assets/ab811e09-002d-493d-8398-aa1eb6c508ec)
For example: Removing codecharta in this picture should not trigger a reload
## Steps to Reproduce the Problem
1. Open CodeCharta
2. Toggle off codecharta 
3. Wait for the short reload
4. Delete codecharta

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes

**Comment by polina-schoenfeld-mw** [comment]
Closes: #3788
