### ISSUE TITLE
Incorrect behaviour when starting to zoom in/out of the map

### ISSUE THREAD

**Issue by Nereboss** [MaibornWolff/codecharta#3754]
# Bug

## Expected Behavior

<GIVEN>

WHEN zooming in or out

THEN
it zoom in only to the cursor and out only from the center of the screen

## Actual Behavior

The first 'tick' of zooming in/out still uses the other 'zoom style' so when first zooming in and then zooming out, the first 'tick of zooming out still takes the cursor as the point from where to zoom

## Steps to Reproduce the Problem
1. zoom in using the mouse wheel (everything should work as expected)
2. zoom out using the mouse wheel (you should feel that the first tick of zooming feels different)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes | no
- CodeCharta Version: current main (unreleased, next version is 1.128.0)
- OS: MacOS
- Browser: Any

## Implementation specifics
we use zooming functionality from threeJS and change the zooming in/out by setting zoomToCursor to true or false in the threeMapControls.service.ts file. This is likely happening after threeJS calculates the zooming for a tick and needs to be changed to happen before.

**Comment by ChristianHuehn** [comment]
Will be accepted and we will change some behavior on this anyway: https://github.com/MaibornWolff/codecharta/issues/3776
