### ISSUE TITLE
Add thousands separation for metrics

### ISSUE THREAD

**Issue by ChristianHuehn** [MaibornWolff/codecharta#3755]
# Feature request
## Description

As an auditor, I want to have the metrics numbers on top separated with a "." every 3 digits, so that I can easier see how big the numbers are.

## Acceptance criteria
- Area/Height/Color metrics have a dot after every 3 digits

## Development notes (optional Task Breakdown)
An example: 
![Image](https://github.com/user-attachments/assets/b0ccf150-03bf-4686-bf14-ef6f3b1406d6)

**Comment by polina-schoenfeld-mw** [comment]
Closed via #3758
