### ISSUE TITLE
Release script doesn't work in Powershell/Cmd because of the Build command in visualisation

### ISSUE THREAD

**Issue by IhsenBouallegue** [MaibornWolff/codecharta#3756]
# Bug
The build script doesn't work in powershell and thus everything that relies on it (the release script).

## Expected Behavior

**GIVEN** the current build script in visualisation:

```bash
ng build && cp electron/* package.json dist/webpack
```

**WHEN** the build script is run,

**THEN** it should work on both Windows and Unix-based systems.

## Actual Behavior

The `cp` command works on Unix-based systems but fails on Windows with the error:

```
'cp' is not recognized as an internal or external command
```

This causes the build script to fail on Windows.

## Steps to Reproduce the Problem

1. Run `npm run build` on Windows with the current `package.json` script.
2. Observe the failure due to the `cp` command.

## Possible Solution

Use `shx` to ensure cross-platform compatibility:

**New script:**

```json
"build": "ng build && shx cp -r electron/* dist/webpack/ && shx cp package.json dist/webpack/"
```

## Workaround

For Windows, use git bush (recommended) or replace `cp` with the Windows-compatible `xcopy` command.

**Comment by phanlezz** [comment]
Maybe we simply add to `VERSION_BUMPING.md`:  'use git bash or add the Unix tools provided by git to your path'
