### ISSUE TITLE
Zooming out does not behave as zooming in

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#3757]
# Bug

## Expected Behavior

GIVEN a user has a map open

WHEN zooming in to a building and then zooming out without moving the cursor

THEN the view should be identical to the original view

## Actual Behavior

When zooming in, everything behaves as expected. Zooming out changes the position. We probably have to memorize the starting points from before zooming in.

## Steps to Reproduce the Problem
1. Zoom into a building
1. Zoom out from that building again

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes
- CodeCharta Version: 1.128.0
- OS: all
- Browser: all

**Comment by ChristianHuehn** [comment]
Yes you are right, that is actually intended at the moment. We want to get feedback on it to decide if we change this or not. As zooming out from a cursor feels weird and lets you move lose track of the map entirely.

**Comment by Richargh** [comment]
I think the new behavior is less than ideal. Zooming in and out moves you across the map. You sort of jump to the right whenever you zoom out. 

https://github.com/user-attachments/assets/fb8dc53d-feb6-4ce3-80c8-d3eac2ad9b1d

**Comment by ChristianHuehn** [comment]
As it was planed to get feedback for it, we had some more discussions which lead to a new feature request:
https://github.com/MaibornWolff/codecharta/issues/3776
