### ISSUE TITLE
Map is behind the metricsbar

### ISSUE THREAD

**Issue by ChristianHuehn** [MaibornWolff/codecharta#3759]
# Bug

## Expected Behavior

The map should only span the space below the ribbonbar

## Actual Behavior
In some circumstances the map glitches behind the ribbonbar which makes some of the content below unseeable

## Steps to Reproduce the Problem
Polina and myself saw it happen in the browser. But we can't reproduce it right now. Please research this topic.

**Comment by phanlezz** [comment]
When the file extension percentage bar is expanded, it partially covers the compass. But I think that is not what you observed. I wasn't able to find anything else. 
There is probably some element that scrolls the canvas upwards or a text element that increases the height of the ribbon bar. 

Do we close the issue for now? @ChristianHuehn 
![grafik](https://github.com/user-attachments/assets/6f17b620-b3f3-4f7b-babf-2b42aa3c94a4)

**Comment by ChristianHuehn** [comment]
@phanlezz it is exactly what I experienced. 👍 
It even slides over the details slider. You wont be allowed to close it unless you close the percentage bar. 

Yes we will close it for now. Thank you
