### ISSUE TITLE
File/Node Explorer dropdown should have more space

### ISSUE THREAD

**Issue by ChristianHuehn** [MaibornWolff/codecharta#3760]
# Bug

## Expected Behavior

GIVEN the file/node explorer is open

WHEN looking at the explorer and opening folders or hovering over entries

THEN there should not be a horizontal scrollbar nor should the left text get moved by the number of files etc.

## Actual Behavior
The text moves significantly and there is a horizontal scrollbar. 

## Screenshots
![image](https://github.com/user-attachments/assets/b7810366-7c23-4a40-89b3-7912ef83ea26)
![image](https://github.com/user-attachments/assets/0ddca273-8a6b-4a26-813b-2941ea8f5b56)
![image](https://github.com/user-attachments/assets/20ecadef-3ce9-4e47-b218-d5e4191d981c)

# Infos
Try revision d17e5993498f27052dbdecba9c7b4e9d63d7e733 to see the intended behavior

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes

**Comment by phanlezz** [comment]
Closed via #3765
