### ISSUE TITLE
Focus does not zoom on a specific building

### ISSUE THREAD

**Issue by ChristianHuehn** [MaibornWolff/codecharta#3761]
# Bug

## Expected Behavior

GIVEN a map with a lot of buildings
WHEN right clicking on a building when clicking on focus
THEN the camera zooms in and shows the full building

## Actual Behavior
It zooms somewhere else near the selected building

## Screenshots
There is a video under Documents > General > Videos > Bildschirmaufnahme 2024-09-20 um 09.02.26 on Teams 

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes

**Comment by IhsenBouallegue** [comment]
The problem might be because the bounding boxes (used for the focus) have the wrong position.
![image](https://github.com/user-attachments/assets/3ed39799-6f64-418e-9205-ca31db49b6c4)
