### ISSUE TITLE
Add an alert when incompatible maps are compared in delta view

### ISSUE THREAD

**Issue by ChristianHuehn** [MaibornWolff/codecharta#3771]
# Feature request
## Description
As a user, I want to see an alert when comparing two maps which have different complexities (mcc and sonar_complexity), so that I can migrate them myself.

## Acceptance criteria
- [ ] Alert is only shown in delta mode when selecting a map
- [ ] Alert contains information about the migration and links to the documentation
- [ ] Alert has a close button and a checkbox for "don't remind me again", not opening the window again

**Comment by BridgeAR** [comment]
The migration might be useful for a few parsers but this is specific to a singular situation.

What about instead just showing the users what metrics do not match by highlighting them in a way that they are not clickable and indicate if map A or map B has the metric.
On top of that (as a second step), add a functionality that allows to link the metric to one available in the other map.

That way it's always working for any combination and helps users to identify the issue fast.

**Comment by BridgeAR** [comment]
I fail to understand how the cc.json format matters in that case. Especially the indication that map A and B do not share the same metric names is something that we have in many situations and one input file has no knowledge about the other one until is it loaded.

I am certain most users are fine with the suggested implementation as it will resolve their immediate need. There are just different ways to resolve that need. One way is specific to that singular metric combination and the other solution is generic to any metric combination and will help future use cases.

CC is a general purpose tool and we have very different use cases (it is even used to visualize financial department data). Thus, generic solutions seem best to me.

**Comment by ChristianHuehn** [comment]
I totally understand the need for the feature you suggested and as you mentioned, we are addressing the current need right now. 

The reason is that when we wanted to give more transparency to our users, we somehow forgot that older maps won't be comparable in delta view. So we talked to some users about their needs. We are sticking with the solution in this issue for now and will take your comments as a feature request.

As for our cc.json, we are currently in the brainstorming phase and depending on the outcome we would either have to change a lot of the code of your suggested feature or do nothing at all. So we should at least wait for that :) 👍

**Comment by ChristianHuehn** [comment]
Doesn't work for
[new.cc.json](https://github.com/user-attachments/files/17414625/new.cc.json)
[old.cc.json](https://github.com/user-attachments/files/17414626/old.cc.json)
