### ISSUE TITLE
Fix flaky pipeline tests

### ISSUE THREAD

**Issue by ChristianHuehn** [MaibornWolff/codecharta#3772]
# Bug
The pipeline right now has some flaky tests in it. Find out which of the tests are broken according on the last pipeline and fix them. 

Please document them in this issue, with their state (fixed/still flaky/too hard to fix in this issue)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes | no
- CodeCharta Version:
- OS:
- Browser:

**Comment by ChristianHuehn** [comment]
![Image](https://github.com/user-attachments/assets/3b57754b-719a-4225-b1d7-44f95eeb1c11)

**Comment by phanlezz** [comment]
I ran the unit and e2e test on my local machines (Win10/Win11). 

Unit Tests: The unit tests seem stable, no issues here in 20+ runs for both machines.

E2E: On my weaker machine, I got one failed test run out of 15, where the same test failed as in the one PR on main:

```
 FAIL app/codeCharta/ui/ribbonBar/searchPanel/mapTreeView/mapTreeView.level.e2e.ts (42.349 s)
  ● MapTreeViewLevel › NodeContextMenu › NodeContextMenu path should remain marked when hovering over another mapTreeView Element

    TimeoutError: Waiting for selector `[id='/root/sample1.cc.json/ParentLeaf/smallLeaf.html']` failed: Waiting failed: 30000ms exceeded

      at Timeout.<anonymous> (node_modules/puppeteer-core/src/common/WaitTask.ts:91:11)
```

> The failed test run was after windows locked itself during in-activity, so this result is not really conclusive. I will start another batch of runs.

**Comment by ViktoriaGordeevaVG** [comment]
That's the case for me as well, all tests have passed, and the timeout for the 3Dprint test has been increased.
