### ISSUE TITLE
Make camera zoom consistent

### ISSUE THREAD

**Issue by ChristianHuehn** [MaibornWolff/codecharta#3776]
# Feature request
## Description

As a user, I want a consistent way of zooming in and out so that I'm able to navigate around the map

## Acceptance criteria
- No modifier is hold
- - Camera zoom-in on mouse
- - Camera zoom-out on mouse
- Modifier is hold (Shift)
- - Camera zooms like zooming-in under the view cube (top right)
- - Camera zooms like zooming-out under the view cube (top right)

## Assumptions & Exclusions
Right now zooming in is working on the mouse and out is done via the cube functionality

**Comment by IhsenBouallegue** [comment]
- Control is already used to increase the speed. We can either override it or simply use something else. I tests with shift and it woks.
- if I understood correctly. Zoom to cursor as  the new default. Zoom to the middle of the screen (threejs's default) only when pressing a modifier key?

**Comment by ChristianHuehn** [comment]
👍  Shift is fine for me
