### ISSUE TITLE
Buildings without area metrics should be visible

### ISSUE THREAD

**Issue by CodeCharta** [MaibornWolff/codecharta#3780]
# Feature request
## Description
As a user I want to see all the buildings even if they dont have an area, so that I get a better feeling for my codebase

## Acceptance criteria
-  Buildings without an area metric should still be visible
- Everything on the interface should still show 0 no matter the implementation
- Only with feature flag
## Development notes (optional Task Breakdown)
https://github.com/MaibornWolff/codecharta/issues/358

## Open questions
We have multiple ideas on how to fix this:

1. Make a minimum area of 0.5 if this is possible in threejs
2. Multiple everything by 2 and add a minimum value of 1

**Comment by ChristianHuehn** [comment]
We enable it for experimental usage
