### ISSUE TITLE
Staging Environment for Visualization

### ISSUE THREAD

**Issue by ChristianHuehn** [MaibornWolff/codecharta#3819]
# Feature request
## Description

As a developer I want to have a staging environment to stop possible regression upfront and allow others to try new changes before they are released

## Acceptance criteria
- There should be an automated workflow to allow an stg deployment every time we push to main
- Visualization https://maibornwolff.github.io/codecharta/visualization/ should be accessible for example from https://maibornwolff.github.io/codecharta/stg/visualization/ 

## Development notes (optional Task Breakdown)
- [ ] 
- [ ] 
- [ ]

**Comment by phanlezz** [comment]
Now that a staging environment for visualization is set up, we need to discuss in which way we want an analysis version. I'm not sure if it makes sense to link a `*.jar` download, which then takes almost the same amount of work to use, as assembling the main branch locally.
