### ISSUE TITLE
Provide a way to view aggregated metrics per programming language

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#393]

**Comment by NearW** [comment]
If it's only for required for screenshotting / giving a quick overview, we can use a simple pie chart.

<img width="601" alt="screen shot 2019-03-08 at 08 48 06" src="https://user-images.githubusercontent.com/12533626/54015121-11651500-417f-11e9-816f-4b37c71caf98.png">

Slices of a pie could also be clickable to automatically start a treeview search, such as ".java" when clicking on the java-slice.

chart was done here: https://www.meta-chart.com/pie#

**Comment by Richargh** [comment]
Solved with #495
