### ISSUE TITLE
Provide a way to specify the project name of the merged file

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#394]
**When** I call `ccsh merge -p CoolProject foo.cc.json bar.cc.json` 
**Then** the project name of the merged file should be CoolProject no matter what the previous project names were.

**When** I call `ccsh merge -p CoolProject someFolder` 
**Then** the project name of the merged file should be CoolProject no matter what the previous project names in that folder were.

**When** I call `ccsh merge foo.cc.json bar.cc.json blub.cc.json` 
**and** the project names for bar.cc.json and blub.cc.json don't match the name from foo.cc.json
**Then** an error message should tell the user which project names don't match and that he can use the `-p` switch to specify a new project name.

**Comment by alexhunziker** [comment]
I have noticed that in the test cases of the Project Merger it says:
```
context("merging project with different names") {
            val projects = listOf(
                    Project("test1"),
                    Project("test2")
            )

            it("should throw a exception") {
                val firstProjectName = ProjectMerger(projects, nodeMergerStrategy).extractProjectName()
                assertThat(firstProjectName, CoreMatchers.`is`("test1"))
            }
        }
```

But it is not checking if an exception is thrown. I also checked: there is no error thrown if the project names do not match, but instead the first project name is taken for the merged project.

What is the expected behaviour here?
