### ISSUE TITLE
New search UI

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#400]
It's currently a bit confusing which settings are stored in the cc.json and which aren't. I'd like to work on a new UI that places all cc.json things close to each other. 

That would mean a new menu, probably in the top-left corner, that includes the `TreeView`, `Blacklist` and `marked packages`. A new feature that could be added are special `views` that show only specific buildings. It can be opened by clicking on the search icon or using the command `Shift+Shift`.

**Comment by alschmut** [comment]
- I understand that its confusing what's stored in the cc.json and what's not. I guess the new settings object from #178 solves that problem a bit, as all that is currently stored in the cc.json will be placed inside the `setting.mapSettings`, but of course thats just the unseen backend..
- What do you think about a small pop-up when downloading/exporting a map and asking the user which objects should be included and which not... At least this would show the user (without looking into the huge cc.json file) what will be stored.
- Regarding your last point: I didn't get it 😄 I think you need to explain that in more detail or with a short sketch

**Comment by Richargh** [comment]
1.
2. I like that idea. That would certainly make it clearer for **save**. I wonder if we should indicate what comes from the map also after **load**ing a map.
3. I don't if I should explain it with a sketch. Last time we did a design workshop the ideas were better because I did not anquor anchor anyone.

**Comment by alschmut** [comment]
2. Good point! I also sometimes clicked the save-button by accident. Another pop-up would solve that. Any kind of indication, what was loaded, is a good idea, I guess. Not sure if a pop-up is the right solution. Maybe we should rather think about a nicely designed notification.

**Comment by alschmut** [comment]
@Richargh Isn't this almost the same as #526? We would just need to add listing the markedPackages in that new tab-view (Search, Hide, Exclude, Marked) as well.

**Comment by Richargh** [comment]
It is a bit more ambitious than #526. 

> It's currently a bit confusing which settings are stored in the cc.json and which aren't. I'd like to work on a new UI that places all cc.json things close to each other.

We fixed this with the new download file menu: `a small pop-up when downloading/exporting a map`

> That would mean a new menu, probably in the top-left corner, that includes the TreeView, Blacklist and marked packages. 

That is #526 

> A new feature that could be added are special views that show only specific buildings. It can be opened by clicking on the search icon or 

Views is a feature that we don't currently have. The idea is to be able to quickly switch between different filtered views of the map. Helpful for audits.

> using the command Shift+Shift.

That would basically look like the IntelliJ search which can find through a lot of stuff.


In total we have most of these features or will implement the useful features when time comes. I'll close this bag of UI ideas and open individual issues if useful.
