### ISSUE TITLE
Histogram for metrics

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#401]
To get a quick overview it would be beneficial to get histograms per metric. Where/how should that be displayed and how interactive can it be?

**Comment by alschmut** [comment]
I think first and easier implementation isa non-interactive one in the legendPanel like this:
(imagine blue were yellow, and grey were red)
<img width="40%" src="https://user-images.githubusercontent.com/23529226/53607895-8ac99a00-3bb8-11e9-96b9-211e07b3a6c3.jpg">
If we can make it interactive without too much effort, we could substitute the current colorSlider...

**Comment by Richargh** [comment]
Looks good to me. But don't we need that for all the metrics: area, height and color?

I don't think the legend should be interactive. I wouldn't expect that from a legend. If we place the histogram somewhere else and make it interactive then hovering over an area in the histogram should highlight all the affected buildings in the CodeMap.

**Comment by BridgeAR** [comment]
I definitely like the idea of the histogram for the color metric. We could in fact replace our current slider with such histogram in our color metric dropdown. That would allow the user to identify an ideal placement much easier than without the information.

Other metrics could also profit from the histogram but there's no point in making it interactive. As such, I would concentrate on the color metric first and think about the other metrics later.

**Comment by BridgeAR** [comment]
@shaman-apprentice this might be an interesting issue for you, since you recently had a closer look at the slider :-)

**Comment by BridgeAR** [comment]
The histogram could also indicate the number of buildings per color "somewhere" (maybe below the slider? Next to our future color selector?).
