### ISSUE TITLE
Custom Scenarios

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#402]
Currently CC supports scenarios. These are hardcoded into the visualization and react to specific metrics.

To give more flexibility we should consider allowing an auditor to define custom metrics. There are several things to consider:

* what is part of a scenario? Metrics, metric options like color sliders, filters ...?
* Where is it stored? in the cc.json? But then the auditor has to create new scenarios for every map.
* How are scenarios created in the ui and how are they selected? Currently they are a bit hidden and cannot be selected without opening the ribbbon.

**Comment by alschmut** [comment]
> what is part of a scenario? Metrics, metric options like color sliders, filters ...?

Good question. I guess that depends on the users.
> Where is it stored? in the cc.json?

I suggest to give the user the option to export and import a separate `scenarios.cc.json` file
> How are scenarios created in the ui and how are they selected?

We could set an `ScenarioManagerPanel` into the sidebar, which displays scenarios with its name as a clickable list item. It could look similar to the blacklist-list and provide round buttons to change or delete these. Adding and changing scenarios could use a pop-up.

**Comment by Richargh** [comment]
Great idea to be able to export/import it as a separate file. And the `ScenarioManagerPanel` is also very good. I don't think we should place it in the sidebar though.

Currently we can select scenarios in the ribbon bar. We have to open the ribbon to select a scenario, which is a problem because it requires an additional click. But that is a separate issue.

It would make sense to place a minimized ScenarioManagerPanel in the same spot.

**Comment by Richargh** [comment]
We'll implement custom scenarios with #675
