### ISSUE TITLE
When I start visualization providing parameters for file, metrics, colors, i have to click "invert colors" twice to get the (not inverted) colors displayed correctly

### ISSUE THREAD

**Issue by silasg** [MaibornWolff/codecharta#42]
v 1.3.2

**Comment by mrpatpat** [comment]
Using `<URL>?file=sample.json&neutralColorRange.flipped=false&neutralColorRange.from=10&neutralColorRange.from=12` in v1.5.1 should display the correct inversion state and clicking the checkbox after that should draw the changes immediately.
