### ISSUE TITLE
Merging two integer values results in a floating point value

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#45]
From https://github.com/MaibornWolff/codecharta/pull/44:

Merging two integer values results in a floating point value. I do not think this will cause further problems in visualizing the data but it should result in an integer value just to be formally correct.

I merged this file with itself:
{ "projectName":"Res", "apiVersion":"1.0", "nodes": [ { "name":"root", "type":"Folder", "attributes":{}, "children":[ { "name":"A", "type":"File", "attributes":{"a":0, "b":1}, "children":[] } ] } ] }

result has "b":1.0

**Comment by mrpatpat** [comment]
CC now accepts floats since it doesn't change anything in logic. To ensure this stays a feature I also added a test case for this.
