### ISSUE TITLE
Reformat complete Codebase with prettier

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#450]
Depends on #178

**Comment by NearW** [comment]
printwidth 140 is way too high. 100 or 120 sounds better.

**Comment by alschmut** [comment]
Well, I am fine with 140, as nobody of us actually wants to print it on a DIN A4 paper and all have screen which can handle that, but I am also fine with 120.

**Comment by NearW** [comment]
Then I assume that the IntelliJ-Prettier-Plugin is not working properly. I read some bad reviews about it as well. When doing long constructors, the plugin is not breaking lines correctly.
