### ISSUE TITLE
File extension distribution for  metrics

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#495]
The chart should show the **distribution** of file extensions in the code base, i.e. how much Java/JavaScript/C# we have. We just use the file extension to determine the programming language. 

F.ex. I can see that Java has 30% of the LoC and  JavaScript has 70% of the LoC. But I also see that Java has 70% of mcc and JavaScript has 30% of the mcc. --> We decided to have one distribution chart but be able to switch the metric displayed. The default metric should be the initial size metric.

~~I can hover with the mouse over the Java distribution and CC shows me all Java files.~~ We decided to move this to issue #545

**Comment by alschmut** [comment]
Does that mean you want 3 pie charts? And did you already think about a place to put it/them?

**Comment by Richargh** [comment]
What's the situation here? Do you need feedback from me or someone else? I'd really like to get it out to our users.
