### ISSUE TITLE
Standalone does not open a window when I double click a building

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#496]

**Comment by alschmut** [comment]
I guess this is, because the project you used does not contain any links. Did you check that? Because I just tried a few projects and it worked..

**Comment by alschmut** [comment]
@Richargh did you check this again, does the "bug" really exist?

**Comment by Richargh** [comment]
Haven't gotten around to it yet. That's why it's still not in the backlog.

**Comment by Richargh** [comment]
not reproducable :)
