### ISSUE TITLE
Cancel Button leads to infinite loading in CC

### ISSUE THREAD

**Issue by JaiJoPa** [MaibornWolff/codecharta#498]
# Bug

## Expected Behavior
  Cancel the File Chooser should not lead to infinit loading

## Actual Behavior
  By clicking on Cancel, CC loads infinit

## Steps to Reproduce the Problem

  1. load a .cc.json File
  2. open the File Chooser 
  3. click on Cancel Button

## Specifications

  - Version: 1.24
  - Platform: any
  - Subsystem: any
  - Browser: Chrome (not in Safari)

**Comment by alschmut** [comment]
Maybe we can fix this, by settings the default value of `CodeChartaController.isLaodingFile` to `false`.
