### ISSUE TITLE
Create CodeCharta GitHub user for releasing

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#519]
# Feature request

## Description

Currently we always use @mrpatpat's GitHub user to do our releases. We should consider creating a separate CodeCharta GitHub-Account. The user will need some kind of access token, which is currently stored in @mrpatpat's account.

- [x] get email address
- [x] create githubaccount
- [x] create npm account
- [x] authorize/add GH account to GH-team
- [x] Generate GH Token and add them to Travis CI Secret Variables
- [x] authorize/add npm account to npm-team
- [x] Generate npm Token and add them to Travis CI Secret Variables

Check only these rights for the GH Token:

![image](https://user-images.githubusercontent.com/2622069/58245087-4e8b7d00-7d54-11e9-8a98-4fd3452e0cdb.png)

Relevant links:
[Travis Settings](https://travis-ci.org/MaibornWolff/codecharta/settings)
[NPM Team](https://www.npmjs.com/settings/maibornwolff/members)
[GH Token Settings](https://github.com/settings/tokens)

**Comment by alschmut** [comment]
We need to wait here, until the CodeCharta NPM account is in the MW team, so it can access the NPM codecharta* projects

**Comment by alschmut** [comment]
I just updated the the NPM token. So the NPM-codecharta account should publish with the next release.

**Comment by Richargh** [comment]
So this issue now "In Review" and we'll wait for the release? :)

**Comment by alschmut** [comment]
> So this issue now "In Review" and we'll wait for the release? :)

Yes ;)

**Comment by alschmut** [comment]
Finally NPM is also published by our codecharta user

<img width="50%" src="https://user-images.githubusercontent.com/23529226/60333439-5238a200-9999-11e9-9afa-ac66cabbe264.jpeg">
