### ISSUE TITLE
Add Sonar Dotnet Parser to SourceCodeParser

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#522]
# Feature request

Add [Sonar dotnet](https://www.sonarsource.com/products/codeanalyzers/sonarcsharp.html) code to the SourceCodeparser. It's free, [open source](https://github.com/SonarSource/sonar-dotnet) and hopefully there are maven sources available.

## Description

Add Sonar dotnet Plugin code to the SourceCodeparser that analyzes the metrics 

* [ ] complexity 
* [ ] functions
* [ ] comment_lines
* [ ] cognitive_complexity
* [ ] ncloc
* [ ] classes
* [ ] complexity_in_classes
* [ ] statements
* [ ] bugs
* [ ] duplication

**Very Important technical feature**: no expects the kotlin ccsh to require dotnet. Please make the parser optional, depending on if the user has dotnet installed.

**Comment by Richargh** [comment]
@alexhunziker can you add all the metrics that the Java Plugin also has?

**Comment by alexhunziker** [comment]
Just an update on this one: The sonar-plugin for dotnet has 2 parts, an analyzer written in C# that generates the metrics (and does the other code analysis) and the java "plugin" which basically just imports the analysis results. This is different from the way the TypeScript plugin works in so far, that the sensor in the plugin does not (according to my current knowledge) start the analysis.

Therefore more research is needed as to how the actual analysis is triggered with the dotnet plugin. This may take some time as i have zero knowledge about C#

**Comment by Richargh** [comment]
Hmm, that is an unfortunate constellation. Please keep at it. JetBrains provides an idea for C#, called [Rider](https://www.jetbrains.com/rider/), but maybe IDEA can already handle C#/VB.NET.

**Comment by alexhunziker** [comment]
Today Ben and I have looked into the C# plugin again:
- As stated before, the plugin has two parts; the actual plugin (java) only imports protobuf files generated by the so-called dotnet-analyzer (c#-code), all the metrics are stored in the protobuf files.
- The dotnet-analyzer  can be built as a .dll library. This file is also present in the sonar-dotnet plugin jar file. However there is no apparent entry point to start the analysis (at least we found none)
- If the user uses the the plugin, he will use the sonar-scanner-msbuild, which works as documented on https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+MSBuild. When we use this scanner, the project will be compiled, and the metrics directly imported into sonarqube. There is no way to fetch the protobuff files along the way.

Given what we have learned, integrating this into the analysis would be a big task. We have no idea where to start. It is also possible that the solution would in the end still require the user to do a preliminary analysis before using the ccsh.

**Comment by Richargh** [comment]
Ok. We'll close this issue for now. My impression is that we've had good success with using Sonar directly, so that's a usable workaround for now. I'd like to reopen this if a new approach pops into your head @alexhunziker or @NearW. The problem that Sonar has is that the code needs to be compilable, which is somewhat of a problem... :|

**Comment by Richargh** [comment]
Next steps:

1. Find a free or not-too-expensive program that generates all metrics we need and provides some form of structured export
2. Use the Roslyn Compiler from Microsoft and implement all Metrics by hand: https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Syntax-Analysis
3. Write a Java-Program using sth like Antlr and implement all metrics by hand
4. Another attempt with the Sonar C# Plugin
