### ISSUE TITLE
Save Dialog

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#523]
# Feature request

It is somewhat confusing that clicking on the save dialog immediately saves a file. Also it is unclear what items are stored in the cc.json in addition to the code. 

## Description

Please add a dialog that is opened when the user clicks on the save button. An idea is included below.

![grafik](https://user-images.githubusercontent.com/28268662/57938365-59638f00-78c8-11e9-853c-664111b45284.png)

**Comment by alschmut** [comment]
@Richargh We should extract this into more issues implementing...
- the createdOn-Date, as this requires all importers to be updated
- the updatedOn-Date, which kinda depends on the createdOn-Date to be present to actually make sense
- the standalone *save-in-existing-file*-button

#### Questions/Notes:
- Implementing a *Save-As*-button into the browser is not easy at all. Are you okey with the current solution to set a filename directly inside the dialog-pop-up (see screenshot).
- The blacklist-object will be decided into excludes and hides in the next step
- The dialog also allows you to select and unselect some of the objects. But it always keeps nodes and attributeTypes (if existing) and empty objects are always unselected

![image](https://user-images.githubusercontent.com/23529226/58480214-c5a88300-8151-11e9-925c-c2a7bdae6f18.jpeg)

**Comment by alschmut** [comment]
New current state
![image](https://user-images.githubusercontent.com/23529226/58490200-9fd8a980-8164-11e9-8cb7-cbcea36f28ba.jpeg)

**Comment by Richargh** [comment]
Nice. It's progressing nicely.

* Please add an explaining label before the checkboxes. Something like "included in the file is". 
* Let's rename it from "Download File" to "Export File". Then it's the same for standalone and browser version. Plus we can add a "Save" Dialog to the standalone later.
* I am not sure about those numbers: "6 Nodes", "3 Edges", etc. It suggests that we can change the number of edges. Can you write it in brackets instead? Something like: "Edges (3 in total)".

**Comment by alschmut** [comment]
![image](https://user-images.githubusercontent.com/23529226/58505631-52b8ff80-8185-11e9-8220-f8b7454a247a.jpeg)

**Comment by alschmut** [comment]
![image](https://user-images.githubusercontent.com/23529226/58574887-f1eaff00-8238-11e9-96d4-e565f196b308.jpeg)

**Comment by Richargh** [comment]
Ship it 👍 I think we can tweak the naming a bit to make it more clear but I want customer feedback for that. For example "Nodes" is very confusing to a user because CC never displays the name node anywhere. But writing "Files" instead would be even more confusing. Let's ship it and see what they suggest.
