### ISSUE TITLE
Move File Settings to File Bar

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#525]
# Feature request

Let's incrementally change our UI. First stop, move the file bar to above the metrics, so it takes on even more of a global spot. See attached screenshot.

![grafik.png](https://images.zenhubusercontent.com/5cd16a929795a865159e70ff/55ff458e-be05-4c32-8eba-b8571f7d17b6)

**Comment by alexhunziker** [comment]
Which one do you prefer, having the labels centered or aligned left?
Rocket for center, Eye for left ;)
![aligned](https://user-images.githubusercontent.com/20796577/59513450-260e2300-8ebb-11e9-8c22-ac2ab2a71b94.PNG)
![centered](https://user-images.githubusercontent.com/20796577/59513451-260e2300-8ebb-11e9-82d1-2cbf5be51f9d.PNG)

**Comment by alschmut** [comment]
- I actually even think we should remove the the labels. It just takes too much vertical space.
- And I would make the selects less wide, especially the mode-select (as its always the same text in there)

**Comment by Richargh** [comment]
* Removing the labels sounds like a good idea. 
* Can we also reduce the font so it takes less space than the metrics bar?
* Can we change the dropdown to a single-select button group like below? No images, just the text Single, Multi, Double.
* Actually, do we even need single, multi, double? We could remove ~single~, because that's basically multi with only one file selected. Then we don't even need the `single-select button group` from above. We only need a delta-toggle, which appears disappears the file to delta with.
* can we color the file bar a bit differently? Make it darker? Or add some other visual change to differentiate it from the metrics?

<img width="122" alt="Screenshot 2019-06-14 at 18 08 01" src="https://user-images.githubusercontent.com/28268662/59522609-69728c80-8ecf-11e9-9333-3e3b604b3fc7.png">

**Comment by alschmut** [comment]
- I think removing the single-select is worth a try. Only "problem", that comes with it, when you want to change to another map, you need to select another map and unselect the current map.

**Comment by alexhunziker** [comment]
If we remove the single mode the file setting bar would look something like this, right?

![grafik](https://user-images.githubusercontent.com/20796577/59591216-eed38800-90ed-11e9-93eb-66fd5566acef.png)

**Comment by Richargh** [comment]
@alschmut makes a valid point. The default is probably single-select and it would annoy our users to always have multiple mode and they want to switch between different maps. Is there a three state switch in Angular?

**Comment by alexhunziker** [comment]
I found this https://material.angular.io/components/button-toggle/overview. The button toggle is a multi state switch component in Angualr Material.

Regarding the labels: While I see the advantage of saving vertical space by removing them, i think we thereby also lose some information; i think that the Reference/Comparison/Mode labels help to unsderstand the controls, don't you think?

**Comment by Richargh** [comment]
> Regarding the labels: While I see the advantage of saving vertical space by removing them, i think we thereby also lose some information; i think that the Reference/Comparison/Mode labels help to unsderstand the controls, don't you think?

Let's remove them for now. The default view is basically a single file select, and next to it our three buttons for single, multi, delta. The user does not even see the other file select, unless he clicks on delta. That should make it obvious to the user what the effect will be.

Have you tested a different, perhaps darker background and smaller fonts to differentiate it from the metrics bar? 

> we could just put 3 conventional buttons without space between them there...

I think having a widget like this would be a great feature because it shows the modes and does not hide them from the user. I think it would be worth it to implement such a custom widget.

**Comment by alexhunziker** [comment]
![grafik](https://user-images.githubusercontent.com/20796577/59683439-78f81b00-91d8-11e9-9e3f-42a7b69e808a.png)

 what do you think? (except that the vertical alignment of the text in the button is still a bit off)

**Comment by Richargh** [comment]
> what do you think?

Ship it :)

**Comment by alschmut** [comment]
> what do you think?

I quite like this triple-button! 👍 
- The import and download button are quite far from each other
- Do you want to set a small height for the buttons?
- And I would use a width of 200px instead of the 300px for the revision-chooser select dropdown
- When changing the mode, some SCSS transitions seem to interfere

Regarding the import and download button
- what about removing the green circular background and just put the icon there like suggested in the above draft. Then we could also make the icons a but larger again.
- Should we change the download button to a floppy disc icon? I still sometimes press the wrong button, as I'm still not fully used to the download-arrow..

**Comment by Richargh** [comment]
> * Do you want to set a small height for the buttons?

That could create a better look. 👍 

> what about removing the green circular background

I think buttons should always be identifiable as buttons. Also we currently have green circular button design, so we would need to change all buttons to look the same way.

> * Should we change the download button to a floppy disc icon? 

In the standalone we might have two buttons soon. One floppy for "save open file", one download arrow for "Download to a different location". Would that confuse you more? Or should we only display the floppy, even on standalone, and ask the use if he wants to "save" or "download"?

**Comment by alschmut** [comment]
> I think buttons should always be identifiable as buttons. Also we currently have green circular button design, so we would need to change all buttons to look the same way.

Yea I know, just as a try. The buttons "folder" and "floppy" in the upper left corner of an application are quite clear to everybody. And we could set the color of the icons to angular-green.

> In the standalone we might have two buttons soon. One floppy for "save open file", one download arrow for "Download to a different location". Would that confuse you more? Or should we only display the floppy, even on standalone, and ask the use if he wants to "save" or "download"?

I would actually think of something like this: Both, browser and standalone have one floppy icon, which opens the "SaveDialog" and in there are the following buttons:
- browser: "Download" button
- standalone:
    - "Replace" button, if file already/still exists on fileSystem, else button is disabled
    - "Save" button, if user changed the download-name or file doesn't exist on fileSystem, else button is disabled

**Comment by Richargh** [comment]
> I would actually think of something like this: Both, browser and standalone have one floppy icon, which opens the "SaveDialog" 

Depending on how often the user wants to save this flow might be inconvenient.

**Comment by alschmut** [comment]
> Depending on how often the user wants to save this flow might be inconvenient.

Yea, okey then let's keep it like it is for now, and we can think about that when implementing the standalone save-feature

**Comment by alexhunziker** [comment]
> And I would use a width of 200px instead of the 300px for the revision-chooser select dropdown
I actually prefer 300px, since in multi-mode allows to display more of the selected maps.

> Do you want to set a small height for the buttons?
@alschmut The tripple-button or the save/open ones?

Regaring the icons i would suggest keeping the current icon for the (current) download functionality and using a floppy disk icon for the standalone save function only.

**Comment by alschmut** [comment]
> I actually prefer 300px, since in multi-mode allows to display more of the selected maps.

Alright, what do you think about the following picture? The tripple button on the left and the selects with a white background?

>  I reduced the size of the tripple-button by 4px

Looks good. now 👍 

![image](https://user-images.githubusercontent.com/23529226/59701164-e0b86100-91ec-11e9-86ae-ec0a67fc1825.jpeg)

**Comment by alexhunziker** [comment]
Looks good, i like the white background :+1:

**Comment by Richargh** [comment]
Awesome. Now there's an obvious difference between the file and metrics bars. And I think the white background for the dropdowns meshes really well. 👍

**Comment by Richargh** [comment]
What happens when I make the window very small? Does the delta dropdown disappear or does CC have a minimum window width?

**Comment by alschmut** [comment]
> What happens when I make the window very small? Does the delta dropdown disappear or does CC have a minimum window width?

Currently it all just disappears, like the metric-sections

**Comment by alexhunziker** [comment]
Should we set a minimum window width?

**Comment by alschmut** [comment]
> Should we set a minimum window width?

I think we should rather investigate and find a good solution for smaller windows

**Comment by Richargh** [comment]
> I think we should rather investigate and find a good solution for smaller windows

I don't think there are that many choices:

* min. window width
* redistribute content somehow fluently until a min. window width is reached :)
* Indicate to the user that he content is hidden

I'll create a new issue to adress this for our two bars.
