### ISSUE TITLE
New Search Bar

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#526]
# Feature Request

Let's incrementally change our UI. Next stop, move the search bar next of the metrics, so it is immediately obvious to our users where to search for stuff. Next to the search field are three buttons. They behave like tabs and allow us to switch between tree view, hidden items and exclude items. The search bar can also be opened independantly from the metrics.

![grafik](https://user-images.githubusercontent.com/28268662/57947562-840d1200-78df-11e9-9ab8-9c2bf9f8cc17.png)

The search + scenario + metrics bar might become a bit wide. That's ok. But please also add a helpful little `...` or something to the right side of the bar if some elements are hidden.

Please change the symbol in the hide and exclude list that you use to remove something from that list. The users think that the trash can symbol completely removes the excluded or hidden buildings from the cc.json. What if we instead present the user with a `regular eye` icon on the **left** side of the hidden/excluded entry? On the left is normally the hide or exclude symbol but that is redundant in the hide/exclude list anyway.

**Comment by alexhunziker** [comment]
![grafik](https://user-images.githubusercontent.com/20796577/59758535-693b0e00-928e-11e9-9f3b-ccf81bd1f8c3.png)

The 3 tabs will then have the following content, did I get that correct?

**Comment by Richargh** [comment]
> The 3 tabs will then have the following content, did I get that correct?

Yes. The buttons have the same behavior as our single/multi/delta buttons. With one addition. The hidden and exclude counter needs to be there somewhere as well. And in the future we might expand this to also include something like "groupings of selected buildings". We have no story for that, it's just an idea.

* Something I just noticed while looking at your screenshots. It's super convenient to have the search field at the top. But the search field does not apply to all three tabs... It's only useful for the treeview really. It's strange to have it above all tabs. Interestingly the search bar in IntelliJ and MacOs functions differently but I have no idea what to do with that information.

> The 3-dot dropdown menu would then be placed next to the search bar, wouldn't it?

Yes.

**Comment by alexhunziker** [comment]
How about we put the 3 buttons to the left & place an input field next to them, similarly to the fileBar, the behaviour of the bar would change according to what button is selected? Something like this:
- Tree View: Search
- Hidden Patterns: A field to enter new patterns to hide
- Excluded Patterns: A field to enter new patterns to exclude

**Comment by alschmut** [comment]
> How about we put the 3 buttons to the left & place an input field next to them

Yes, thats sounds good 👍 Lets also do the triple-selector again?

> similarly to the fileBar, the behaviour of the bar would change according to what button is selected?

I think the search bar always fits. Following use cases:
- Tree View Tab: User searches nodes -> TreeView filters and CodeMap highlights searched nodes
- Hidden Patterns Tab: User searches nodes -> CodeMap adapts (as it were hidden) and button to add to blacklist appears
- Excluded Patterns Tab: User searches nodes -> CodeMap adapts (as it were excluded) and button to add to blacklist appears

**Comment by alschmut** [comment]
What I just realised is, the search icon, is quite important and it should be easy recognizable for the user. Just as an idea, how about replacing the TreeView icon with the search icon? Is it too hidden inside the buttons then?

**Comment by Richargh** [comment]
* Tree View: Search + three dots
* Hidden Patterns: A field to enter new patterns to hide + ~three dots~ turn to button + hide on enter
* Excluded Patterns: A field to enter new patterns to exclude + ~three dots~ turn to button + exclude on enter

Isn't the search icon easily recognizable because it's an input  field with a "search lens" icon? When clicking into this input field the view from the triple-selector is opened: treeview, hidden or excluded. When the user clicks on the treeview icon the treeview is also openend. Seems somewhat redundant. So suppose we remove the treeview icon and only display the search lens: is it still obvious to the user how to open the treeview?

**Comment by alschmut** [comment]
> When the user clicks on the treeview icon the treeview is also openend. Seems somewhat redundant. So suppose we remove the treeview icon and only display the search lens: is it still obvious to the user how to open the treeview?

Thats what I asked as well ;) I think we'll need to try and take a visual look..

**Comment by Richargh** [comment]
I just checked the user evaluation results that we received via mail on April 1st and added a couple things to the issue.

**Comment by alexhunziker** [comment]
![grafik](https://user-images.githubusercontent.com/20796577/60323644-ea775c80-9982-11e9-86bf-61fdfcfb3b14.png)

**Comment by Richargh** [comment]
@alexhunziker I just had an idea and I am not sure if it was suggested in the weekly 2h ago :) 

What if we make the search bar into a search field and place it below the distribution bar? Then it becomes just this free-floating search field with our three tree/exclude/hide icons in the top left corner. Then it won't overlay any metrics or distributions when you open it.

**Comment by alexhunziker** [comment]
![grafik](https://user-images.githubusercontent.com/20796577/60525644-11b98b00-9cef-11e9-82d9-5bdcfa90b2b0.png)

How about we put the free floating search/blacklist box where the viewCube is, and put the viewCube in the bottom right corner? I had the impression that if we put the box in the top-left corner, it was distracting too much...

**Comment by Richargh** [comment]
Can't we leave it in the left upper corner and only display the search field. It only becomes big once we open treeview/exclude/hide. Take a look at this [leaflet example](https://labs.easyblog.it/maps/leaflet-search/examples/simple.html), which has a non-distracting search icon. It's on the right but good for demonstration purposes. :)

**Comment by Richargh** [comment]
My idea goes like this:

* We place the search bar in the top left corner
* You can only see treeview/exclude/hide and a small search field
* You click into the search field and the field expands so you can see more characters
* You can manually expand treeview/exclude/hide, similar to the ribbon bar, by clicking on something

**Comment by alexhunziker** [comment]
> You click into the search field and the field expands so you can see more characters

I will implement it, and then we can see how it looks :)

**Comment by Richargh** [comment]
I'm very interested to see the new search bar. One thing I just noticed: can you place the search field on the left side of the buttons? Like in the mockup.

**Comment by alexhunziker** [comment]
![grafik](https://user-images.githubusercontent.com/20796577/60883104-93f30380-a249-11e9-8528-e16074a925a1.png)

This is what I did based on the discussion on Friday. It is not finished yet (the tripple button needs to be smaller, spacing is not optimal yet, ...), but in general this is how it will look like. Do you like it or should we use the floating panel as shown on Friday?

**Comment by alschmut** [comment]
Thanks @alexhunziker I think we should stick to this idea 👍 
- The input field placeholder should be grey
- How about the shadow on bottom of the panel? There should be an existing CSS class you need to add to the new html-panel
- What about the dots instead of the number at the tab buttons?
- Is the height of the new panel fixed or is it endless, depending on the list inside? Maybe it makes sense to be able to adjust it manually between a given range..

**Comment by alexhunziker** [comment]
thanks for the feedback 👍 
1-3 are things I wanted to do as well, I just wanted to know first if we are sticking to the current approach or not :)

> Is the height of the new panel fixed or is it endless, depending on the list inside? Maybe it makes sense to be able to adjust it manually between a given range..
That's the idea, but it is not implemented yet

**Comment by Richargh** [comment]
Visually it looks good and exactly what we discussed. I tried running it on my machine to see how it feels but you haven't commited yet :( 

Anyway :) Please continue with your work and also post how the extended ribbon bar looks. Perhaps we'll then follow @alschmut suggestion from long ago and make each field indivually openable ;)

**Comment by alschmut** [comment]
@alexhunziker awesome :)
