### ISSUE TITLE
Metric Attribute list side bar

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#527]
# Feature request
Let's incrementally change our UI. Next stop, move the metric attribute list to the right side. 

Currently the metric attribute list can be opened by clicking on the file path indicator. In the settings this is called the detail panel. This issue replaces this detail panel and it can be removed.

## Description
The new metric side bar is useful when users want to check out other metrics beside the three selected ones for size, height and color: "this building has high complexity, bad line coverage but how often is it actually changed?". The features are:

- [x] Is on the right side
- [x] opens if a user has selected a building (orangy), closes if she deselects a buildings or if he presses the close symbol
- [x] will only show metrics for the selected building
- [x] it can be scrolled, just like before, to check out all the other metrics.
- [x] the name and basic metrics are "frozen", so we don't lose this information while looking at other metrics
- [x] the window should be horizontally very slim
- [ ] ~If the user clicks on the file path it opens vertically, like a tree view. Unlike a tree view it can only be expanded fully and minimized fully. And unlike our regular tree view on the upper left side it does not~
- [x] Show the URL in a tooltip when hovering the nodeLink icon
- [x] Hide AttributeSideBar onFileSelectionStateChanged and onBlacklistChanged
- [x] the full path requires a lot of horizontal space. So we won't show the complete file path and instead only the fitting parts. The path is now word-wrap and shown over multiple lines.
- [x] Fix scrolling behaviour when fixed header is getting longer due to long strings visible over multiple lines.
- [x] Move the viewCube component when the sideBar is opened to be on the left of it (see comment below)
- [x] Move the legendPanel when the sideBar is opened to be on the left of it (see comment below)
- [x] For the above metrics table: Show two metrics in a row (see comment below)
- [x] Move the link icon next to the selected nodename
- [x] Move the close icon to the top right corner
- [x] Color the delta value background box according to the `node.deltas["theMetric"]` and `settings.appSettings.invertColors` in light green or red. This would currently mean 4 times duplicated code inside the html file.

 show the complete structure, but only the path to this specific file.

The result looks something like this:

![Metric-Bar](https://user-images.githubusercontent.com/28268662/62372104-e1a41880-b536-11e9-89a2-16af135b3bbe.png)

While I do like the radial buttons proposed in the screen shot I think we should implement these buttons with a later story.

## Inspiration

I was inspired by this UI mockup:

![UI-Refactoring](https://user-images.githubusercontent.com/28268662/62371161-6a6d8500-b534-11e9-8ee8-9e9fd3bcb923.png)

**Comment by Richargh** [comment]
I updated the description.

**Comment by alschmut** [comment]
@Richargh this looks awesome! A lot better than a simple key-value table.

- If I get it right, it's worth to mention that the AttributesSideBar will only show metrics for the **selected** building, which I think is a really nice solution, as we always show the 3 hovered metric values next to the metric-chooser.
- I am not yet convinced to "duplicate" the treeView though.

**Comment by Richargh** [comment]
I updated the description :)

> * only show metrics for the selected building 

--> yes

> * I am not yet convinced to "duplicate" the treeView though.

Wasn't the intention. I only wanted to show the path to the selected file using the vertical space instead of the horizontal space. Instead of showing the path like this:

/root/de/maibornwolff/codecharta/visualization/app/settings/services/foo/service.spec.ts

we can show it like this:

root
  de.maibornwolff.codecharta.visualization --> compatacted because the folders are empty
   app
      settings
         services
           foo
             service.spec.ts

**Comment by alschmut** [comment]
@Richargh I couldn't wait to start implementing this issue 😄

Here is a current state of an AttributeSideBar:
- Having the primary metrics (inside the upper box) side by side, doesn't work well for long metric names and when showing the delta values. Thats why they are below each other.
- The path is not implemented as requested yet.
- The secondary metrics (the below box) is scrollable
- The left upper cross closes the panel and the right upper external link icon opens the file using the provided weblink

#Ideas 
- Instead of the delta values shown inside the brackets, a similar approach to #696 could lead to a cleaner look using coloured boxes.
- The legendPanel is (again) distracting at its current position...
- How do we wanna display long file names?

In single mode:
![Screenshot 2019-08-25 at 00 36 50](https://user-images.githubusercontent.com/23529226/63643441-76caa500-c6d0-11e9-9f7d-5ffa2174ad6b.jpg)

In delta mode:
![Screenshot 2019-08-25 at 00 40 13](https://user-images.githubusercontent.com/23529226/63643462-ed67a280-c6d0-11e9-9407-c5f915771da7.jpg)

**Comment by Richargh** [comment]
@alschmut what happened to #693 and #529 ? Don't you work on these issues as well?

**Comment by Richargh** [comment]
as for the layout: I like the visuals. It's nicely split up between top and bottom. 

> Having the primary metrics (inside the upper box) side by side

Hmm. What about placing the symbols with their values side by side but the potentially long metric names under their symbols? 

|  (symbolArea) (valueArea) (deltaArea) (nameOfArea) |  (symbolHeight) (valueHeight) (deltaHeight) (nameOfHeight)  |
|---|---|
|   |   | 

becomes

|  (symbolArea) (valueArea) (deltaArea) |  (symbolHeight) (valueHeight) (deltaHeight)  |
|---|---|
| (nameOfArea)  | (nameOfHeight)  |

**Comment by alexhunziker** [comment]
> The legendPanel is (again) distracting at its current position...

How about we just move the viewCube and the legend Panel to the left, so that they are not covered by the side bar, something like that:

<img width="1552" alt="sidebar_mockup" src="https://user-images.githubusercontent.com/20796577/63947337-037db600-ca77-11e9-889f-5b8e6d87e068.png">

**Comment by alschmut** [comment]
New current status:
- The link icon and the close icon are moved
- The metric values have a grey/green/red background

![Screenshot 2019-09-14 at 20 09 13](https://user-images.githubusercontent.com/23529226/64912159-93845680-d72b-11e9-8a0a-4ee748711519.jpg)
![Screenshot 2019-09-14 at 20 09 05](https://user-images.githubusercontent.com/23529226/64912160-93845680-d72b-11e9-9224-98e65bd5b1cb.jpg)

**Comment by fatihi** [comment]
I would actually prefer if the sidebar closed when a building is not selected. I moved up the bug that keeps the selection when settings are changed and would prefer if both this bug and the other one are released together.

**Comment by alschmut** [comment]
@fatihi 

@NearW and me just fixed the bug on a separate branch. After some new tests are added and a review both are ready to merge.

**Comment by fatihi** [comment]
Oh that's nice! In that case could you link them together?
