### ISSUE TITLE
Add metric dropdown for edges and palm tree effect :)

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#529]
# Feature request

Currently it's unclear that we have edges, what edges are picked if there are multiple edge metrics available and hard to know what buildings have the worst edges. Worst for this issue means the buildings that have the highest sum of ingoing **and** outgoing edges. 

## Feedback

- [x] Show all buildings and not only those with edges. 
- [ ] Create a three-way toggle: show all buildings even if they have no edges, show only buildings with edges, disable all edge showing and palm-tree effect (undone, as third option is the same as having the preview slider at 0)
- [x] Update the toggle A,B,C inside the edgeSettingsPanel. Remove option to not show any edges, as this state is also provided within the preview-slider. Create checkbox for both other states instead
- [x] Slider to change the curve of the edges
- [x] The count of ingoing and outgoing edges should be splitted
- [x] Test the edge effect with an [Apache Netbeans](https://github.com/apache/netbeans) map
- [x] Color in and outgoing edges in a different useful color (as an edge can be in and outgoing for different nodes, the hovered node determines the color first)
- [x] Show edges onHover only when valid edgeMetric is selected
- [ ] Outgoing Edges should start from one of the four edges of the building (undone, because it is less clear which node an edge corresponds to)
- [ ] Debounce edgeMetricServcie broadcast like in settingsService (not necessary, as it makes loading slower)
- [x] Update edge-metric dropdown to new design
- [x] Show sum symbol if applicable for edge metrics
- [x] Update edge curve calculation with new edge start/end points
- [x] Update edges when buildings height changes due to scaling
- [x] Fix removing edgePreviews, when selecting edgeMetric `None`
- [x] There should be no edges on hovering nodes, when selecting edgeMetric `None`
- [x] Tooltip if no Edges available
- [x] Increase Test Coverage for: `codeMap.arrow.service`, `edgeSettingsPanel`
- [x] When a building is highlighted, the edges endpoint buildings should be highlighted too
- [x] Fix on new File loaded, the settings/previews are not applied
- [x] Add reset button to edgeSettingsPanel
- [x] Disable edgeSettingsPanel settings when no edges found

## Description

* Let's add a new metric dropdown with which we can select what ingoing and outgoing edges to visualize.
* The building with the most ingoing and outgoing edges is displayed and visualized in the following way
  * the ingoing edges all go into the top of the building into the center
  * the outgoing edges all leave from the side of the building
  * without user interaction only 1/10th or so of the edges are displayed. I imagine it'll look a bit like a **palm tree** :)
  * The user can see that there are a high number of outgoing and ingoing edges because there are lots of short arrows drawn.
* if the user hovers over any building CC shows the full edges and where they lead or come from. 
  * The buildings where the edges come from are also highlighted.
  * CC shows the full edges for as long as the user hovers over the building or has it selected.
* The options for the metric dropdown control how many of the buildings have visible 1/10th edges. The default is 1, similar to the show label counter.
* If no edges are available the dropdown is disabled and displays a helpful message why and how to generate edges. A helpful reminder to check out the analysis wiki is enough. We don't need to specify the exact analysis filter because that might change in the future.
* The right-click `show edges` button is removed from the context menu.

Is this the final metric display issue? No, but this should prove a very good starting point for our users. Based on the feedback we can then change how edges are displayed.

The result looks something like this **without** hover:

![IMG_4799](https://user-images.githubusercontent.com/28268662/62376515-187f2c00-b541-11e9-9e84-5094c6fc1a70.JPG)

And **on** hover the full edges are drawn:

![IMG_3890](https://user-images.githubusercontent.com/28268662/62376538-2634b180-b541-11e9-941b-558e8dca68b8.JPG)

**Comment by Richargh** [comment]
I just added beautiful palm tree sketches :) and @NearW has seen me draw them live and with force.

**Comment by alexhunziker** [comment]
[cc_with_edges.cc.zip](https://github.com/MaibornWolff/codecharta/files/3472356/cc_with_edges.cc.zip)

I created a .cc.json file of codeCharta with edges for testing :)

**Comment by Richargh** [comment]
@alschmut and @JaiJoPa I just updated the feedback in the description, because I had a horrible thought: what if our users don't want to see the edges?

> Create a three-way toggle: show all buildings even if they have no edges, show only buildings with edges, disable all edge showing and palm-tree effect :(

**Comment by NearW** [comment]
![edgesplit_bigmap](https://user-images.githubusercontent.com/12533626/63170746-3ddc6180-c03a-11e9-9c1d-cf835529040d.gif)
![edgesplit](https://user-images.githubusercontent.com/12533626/63170748-3ddc6180-c03a-11e9-817c-4400dad1584c.gif)

@alschmut destroy me

**Comment by alschmut** [comment]
Soooooo: 😄 

on the one hand I like it and it works, on the other hand its getting a bit messy and with a too big distance I can't recognise, which arrows are ingoing and which outgoing. Did you check having slightly shorter default lines?

**Comment by Richargh** [comment]
Interesting a couple of questions:

1. I get why the outgoing edges don't go out from the sides. That would be strange, especially for flat buildings. Can you humor me and make the edges got out from the "edge" of the top of the building?
2. It's hard to see which buildings are connected to which. Can you highlight all connected buildings?
3. The arrows are hard to see: can we color their insides different from their outsides? What if the insides of the arrows are white with a black "frame".
4. Contrary to what I said before, how about we experiment with colored arrows? Purple filled outoing and blue filled ingoing?
5. How do these arrows look if they are form a flat curve? Then they go through buildings but if only the connected buildings (2) are highlighted that could still work.
6. Can we give the ingoing and outgoing arrows different curves? Ingoing very steep like here, outgoing very flat.

**Comment by NearW** [comment]
> on the one hand I like it and it works, on the other hand its getting a bit messy and with a too big distance I can't recognise, which arrows are ingoing and which outgoing. Did you check having slightly shorter default lines?

Well, before all edges were just overlapping in the center. At least you can see if an edge is outgoing or incoming now. We will have a slider to adjust the curve later

**Comment by NearW** [comment]
> I get why the outgoing edges don't go out from the sides. That would be strange, especially for flat buildings. Can you humor me and make the edges got out from the "edge" of the top of the building?

You mean like mentioned in the story here? Pick one of the 4 edges with the shortest distance to the target building?

> It's hard to see which buildings are connected to which. Can you highlight all connected buildings?

Yes. Soon™

> The arrows are hard to see: can we color their insides different from their outsides? What if the insides of the arrows are white with a black "frame".

We'd need a bounding-geometry around the arrow. I couldn't find something usual.

> Contrary to what I said before, how about we experiment with colored arrows? Purple filled outoing and blue filled ingoing?

I implemented that before. We can easily do that. Changing the color the the whole arrow is no problem.

> How do these arrows look if they are form a flat curve? Then they go through buildings but if only the connected buildings (2) are highlighted that could still work.

We will have a slider to adjust the curve and allow it to pass through buildings. We can set a default once we have some user feedback.

> Can we give the ingoing and outgoing arrows different curves? Ingoing very steep like here, outgoing very flat.

The curves are drawn before and we just cut their visibility, when a building is not hovered. An outgoing curve will be an incoming curve for another building.

> How does it look with a big map? :)

Waiting for netbeans... :b

**Comment by Richargh** [comment]
> You mean like mentioned in the story here? Pick one of the 4 edges with the shortest distance to the target building?

Yes, that's what I mean.

> We'd need a bounding-geometry around the arrow. I couldn't find something usual.

OK, nevermind :)

> An outgoing curve will be an incoming curve for another building.

True, nevermind the comment *cough...

**Comment by alexhunziker** [comment]
> An outgoing curve will be an incoming curve for another building.

We could still achieve a similar effect though, by moving the highest point of the curve from the middle towards the incoming building

Also I have two more questions:
When we hover a building, we are displaying edge metrics for this building, like we do for the color/height/area metric. 
1. On Friday we decided to show the incoming and outgoing edges separately. However, I thought that this might not be very meaningful for some of the metrics (e.g. pairing rate) where a separation into incoming and outgoing edges is somewhat arbitrary. Maybe showing the total incoming and outgoing edges together is the better  option after all, what do you think?
1. It makes probably sense to decorate the map nodes with the edge metrics, (as we are doing with the other metrics) in order to being able to sum up the value for folders/packages. We could now put them together with the other metrics into the node "attributes". However, this might lead to data being overwritten if the name of the edge metric is already used for other metrics. Furthermore, i am not sure if it makes sense to combine them, since edge metric counts are not exactly the same as the other metrics. Therefore I thought about storing them as "edgeAttributes" or something, so we have them separated from the rest. Does anybody have objections or opinions regarding this?

**Comment by alschmut** [comment]
@alexhunziker I shortly answer to your two question:
1. I can't say if its useful to have the values of incoming and outgoing separated, but regarding your example the pairing rate value is different for in- and outgoing edges. Its always: When fileA is changed, chance is x% that film is changed in the same commit. This means its not necessarily the same value the other way around :)
2. I agree and would also think about adding a separate attributes object to the node.

**Comment by alschmut** [comment]
I just realised, that the TreeViewSearch does not work on this branch (:

**Comment by alexhunziker** [comment]
> I just realised, that the TreeViewSearch does not work on this branch (:

I just checked; it is not a problem with the branch, as we have the same issue on master... we should fix that before releasing the next version.

**Comment by alexhunziker** [comment]
Netbeans for some reason had almost no edges, according to codemaat (either there are none, or there is an issue with the software)... anyways i did a map of the sonar-java plugin, while it only has around 200k rloc, i think it should still be big enough for developing the edges features.
[sonar_java_edges.cc.zip](https://github.com/MaibornWolff/codecharta/files/3531441/sonar_java_edges.cc.zip)

**Comment by alschmut** [comment]
Suggestion to replace the 3 way toggle:
<img width="40%" src="https://user-images.githubusercontent.com/23529226/63582572-9a3f0400-c599-11e9-9b5b-e4dec2bd0d75.jpeg">

**Comment by alschmut** [comment]
We also have to think about, what we gonna do with the edge options inside the nodeContextMenu.
