### ISSUE TITLE
Opening the same file a second time does not work

### ISSUE THREAD

**Issue by xWorkerBeex** [MaibornWolff/codecharta#53]
Step 1: Choose a file to visualize via the "Open File" menu
Step 2: Change this file (e.g. new analysis) while keeping the visualization running
Step 3: Try to load the same file again vie the "Open File" menu. As the filename doesn't change, a reload of the map is not triggered. You have to reload the visualization or choose another cc.json file for it to work again.

**Comment by mrpatpat** [comment]
Fixed on current master. It will be a part of the next release.
