### ISSUE TITLE
Describe how to setup a local Sonar Server for CodeCharta

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#531]
# Feature request

We have documentation that describes [how to merge information from Sonar and Git](https://github.com/MaibornWolff/codecharta/wiki/Using-Sonarqube-and-Git-data-to-visualize-Codecharta's-own-Code). But we don't have documentation that describes how to setup a Sonar Server on a local development machine. This documentation probably exists somehwere else. It would be beneficial to have it in the CodeCharta wiki because Sonar is a very powerful tool that is regularly used.

## Description

Create a wiki page that describes in quick easy steps how to create a Sonar instance and upload a project to it. Test this with a Java, a SQL and a C project. That should give the example enough breath to be applicable to different projects.

Do not describe how to extract data with `ccsh sonarimport <URL> <PROJECT_ID>`. Do describe however which <URL> and <PROJECT_ID> to use, because that is relevant to the other [tutorial](https://github.com/MaibornWolff/codecharta/wiki/Using-Sonarqube-and-Git-data-to-visualize-Codecharta's-own-Code) to which you can link.

Open Source projects to analyze can be found [here](https://projects.apache.org/statistics.html), creating your own project is also ok though.

**Comment by alexhunziker** [comment]
https://github.com/MaibornWolff/codecharta/wiki/Analyze-Projects-with-a-local-SonarQube-Instance-and-CodeCharta

**Comment by Richargh** [comment]
That was fast, thanks :) A couple of remarks:

* Please add a purpose statement in the beginning. Why should we create a local Sonar instance? Because Sonar has a significant amount of Code Analyzers. We can use Sonar a) for local analyzation or b) in case we want to add it to a build pipeline for quality metrics.
* "Click on the plus icon to create a new project": This is a step in the Sonar UI right? Can you add a link to this step in the official Sonar docs or a screenshot?
* "Gradle only": Maven also needs a plugin right? Because you are calling `mvn sonar:sonar`. You can link to the Sonar docs page if you want here.
* We don't require details how to analyze projects other than Java in this how-to. We don't need the C# section, the Other section should stay. In the other section please mention that Sonar can also analyze C#, JavaScript, TypeScript, C++ projects and provide a link to the sonar docs.
* Every example analyze code references the <PROJECT_KEY> but the ccsh example suddenly talks about <PROJECT_ID>. That is strange. Also `ccsh sonarimport` is missing the <URL>. 
* Test if the metric upload also works for a simple C or C# project. Only document if specific steps are necessary for this to work => do I need to install something special into the Sonar server.

**Comment by alexhunziker** [comment]
Ok i have edited the page according to the remarks.

The C# process is different from the "other" section. If we want the C# code to be analyzed we have to use a different tool for the analysis, therefore there is a separate section for this. (Note: I am still struggeling to getting the Sonar Scanner for MSBuild to work; so far with limited success, the building process fails if the Sonar Scanner is active)
