### ISSUE TITLE
Describe how to generate a cc.json from an SVN log

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#532]
# Feature request

Currently we have documentation that describes how to parse a `git.log` file. The `ccsh scmparser` does also [support](https://github.com/MaibornWolff/codecharta/tree/master/analysis/import/SCMLogParser) analyzing a `svn.log`. Please create an example how to do this.

## Description

The example describes how to analyze the svn repository of [openoffice](https://openoffice.apache.org/source.html) or any other SVN project.

**Comment by Richargh** [comment]
The point wasn't to update the ReadMe. The point was to extend our wiki so even people that don't browse through our code can find the documentation. Please create a wiki page.

Currently I can find all examples in the wiki: https://github.com/MaibornWolff/codecharta/wiki

**Comment by Richargh** [comment]
To be clear, I have almost no problem with the content of the Readme, just the location. It's hidden currently. If we move it to the Wiki it should have an introductionary sentence though :)

**Comment by alschmut** [comment]
@Richargh sorry for the misunderstanding ;) Here is an updated wiki page also mentioning parsing SVN logs: https://github.com/MaibornWolff/codecharta/wiki/Using-Sonarqube-and-Git-data-to-visualize-Codecharta's-own-Code

**Comment by Richargh** [comment]
Thanks @alschmut 
I changed the title to reflect that we can also use svn log `Using Sonarqube and the Log from Git or Svn to visualize Codecharta's own Code`. Did you test the method with the Openoffice repo?

**Comment by alschmut** [comment]
Yes I tested it with exactly that repo, its huge and took some time, but it was as simple as described in the wiki/readme ;)

**Comment by Richargh** [comment]
Ok, then consider my objections invalid :) I'll move this issue to done.
