### ISSUE TITLE
Integration Tests cannot be started from Windows Command Line

### ISSUE THREAD

**Issue by alexhunziker** [MaibornWolff/codecharta#534]
# Bug

Integration tests cannot be executed with gradlew.bat (Windows cmd). 
However launching them with bash (e.g. GitBash) on Windows works.

## Expected Behavior
Starting the tests should work from gradlew.bat (, or the option should be disabled.)

We'll not write a separate windows script for the integration tests. Instead we'll **inform the user that he should use Git Bash and fail the integration test.**

## Actual Behavior
Execution fails with message: 
> A problem occurred starting process 'command 'sh''

## Steps to Reproduce the Problem

> gradlew.bat integrationTest

**Comment by Richargh** [comment]
@alexhunziker is this issue solved?

**Comment by alexhunziker** [comment]
No, but there is a workaround to just use the bash script (e.g. with GitBash) on Windows.

(The issue is essentially that in the script executing the integration test we launch a .sh file, which on windows CMD unsurprisingly fails)

**Comment by Richargh** [comment]
I don't want to add a second script just for windows. Then we have to keep that script in sync with the .sh script. But I think it makes sense to point the user in the right direction. Can we add a helpful message that reminds the user to open Git Bash when running `gradlew.bat integrationTest`?

**Comment by alexhunziker** [comment]
completely agree on not writing a separate windows script :) concerning the information message; we surely can give a message depending on the operating system. I don't know if gradle knows from which console it was launched but i guess it sould be possible too

**Comment by Richargh** [comment]
I updated the expected behavior. gradle definately has an `os` property. If it does have a shell property I don't know but we should be able to figure it out while fixing this bug.
