### ISSUE TITLE
Describe how to generate cc.json with SourceMonitor-UI

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#535]
# Feature request

Please describe how to export [SourceMonitor](http://www.campwoodsw.com/sourcemonitor.html) data and import it in the ccsh to generate a cc.json. This is largely a helpful rewrite of the [CSVImporter ReadMe](https://github.com/MaibornWolff/codecharta/tree/master/analysis/import/CSVImporter). 

Please create an example that analyzes non-java code without our SourceMonitor wrapper script. Apache provides a large repository of [open source projects](https://openoffice.apache.org/source.html).

**Comment by NearW** [comment]
https://github.com/MaibornWolff/codecharta/wiki/Generate-a-cc.json-with-SourceMonitor

**Comment by Richargh** [comment]
I like it. I haven't checked the steps in Parallels but it's very detailed and shouldn't leave any questions. Can someone else also check so we can close it?

**Comment by alexhunziker** [comment]
Looks good :+1:
