### ISSUE TITLE
Import CKJM Metrics

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#536]
# Feature Request

We want to import metrics generated by [ckjm](https://www.spinellis.gr/sw/ckjm/). This tools processes Java Bytecode and calculates for each class the following six metrics proposed by Chidamber and Kemerer.

    WMC: Weighted methods per class
    DIT: Depth of Inheritance Tree
    NOC: Number of Children
    CBO: Coupling between object classes
    RFC: Response for a Class
    LCOM: Lack of cohesion in methods

 In addition it also calculates for each class

    Ca: Afferent couplings
    NPM: Number of public methods

**Comment by BridgeAR** [comment]
Focusing on single programming languages and adding new parsers for them is a lot of work without gaining a lot from it. Instead, adding a generic parser that would be able to identify these would be great.

@ce-bo you might be interested in these metrics.

**Comment by ce-bo** [comment]
Thanks @BridgeAR. I would like to put it back into Backlog for now.

**Comment by ChristianHuehn** [comment]
moved to metric gardener: https://github.com/MaibornWolff/metric-gardener/issues/377
