### ISSUE TITLE
Add Pipe-Support to Sonarimport and scmlogparser

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#537]
# Feature request

Currently the importer in the ccsh need to run seperately from each other:
```bash
cd junit4
git log --numstat --raw --topo-order > ../junit.log
cd ..

ccsh sourcecodeparser -p junit4 -o junit4-2017.source.cc.json junit4/
ccsh scmlogparser -p junit4 -o junit4-2017.git.cc.json junit.log
ccsh merge -o junit4-2017.merged.cc.json junit4-2017.source.cc.json junit4-2017.git.cc.json
```

The more importers we use (codemaatimporter f.e.x.), the more intermediate cc.json files we have. Also the command could be clearer. 

Linux/Mac provides the pipe operator which can be used like this:
```bash
echo 'foo'     \
  | sed 's/d/a/' \
  | sed 's/e/b/' \
  | sed 's/f/c/' \
  > result.txt
```

In Windows it looks like this (shortened a bit because I don't know any useful cmds in Windows):
```bash
echo 'foo'     ^
  > result.txt
```

## Description

Please add support to the importers for piped content. The sonarimporter and scmlogparser should both be able to receive a cc.json via linux/mac/windows pipe and add their data to the cc.json. The result could look like this:

```bash
cd junit4
git log --numstat --raw --topo-order > ../junit.log
cd ..

ccsh sourcecodeparser -p junit4 junit4/ \
  | ccsh scmlogparser junit.log -o junit4-2017.merged.cc.json
```

Please test this with a large codebase like Apache Netbeans, to see if the importer can handle large projects.

## Hint

[My repo](https://github.com/Richargh/sandbox-kotlin-picocli-pipes) has attempted this but the results are somewhat mixed. Apparently the pipe `| ` redirects in Java to `System.in`. But it's not obvious how to differentiate between the cases where the user wants to use the `|` and when he wants the intermediate files and does not use the `|`.

**Comment by alexhunziker** [comment]
We already have pipe support for the two importers since #732 and #737, i think we can therefore close this
