### ISSUE TITLE
New TokeiImporter: Import Tokei Json Metrics

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#538]
# Feature request

Please add support for [Tokei](https://github.com/XAMPPRocky/tokei) Metrics in the json format: "Tokei is a program that displays statistics about your code. Tokei will show number of files, total lines within those files and code, comments, and blanks grouped by language." It supports [a lot of languages](https://github.com/XAMPPRocky/tokei#supported-languages) for these metrics.

## Description

After various installation or manual cp options, we can use Tokei like this: `tokei -o json . > tokei.json` or `tokei -o json > ccsh tokeiimporter -p foo`

The metrics tokei generates are loc=`loc`, code=`rloc`, comments=`comment_lines` and blanks=`empty_lines`. All metrics are absolutes.

That gives us the ability to use tokei metrics as a baseline and then extend the results for specific languages like Java, for which we can generate even more metrics.

The tokeiimporter should have **pipe support** and log all info-messages to stderr so we can pipe the result from the importer into another importer like `ccsh modify`.
The result could look like this:
```
tokei -o json \ 
> ccsh tokeiimporter -p foo \ 
| ccsh modify --moveFrom foo --moveToBar -o tmpo.cc.json
```

**Comment by NearW** [comment]
Is there a demand to be able to analyze a project and only retrieve the rloc metric?
Shouldn't all code-analyzer that provide metrics like mcc or lcom be able to provide rloc?

**Comment by Richargh** [comment]
@NearW thanks for commenting. The incubator column is exactly here so we can discuss ideas before commiting to them. :)

Well tokei has support for let's say 100 languages (I am bit lazy to actually count it). Our source code parser can support 1 language, and the second language is proving troublesome. Sonar supports some 30 languages. 

The trouble with not supporting a language is that it does not show up in CodeCharta. The files simply have no loc and are not displayed. My idea is to be able to run tokei on any code base and get simple metrics like LoC and #comments. Then afterwards I can run Sonar or sourcecodeparser and get much more detailed metrics. Does that answer your question?

**Comment by Richargh** [comment]
I just realized that we could model this fallback in our cc.json somehow. The attribute-information could reference fall-back attributes when the main attribute is 0. That way we can link "loc" as fallback for "rloc". I wonder if that can be made transparent or useful...
