### ISSUE TITLE
Import dependency-check information

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#539]
# Feature request

Please provide an importer for the security tool [owasp dependency checker](). 

It can be started like this: `dependency-check.sh -s <codefolder> -project MyProj -f CSV`.

The result looks like this:

|Project|ScanDate|DependencyName|CVE|CWE| Vulnerability|
|-------|-----        |-----                     |---- |---   | -------         |
|MyProj|May 22|ecstatic:3.3.1|830| | Versions of `ecstatic` prior to 4.1.2, 3.3.2 or 2.2.2 are vulnerable to Open Redirect....|

**How can we display and store this in CodeCharta?**

**Comment by NearW** [comment]
I don't see a way to map this information to our buildings representing files and folders.

- Apply this information/metric to the root-folder only (probably too hidden from the user)
- We need a 2nd view for the codecharta than just a city representing a folder-hierarchy to display project specific information

**Comment by Richargh** [comment]
That's exactly my problem. Can we and should we add this information to CC? It is extremely useful to have this security information. 

My idea goes in the same direction that you have, a separate view of sorts: I wonder if we can combine it with a possible bug-view that we have yet to implement. Sonar f.ex. provides the number of bugs that the code has. We could add this bug information to the cc.json, seperate from `node` and `edges`. Then we can not only add source code bugs but also security bugs to the `bug` entry in the cc.json.

**Comment by NearW** [comment]
Although bugs/issues are referenced to files and a specific line of code in it, while the dependency-check references the whole project.

We currently add the number of bugs/issues as a metric to the buildings. We could add another Dropdown-Selection for issues that simply hides all buildings that are not affected by this bug/issue. This dropdown would be unselected by default and we could implement this into the current view in codecharta. But as you said earlier, we need something like a field `issues[{type, name, file, loc}]`

**Comment by Richargh** [comment]
> add another Dropdown-Selection for issues that simply hides all buildings that are not affected by this bug/issue.

That could look very nice and informative! 👍 Dependency check could then highlight the pom.xml or build.gradle etc. where the issues come from or simply nothing. I think we are close to something here. We should probably implement the sonar issues first and in that story think of the format, then think of dependency check. Do you have an idea where to place that dropdown in the new UI? :)

**Comment by Richargh** [comment]
To clean up a bit I'll close this issue and leave it to @fatihi if he wants to reopen it.
