### ISSUE TITLE
Scaling sliders should have fixed values

### ISSUE THREAD

**Issue by xWorkerBeex** [MaibornWolff/codecharta#54]
As a user, I would like to have fixed values for the scaling sliders. For example, I can't choose a scaling of 2, only 1.996 and 2.013. 

Fixing the sliders to 0.05 or 0.1 per step would spare a user the struggle of not getting that perfect 2.0

**Comment by mrpatpat** [comment]
Thank you for the suggestion. This really enhances user experience. I implemented in 12c8a66. It will be part of the next release.
