### ISSUE TITLE
SonarImporter should have a progress indicator

### ISSUE THREAD

**Issue by alexhunziker** [MaibornWolff/codecharta#544]
# Feature request
The SonarImporter should have a progress indicator, since, if there are many issues and the connection is slow, it can take a while to import a project.

**Comment by alschmut** [comment]
Do you think we can implement a progress indicator, which can be accessed from every importer/filter/etc? So we kinda implement it once, and not separately for every importer :)

**Comment by alexhunziker** [comment]
That seems like a good idea. The question is where to put it, my first idea would be to put it into the model subproject (inside a new progressIndicator package or something like that)

**Comment by alschmut** [comment]
Yea I thought about something similar 👍
