### ISSUE TITLE
Improve Reliability of merge filter

### ISSUE THREAD

**Issue by alexhunziker** [MaibornWolff/codecharta#547]
# Feature request

The MergeFilter relies on the hierarchies of the files merged. But these hierarchies are often not matching up (e.g. because one cc.json file has the root folder one hierarchy below or above the other one).
At the moment we just merge them anyways, the only check is that the project name adds up (which is never the case for parsed SVNLogs btw, since they don't obtain the project name). We should provide some better checks or merging mechanisms for the filter to:
1.  Inform the user about potential project structure mismatches
2.  If possible correct mismatches (?)

**Comment by Richargh** [comment]
1. is a great idea. The merge should be aborted with a helpful message. But what can we suggest to the user instead?
2. I wonder if we should do this automatically at all. How about we create a new CC filter called `ccsh moveHierarchy` that allows us to move complete hierarchies inside one cc.json.

**Comment by alexhunziker** [comment]
I like the idea of a separate filter, it is probably more transparent than if we try to fix something automatically. What that filter would actually do, is extract a subproject from a cc.json, right? Do you think  it should also able to insert additional levels of hierarchy into a project?

**Comment by Richargh** [comment]
I think both ways are necessary. If you have 10 files and 9 of them have the same hierarchy, you want some filter that can fix the hierarchy of that 10th file. 

After what tool should we model this? Is it a `grep`, a `sed`, a `mv`, a ... Or perhaps it's something more visual, that open some command-line menu where you can move stuff up and down? It seems this tool is something you use to fix something in your cc.json, not something you would use in your build pipeline all the time. What do you guys think?

**Comment by alexhunziker** [comment]
For the merge filter i have added some informative warnings about merges that did not go how the user might have intended them to go.

Regarding the modification of project structures, I have implemented a new filter that can 
- extract a subproject from the json structure (e.g. making /root/foo/bar -> /root and discarding the rest of the project) -OR- 
- move nodes, that are not leaves, aroung (e.g. /root/foo/bar -> /root/bar)
- additionally it can print the first x levels of the hierarchy of a cc.json file to the console, so that users can inspect the structure

Interface wise I kept it in line with our other ccsh tools, so everything is done by specifying command line paramters (e.g. --extract=/foo/bar). What do you think of that approach, and how do you think this filter should be called? (Personally i think we should model the tool in such a way that it can be part of a pipeline, since you may have two different data sources which will always produce missmatching project structures that one might want to correct automatically)

**Comment by Richargh** [comment]
**Should we move this new filter to a separate issue?**

I have a couple of comments regarding this filter:
* Great idea to be able to print the structure, see my comments on the tree tool example
* What's the name of the filter? `ccsh structure` perhaps or `ccsh tree` or `ccsh move`? 
* what are the possible parameters? `--extract` does what?
* why can't it also move and delete leaves?
* let's model it so it can be part of a pipeline.

Do you know about the bash tool tree? The output for two levels deep looks like this:
![Tree](https://user-images.githubusercontent.com/28268662/58871219-e9c01300-86c1-11e9-84c0-5ecadd624825.png)

Here is my idea of the interface, not using a specific name:

**Given** I have a <name>.cc.json with: /blub.js, /presentation/ctrl.js, /book/domain/foo.js and /paper/domain/bar.js
**When** I execute `ccsh <ourfilter> --moveFrom "/*/domain/*" --moveTo "/src/*/domain/*" <name>.cc.json`
**Then** the result will be a cc.json with /blub.js, /presentation/ctrl.js, /src/book/domain/foo.js and /src/paper/domain/bar.js

**Given** I have a <name>.cc.json with: /blub.js, /presentation/ctrl.js, /book/domain/foo.js and /paper/domain/bar.js
**When** I execute `cat <name>.cc.json | ccsh <ourfilter> --moveFrom "/*/domain/*" --moveTo "/src/*/domain/*" `
**Then** the result will be a cc.json with /blub.js, /presentation/ctrl.js, /src/book/domain/foo.js and /src/paper/domain/bar.js

**Given** I have a <name>.cc.json with: /blub.js, /presentation/ctrl.js and /node_modules/...
**When** I execute `ccsh <ourfilter> --remove "/node_modules/* <name>.cc.json"
**Then** the result will be a cc.json with /blub.js, /presentation/ctrl.js, /presentation/ctrl.js but no node_modules any longer.

The difference between 1st and 2nd example is that in the second I pipe the output from one script into another. This is very helpful to be able to compose ccsh commands without creating intermediate cc.json that are not helpful.

**Comment by alexhunziker** [comment]
> What's the name of the filter? ccsh structure perhaps or ccsh tree or ccsh move?

I thought about `modify`, but I like `tree` and `structure` equally

> what are the possible parameters? --extract does what?

Extract takes a subproject (=path) and makes it the new root of the file (this is the functionality we could have used to adjust the structure for Christians recent projects)
Currently there are the following parameters: --extract, --inspectStructure, --outputFile, --moveFrom, --moveTo, --projectName

> why can't it also move and delete leaves?

If we move /foo/bar to /foo/barx, but barx already exists, it will currently just copy all the leaves of bar into barx. So it copies basically just the children of a folder to the new location, and therefore copying leaves is not possible currently. If copying single leaves is a use-case we want to support, it could be implemented though.


So if I understand correctly, we also want a --remove option? I will implement one.

The interface is currently like your first example, so like

> ccsh modify file.cc.json --moveFrom /root/foo/bar --moveTo /root/foo

Do you think there should be the possibility to use wildcard characters in the parameters? Personally I think that most often the user would probably specify the full paths where the nodes should come from/go to

**Comment by Richargh** [comment]
Should this be a separate issue? It seems to be turning into a bigger issue.

* `modify` is a good name. Let's stick to that.
* I don't like `--extract` because it does not tell me what it does. How about `--setRoot`? 
* I don't know about `--inspectStructure`. That's not clear either. How about `--printLevels 1` or something like that?
* We don't need copying. There is no usecase I can think of that requires leaves to be replicated in any way. If we move /foo/bar to /foo/barx, but barx already exists I think /foo/barx should have all content from /foo/bar. 
* `--remove` for node_modules or vendor libraries would be beneficial. 
* You are probably right. Let's not add wildcards and require full paths. Keeps it simpler. 
* Did you check the pipe example I gave? Can you also implement this? 

If we have a pipe operator we can write code like this:
```
cat foo.cc.json \
  | ccsh modify --moveFrom /root/foo/bar --moveTo /root/foo \
  | ccsh modify --moveFrom /root/foo/trick --moveTo /root/trick \
  | ccsh modify --moveFrom /root/foo/blub --moveTo /root/blub -o modified.cc.json
```

**Comment by alexhunziker** [comment]
> Should this be a separate issue? It seems to be turning into a bigger issue.

Well, theoretically we are doing more than what the issue title would imply... And we are also closing #181 druring the process. On the other hand the new filter is almost finished, so from that perspective we can leave it as one issue.

> I don't like --extract because it does not tell me what it does. How about --setRoot?
> I don't know about --inspectStructure. That's not clear either. How about --printLevels 1 or something like that?

I changed the naming of these 2 parameters

> We don't need copying. There is no usecase I can think of that requires leaves to be replicated in any way. If we move /foo/bar to /foo/barx, but barx already exists I think /foo/barx should have all content from /foo/bar.

Oh, I did a mistake I meant moving the nodes (copying indeed makes little sense in this context)

> --remove for node_modules or vendor libraries would be beneficial.

Implemented it.

> Did you check the pipe example I gave? Can you also implement this?

I think it could be donne, we could serialize the input stream as a project and then continue there. I see one possible issue with the Windows cmd though:
The windows cmd limits the length of a line, so piping big projects via this method might not work there

I think it would make sense to address the piping issue as a whole in #537 and then add it everywhere we want it. What do you think?

**Comment by Richargh** [comment]
> On the other hand the new filter is almost finished, so from that perspective we can leave it as one issue.
The important part to me is that the new filter is not lost in the changelog.

> I think it would make sense to address the piping issue as a whole in #537 and then add it everywhere we want it. What do you think?
Theoretically there is no difference and we can add it later. What makes me nervous is that I don't know what we need to do to add it later. Do we need to change the interface of all filters? 

I'd like to use `ccsh modify` to implement the pipe functionality as well. Then we have the experience to know what #537 requires. So please take another two days at least and try to implement it. If it takes longer than that we'll move the pipe ability to a separate issue to get the `ccsh modify` released now.

Regarding the windows cmd, I think piped values are not serialized by windows but provided as a stream to the java program. The length of the line should not change at all.

**Comment by Richargh** [comment]
Does the pipe functionality work? What happens when I use it multiple times in a row?

**Comment by alexhunziker** [comment]
The pipe functionality works, however currently using it multiple times is prevented by our log messages; if we log something the "project" generated is no longer in a valid json format anymore.

**Comment by Richargh** [comment]
Hmm, can we use it in this state? 

* What happens if I display a progress bar? Well something where I use \r to go back and remove characters?
* Is the problem solved by logging to the error stream instead?
* Or should we include a silent mode -s and -S? I think that comes from curl.

**Comment by Richargh** [comment]
> Hmm, can we use it in this state?

@alexhunziker is it usable now?
