### ISSUE TITLE
Add Importer for semantic

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#556]
# Feature request

Add an importer for the command-line tool [semantic](https://github.com/github/semantic/blob/master/README.md)

**Comment by BridgeAR** [comment]
@ce-bo is currently implementing a parser using [tree-sitter](https://tree-sitter.github.io/tree-sitter/). It supports more languages and is easier to use.

**Comment by BridgeAR** [comment]
Closing as duplicate of #1885
