### ISSUE TITLE
Move partly outdated gh-pages content to wiki

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#557]
I would like to move the remaining content of the [gh-pages](https://maibornwolff.github.io/codecharta/) to our [wiki](https://github.com/MaibornWolff/codecharta/wiki) and finally remove the gh-pages site. We never really kept it up to date and it also doesn't look as professional as the wiki.

- we should check which content for doing a sonar analysis is already in the wiki
- are you fine with not describing how the GUI works, as it changes quite often together with the screenshot? It should mostly be self-explanatory
- maybe we should keep the following GUI-features:
    - right click a node -> open context-menu
    - left click and drag -> rotate
    - right click and drag -> move the blocks
    - use mousewheel -> zoom in and out

**Comment by Richargh** [comment]
> remove the gh-pages site. 

Let's not do that. I always thought that the [gh-pages](https://maibornwolff.github.io/codecharta/) should be the page our customer visists (the person paying :) and the [Github ReadMe](https://github.com/MaibornWolff/codecharta/blob/master/README.md) the one the users visits. 

> We never really kept it up to date 

In stark contrast to my intentions above, I think we did not a single update in years. 

> and it also doesn't look as professional as the wiki.

Full agreement here. Can we turn it into a cool splash page that explains what problems CC solves and how to get started, which is a link to the wiki? Perhaps you have other ideas? Or even better examples from other projects, what do they use their Github pages for?

**Comment by alschmut** [comment]
> Can we turn it into a cool splash page that explains what problems CC solves and how to get started, which is a link to the wiki?

I was actually rather thinking about removing the page at all. Aren't our Readme and 2-3 MW-articles the only sites, which link to our gh-page? That means people visit our actual gitHub repository first...

I am fine with a splash-page as well, if it makes sense, and people (clients) actually visit that page, but again, a splash page needs pictures and a picture will most likely be a screenshot of our tool, which has to be updated whenever we make changes.

I would rather try to improve our Readme (again) and make this the splash page, with links to the wiki and further instructions. What do you guys think about that?

> Do we want that replication?

I think a bit of replication is okey, but still I would try to merge the gh-pages sonarQube-content with some existing pages

> Keep the features? Why is this then part of a documentation issue? Or add documentation for how they work in the wiki?

😄 I just meant to add/keep this short list of functionality documentation, as we heard that users only found the context menu by *accident* (until we find a better solution, how the users gets notified to use the right-click on nodes)

**Comment by Richargh** [comment]
We now have new project docs with #682 so I'll close this issue
