### ISSUE TITLE
Create Wiki home page

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#558]
We should think about adding content to our wiki home page, as it currently looks like the following screenshot. 
- Mainly the target is to highlight the wiki pages we have, so the user can actually fine it
- Our currently 8 existing pages are super hidden on the right inside the sidebar
- Do we have different related topics (examples, getting started, how to) to group pages?

![image](https://user-images.githubusercontent.com/23529226/58950834-931d0c80-8787-11e9-87b5-58096a8106e3.jpeg)

**Comment by Richargh** [comment]
Here's a couple of things I have seen:

> @kelseyhightower: Why is no one using our open source project in production?
Show me the "end-user" documentation
Aaaand scene
>@lesv: @kelseyhightower OSS projects need to:1. Say what they do (and ideally the value proposition) on their homepage. 2. Give me an estimate how hutch work to kick the tires. (Less than 1h) 3. Est. for prod roll out. Most is really hard to use.
>@gpjonesii: @kelseyhightower It's not just about documentation. It's about commercial support, maintenance, security, legal idemnification... in short 'risk' - which is why companies like Red Hat, Docker, Heptio, etc. exist. You try telling shareholders you lost millions because you used unsupported OSS.
>@gortok: @kelseyhightower That’s huge for me. When I come to the page for your OSS GitHub project, I’m expecting to see how that project benefits me as a user. What problem does it solve? Why should I invest time in it vs any other project it competes with?
>@carmendeardo: @kelseyhightower Users of our systems master phone and app features on the fly yet folks in many IT shops are still in the newspaper business producing masses of end user documents.

[Gitpitch](https://gitpitch.com/docs) was suggested once to me as an example of good documentation.

There is also an article called [How to write good documentation](https://www.divio.com/blog/documentation/) which suggests that docs needs to include and be structured around its **four different functions**: 

* tutorials
* how-to guides
* explanation
* technical reference

**Comment by Richargh** [comment]
Summary, I think we should structure our documentation after the four different functions and start by explaining the problem we are trying to solve.

**Comment by alschmut** [comment]
That sounds like a good plan and the "documentation about the documentation" is quite detailed as well 👍

**Comment by Richargh** [comment]
I might get around to this around mid-july. If you want to take a stab you are very welcome to do so and move this issue to in-progress :)

**Comment by Richargh** [comment]
Done Mid-November with #682
