### ISSUE TITLE
Change hover effect to a spotlight

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#576]
# Feature request

Currently CodeCharta slightly lightens the color of buildings when the mouse hovers over them. It works but when doing a presentation the people further in the back can't see the hovered building so clearly. 

## Description

How about we change the effect to something like this (this picture is just an example and no longer covers the intent completely, see below for details):

![hover.jpg](https://images.zenhubusercontent.com/5cd16a929795a865159e70ff/4c43779f-52ee-48f7-9c86-7107af3b1a4b)

The idea is to darken all buildings that are not hovered, instead of highlighting the one building that is hovered. It works like this:

* buildings have regular brightness but then
* mouse enters some perimeter and
* buildings far away from the mouse are now very dark
* They get progressively lighter the closer they are to the mouse pointer
* the building right under the mouse pointer is significantly brighter than the buildings sorrounding it but still only regular brightness

The result is somewhat like a **spotlight**. We don't need that light circle or different levels of brightness for a single building though. It's probably not necessary to darken the whole background because it might be visually tiring.

## In combination with the new select

The nice thing is we can also combine this rather well with a different way of *selecting* buildings (not part of this issue):

![hover+select.jpg](https://images.zenhubusercontent.com/5cd16a929795a865159e70ff/a54fcadc-fb9f-451e-8821-2216af5159d1)

**Comment by Richargh** [comment]
After our discussion and some additional input from @felixherbst and Olex I changed the intended effect a bit.

**Comment by alschmut** [comment]
Regarding the discussion about a presentation mode button for a larger spotlight, how about the `fa-television`-icon?
<img width="40%" src="https://user-images.githubusercontent.com/23529226/61182121-fae83200-a626-11e9-80fe-15685b8770d4.jpg">
