### ISSUE TITLE
Change building selection effect

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#577]
# Feature request

Currently buildings can be selected which changes their color to orange. 

* Unfortunately that means we no longer know the original colors. 
* Additionally users have requested that we change this confusing behavior, because the selection effect uses the orange color.

What if we instead mark it by coloring the building sides white, similar to a wireframe? Here is an example:

![select.jpg](https://images.zenhubusercontent.com/5cd16a929795a865159e70ff/b7be790a-5874-4888-bb69-28a0e44c6da0)

Does the selection effect have to look exactly like this? No. It's an idea and if better ideas come up, please don't hesitate to suggest them.

**Comment by alexhunziker** [comment]
I think there also was once the idea to let the building glow. I found this example for Three.js http://stemkoski.github.io/Three.js/Selective-Glow.html. what do you think about using an effect like that?

![grafik](https://user-images.githubusercontent.com/20796577/65436181-083d4c00-de22-11e9-830a-f46624d1ccd7.png)

**Comment by alschmut** [comment]
@alexhunziker Its an option to try, but I think it also depends on the effort and the time it takes to implement.
