### ISSUE TITLE
If the window is too small horizontally the controls get hidden

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#582]
# Bug

Controls in our file and metric bar disappear when the window is too small horizontally. The user now has no way to know that content is missing.

## Expected Behavior

The user knows that content is missing or there is no way that content is missing. Please do not show a burger menu.

## Actual Behavior

Content is missing.

**Comment by Richargh** [comment]
By accident I stumbled over an idea [sausage links](https://bradleytaunt.com/hamburger-menu-alternative/) :)

**Comment by alschmut** [comment]
As a first step. The sections don't get hidden, when there's no space

![image](https://user-images.githubusercontent.com/23529226/60328268-3d0a4600-998e-11e9-82b5-b1ad1941355c.jpeg)

**Comment by Richargh** [comment]
Nice. I am tempted to leave it at that and apply the same idea to the file bar. What do you think?

**Comment by alexhunziker** [comment]
As a side effect of #526 the ribbon bar now looks like this, if there is not enough space:
![grafik](https://user-images.githubusercontent.com/20796577/61048269-ad2eb800-a3e1-11e9-82b0-643e22d67f91.png)
So I guess I fixed this one by accident too :)

**Comment by alschmut** [comment]
@alexhunziker I think i removed 1 or 2 unused CSS lines on the ribbonBar. Maybe we can remove those on #526 as well

**Comment by alexhunziker** [comment]
just checked that; you probably mean the vertical-align:top. I tried to remove it, but it seams that with the searchPanel we actually need it.

**Comment by alexhunziker** [comment]
we should probably also update the file panel to show the same behaviour than the ribbon bar...
