### ISSUE TITLE
Labels height doesn't adjust to scaled map

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#594]
# Bug

## Expected Behavior
- When scaling the map (RibbonBar -> Height section -> Height slider)
- Then Labels adjust according to map height

## Actual Behavior
- When scaling the map (RibbonBar -> Height section -> Height slider)
- Then Labels do not adjust correct

### Screenshots

<img width="50%" src="https://user-images.githubusercontent.com/23529226/59980034-117f0880-95e8-11e9-8fa2-797cf3ab7676.jpeg"><img width="50%" src="https://user-images.githubusercontent.com/23529226/59980039-1b087080-95e8-11e9-9cca-ca635d11d9ef.jpeg">

## Specifications

  - Version: 1.26.0

**Comment by alschmut** [comment]
Although, maybe it makes more sense to investigate time into some brand new labels with #334

**Comment by alexhunziker** [comment]
is there any instance where we use scale.x or scale.z (the one from settings.appSettings.scaling)? Or in other words: can i simplify the label scaling, by only taking the y-direction into account?

**Comment by alschmut** [comment]
We are not scaling the other two dimensions. And I once thought about it as well, but i actually don't know what's better. Currently its generic for potentially scaling the whole map in each dimension..

**Comment by alexhunziker** [comment]
I think keeping the generic approach is probably better. if we want to remove the x and z scaling functionality completely, we can delete it everywhere at the same time later.
