### ISSUE TITLE
Add save button and indicator that cc.json contents have been modified

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#598]
# Feature request

## Description

You currently don't know if the cc.json has been modified since loading it into the visualization. 

Add an indicator in standalone to the file bar that shows the user when the file has been modified. This feature is rather common in many editors. You do not have to figure out if the file later was restored to the original state. The indicator only disappears, when clicking the also added save button, not the export button in the file menu.

**Comment by BridgeAR** [comment]
This is going to become obsolete as soon as the custom configs feature is fully implemented. Closing due to that.
