### ISSUE TITLE
Delta shown although not in delta mode

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#60]
Although I'm not in Delta mode and I only imported one single cc.json into the application there is some mysterious Delta value showed in the details. Please see the screenshot. Json file can be provided if necessary. 

<img width="1352" alt="bildschirmfoto 2018-01-17 um 13 24 23" src="https://user-images.githubusercontent.com/16349180/35042664-ddbafa30-fb89-11e7-8716-732c89e609ed.png">

**Comment by mrpatpat** [comment]
This bug will be fixed as soon as we merge PR #58 .
