### ISSUE TITLE
Move path indicator into the file bar

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#607]
# Feature request

## Description

The file path indicator takes a lot of space and risks being overlayed by other controls. How about we place it where the file bar is normally? We don't need the file bar while hovering over buildings.

The result could look like this, with a clear separation between the folders and files:

![file-path-bar](https://user-images.githubusercontent.com/28268662/62375470-aad20080-b53e-11e9-82b8-c011092cf873.png)

* Please ignore the fancy icons. We don't need them. Regular file and folder icons are perfect.
* If the path is wider than the available space we'll wrap at the end and use two or more lines to display the path. That's the same behavior as our current path indicator.

**Comment by Richargh** [comment]
I added a screenshot

**Comment by alschmut** [comment]
I like it 👍 Just not sure if there are projects that have a too deep hierarchy to show the full path. We don't have any data available for tagging folders as modules (with the blue square), like IntelliJ does, but I think simple folder and file icons are nice. What does the transparent dot on the folder mean?

**Comment by Richargh** [comment]
> too deep hierarchy to show the full path

Our current path indicator then uses two or three rows. Which we should also do. Maybe decrease font size then as well.

> I think simple folder and file icons are nice

I agree. Nothing fancy necessary here. Just our regular icons.

> What does the transparent dot on the folder mean?

I think that indicates that this is a package, not a regular folder.
