### ISSUE TITLE
Standalone cannot be started any more

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#613]
# Bug

## Expected Behavior

`npm install` then `npm run start` opens CC in the newest version available online.

## Actual Behavior

The window does not display anything.

## Steps to reproduce

* `npm install` 
* `npm run start`
* see screenshot

### Screenshots

![Screenshot 2019-06-28 at 09.11.46.png](https://images.zenhubusercontent.com/5cd16a929795a865159e70ff/7c855c3d-800d-4d2a-814b-ccce888ed5e9)

**Comment by NearW** [comment]
`npm run build` ? :)

**Comment by Richargh** [comment]
Nevermind, I did not know we have to run `npm run build`.
