### ISSUE TITLE
Add clarifying information which file is which in the file bar when in delta mode

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#615]
# Feature request

The file bar does not provide information which file is the baseline in the UI and what file is the delta.

## Description

Please add information which of the two files in the file bar is which.

Let's use `pictogramms`. The left file picker gets the grey box, representing the grey baseline building. The right one gets the green/red delta building. There are small `+` and + `-` next to them. Green/red have to switch if colors are inverted. 

![59985721-1f09b200-962b-11e9-97de-6e58be127491](https://user-images.githubusercontent.com/28268662/60075281-3927bb00-9725-11e9-868d-01776af97cce.jpg) --> I was too lazy to also remove the old and new labels which should no longer be visible, but you get the idea.

**Comment by JaiJoPa** [comment]
I have put the pictogram in- and outside the filePanel. Which one do you guys, should we use ? 

inside:

![pictogram_inside](https://user-images.githubusercontent.com/50145538/62547075-e9302e00-b864-11e9-9de2-955d9f47bd4f.PNG)


outside:

![pictogram_outside](https://user-images.githubusercontent.com/50145538/62547092-f0efd280-b864-11e9-9027-94d29e45fac6.PNG)

**Comment by fatihi** [comment]
After seeing both, I actually prefer the outside option.
Having the colors inside makes it look it the colors are part of the choice in the dropdown
