### ISSUE TITLE
SCMLogParser: Calculate temporal coupling 

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#622]
# Feature request

[CodeMaat](https://github.com/adamtornhill/code-maat) calculates a very useful metric called temporal coupling. Unfortunately most development work now flows into the commercial version [CodeScene](https://codescene.io) and maat received its last code change years ago.

## Description

Calculate temporal coupling in CC. Temporal coupling is defined by Adam Tornhill in [Your Code as Crime Scene](https://www.amazon.com/Your-Code-Crime-Scene-Bottlenecks-ebook/dp/B00ZB5XWBI/) or the follow-up [Software Design X-Rays](https://www.amazon.com/Software-Design-X-Rays-Technical-Behavioral-ebook/dp/B07BVRLZ87/). 

Here's how I understood it: 

* Look at all instances, which can be commits/close time-windows/branches
* When file A is changed, how often is file B also changed? coupling A --> B
* Is the reverse also true or is file B changed without file A changing?
* given all the instances, how often is file A changed and file B as well? In percent, that is the temporal coupling between A --> B.

Please invest time to research this and compare it to the result calculated by codemaat for a couple of open source code bases.

**Comment by alexhunziker** [comment]
So I have implemented temporal coupling edges in the SCMLogParser. However the metrics did not match the results of CodeMaat. 

Today I did some research as to what the differences are. Result: We are (already in the current version of CodeCharta) calculating highly coupled files differently from CodeMaat:

Code Maat seems to be doing: 
`(nr_of_commits_fileA+number_of_commits_file_B)/(nr_of_joint_commits*2)` and then they do one edge from (I guess) the file with more total commits to the other file.

CodeCharta does: 
`nr_of_commits_fileA/nr_of_joint_commits` and `nr_of_commits_fileB/nr_of_joint_commits` which may or may not result in two edges.

Which way do we want to calculate this metric?

**Comment by alexhunziker** [comment]
Here are my test log files, in case you want to experiment with them:

[log_format_scmparser.log](https://github.com/MaibornWolff/codecharta/files/3734667/log_format_scmparser.log)
[log_format_codemaat.log](https://github.com/MaibornWolff/codecharta/files/3734668/log_format_codemaat.log)

Results:
>CodeMaat: visualization/app/codeCharta/ui/codeMap/codeMap.component.ts,visualization/app/codeCharta/ui/loadingGif/loadingGif.component.ts,93,8

> CodeCharta: "edges":[{"fromNodeName":"/root/visualization/app/codeCharta/ui/codeMap/codeMap.component.ts","toNodeName":"/root/visualization/app/codeCharta/ui/loadingGif/loadingGif.component.ts","attributes":{"pairing_rate":0.875}},{"fromNodeName":"/root/visualization/app/codeCharta/ui/loadingGif/loadingGif.component.ts","toNodeName":"/root/visualization/app/codeCharta/ui/codeMap/codeMap.component.ts","attributes":{"pairing_rate":1.0}}]

**Comment by fatihi** [comment]
So I thought about both calculations and while they look similar, I think they are different metrics:
* the one Code Maat calculates is the coupling between two files
* the one we calculate is the coupling of one file to another

I actually like the way we calculate it more, since the way code maat calculates it, some extreme examples may not be found. Here is one:

Commits A: 100
Commits B: 1
Joint Commits: 1

CodeMaat: 2*1/101 ~ 0,02
CC:
A: 1/100 = 0,01
B: 1/1 = 1

Here you can see that B is always checked in together with A, but CodeMaat wouldn't find that case, while a coupling of 100% in CC should draw some attention.
