### ISSUE TITLE
Gain space in ribbonBar by replacing scenario select and shortening metrics

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#628]
# Feature request

## Description

Fastest solution to gain more space in the ribbonBar, is to remove the scenario section and replace it with a button, which opens up a select menu visually like the select behind the three dots in the search panel (see image). 

* Let's place that button left of the metrics to which it is connected. Same place as before. 
* Let's also make all the metric dropdowns shorter. We need to make room for the edges dropdown to the right. On a 13" screen all metric dropdowns should be visible.

<img width="40%" src="https://user-images.githubusercontent.com/23529226/60888193-1c73a300-a24e-11e9-9058-3ba7d01ab6cb.jpeg"> <img width="20%" src="https://user-images.githubusercontent.com/23529226/60888013-b2f39480-a24d-11e9-9325-852049eb67ab.jpeg">

**Comment by Richargh** [comment]
@alschmut I changed the text a bit and added shortening of the metrics in general

**Comment by alschmut** [comment]
Thanks @Richargh. Do we also decide to use this select-panel, in order to not show the current (valid or invalid) scenario at all like mentioned in the bug/feature #641?
<img width="20%" src="https://user-images.githubusercontent.com/23529226/60888013-b2f39480-a24d-11e9-9325-852049eb67ab.jpeg">

**Comment by Richargh** [comment]
Seems like a good idea. If we ever decide to add custom metrics we'll have to change this but we haven't added custom metrics for a long time now :)
