### ISSUE TITLE
Reposition Legend Panel

### ISSUE THREAD

**Issue by alexhunziker** [MaibornWolff/codecharta#633]
# Feature request

We should probably reposition the LegendPanel as with the new Search Panel, it can look odd at times, if the search panel grows in size:

![grafik](https://user-images.githubusercontent.com/20796577/61049158-0e578b00-a3e4-11e9-9c16-4451e40c20fd.png)

Where should we put it?

**Comment by Richargh** [comment]
Did we agree on bottom-right?

**Comment by JaiJoPa** [comment]
I don't think so, but I've put the legend on the bottom-right to see how it looks like. 

![right-bottom](https://user-images.githubusercontent.com/50145538/61130296-a3c34f80-a4b6-11e9-9842-3a3746206446.PNG)


And put it also on the right side

![right](https://user-images.githubusercontent.com/50145538/61130320-b3429880-a4b6-11e9-96e9-92c0ffeba1c5.PNG)

**Comment by JaiJoPa** [comment]
Okay, we can actually exclude the second one, because it will cover the cube, when the ribbon bar is dropped.

**Comment by alexhunziker** [comment]
actually the view cube will not move anymore when the ribbon bar is toggled after #526 :)
