### ISSUE TITLE
Information about scenario not displayed after selecting a scenario

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#641]
# Bug

## Expected Behavior
- Clicking the Scenario Button and selecting a scenario should result in the button displaying the current scenario
- Clicking the Scenario Button and then click somewhere else to exit the dropdown should result in the button displaying the placeholder `Metric Scenario` again

## Actual Behavior
- Clicking the Scenario Button and selecting a scenario will result in the button not displaying anything
- Clicking the Scenario Button and then click somewhere else to exit the dropdown will result in the button not displaying anything

### Screenshots
![scenario_bug](https://user-images.githubusercontent.com/12533626/61522240-45482500-aa12-11e9-8ec8-e43e56faa4f6.gif)

## Steps to Reproduce the Problem

  1. Click Scenario Button
  2. Click a scenario 
  3. Information about current scenario is gone

  1. Click Scenario Button
  2. Click somewhere else to exit dropdown 
  3. Information about current scenario is gone

## Specifications

  - Version: 1.29.0
  - Platform: MacOS
  - Browser: Chrome

**Comment by alexhunziker** [comment]
Is this the same as #585 ?

**Comment by Richargh** [comment]
Looks like it, but it's made obsolete by #628

**Comment by alschmut** [comment]
We'll close this issue, as @Richargh mentioned, its obsolete by #628
