### ISSUE TITLE
Reposition Show Complete Map-Button

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#642]
# Feature request

## Description
LegendPanel now overlaps with the Show Complete Map-Button

Possibilities:
- [ ] Move LegendPanel up a bit and place the button down below
- [x] Move the Button under the viewcube
- [ ] Move the Button to the filepanel

Additionally, we could think about an icon, that indicates this purpose. We use a bullseye to represent focusing. We could use the same icon and cross it with a line or something to indicate unfocussing.

**Comment by Richargh** [comment]
@NearW I think it should be under the viewcube. In the bottom right corner it's invisible. In the file panel (that's where we select our maps right? :) ) it could get lost in delta view.

**Comment by alschmut** [comment]
I am fine with under the view cube as well 👍 do we also wanna decrease the text size to make the button less large.

We might already have had a discussion about that some time ago, but I don't really like the long "Show complete map" name anymore and would rather suggest "Unfocus", as it is the opposite word after pressing a "Focus" button somewhere else. What do you think about a renaming?
