### ISSUE TITLE
Disable adding pattern when search is empty

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#654]
# Bug

## Expected Behavior
**When** the search pattern is empty
**then** the add-pattern-menu should disable the appropriate Hide/Exclude option

## Actual Behavior
**When** the search pattern is empty
**then** all options (Hide/Exclude) are available to click inside the add-pattern-menu

**When** the search pattern is already inside the Hide/Exclude list
**then** the add-pattern-menu disables the appropriate Hide/Exclude option

### Screenshots

<img width="70%" src="https://user-images.githubusercontent.com/23529226/61995182-a0b28c80-b07c-11e9-88f7-fa3c2db594e2.jpeg">

## Comments
The `searchBar.component.html` still contains some dead code, which was used before to disable the options depending on the amount of matching files/folders from the search.

## Question
Should we also disable the options, when no nodes match the pattern, like before or only when the pattern is empty?

## Steps to Reproduce the Problem

  1. Open codeCharta
  1. click the "three dot"-button to add a blacklist pattern
  1. click the option Hide or Exclude
  1. Now an empty pattern was added to the blacklist

## Specifications

  - Version: 1.30.0
  - Platform: macOS
  - Browser: Safari

**Comment by fatihi** [comment]
> Should we also disable the options, when no nodes match the pattern, like before or only when the pattern is empty?

Yes, since you could have a rule that already excludes it, then you wouldn't be able to add another rule to exclude it and delete the old rule.
