### ISSUE TITLE
Add example to our README instead of a reference to the wiki

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#673]
# Feature request
Users are looking for a quick example on how to use the tool on this repo's mainpage. They will find a link to our wiki, which contains detailed examples.
It would be great to have a quick example in our README that shows a quick workflow on how to analyze a Java-Project with the SourceCodeParster, generate a git.cc.json and merge these. 

See [ShellJS](https://github.com/shelljs/shelljs#examples) 

## Description

- Update the README and add a quick example directly instead of a reference to the wiki.
- Use the SourceCodeParser(Java)->SCM(git)->Merge->Visualization workflow

**Comment by Richargh** [comment]
We actually updated the readme very recently with the #785 so I consider this to be done
