### ISSUE TITLE
Custom persisted scenarios

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#675]
# Feature request

Sometimes the user wants to have multiples views of the map and be able to switch between them easily but keep the **same camera perspective and metrics.** To accomodate this we'll implement custom scenarios (after two years of waiting :) #402 and #226).

## Description

* The custom scenarios are not tied to a map but instead globally to CodeCharta and they can be applied to any map. 
* The web version might use local storage to store them persistently. 
* The current scenarios (complexity and coverage) are now initial custom scenarios. 
* Scenarios that are not available because a metric is missing should be displayed but cannot be selected which a helpful message explains
* Scenarios contain at least one of these: camera position, size, height, color, edge metric
* The size, height, color, edge metrics also contain the slider values
* Existing scenarios can be deleted if wanted
* Changing any metric or camera position adds a star * to the scenario button, indicating a new scenario can be stored
* We use the [Plus-Icon](https://fontawesome.com/icons/plus?style=solid) instead of the save icon, to differentiate it from the cc.json.
* We don't provide an edit for scenarios. If users want to change a scenario, they can apply the scenario, change what they want, store it as a new scenario and delete the old one. If that process needs to happen all the time we'll create a new issue to actually edit scenarios.

## Examples

*When* I click on the scenario button
*Then* the scenario menu shold show me all the stored scenarios with icons that tell me if that scenario changes the camera position, the size, the height, the color and/or the edge metric.

*When* I change the camera position or any metric including sliders
*Then* a star appears next to the scenario button

**Given** a star is next to the scenario button
*When* I click on the scenario button
*Then* the scenario menu should include at the top a new scenario name "custom" with a [Plus-Icon](https://fontawesome.com/icons/plus?style=solid) next to it

*When* I click on Plus-Icon next to a custom scenario
*Then* a menu should open where I can select what is included in my custom scenario and what name it has.

![Metric-Scenario](https://user-images.githubusercontent.com/28268662/63159326-9c461780-c01b-11e9-8529-1c9fad92640e.png)

**Comment by Richargh** [comment]
@NearW I changed the text rather radically, please take a look if this matches your understanding.

**Comment by Richargh** [comment]
@alschmut we've been talking about custom scenarios for a loooong time :) #402 and #226
