### ISSUE TITLE
Color-Range-Slider resets when entering numbers

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#676]
# Bug

The sliders in the color-settings-panel have a weird behaviour when entering numbers. 

If you write `10` in the left field, and then update the right field to `100`, you will enter a `1` first. Then the components updates the left field, because it can't display the range 10->1, since 10 is obviously greater than 1. We should change the applying behaviour from `onChange` to `onSubmit` or when you click somewhere else.

## Expected Behavior
*When* I enter a `10` to the left field and then a `100` to the right field
*then* it should not update the view instantly and reset the left field, because 10 is greater than 1, when you entered the first number. 

## Actual Behavior
*When* I enter a `10` to the left field and then a `100` to the right field
*then* it updates the view instantly and reset the left field, because 10 is greater than 1, when you entered the first number. 

### Screenshots
![color-settings-reset](https://user-images.githubusercontent.com/12533626/62780941-20961900-bab7-11e9-9c79-b9f4d206a565.gif)

## Steps to Reproduce the Problem

  1. Type 10 into the left field of color-settings-panel
  2. Type 100 into the right field of color-settings-panel
  3. Left field gets reset

**Comment by fatihi** [comment]
The problem could be fixed by making the commit on leave or after a timeout of a second of not entering anything, preferably the latter one
