### ISSUE TITLE
Buildings where color-metric-value is 0 are displayed in grey

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#677]
# Bug

## Expected Behavior
Buildings with a colour-metric value == 0 should be coloured green (or red when inverted)

## Actual Behavior
Buildings with a colour-metric value == 0 is coloured grey

### Screenshots
![image](https://user-images.githubusercontent.com/23529226/62868137-37d24200-bd15-11e9-8e74-d80ff6b9b05d.jpeg)

## Steps to Reproduce the Problem

  1. Load a map with metric values equals 0
  1. Select the metric as color metric
  1. check out the buildings with color-metric value 0

## Comment
I checked the metric-values inside the `cc.json` file. They are not null or similar, they are `0.0`.

## Specifications

  - Version: 1.32.0
  - Platform: Mac
  - Browser: Safari

**Comment by fatihi** [comment]
Is there any metric that could return a null value? If so, we should make sure that in that case the building stays grey to indicate that the metric is not applicable. I can't think of a metric that wouldn't return a value though

**Comment by alschmut** [comment]
@fatihi if a metric value is `null`, a string or an object, the file doesn't even load... it shows this error message instead:
```
[ { 
"keyword": "type", 
"dataPath": ".nodes[0].children[0].attributes['rloc']", 
"schemaPath": "#/definitions/attributeList/patternProperties/%5E%5BA-Za-z0-9_%5D%2B%24/type", 
"params": { "type": "number" }, 
"message": "should be number" 
} ]
```

Should we change that behaviour?

What I actually meant with this issue is that we should show the correct color, if the metric value is 0 (a valid number)

**Comment by fatihi** [comment]
I was not sure if there was a metric which could return a valid null value, but if that is the current behavior, I think not. So please don't change it :)

Except the bug you described of course, that is definitely a bug! Thank you!
