### ISSUE TITLE
Bug: Exported cc.json include data that is not supposed to be there

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#679]
# Bug

## Expected Behavior

* The node of `"type": "Folder"` has empty `"attributes": { }`
* The node of `"type": "File"` does not have the attribute unary
* The node of `"type": "File"` does not have the `"origin": "sample1.cc.json"`

The visualization is not supposed to modify the `"nodes": []` or `"edges": []`. These are generated by the analysis. More specifically the problems are:

* A folder is not supposed to have any attributes. The Visualization is supposed to either sum or average the "file"s inside a "folder" but should not store these values in the cc.json.
* The unary attribute is a virtual attribute that is 1 for each "file". It's not supposed to be in the cc.json.
* The origin is very useful to differentiate in *Multiple Mode* where the file came from. It's weird to have it when I opened the file in *Single Mode*. 

Now for the bigger question: If I had openend multiple files in *Multiple Mode* should the "origin" be there for each "file"? I don't think it should. Currently the download button in *Multiple Mode* can be used to merge files but that was never the intention of *Multiple Mode. Merging files is supposed to be done by analysis and the merge filter. I think **we should disable the download** button for *Multiple* and *Delta Mode* because it's unclear what the resulting file will contain.

## Actual Behavior

When I save a cc.json from the visualization it includes data it's not supposed to include:

* The node of `"type": "Folder"` has `"attributes": { "unary": 4, "avgCommits": 146, "rloc": 600, ... }`
* The node of `"type": "File"` has this `"attributes": { "unary": 4 }`
* The node of `"type": "File"` has this `"origin": "sample1.cc.json"`

## Steps to Reproduce the Problem

  1. Open [CodeCharta with mini-map](https://maibornwolff.github.io/codecharta/visualization/app/index.html)
  2. Press the download button
  3. Press save

## Specifications

  - Version: 1.32.0
  - Platform: Web
  - Subsystem: Visualization
  - Browser: Firefox

**Comment by alschmut** [comment]
Short side note: I imported a cc.json file with 1.5MB after using the analysis and when I exported that map, it had 8.6MB. So while removing duplicated data with this issue, we should also consider minimizing the file size by removing whitespace/line breaks etc.

**Comment by alexhunziker** [comment]
> So while removing duplicated data with this issue, we should also consider minimizing the file size by removing whitespace/line breaks etc.

From looking at the code, it seems as if the whitespaces/line breaks were introducend intentionally; the json string is formatted before being downloaded. Therefore I guess it was once considered a feature...

So the question now is: bug or feature?

**Comment by alschmut** [comment]
@alexhunziker I was not part of that discussion and in my opinion there are lots of applications, which show the file content formatted. So I would rather focus on reducing the file size and not format the json.

**Comment by alexhunziker** [comment]
@alschmut  I am fine with removing this, i just wanted ensure that I am not removing a feature here. What do you think, @fatihi ?

**Comment by fatihi** [comment]
I'm with @alschmut here, the file is not intended to be read manually. If someone still wants to do that, there are programs that format json automatically.

**Comment by alschmut** [comment]
> Short side note: I imported a cc.json file with 1.5MB after using the analysis and when I exported that map, it had 8.6MB. So while removing duplicated data with this issue, we should also consider minimizing the file size by removing whitespace/line breaks etc.

With this issue implemented, I just shortly wanna mention, how much smaller in size our exported files just got. When I imported the same 1.5MB cc.json file and exported it afterwards, it had surprisingly just 1.3MB. I don't have an answer to why it is even smaller than 1.5MB, but I guess its a pretty good improvement from exporting a file which had 8.6MB before.
