### ISSUE TITLE
Migration from Java to Kotlin in analysis

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#68]
Hi all,

I'd like to discuss unifying the language in the analysis part to Kotlin. I think it would be good to have one language only for the analysis and I think Kolin is mature, easy to learn and some major improvements compared to java. Furthermore, it is rather easy to migrate from java to kotlin.

Please vote.

**Comment by thorsten** [comment]
Hi @ukinimod,

what are the main improvements of Kotlin compared to Java?

Cheers
Thorsten

**Comment by ukinimod** [comment]
Hi @thorsten,

the main improvements are less boilerplate code compared to java and null safety, while being completely interoperable with java (at least java version <= 8). There are two sub projects in CodeCharta written in Kotlin: ValidationTool, MergeFilter.

**Comment by thorsten** [comment]
@ukinimod well, then do it! :-)

**Comment by ukinimod** [comment]
Done in PR #77
