### ISSUE TITLE
Improve Docs

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#682]
# Feature request

Let's improve our README as well as the user and developer documentation. We should also move the user and dev documentation all to gh-pages or move it all to the wiki. All visual doc should use draw.io because we can visualize our workflow with flowcharts in which the nodes have links to our various importers.

* Github-pages can be visually customized (custom header/footer/whatever), probably exported as pdf and provide possibilities like multi-column layouts where images are directly next to the text. Also we can link to source code directly and probably verify it's all there.
* The wiki has these benefits ...

See also #558. Also #673

**Comment by alschmut** [comment]
I would suggest to move it all to our wiki. I never really liked our gh-pages. It doesn't look nice or modern, the user doesn't see any structure or any other existing pages and we barely keep it up-to-date.

**Comment by alschmut** [comment]
On the other hand, my favourite documentation type actually looks like this. This doc is the documentation for the tool to create those docs at the same time.. It might be some effort to integrate this *layout* into our gh-pages, but it could be worth it. What do you think?

https://docs.readthedocs.io/en/stable/index.html

![image](https://user-images.githubusercontent.com/23529226/63102265-183c5300-bf7b-11e9-886c-46414f8556d8.jpeg)

**Comment by Richargh** [comment]
Progress Update

* The docs are now using the minimal mistakes theme
* Full-text search works
* Some ADRs are written
* Design Goals formalized
* Lot's of documentation placeholders were created
* TODO: write more docs :)
* TODO: find a better splash page image. The challenge here is to find an image that meshes with the white text on the left side.

Jekyll can be started locall and this is what it looks like:

![Screenshot 2019-10-21 at 17 15 25](https://user-images.githubusercontent.com/28268662/67218459-b12d9580-f426-11e9-91f2-5657557762f5.png)
![Screenshot 2019-10-21 at 17 17 21](https://user-images.githubusercontent.com/28268662/67218460-b12d9580-f426-11e9-87a2-dbbccd2041d9.png)

**Comment by NearW** [comment]
I got some user feedback regarding an addition for the installation docs:

Although ccsh has both, a Windows batch and a Linux shell flavor, the latter runs well on the Ubuntu subsystem in Windows 10 (no Cygwin or gitbash needed).

A rough outline of installation steps:
- Copy the codecharta-analysis binaries to a location of your choice on the Windows hard disk.
- Activate Linux subsystem in Windows features (requires privileged user).
- Open the Windows store and install the (free) Ubuntu version of your choice, e.g. 18.04 LTS.
- Once you have successfully openend the Ubuntu shell from the Windows start menu, you may perform the following steps:
-- Install a JRE e.g. by executing sudo apt-get update && sudo apt-get install default-jre
-- Add the ccsh executables to the shell PATH, e.g. PATH=/mnt/c/codecharta-analysis:$PATH
