### ISSUE TITLE
CCSH script generator

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#683]
# Feature request

Provide a ccsh script generator for the following importers: SourceCodeParser, SonarImporter, ScmLogParser and MergeFilter.

The ccsh generator is a separate project on the same level as analysis and visualization and uses Typescript.

**Comment by BridgeAR** [comment]
I guess this is meant as a way to automate the tooling? I am going to open a new issue around that topic and I am going to close this one for now.
