### ISSUE TITLE
Custom persisted scenarios in Standalone

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#684]
# Feature request

This is #675 but for the standalone. In the standalone we should make sure that scenarios are persisted which might be different than in the web-version. If I upgrade my standalone version the scenarios should still be there. Depending on how this works in nw.js we might need to store it as a separate user.settings file.

**Comment by BridgeAR** [comment]
@Richargh do you know if the standalone version is frequently used? Or is it likely that people mostly use the website instead?

**Comment by BridgeAR** [comment]
What this feature pretty much represents is to try to load a local settings file during startup. This file would automatically be used instead of the local storage in case the standalone version is used. This is important for everything that is saved in the local storage right now.

@ce-bo FYI

**Comment by ce-bo** [comment]
Thanks to PR #1709 we can now change the CustomConfigs and CustomScenarios to adapt the new CodeChartaStorage system.

**Comment by BridgeAR** [comment]
@ce-bo is this already resolved? Or do we still have to implement something here?
