### ISSUE TITLE
By default the distribution metric should be the same as the size metric

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#689]
# Feature request

Depending on the map, the distribution metric currently defaults to seemingly random metrics: line_coverage, classes and interfaces, pairingRate etc. 

**Intended** as a quick-fix: if this is not simple to do within **a couple of hours** then please 1) don't do it, 2) comment why it's difficult (tech issues, test issues, unclear goals, etc.) 3) let's figure out together if we should do it.

## Description

Why does it do that? Can we change it so it defaults to the size metric (usually rloc)?

**Comment by alschmut** [comment]
sure, that's an easy fix 👍
