### ISSUE TITLE
Tree View should by default have openend the first level

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#690]
# Feature request

Opening the tree view currently results in seeing the closed folder "root". This is inconvenient, because I gain no knowledge from this and always have to expand the root folder anyway. 

**Intended** as a quick-fix: if this is not simple to do within **a couple of hours** then please 1) don't do it, 2) comment why it's difficult (tech issues, test issues, unclear goals, etc.) 3) let's figure out together if we should do it.

## Description

Can we expand only the root folder by default? Instead of:

/root/de.maibornwolff.codecharta/visualization/app

we'll see:

/root/de.maibornwolff.codecharta/visualization/app
|- app.scss
|- app.ts
|- index.html
|- mixins.scss
|- puppeteer.helper.ts
|- codecharta
|- testVille

**Comment by alschmut** [comment]
Your description is slightly inconsistent.. do you want to have opened the **first** level or a potentially useful one on level 1,2,3,4,5,...? Corresponding to your "imported" example, opening the first level would show
```
/root
|- de
|- otherFilesInRoot.md
```

`/root/de.maibornwolff.codecharta/visualization/app` is not the first level, but the 3rd (if `de.maibornwolff.codecharta` counts as one)

**Comment by Richargh** [comment]
@alschmut it's the first level when considering path compaction that we have. I don't want any logic that figures out what a useful level is.
