### ISSUE TITLE
During search only the found items should count

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#692]
# Feature request

Suppose I have a map and I want to find out how much code we have that concerns `**/*import*` of data. I can type this query into the search field. Afterwards I hover with my mouse over the whole project but the metric sum now includes all files, not just those for import.

**Intended** as a quick-fix: if this is not simple to do within **a couple of hours** then please 1) don't do it, 2) comment why it's difficult (tech issues, test issues, unclear goals, etc.) 3) let's figure out together if we should do it.

## Description

When I search for a term only the found files should count in the metric sum/average.

**Comment by alschmut** [comment]
I guess you are talking about the metric values shown next to the metricChooser and in the detailPanel/attribute-sidebar.

**Comment by Richargh** [comment]
@alschmut please take a look again, is it now more clear?

**Comment by BridgeAR** [comment]
AFAIK this is already fixed. Let's check and just fix this if not.

**Comment by RomanenkoVladimir** [comment]
I don't understand the bug?
Hovering root while filtering for e.g. **/*state* will give us the metric values for all files and not just the highlighted ones in the online demo, however I am not sure that it is not intended`?

**Comment by ce-bo** [comment]
We talked in our Weekly about this issue. @Richargh Could you please explain what you mean here?
The currently described behaviour seems unintuitive for the end-user.
