### ISSUE TITLE
Count how many files belong to the file extension

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#695]
# Feature request

When reviewing source code it's a good idea to check you have received the right artefact. To do that you compare the lines of code you have received and the number of .kt/.html etc. files with the expected value.

## Description

In #495 we added a file distribution bar that shows the distribution of file extensions such as .kt or .java. When we click on that bar it opens downward and shows the percent for the extension. Can we also show how many .kt/.ts etc. files we have received together with a file symbol?

**Comment by alschmut** [comment]
Its not most intuitive way, but if you select metric `unary`, every file is counted as `1`... then you got the file count 😄

**Comment by Richargh** [comment]
> Its not the most intuitive way, but if you select metric unary, every file is counted as 1... then you got the file count 

Hadn't thought of that. That's a cool extra thing we have, but as you said it's the percentage.

**Comment by alschmut** [comment]
I just need some clarification, as I am not into the topic, for that issue: The file extension bar always shows data corresponding to the selected metric. For example using the `sonar_bugs` metric:

|path|sonar_bugs|
|---|---|
|file1.aaa | 3 |
|file2.aaa | 7 |
|file3.bbb | 10 |
|file4.ccc | 15 |
|file5.ccc | 5 |
|file6.ccc | 10 |

- the distribution bar shows
  `sonar_bugs`: `aaa (20,00%) | bbb (20,00%) | ccc (60,00%)`

- and you want the number of files like this?
  `sonar_bugs`: `aaa (20,00%, 2 files) | bbb (20,00%, 1 file) | ccc (60,00%, 3 files)`

- or should we add the absolute values and let the user select the intuitive `unary` metric?
  `sonar_bugs`: `aaa (20,00%, 10) | bbb (20,00%, 10) | ccc (60,00%, 30)`

**Comment by alschmut** [comment]
This issue was actually implemented with version 1.41.0 in #545

**Comment by Richargh** [comment]
Secret features. I did not know about this feature. Very nice!
