### ISSUE TITLE
Metric values can overlap metric names

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#696]
# Feature request

Metric values can grow quite large. The lines of code especially can reach 20 million lines on larger maps. Currently CodeCharta grows the space for metric values a bit, but larger values are still clipped:

![Metric-Value-Current](https://user-images.githubusercontent.com/28268662/63170595-e938e680-c039-11e9-8b10-aee07e099116.png)

## Description

How about we let the metric values overlay the metric names? While hovering we don't need to change the metric names anyway. Then we also don't need the dash when nothing is hovered. I suggest we add a grey box around the metric values (a bit like our scenario button). That should also make the metric values changing much more obvious. 

After, when not hovering
<img width="40%" src="https://user-images.githubusercontent.com/23529226/63171192-526d2980-c03b-11e9-9725-3681426740d5.jpeg">

After, when hovering
![Metric-Value](https://user-images.githubusercontent.com/28268662/63190280-2fa43a80-c066-11e9-8861-d557c569d50f.png)

We can also change the color for positive, negative deltas. For this mockup I put the delta metric on top of the current metric to make it clear that they are related:

![Metric-Value-Delta](https://user-images.githubusercontent.com/28268662/63190129-d936fc00-c065-11e9-848e-0f83ed3a201d.png)

The visualization should look like the one from #735

**Comment by alschmut** [comment]
I like the grey, red, green elements, but would make them slightly smaller so they fit on top of the grey line. I would also suggest to remove dash, when nothing is hovered, and possibly make the select slightly longer.

Before, when not hovering
<img width="40%" src="https://user-images.githubusercontent.com/23529226/63170781-62383e00-c03a-11e9-8b01-78a7b20de898.jpeg">

After, when not hovering
<img width="40%" src="https://user-images.githubusercontent.com/23529226/63171192-526d2980-c03b-11e9-9725-3681426740d5.jpeg">

After, when hovering
<img width="40%" src="https://user-images.githubusercontent.com/23529226/63171033-fd311800-c03a-11e9-92dd-f8f8d0149ee1.jpeg">

**Comment by Richargh** [comment]
I changed the delta mockup and included the suggestion to remove the dash.

**Comment by alexhunziker** [comment]
I implemented it, so that the style matches what we now have in the attribute-side-bar (i.e. for delta mode there are now two rounded boxes, like in the mockup of @alschmut). Any objections to that?

For the colouring in the delta mode: I noticed that currently we only color the delta for the height metric in the ribbon-bar, but in the attribute-side-bar we colour all 3 metrics. Which behaviour do you prefer? I can see reasons for both and do not have a strong opinion on this.

**Comment by alschmut** [comment]
What do you think about this idea to move the slider-labels and make them slightly smaller in order to get more space in the ribbon-bar?

Before
![Screenshot 2019-11-06 at 18 21 21](https://user-images.githubusercontent.com/23529226/68321621-52bd1400-00c2-11ea-8f3d-24b4aa31c174.jpg)


After
![Screenshot 2019-11-06 at 18 19 49](https://user-images.githubusercontent.com/23529226/68321464-0f62a580-00c2-11ea-8e3a-9fdea277d8bc.jpg)

**Comment by alexhunziker** [comment]
I have also reduced the size of the sliders (including the range slider of the color section and the edge metrics) Here is what it looks like:

![grafik](https://user-images.githubusercontent.com/20796577/68323670-358a4480-00c6-11ea-8986-8cfeebf33dac.png)

Now, as you can see, there is already quite some overlapping going on even tough it is a relatively small map. When we have bigger maps, or a delta map I fear that it will cover most of the metric name pretty soon, which may look odd. 

Regarding the labels of the sliders: I generally like the idea of moving them above the sliders, looks cleaner in my opinion.

**Comment by alschmut** [comment]
I guess we have multiple options here:
- How about if we hide the color section completely in delta mode, like mentioned in #769 and enlarge the remaining sections? Then we have more space for the overlapping metric values
- or we could somehow try to show the metric values below its metric name. I think generally this would look nice as well. The only problem will be that the ribbonbar then needs more height (even if we reduced the font size)

**Comment by fatihi** [comment]
@alschmut I like what you did with the slider labels! Have to agree with @alexhunziker , they look cleaner.
I'm not sure about both of your suggestions though... 

Hiding the color section might be a good idea, but that means that you start having different uis for delta and normal mode, which could be hard to manage.

About increasing the height, I would have to see an example how much the height is increased, but I would prefer not to increase it if possible.

**Comment by alschmut** [comment]
Thanks @fatihi fir you thoughts!
- Hiding the color section is not a big code change.
- I pushed a separate branch called [spike/696/rework-slider-labels](https://github.com/MaibornWolff/codecharta/tree/spike/696/rework-slider-labels) with the commit for the moved sliders, so you can have another look.

**Comment by fatihi** [comment]
Thank you, I will check it out!

**Comment by alschmut** [comment]
After talking to @fatihi we decided to:
- use the new slider-labels on [spike/696/rework-slider-labels](https://github.com/MaibornWolff/codecharta/tree/spike/696/rework-slider-labels)  
- reduce the width only a bit so all sections inside the ribbonBar fit at least on a/my 13" MacBook display.

Afterwards we implemented all the issue mentions and could merge it, as the new metric-value boxes are quite worth seeing in my opinion. If we should have new ideas regarding a more efficient/fitting implementation for the metric values / with of the sections / or with the delta mode, we can implement that with a later issue or in addition to #769
