### ISSUE TITLE
Invert AreaMetric

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#697]
# Feature request

## Description

We have options to invert the height and the color to adapt to metrics like test-coverage, which are interpreted to be better the higher the values are. If I want to set a metric like this to areaMetric, I would like to invert the amount of area, which is used for the nodes.

## Required steps
- [x]  Implement feature in AngularJS
- [x] Migrate feature to Angular

**Comment by BridgeAR** [comment]
This could be done by using `<ctrl> + <left click>` on a building or folder. That should be pretty straight forward.
