### ISSUE TITLE
Split event management into multiple services

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#698]
# Feature request

## Description

Since we merged #671 we want to split the settingsService with its events into multiple services, each storing only one property or a few combined ones.

### Ideas
- Use the current Settings interface structure to adapt folder structure
  - Rename the `settingsService` folder into `settings`
  - Add the following folders into the `settings` folder:
    - appSettings
    - dynamicSettings
    - fileSettings
    - treeMapSettings? Maybe we find a better solution where to store the `mapSize` property
- Each property, which already has its own event will be separated into a separate service inside the correct settings sub folder. The Service contains its event subscriber interface and its static event name.
- The `SettingsService.updateSettings()` will not be called from within a component. It only listens to the other new services and updates its settings bundle.

### Before starting, some Questions:
- Think about how we could implement #476 with the new settings services. How do we store multiple settings, if we have multiple services?
- We should finally check, if RxJS makes our life easier with lots of events.

**Comment by alschmut** [comment]
I was taking some moments to rethink our intent to split the settingService together with ideas to store multiple settings version for different maps or even a history of settings for each file.

Instead of:
- splitting every single property into a separate service.
- collecting data from every service into a all encompassing settingService (in case many of the properties are needed)

we could:
- keep the settingsService as a central and structured data storage
- create separate services for each settings-property* (without storing the data itself!)
- each service will 
  - provide a method to update the property and store the data inside the settingsService, 
  - collect the property data from the settingsService
  - broadcast a separate event for only the one property
- the settingsService will ideally not broadcast any event with the complete settings object

=> this means the UI components and other services only access the property-services
=> this also makes it easier to manage multiple settings, as only the settingsService could provide a blackBox storage of map or time-dependant settings, without having to update every of the separate services

An example of such a service is shown below:

###### * a property is for example the `areaMetric` or the `amountOfEdgePreviews`

```
import { SettingsService } from "../settings.service";
import { IRootScopeService } from "angular";

export interface AmountOfEdgePreviewsSubscriber {
	onAmountOfEdgePreviewsChanged(amountOfEdgePreviews: number)
}

export class AmountOfEdgePreviewsService {

	private static AMOUNT_OF_EDGE_PREVIEWS_CHANGED_EVENT = "amount-of-edge-previews-changed-event"

	constructor(private settingsService: SettingsService) {
	}

	public getAmountOfEdgePreviews(): number {
		return this.settingsService.getSettings().appSettings.amountOfEdgePreviews
	}

	public updateAmountOfEdgePreviews(amountOfEdgePreviews: number) {
		this.settingsService.updateSettings({
			appSettings: {
				amountOfEdgePreviews: amountOfEdgePreviews
			}
		})
		this.notify()
	}

	private notify() {
		this.settingsService.notify(
			AmountOfEdgePreviewsService.AMOUNT_OF_EDGE_PREVIEWS_CHANGED_EVENT, 
			{ amountOfEdgePreviews: this.settingsService.getSettings().appSettings.amountOfEdgePreviews }
		)
	}

	public static subscribe($rootScope: IRootScopeService, subscriber: AmountOfEdgePreviewsSubscriber) {
		$rootScope.$on(AmountOfEdgePreviewsService.AMOUNT_OF_EDGE_PREVIEWS_CHANGED_EVENT, (event, data) => {
			subscriber.onAmountOfEdgePreviewsChanged(data.amountOfEdgePreviews)
		})
	}
}
```

**Comment by alexhunziker** [comment]
So if I understand correctly the idea is to generate one service per setting, while keeping the settingsService to persist the actual state, right? And if so, we would have 20-30 services or so, which look very similar to the one you have shown above?

If so I asked myself if we are not generating too much boilerplate code by splitting the settings service (we would have ~40 loc plus let's say ~80 loc of specs per service). Aren't we creating a bit much overhead with this? Or am I missunderstanding something here?

**Comment by alschmut** [comment]
Yes, you get it right. It is quite some boilerplate code (which could be generated by plop), but the advantage I see is:
- The UI components get separate events, that are defined in separate services (unlike our current state to put all events into the settingsService/Events file)
- all settings together can be managed inside the settingsService, when we want to save any of the settings properties in multiple states (for every map a separate object). Doing this inside every single service gives us even more boilerplate and potential inconsistency.

I don't claim that this is the best solution, but it is a lot better for each UI component and service, which uses the settingsService up to date, because:
- properties can have their own debounce time
- the onSettingsChanged event is mostly not needed
- the onSettingsChanged with its update object (containing only the updated properties) does not have to be checked for the "wanted" property
- keeping the update object inside the settingsService up to date is tricky and makes problems again and again with our debounce time and the partially split events.

This issue is meant to be discussed from multiple perspectives and various ideas, because its hopefully gonna result in an architecture we will use for a long time.

**Comment by alschmut** [comment]
After we (@NearW, @JaiJoPa, @alexhunziker and me) had a discussion about the event splitting we came up with the following:
- Having one abstract class which provides all unified functionality
- And many very small Services, which are used by the UI-components and set an unique EVENT_NAME

... more information following

```
import { SettingsService } from "./settings.service"
import { IRootScopeService } from "angular";
import _ from "lodash"

export interface SettingsFieldSubscriber {}

export class AbstractService {

	public static EVENT_NAME: string
	private static FIELD_NAME: string
	private debounceTime: number = 0
	private readonly debounceBroadcast: (data: any) => void

	constructor(private $rootScope: IRootScopeService, private settingsService: SettingsService) {
		AbstractService.generateID()
		this.debounceBroadcast = _.debounce((data) => {
			this.$rootScope.$broadcast(AbstractService.FIELD_NAME, data)
		}, this.debounceTime)
	}

	public get() {
		return this.settingsService.get(AbstractService.FIELD_NAME)
	}

	public update(value) {
		this.settingsService.update(AbstractService.FIELD_NAME, value)
		this.notify(value)
	}

	private notify(value) {
		this.debounceBroadcast({ [AbstractService.FIELD_NAME]: value })
	}

	private static getMethodNameFromEventName(): string {
		return null
	}

	private static generateID() {
		this.FIELD_NAME = AbstractService.EVENT_NAME
	}

	public static subscribe($rootScope: IRootScopeService, subscriber: SettingsFieldSubscriber) {
		$rootScope.$on(this.EVENT_NAME, (event, data) => {
			const methodName = this.getMethodNameFromEventName()
			subscriber[methodName](data[this.FIELD_NAME])
		})
	}
}
```

```
export interface AmountOfEdgePreviewsSubscriber extends SettingsFieldSubscriber {
	onAmountOfEdgePreviewsChanged(amountOfEdgePreviews: number)
}

export class MyService extends AbstractService {

	constructor($rootScope: IRootScopeService, settingsService: SettingsService) {
		MyService.EVENT_NAME = "my-event-changed"
		super($rootScope, settingsService)
	}
}
```

**Comment by alschmut** [comment]
### A working example can be found on the linked branch:
- Inheriting static variables didn't work, which means the eventName, fieldName as well as the subscribe methods are now NON-static.
- Instead of providing the event name like `"area-metric-changed-event"` and reconstructing the fieldName and the methodName, I turned it the other way around and provide a camelCase fieldName within the constructor `"areaMetric"` and and enum EventType. This makes it in my opinion easier to follow the practice.

### Issues I found
- The implementation of scenarios will have to be adapted, as we currently store a partial Settings object as a scenario and send that to the settingsService, whenever it has to be applied.

### Suggestions
- Add another field to provide a defaultValue, which will be set when codeCharta is loaded
- Add a `reset()` method to the `AbstractService` to reset the value to the defaultValue



```
import { SettingsService } from "./settings.service"
import { IRootScopeService } from "angular"
import _ from "lodash"

export enum EventType {
	Added = "added",
	Removed = "removed",
	Changed = "changed"
}

export interface SettingsFieldSubscriber {}

export abstract class AbstractService {
	private eventName: string
	private readonly debounceBroadcast: (data: any) => void

	constructor(
		private $rootScope: IRootScopeService,
		private settingsService: SettingsService,
		private fieldName: string,
		private eventType: EventType,
		private debounceTime: number = 0
	) {
		this.debounceBroadcast = _.debounce(data => {
			this.$rootScope.$broadcast(this.eventName, data)
		}, this.debounceTime)
		this.generateEventName()
	}

	public subscribe($rootScope: IRootScopeService, subscriber) {
		$rootScope.$on(this.eventName, (event, data) => {
			const methodName = this.getMethodName()
			subscriber[methodName](data[this.fieldName])
		})
	}

	public get() {
		return this.settingsService.get(this.fieldName)
	}

	public update(value) {
		this.settingsService.updateObject(this.fieldName, value)
		this.notify(value)
	}

	private generateEventName() {
		this.eventName = this.getSplitFieldName()
			.concat(this.eventType)
			.concat("event")
			.map(x => x.toLowerCase())
			.join("-")
	}

	private getMethodName(): string {
		return ["on"]
			.concat(this.getSplitFieldName())
			.concat(this.eventType)
			.map((x, index) => (index == 0 ? x : _.capitalize(x)))
			.join("")
	}

	private getSplitFieldName() {
		return this.fieldName.replace(/([A-Z])/g, "-$1").split("-")
	}

	private notify(value) {
		this.debounceBroadcast({ [this.fieldName]: value })
	}
}
```


```
import { SettingsService } from "./settings.service"
import { IRootScopeService } from "angular"
import { SettingsFieldSubscriber, AbstractService, EventType } from "./abstract.service"

export interface AreaMetricSubscriber extends SettingsFieldSubscriber {
	onAreaMetricChanged(areaMetric: string)
}

export class AreaMetricService extends AbstractService {
	constructor($rootScope: IRootScopeService, settingsService: SettingsService) {
		super($rootScope, settingsService, "areaMetric", EventType.Changed)
	}
}
``

**Comment by NearW** [comment]
Thanks for your investigation, @alschmut 

## Event Naming
What do we, if we don't add, remove or change the field?
For example: We're focusing a node. This means, we're setting the focusedNodePath from an empty string `""` to `"my/Path"`
Is this changing or adding?

Another example: We now unfocus the node. So we're setting the value back to `""`.
Changing or removing?

If we decide both to be changing, we have the same problem again that we have one event for two different actions. On the other hand, `addFocusedNodePath` and `removeFocusedNodePath` sound ok, but a less technical and more business logical name would be better in my opinion.

I think `onFocusNode` and `onUnfocusNode` just sounds better.

## Default Subscription
Also, when a service provides a method `subscribe`, I expect to subscribe to the same kind of event all the time. I suggest that to be the CHANGED event. With your new approach, this could be anything provided in the constructor, making it quite unpredictable.

## What do we actually want?
- A default event to know, if the value changed in any way
- A default event name for this
- A default subscribe method that let's us subscribe to that event
- Being able to add more subscribe-methods and events to our services after inheriting

And let's move string transformation for event-name generation to it's own class

**Comment by NearW** [comment]
## My suggestion

```
import { SettingsService } from "./settings.service"
import { IRootScopeService } from "angular"
import _ from "lodash"

export interface SettingsFieldSubscriber {}

export abstract class AbstractService {
	private eventName: string
	private readonly debounceBroadcast: (data: any) => void

	constructor(
		private $rootScope: IRootScopeService,
		private settingsService: SettingsService,
		private fieldName: string,
		private debounceTime: number = 400
	) {
               
		this.eventName = new SettingNameGenerator(eventName).generateEventName()
		this.debounceBroadcast = _.debounce(data => {
			this.$rootScope.$broadcast(this.eventName, data)
		}, this.debounceTime)
	}

	public subscribe($rootScope: IRootScopeService, subscriber) {
		$rootScope.$on(this.eventName, (event, data) => {
			const methodName = new SettingNameGenerator(eventName).getMethodName()
			subscriber[methodName](data[this.fieldName])
		})
	}

	public get() {
		return this.settingsService.get(this.fieldName)
	}

	public update(value) {
		this.settingsService.update(this.fieldName, value)
		this.notify(value)
	}

	private notify(value) {
		this.debounceBroadcast({ [this.fieldName]: value })
	}
}
```

```
import { SettingsService } from "./settings.service"
import { IRootScopeService } from "angular"
import { SettingsFieldSubscriber, AbstractService, EventType } from "./abstract.service"

export interface AreaMetricSubscriber extends SettingsFieldSubscriber {
	onAreaMetricChanged(areaMetric: string)
}

export class AreaMetricService extends AbstractService {
	constructor($rootScope: IRootScopeService, settingsService: SettingsService) {
		super($rootScope, settingsService, "areaMetric")
	}
}
```

```
export class SettingNameGenerator {
        constructor(private fieldName: string) {}

        public generateEventName(): string {
		return this.getSplitFieldName()
			.concat("changed")
			.concat("event")
			.map(x => x.toLowerCase())
			.join("-")
	}

        public generateMethodName(): string {
		return ["on"]
			.concat(this.getSplitFieldName())
			.concat("changed")
			.map((x, index) => (index == 0 ? x : _.capitalize(x)))
			.join("")
	}

        private getSplitFieldName(): string {
		return this.fieldName.replace(/([A-Z])/g, "-$1").split("-")
	}
}

**Comment by alschmut** [comment]
With @NearW I just discussed following topics:
- Extracting the SettingNameGenerator is a very good idea
- implementations of the AbstractService can overwrite the `update()` method to send multiple events like (myVariableAdded and myVariableRemoved)
- Create a separate AbstractDebounceClass which debounces the broadcast, as this gets trickier, when we want to send multiple events from one service
- Remove the debounce from the normal AbstractClass, as it is only necessary for sliders and inputFields like the search.
- Create BundleServices like AppSettings, DynamicSettings and FileSettings Services, which inject its partial Services like the AreaMetricService for the DynamicSettingsService. This service then provides the option to update multiple of its settings
- Same as the bundle services, a settingsBundleService exists, which can split an settingsUpdate object into smaller parts and calls the bundleServices appSettingsService, etc...
- This means there exists a linear dependency through the services. The settingsService acts like a dataStorageDictionary for all settings, but doesn't not accept recursiveUpdateObjects (as of now) instead this has to be done with the SettingsBundleService
   `SettingsService -> FieldService -> DynamicSettings -> SettingsBundleService`
- Check if we will have a circular dependency
- Each Service should have a defaultValue, which can be applied. **Question**: Do we use an event or a public `resetToDefault()`. method on which the defaultValue gets applied? Example: Use of the resetButton.
- The Scenario service could call the SettingsBundleService with a partial settingsObject

**Comment by NearW** [comment]
I got some feedback from Fatih today:
- DON'T create event-names and method-named from a string given in the constructor
Even though this will reduce code duplication a lot, the class is super difficult to debug and understand in general. Also we don't create default behaviour that we might not use; for example a subscribe method to `onFocusNodeChanged`
- Instead create an interface `SettingFieldService` that looks like this:
```
export interface SettingFieldService {
	get(field: string)
	update(value: any)
}
```
Since we usually have custom event methods, we won't provide one in the interface (and without subscribe, there won't be a notify either)

- Use service-injection to update from viewModel to state an observer pattern to update from state to viewModel
Here is an example on how we update the blacklist after the user excludes a building using service injection:
`UI-Controller knows BlacklistService (has it injected), calls blacklistService.update(blacklist)` and notifies subscribers => `BlacklistService -> UI-Controller`
`BlacklistService knows FileSettingsService and calls fileSettingsService.update(partialFileSettings)` => `FileSettingsService -> BlacklistService -> UI-Controller`
`FileSettingsService knows SettingsService and calls settingsService.update(partialSettings)` => `SettingsService -> FileSettingsService -> BlacklistService -> UI-Controller`

But how do we let the trigger the blacklist-changed-event in the BlacklistService when we updated the whole settings at once? Observer-Pattern.
`ScenarioService knows SettingsService and call settingsService.update(partialSettings)` 
SettingsService provides a subscribe method for FileSettingsService, AppSettingsService and DynamicSettingsService. Once the settings get updated, the three services are notified.
FileSettingsService provides a subscribe method for BlacklistService. Once the FileSettings get updated, BlacklistService will be notified. The BlacklistService can notifier his subscribers then.

**Comment by NearW** [comment]
```
export interface SettingFieldService {
	get(field: string)
	update(value: any)
}
```

```
export interface AreaMetricChangeSubscriber {
	onAreaMetricChange(areaMetric: string)
}

export class AreaMetricService implements SettingFieldService, DynamicSettingsSubscriber {
	private eventName: string = "AREA_METRIC_CHANGE"
	private fieldName: string = "areaMetric"
	private default: string = "rcc"

	constructor(private $rootScope: IRootScopeService, private dynamicService: DynamicService) {
		dynamicService.subscribe(this.$rootScope, this)
		this.reset()
	}

	public onDynamicSettingsChange(dynamicSettings: DynamicSettings) {
		this.notify(dynamicSettings.areaMetric)
	}

	public subscribeToAreaMetricChange($rootScope: IRootScopeService, subscriber: AreaMetricChangeSubscriber) {
		$rootScope.$on(this.eventName, (event, data) => {
			subscriber.onAreaMetricChange(data[this.fieldName])
		})
	}

	public get(field: string) {
		return this.dynamicService.get(this.fieldName)
	}

	public update(areaMetric: string) {
		this.dynamicService.update({ areaMetric })
	}

	public reset() {
		this.update(this.default)
	}

	private notify(areaMetric: string) {
		this.$rootScope.$broadcast(this.eventName, { areaMetric })
	}
}
```

```
export interface DynamicSettingsSubscriber {
	onDynamicSettingsChange(dynamicSettings: DynamicSettings)
}

export class DynamicSettingsService implements SettingsSubscriber {
	private eventName: string = "DYNAMIC_SETTINGS_CHANGE"

	constructor(private $rootScope: IRootScopeService, private settingsService: SettingsService) {
		settingsService.subscribe(this.$rootScope, this)
	}

	public onSettingsChange(settings: Settings) {
		this.notify(settings.dynamicSettings)
	}

	public subscribe($rootScope: IRootScopeService, subscriber: DynamicSettingsSubscriber) {
		$rootScope.$on(this.eventName, (event, data) => {
			subscriber.onDynamicSettingsChange(data.dynamicSettings)
		})
	}

	public get(field: string) {
		return this.settingsService.getSettings().dynamicSettings[field]
	}

	public update(dynamicSettings: DynamicSettings) {
		this.settingsService.update({ dynamicSettings })
	}

	public reset() {
		//Call each injected service.reset()
	}

	private notify(dynamicSettings: DynamicSettings) {
		this.$rootScope.$broadcast(this.eventName, { dynamicSettings })
	}
}
```

```
interface SettingsSubscriber {
	onSettingsChange(settings: Settings)
}

export class SettingsService {
	private eventName: string = "SETTINGS_CHANGE"

	constructor(private $rootScope: IRootScopeService, private dynamicService: DynamicSettingsService) {
	}

	public subscribe($rootScope: IRootScopeService, subscriber: SettingsSubscriber) {
		$rootScope.$on(this.eventName, (event, data) => {
			subscriber.onSettingsChange(data.settings)
		})
	}

	public getSettings() {
		return this.settings
	}

	public update(dynamicSettings: DynamicSettings) {
		//update settings partially
		this.notify(dynamicSettings)
	}

	private notify(settings: Settings) {
		this.$rootScope.$broadcast(this.eventName, { settings })
	}
}
```

**Comment by alschmut** [comment]
I think generally this is a good approach. I just found one more question:
- Which object does e.x. the SettingsService notify? The full settings object? How do the other services then know, what was updated?
- Another goal with this refactoring was also to eliminate the settingsService.update object. If e.x. nobody listens to the settingssService (except for the dynamicSettingsService etc.), we won't need to send a full settingsObject, correct? Because in the end the small services (like AreaMetricService ) will handle the events, which are received by the UI components etc.

**Comment by fatihi** [comment]
- The notify only works downwards. The SettingsService would notify FileSettings, AppSettings and DynamicSettings. These can then decide if anything they care about changed and continue notifying.
- You will have the option to update either some small settings or even something big, depending on what changes. Of course you should only update as much as necessary. As described above, if something in SettingsService is updated, there will be a wave of updates, which should be avoided if possible.

**Comment by mrpatpat** [comment]
Hi, 

there are a few things I would like to add to this discussion. 

Firstly I think having a blueprint for state managing components is a good idea, since state management will always be an important part. Unidirectional flow is a good and proven idea, too.
But I am not sure if inheritance is the way to go here. Are you sure there will be no problems with the angular dependency injection with inheritance? I think it is a good idea to at least think about the inheritance vs. composition issue here. Personally I dont like using an abstract service for one possible optional trait of a service because when you decide to add another trait you will need another inheritance layer or break single responsibility and create a god object. 
Secondly, handling of the observe logic can be done by rxjs. You can implement it yourself or through the angular event mechanism, but you can easily use a documented and tested library for this purpose.  
And lastly, the whole idea reminds me of redux. Why not just use redux? There are AngularJs integrations for it.

**Comment by NearW** [comment]
We want to move all data (model) from the services to a single source of truth store. This will remove the term `settings` in our application as we used it before. Instead, we'll manage ONE big state that contains the whole model including things like the scene (selectedBuilding, hoveredBuilding, codeMapMesh), fileStates and the properties of our settings object.

Steps to move a property from a service to the new store:
1. Create Actions
2. Create Reducer and it's tests
3. Create a Service for subscription and it's tests
4. Find all references for earlier subscription on that property and replace it with the new service
(5.) If you have to update a temporary settings object, because it got passed as a parameter to a function, add a TODO. For an example, search the project for "TODO"

We will handle 1-2 properties per PR. Please use the following naming convention for branching:
**tech/698/redux-MY_PROPERTY-_MAYBE_ANOTHER_PROPERTY**

**Comment by alschmut** [comment]
For further work on this issue and a more specific feature request, we continue with #804
