### ISSUE TITLE
Performance of tool tips

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#70]
It takes too much time for the tooltips to show for metrics and scenarios (in the online demo). I tried it with npm run serve and they seem to be shown not at all. Any ideas what is causing this?

**Comment by mrpatpat** [comment]
As stated in [W3C](https://www.w3schools.com/tags/att_global_title.asp) the title tag is shown as a tooltip "mostly". Current Firefox and Chrome display it correctly for me. 
Therefore I guess it is a browser compatibility problem. It can be solved by using JS or CSS tooltips. 
I also fixed the problem that the dropdown itself had no tooltip. Only the options had them (after clicking on the dropdown).

**Comment by ukinimod** [comment]
I was using Safari as browser. It takes about 2-3 seconds for the tooltips to appear.

**Comment by mrpatpat** [comment]
I will look into the problem in safari.
