### ISSUE TITLE
Building stays highlighted when Settings are changed

### ISSUE THREAD

**Issue by JaiJoPa** [MaibornWolff/codecharta#711]
## Description

Building stays highlighted when Settings are changed

# Bug

## Expected Behavior

When Settings are changed and the map is updated, only the hovered building should be highlighted

## Actual Behavior

When a building is marked and then the settings are changed, hovering a random building will additionally show the previous marked building as highlighted. 

### Screenshots
![highlight_bug](https://user-images.githubusercontent.com/50145538/64010817-c834c300-cb1a-11e9-857c-ccab3be770a7.gif)

## Steps to Reproduce the Problem

  1. Mark a building
  2. Change settings, e.g. area-margin setting
  3. Hover over a random building

## Specifications

  - Version: 1.32.0
  - Platform: Windows
  - Browser: Chrome, Firefox

**Comment by NearW** [comment]
Linked to #672

**Comment by alschmut** [comment]
This will be fixed with #527.

**Comment by alexhunziker** [comment]
Fixed by PR #735 (closing  issue #527)
