### ISSUE TITLE
Delta mode does not work with exported files

### ISSUE THREAD

**Issue by alexhunziker** [MaibornWolff/codecharta#730]
# Bug

## Expected Behavior
Switching to Delta Mode should actually render the map in delta Mode.

## Actual Behavior
When I load two Maps into CodeCharta and switch to Delta mode, the buildings become grey, however they are not recalculated. 

As shown in the screenshot, if I for example was in the Multiple mode before, both Maps (which have a delta) are still shown side by side just now in grey.

### Screenshots
![grafik](https://user-images.githubusercontent.com/20796577/65078334-17914500-d99d-11e9-94a2-e803711ff15f.png)

## Steps to Reproduce the Problem

  1. Load two Maps with a Delta into CodeCharta
  1. Switch to Delta Mode

## Specifications

  - Version: 1.33
  - Platform: Windows
  - Browser: Firefox

**Comment by alschmut** [comment]
So the following options worked for me on the current master and the released 1.33.0 on GitHub.io:
- Safari on Mac
- Chrome on Mac
- Firefox on Mac
- Chrome for Windows in Parallels (on Mac)
- Firefox for Windows in Parallels (on Mac)

You can reproduce the bug on your windows machine in Firefox? How about other browsers? Which maps did you load and do they potentially have no delta?

**Comment by alexhunziker** [comment]
So I did this with a current and an old version of codechartas demo map (i.e. the visualization). There is a delta between them (the old file is approx 3 month old). It is reproducible on Windows 10 with Firefox (69.0) and Chrome (76.0) both on my work laptop as well as on my private machine. I did test it on the released 1.33.0

The issue seems to be that the delta map is never generated. The map selected before switching to delta mode is still displayed, and you can still operate on it (exclude nodes, ...) but changing metrics etc does not work anymore. When switching back to single/multiple mode CodeCharta works again as expected.

**Comment by alschmut** [comment]
So, I can't tell why it doesn't work, but I found out the following:
- delta mode works with every other map I tried, just not with the two maps I received from @alexhunziker.
- I also think this is browser independent.
- I tried the two maps from @alexhunziker with versions 1.28.0 and it didn't work either. So I rather think, there is something wrong with the files, which doesn't mean that this is not potentially our fault...
- #679 might be a first step to clean our exported files, as one can see that the files Alex used are exported (includes attributes on the root-level node)

**Comment by alschmut** [comment]
@alexhunziker do you still find this bug?

**Comment by alexhunziker** [comment]
Yes, the issue can still be reproduced with the maps attached

[broken_delta.zip](https://github.com/MaibornWolff/codecharta/files/4035479/broken_delta.zip)

**Comment by alschmut** [comment]
@NearW When using the files an error (can not get `parentNode.children` of undefined) occurs inside the [mapBuilder.ts#L14](https://github.com/MaibornWolff/codecharta/blob/master/visualization/app/codeCharta/util/mapBuilder.ts#L14)
