### ISSUE TITLE
Create CodeCharta Jenkins Plugin

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#734]
# Feature request

Publish CodeCharta-Visualization to the Jenkins Plugin Store. An initial Spike has been done.

**Comment by Richargh** [comment]
A lot has happened here and we should be able to release a Jenkins Plugin if we want.

**Comment by BridgeAR** [comment]
I am going to close this as it's unlikely that we are going to implement this anytime soon.
