### ISSUE TITLE
Edges should stay visible for selected building

### ISSUE THREAD

**Issue by alexhunziker** [MaibornWolff/codecharta#736]
# Feature request

If a building is selected, its Edges should stay visible, even if the building is not hovered. The Edges should only be cleared once the building is un-selected.

## Example Use-Case
If I look at the edges of a building, I want to know where they are going. One way I could figure this out is by hovering over the buildings that the edges are leading to, to see their names. However, currently, as soon as I unhover the first building, the edges disappear and i have no visualization anymore which helps me to find the second building. If the Edges stay visible for selected buildings, this issue is solved.

**Comment by Quicano** [comment]
I have a small follow-up question for this case: 
First Step: Building is clicked and the Pairings are visible. 
Second Step: I am hovering over other Buildings while the "Click" is active. 
Are the Edges of the "clicked Building" supposed to stay visible while I am hoving over the other Buildings (first Solution) or are they Supposed to only stay visble while everything is unhovered (Second Solution).
First solution: 
+ You can compare different Edges and Pairings and you can get a better Picture as a whole
- They Edges might overlap and it isn't clear for which building they are supposed to show

Second Solution: 
+ This one might be less confusing 
+ You dont run the risk of overlapping edges
- no comparison between 2 different Building Edges

**Comment by alexhunziker** [comment]
Yes, I would also opt for the 1st solution.

The edges of the selected building should be visible until the selection is cleared.
The edges of a potentially hovered building should be visible in addition to the edges of the selected building. So we may have the edges of the selected and the hovered building visible at the same time.

**Comment by alschmut** [comment]
@Quicano I would probably expect to see edges for both the clicked and the hovered building (so your first solution), but that's just my opinion.

**Comment by Quicano** [comment]
I agree with both of you. Can I take the decision to do the first Solution, or should I enquire Fathi's opinion first?

**Comment by alschmut** [comment]
Just do it 👍

**Comment by fatihi** [comment]
I'm also in favor of the first solution. I will add a feature request soon to regulate the number of edges

**Comment by Quicano** [comment]
Should be working as expected, now asking for code review :))

**Comment by alschmut** [comment]
Do you want to create a PR. It makes conversation about code easier :)

**Comment by JaiJoPa** [comment]
I was testing the UI, and I found a weird behaviour when choosing a metric for the edges. 

![Edges_should_stay_visible](https://user-images.githubusercontent.com/50145538/71723528-425cb780-2e2d-11ea-95da-5f57c01b93a0.gif)


Expected behavour:
When selecting a building with edges and deselecting it by clicking somewhere outside the map
Then the Edges and Highlighting should be cleared

Actual Behavour:
When selecting a building with edges and deselecting it by clicking somewhere outside the map
Then another building is selected

If you click once more somewhere outside the map, the building which was selected before is selected again.  They are those two buildings are switching each time you click somewhere outside the map.
