### ISSUE TITLE
Additional help on usage of SCMLogParser

### ISSUE THREAD

**Issue by alexhunziker** [MaibornWolff/codecharta#738]
# Feature request

Currently the SCMLogParser has functions implemented, that print help on how to get the different input log formats we can parse (example commands) as well as which metrics will be calculated upon the import of a log in such a format. However these functions cannot be called by the user currently and are therefore useless in the current state. If we keep the functionality, we should make the feature available for usage. We should also provide a parameter to the SCMLogParser which lists all of the input formats we can process.

**Comment by BridgeAR** [comment]
I am going to close this as won't fix for now. We want to automate most parsers including the SCMLogParser. That would be done by such automation and no user interaction would be required anymore. If any user interaction is required, just ask a question on the command line directly.
