### ISSUE TITLE
Remove unused layout switcher code files

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#750]
# Tech

## Description

We have some code-files in our repository, which are in fact unused since its implementation. 

- the outdated /app/testVille root component
- the ui/layoutSwitcher component
- and some code in app.ts to configure the page switch

The [Layout Switcher PR](https://github.com/MaibornWolff/codecharta/pull/142) was supposed to be used for a multi-page codecharta. In more detail it was planned to move the [TestVille](https://github.com/MaibornWolff/TestVille) project into the codecharta project, while at the same time it was supposed to be completely separate.

## Question
Do we wanna keep the unused files in our project or undo them?

**Comment by alschmut** [comment]
In my opinion, if a TestVille layout will be applied at some point, we can still check the git history and reuse what is helpful, but until then files like the [testVille.component.html](https://github.com/MaibornWolff/codecharta/blob/master/visualization/app/testVille/testVille.component.html) just get more outdated day by day. So I would undo the changes to have a clean and on the current functionality focused project.

**Comment by fatihi** [comment]
I am also in favor of removing them, that's one of the reasons people use versioning 🤷‍♂
