### ISSUE TITLE
Different text size in dropdown menu

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#756]
# Bug

## Expected Behavior
Both dropdowns should have the same text styling

## Actual Behavior
Dropdowns have different text stylings

### Screenshots

![Screen Shot 2019-10-18 at 09 26 20](https://user-images.githubusercontent.com/12533626/67074615-c0dc7e00-f189-11e9-8fad-9a063e38f291.png)
![Screen Shot 2019-10-18 at 09 26 26](https://user-images.githubusercontent.com/12533626/67074619-c3d76e80-f189-11e9-82d2-d4d7a4936668.png)

Which one do we prefer here? @fatihi

**Comment by fatihi** [comment]
Take the font of the first screenshot please.

**Comment by alschmut** [comment]
This bug is fixed with the branch for #696
