### ISSUE TITLE
SCMLogParser: project creation with only one leaf should display a hint to specify input-format 

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#762]
# Feature request

## Description

The input-format is git.log per default. In our examples we use GIT_LOG_NUMSTAT_RAW.

We should display a hint to specify the correct input-format when the SCMLogParser creates a project with only one leaf.

**Comment by BridgeAR** [comment]
This does not seem to be important as soon as we automate triggering the parsers to generate the required cc.json. I am going to close this as we are unlikely going to address this anytime soon.
