### ISSUE TITLE
Delta values not summed up on folders 

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#781]
# Feature request

## Description

Currently we just display the delta-icon without a number when hovering over a folder.
Let's display the sum of all the deltas in that folder when hovering over it.

currently:
<img width="739" alt="Screen Shot 2019-11-13 at 11 29 57" src="https://user-images.githubusercontent.com/12533626/68755857-6bb94e00-0609-11ea-906a-e4bf5f339986.png">

**Comment by alschmut** [comment]
I implemented summing up the delta values, but am not sure, what to do with the sum-icon. I find following options:
1. Show the sum-icon twice for both values, although this actually takes too much space.
1. Show the icon once before or after the values (not inside the rounded box). Should it be in a separate rounded box? But which background-color has that box?


![image](https://user-images.githubusercontent.com/23529226/69169705-1a252d80-0af9-11ea-8d2a-b77a5d031ceb.jpeg)
