### ISSUE TITLE
improve docs even further

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#782]
Now that we have a jekyll page [here](https://maibornwolff.github.io/codecharta/), we should work on the following things:

**General:**
- [ ] Add a favicon
- [ ] Add a link to our gh-pages to the wiki home and the main README
- [ ] Check why paths of images can't be resolved, see [here](https://maibornwolff.github.io/codecharta/docs/step-by-step/) at the end. I fixed this locally [here](https://github.com/MaibornWolff/codecharta/pull/779/commits/0c3108082cf9c12304670bbdcb76f09ffeaf30fb), but the path on github is different, I guess. 
 
**step-by-step.md:**
- [ ] `./ccsh sonarimport [sonar-server-url][project-id]`, explain what the url and what the project-id is, because url is only the host-adress and project-id is actually the project-key found on the page (we should give a hint to find this information in the sonarimport README and update it there)
- [ ] move navigation part to the user controls part

**Discussion:**
- I don't think the how-to's should be considered "news", rather have an own page for each release, ADR and how-to (guides), instead of bundling them in a category page

**Comment by Richargh** [comment]
We improved the docs quite a bit since then :)
