### ISSUE TITLE
Update releases in github-pages automatically

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#783]
We have a release category in our [gh-pages](https://maibornwolff.github.io/codecharta/categories/#release) now and we need to update it automatically, when releasing. This can be done by creating the required files and move them to the gh-pages folder BEFORE making the release commit. When we release, we will do two commits. One updates the gh-pages, the other one tags the release.

Please note that you probably want to extract the latest unreleased patch notes. We already wrote a script for this earlier [here](https://github.com/MaibornWolff/codecharta/issues/533#issuecomment-505508299)

**Comment by BridgeAR** [comment]
Is this still something that needs to be addressed?

**Comment by NearW** [comment]
Yes, please. This would get rid of the release preparation PRs before evey release.

#voteforhigherpriority

**Comment by BridgeAR** [comment]
Go for it
