### ISSUE TITLE
Improve Treemap- and search for a different Layout-Algorithm

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#788]
# Feature request

CodeCharta's current building algorithm has a couple of issues:

1. It's not stable for refactorings. When a buildings metrics significantly change it might move from the top-left corner to the bottom right. That's bad if you periodically look at CodeCharta and have trouble finding the buildings.
2. It's hard to find important packages because all packages sort of blend together in the map, no matter how big it is. It would be great if the packages with a big area metric are visually clearly seperated from the other packages. 
3. The algorithm itself might not be optimal for code.

## Description

The goal of this research is to figure out how we can improve the treemap algorithm (1, 2) and experiment implementing a completely different algorithm like [EvoStreets](https://www.ifi.uzh.ch/dam/jcr:ffffffff-ce15-4fae-0000-00007b969ed5/16_frank_steinbrueckner.pdf), see below:

![Screenshot 2019-11-16 at 12.48.12.png](https://images.zenhubusercontent.com/5cd16a929795a865159e70ff/c93dce0a-80d8-4069-9430-31074b994747)

The result might be that we can switch between two or three layouts in the map.

**Comment by BridgeAR** [comment]
This should be addressed by the street map layout that we added in v1.65.0. I do like the upper picture as well but I guess that's somewhat out of scope for now.

Closing as resolved therefore. @Richargh if you would rather keep it open, please just do so :-)
