### ISSUE TITLE
MarkedPackages do not get saved when loading files

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#798]
# Feature request or Bug

## Description

Currently, when we load files, which contain previously marked packages, into codeCharta the `markedPackages` are not saved in the `CCFile` (see [codeCharta.service.ts#L42](https://github.com/MaibornWolff/codecharta/blob/master/visualization/app/codeCharta/codeCharta.service.ts#L42)).

As the markedPackages have not been exported yet, if we decide to import them, I would suggest to clean the interface first in order to not export the `markedPackages.attributes`:

- Lets show the full path inside the legend panel and crop the left side using some CSS. Then we do not need to create a second cut path (see `markedPackages.attributes["name"]` in the `legendPanel.ts`). 
- This will decrease some code inside the legendPanel, but also remove the 3 dots inside the legenPanel, when a path is too long.
- Afterwards we can remove the `markedPackages.attributes`

**Comment by Richargh** [comment]
This is super annoying, please fix it!
