### ISSUE TITLE
Rework state -> viewModel dataflow

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#812]
# Feature request

## Description

Currently:
- When I use the UI, the viewModel gets updated in the controller and we broadcast an event based on the value in the viewModel.
- All subscribers to that event get notified and act accordingly

What we want:
- When I use the UI, an action is triggered that updates the state. The state initiates an event broadcast based on the value in the state.
- The UI-Controller that contains that viewModel subscribes to the relevant state-changes in order to update the viewModel

**Comment by BridgeAR** [comment]
@NearW is this something you already addressed recently?

**Comment by NearW** [comment]
@BridgeAR No, but this has been enforced over time. Closed
