### ISSUE TITLE
[Spike] Component Injection depending on environment

### ISSUE THREAD

**Issue by fatihi** [MaibornWolff/codecharta#815]
# Feature request

We want to start building the desktop client. Having conditions in the rendering of components depending on the environment can make components too complex. A cleaner way would be to write different components that are being injected by Angular depending on the environment.

## Description

Research if it is possible to make Angular inject different components based on the environment.

**Comment by alschmut** [comment]
Maybe there is a misunderstanding, but I think we can easily have a controller class which stores a `isDesktopEnvironment` in the `viewModel` field,
- which gets updated whenever we change the environment and
- which we can access from the html template to load different sub-components depending on the environment

Example:
```
<some-desktop-component ng-if="$ctrl._viewModel.isDesktopEnvironment"></some-desktop-component>
<some-browser-component ng-if="!$ctrl._viewModel.isDesktopEnvironment"></some-browser-component>
```

**Comment by alexhunziker** [comment]
We did something like this last year here https://github.com/MaibornWolff/codecharta/tree/spike/323/standalone-only-features. The focus there was how to access the file system. I did another branch https://github.com/MaibornWolff/codecharta/tree/spike/815/componenet-based-on-env with a small node Environment detector, very similar to what @alschmut described above. Is this what we are looking for?

**Comment by NearW** [comment]
Webpack provides a better way to set a global environment variable through CLI arguments. This is already implemented in the spike branch.

I tried the conditional component injection but failed. The standalone component is not rendered for some reason and I don't know why this is the case.

```
import "../../state/state.module"
import "../dialog/dialog.module"
import angular from "angular"
import { downloadButtonComponent } from "./downloadButton.component"
import { isStandalone } from "../../util/envDetector"
import { downloadButtonStandaloneComponent } from "./downloadButton.standalone.component"

const module = angular.module("app.codeCharta.ui.downloadButton", ["app.codeCharta.state", "app.codeCharta.ui.dialog"])

if (isStandalone()) {
	module.component(downloadButtonStandaloneComponent.selector, downloadButtonStandaloneComponent)
} else {
	module.component(downloadButtonComponent.selector, downloadButtonComponent)
}
```

**Comment by alexhunziker** [comment]
you almost had it, just the selector was wrong. Now it is working.

I saw that you removed this section from the webpack.config 

```
	if (env.STANDALONE === "true") {
		exports.target = "node"
	}
```
However, as far as i understood it, this one is needed when we want to use the node specific libs, so we may want to keep that.

**Comment by NearW** [comment]
> you almost had it, just the selector was wrong. Now it is working.

OMG. Of course. Thanks for pointing that out!

I don't really see a use case here where we actually need that. Where did you read that?
