### ISSUE TITLE
Performance issue on switching Mode

### ISSUE THREAD

**Issue by alexhunziker** [MaibornWolff/codecharta#823]
# Bug

## Expected Behavior
On OS X with Chrome switching modes is quite snappy.

## Actual Behavior
On Windows w. Firefox switching between single and multiple mode takes very long (up to 30s) for a 400k loc map. During this time CC is frozen and the browser warns about a long running script. On Chrome the performance is better, yet not amazing.

### Screenshots

![grafik](https://user-images.githubusercontent.com/20796577/71971352-b66ed500-320a-11ea-8e8b-da7345084e10.png)

  - Version: 1.41
  - Platform: Windows
  - Browser: Firefox

**Comment by alschmut** [comment]
@alexhunziker did you check if this might be resolved with the new redux store?

**Comment by alexhunziker** [comment]
I noticed it on this branch ;) 

however i already localized the problem and fixed it, it was an excessive use of the getCodeMapNodeFromPath() function by the EdgeMetricDataService.

**Comment by alexhunziker** [comment]
will be fixed with #804
