### ISSUE TITLE
Remove deprecated no-unused-variable rule from TS lint

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#825]
```
		"no-unused-variable": [true, { "ignore-pattern": "^_" }],
```

is deprecated. We should use the built-in typescript compiler check instead. This can be enabled in the tsconfig by setting `noUnusedLocals` to true.

To ignore a line, simply use this annotation: `// @ts-ignore`

**Comment by fatihi** [comment]
This should be pretty small... and maybe do this together with #826 ?
