### ISSUE TITLE
TSLint: new rule prefer-const

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#826]
Add and test this rule: https://palantir.github.io/tslint/rules/prefer-const/

**Comment by BridgeAR** [comment]
I suggest that the projects makes use of a predefined rule set. That way it automatically relies upon the best practices and the experience of the developers who invested into the predefined rule set and adding new rules does not need any discussion anymore.

Some of these sets can be found in the TSLint project: https://github.com/palantir/tslint#custom-rules--plugins

Please note that TSlint is deprecated and moving to ESLint should be added to the roadmap.

**Comment by NearW** [comment]
https://github.com/MaibornWolff/codecharta/pull/934

Done here
