### ISSUE TITLE
TokeiImporter creates falsified node-names

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#841]
# Bug

## Expected Behavior
Given the generated file from tokei has objects (nodes) with names like `my/path/someNode.css`
Then the TokeiImporter should extract the name `someNode.css`

## Actual Behavior
Given the generated file from tokei has objects (nodes) with names like `my/path/someNode.css`
Then the TokeiImporter sometimes extracts the name `someNodecss` (missing the file extension dot `.`)

## Steps to Reproduce the Problem
  1. `brew install tokei`
  1. `tokei myProject/ --output json > analyzedProject.json`
  1. `ccsh tokeiimporter -o analyzedProject.cc.json analyzedProject.json`

## Specifications

  - Version: 1.41.0
  - Platform: macOS

**Comment by alexhunziker** [comment]
I can't reproduce this issue. Could you provide the json generated by Tokei?
