### ISSUE TITLE
Docker Hub Image broken

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#843]
# Bug

The published docker image on docker hub is broken right now. Either our documenation is or the container itself.

On first investigation it's weird, that we build our standalone and publish it to an nginx docker container. The docker container should publish our web-version that is built by `npm run build:web`. However, this shouldnt be the problem though, since we built docker images in the past with the standalone command.

**Comment by alschmut** [comment]
Currently we also still use the Docker ID of @ukinimod. It might make sense to replace that with a separate codeCharta account, like for npm and gitHub with #407
