### ISSUE TITLE
Compress output data

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#848]
# Feature request

The generated `cc.json` files might become quite big depending on the size of the project. As such, it would be great to minimize the file size and to compress them. It should be relatively straight forward to first implement something like this with an option and to later on switch the default as semver-major.

The data is very similar and repetitive. It is therefore likely that the file size would be a minimized to a maximum of 1/10 using a fast compression algorithm.

All tools handling the files should be able to handle compressed and uncompressed data.

**Comment by BridgeAR** [comment]
Subtasks:

Steps to achieve this:

- The backend should ask the user if the user wants to receive a compressed file or a regular json file and returns that to the user (either with a flag or by asking the user on the terminal)
- The frontend should be able to identify the json or compressed file and determine if it should decompress the file before actually reading the json

The algorithm should be very fast, so choose wisely ;-)

**Comment by RomanenkoVladimir** [comment]
As of now we run of memory when parsing big files, one solution would be to increase avalible heap size or we could look into using another library instead of GSON, in this case both issues would require changing the project Serialization/ Deserialization
