### ISSUE TITLE
bin/ccsh: 3: [[: not found

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#849]
# Bug

Executing ccsh always prints a `[[: not found`.

## Expected Behavior

Not to print an not found error.

## Actual Behavior

Each time `cssh` is executed, it prints the not found error. Each test run logs these as well:

https://travis-ci.org/MaibornWolff/codecharta/builds/643504125#L3627

## Steps to Reproduce the Problem

  1. Run `ccsh -v`

## Specifications

  - Version: 1.41.9
  - Platform: Linux x64

**Comment by alexhunziker** [comment]
https://stackoverflow.com/questions/3427872/whats-the-difference-between-and-in-bash/3427931

The [[ we use for the if statement is apparently bash specific and not supported in standard sh. We should probably replace it therefore with [

**Comment by NearW** [comment]
Why was it executed with sh though? the shebang says it's supposed to run with bash.

If travis does not support bash, we should maybe migrate all our .sh files to sh and use the sh shebang

**Comment by alexhunziker** [comment]
well actually for the gradlew file we use sh and for the integrationTest it is bash. so strictly speaking altering only one of them would have been enough.
