### ISSUE TITLE
Improve map navigation

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#851]
# Feature request

## Description

Current map navigation does not seem intuitive for all users.

* Zooming does not use the current mouse as focus point but the center of the map.
* ~~Double click and moving the mouse starts to spin the map around instead of moving the current viewpoint.~~

~~I recommend to implement an option to switch the mouse button behavior and add that option to the current options~~

**Comment by BridgeAR** [comment]
I believe this is unblocked due to #3077 landing, I am not completely certain though. Maybe someone could check that?

**Comment by IdrisLaabidi** [comment]
Blocked until #3682 is finished

**Comment by IdrisLaabidi** [comment]
This issue has been resolved and closed with the merge of PR #3693 .
The zoom functionality has been enhanced to focus on the mouse cursor, thanks to MapControls module from Three.js, which handles this behaviour inherently.
