### ISSUE TITLE
Name JS functions where the name is not inferred

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#852]
# Feature request

In case of errors or while profiling it's important to know the stack. The problem is, that multiple used functions seem to be anonymous. Most functions infer their names from their variable names but that's not always possible. In such cases, it's good to use "old school" functions as in `function foobar() {}` instead of arrow functions `() => {}`.

Mostly, this applies to callbacks and events. Since these functions are not assigned to a variable or property, it's not possible for the compiler to infer the name.

**Comment by BridgeAR** [comment]
I gave this a high priority due to being able to better identify functions while profiling and due to it being so simple to address.

**Comment by NearW** [comment]
I didn't really understand if this applies to functions with parameters now or not.

```ts
const arr = [{age: 25, name: "Alice"}, {age: 24, name: "Bob"}]
const names = arr.map(x => x.name) // ["Alice", "Bob"]
```

Does this apply to the map callback?

**Comment by BridgeAR** [comment]
The closure is nameless, so yes. It's not observable directly but it could show up in the stack while profiling. It depends on the code in what way it might need to be refactored.

I suggest to start with all promise code (i.e., remove all `.then` and `new Promise` in favor of `async / await`). Then check for all "hot" anonymous functions: these likely indicate code paths that could be optimized. E.g., `getNodesAsArray`. This currently goes through all child nodes and creates sub arrays each time that is then spread and later on mapped. It could instead do everything in a single step: recursively go through the children and pass through a single array that is contains nodes created by `LayoutHelper.buildNodeFrom()`. That way there's no need to create any intermediate array that has to be spread into other arrays.

In the end, the anonymous functions should not turn up as hot code paths. If they still do, it might make sense to give them a name.

**Comment by NearW** [comment]
I totally agree on the async/await part and I can see why this can be very helpful, but as you already mentioned:
> In the end, the anonymous functions should not turn up as hot code paths

Keeping anonymous functions increases readibility. What we need is more awareness of when these are becoming a performance issue. This mostly happens when using methods like map and filter in a loop or when concatinating those.
