### ISSUE TITLE
Split the project into visualization and analysis

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#861]
# Question

I have not been with CodeCharta at the time, when people decided to put the visualization and the analysis part into one project long ago. Probably there were some good reasons, but time changes and the projects get larger day by day. Now I am just questioning if this is still the best solution or if we should consider separating the two parts into individual projects `codecharta-visualization` and `codecharta-analysis` with individual pipelines, releases etc. 

How about shortly collecting all prop's and con's in the list below? I am sure there are people who have a lot more experience than me about that topic, so feel free to edit this description/list and optionally comment your changes below, so we get a notification that something has changed 😃 

## Pro's
- Less time for travis to run the pipeline, generally means less time to wait until PR's can be merged
- Individual releases show more accurate if the desired project (visualization or analysis) changed
- Inidvidual IDE configuration to use gradle for the analysis project, but not for the visualization

## Con's
- the effort to separate the projects
- increasing the distance between both projects although they are closely related using the cc.json schema. Although this could be solved by a good README referencing the other project.

## Following questions
- Where is the CHANGELOG past gonna be? Manually separated or do both get the full CHANGELOG of the past?
- The visualisations package.json includes the `apiVersion` of the cc.json schema. Is this documented somewhere?
- Will we move the gh-pages folder into the visualization project?

**Comment by BridgeAR** [comment]
While I like the suggestion, it's something that takes time. Without having more people work on CodeCharta it's unlikely going to be a high priority.

**Comment by NearW** [comment]
We'll work on some of the points in here.
For now, we'll manage two individual CHANGELOGs. One for the visualization and one for the analysis. The old CHANGELOG contains a link to the new ones and the new ones contain a link to the old one.
We'll also update the release-script, so that you can decide which versions you want to increase. The releases binaries will still include both visualization and analysis, even though one of them didn't change.

**Comment by NearW** [comment]
Update on my recent comment:

Splitting the changelogs and versions is easy.However, we can't manage two different releases. A release is tagged with the newest version number. We could have release 2.1 for visualization and the next time 2.1 for analysis. Those are the same version with the same tag.
We could solve this by adding a pre or post-fix to the tag like `2.1.0-vis` and `2.1.0-ana`, but what do we do if we release both at the same time?
I think it makes more sense to split the repo at some point.

https://docs.github.com/en/github/using-git/splitting-a-subfolder-out-into-a-new-repository
