### ISSUE TITLE
Wrong max value of metric calculation

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#876]
# Bug

## Expected Behavior
I'd assume that the maxValue of a metric shown in parenthesis behind the metric name is calculated only by the files that are shown in that map. Therefore in my gif the value for avgCommits should be 0.

## Actual Behavior
The maxValue is calculated with ALL files loaded. It doesn't matter if they're currently selected or not. This results in a wrong max value that is used to determine what metric we will use as a default. This default can result in an area metric selected, that is 0 meaning it show's a blank map.

## Additional Infos
This happens with downloaded maps, because when you open two maps A and B, where A has metric "rloc: 10" and "mcc: 5" and B only has "rloc: 12" then the downloaded map B_DOWNLOADED has metrics "rloc: 12" and "mcc : 0". When the metric isnt available at all, it can't be selected. That's why this bug mostly occurs with downloaded maps.

## Screenshots

![wrong_metric_selected](https://user-images.githubusercontent.com/12533626/76435733-abc1ef00-63b7-11ea-850a-f2093eda2de3.gif)
Shows that the wrong max value is shown. It should be 0 for the second map.

![wrong_default_metric_selected](https://user-images.githubusercontent.com/12533626/76436862-0c056080-63b9-11ea-8205-991ec1acc0c5.gif)
Shows that the wrong metric is selected by default.

## Steps to Reproduce the Problem
  1. Open two downloaded maps
 2. Select a metric that is actually 0 but is shows a higher max value

**Comment by alschmut** [comment]
This is probably related to #863
