### ISSUE TITLE
Tech: extend eslint config with recommended configs

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#878]
# Feature request

## Description

As a developer, I want to enforce best practices with recommended rulesets. This can be done by replacing the current extend block of the eslint config with
```
"extends": ["eslint:recommended", "plugin:@typescript-eslint/eslint-recommended", "plugin:@typescript-eslint/recommended", "prettier"]
```
This ruleset produces around 2000 warnings/errors at the moment.

Please do not start this issue while there are major changes going on. Once this issue is started, finish it as quick as possible before working on another issue.

This closes #826 and #865

**Comment by NearW** [comment]
Plugins to use:
https://github.com/mysticatea/eslint-plugin-node
https://github.com/sindresorhus/eslint-plugin-unicorn
https://github.com/mysticatea/eslint-plugin-eslint-comments#readme

Rule to enable:
https://eslint.org/docs/rules/no-return-await

**Comment by BridgeAR** [comment]
Closing as resolved
