### ISSUE TITLE
Filter: Migrating older cc.jsons

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#884]
# Feature request

## Description

As a user, I want to migrate my older versions of the cc.json to a newer or the newest available version, so that it can be loaded in the visualization for sure.

## Acceptance criteria
- After migrating, the cc.json can be correctly validated with `ccsh check myFile.cc.json` using the generated scheme.json of #860 
- The CLI should look like this `ccsh migrate myOldFile.cc.json -v 1.1 -o myNewFile.cc.json`. Per default, the -v should be the newest version. If -o is not provided, print it in the console.
- If the cc.json that should be migrated is missing the version-field or encounters a problem, print a meaningful error message

## Open questions
Should we generate scheme.json for each version so that we can validate the cc.json before migrating? If so, we should specify the version in the check tool like `ccsh check myFile.cc.json -v 1.0`

**Comment by BridgeAR** [comment]
As an alternative solution for this:

What about implementing a strategy to auto-detect the version while loading it into the visualizer? That way it would be transformed internally and the user could get a pop-up notification about the ongoing transformation including an option to download the cc.json with the new structure.

That way it's super user friendly while probably being a bit more work implementation wise.

**Comment by Richargh** [comment]
Older Versions? Does there exist a v2 of the cc.json? Also does the mergin of old/new files still work?

**Comment by alschmut** [comment]
😂 nice Richard :D no don’t worry, there is no 2.0.  but when I was generating a correct Schema to validate our cc.json for #860 we found out that exported cc.json files before July 13th 2019 included the fileName property, that actually never existed on the cc.json schema, but was exported as we decorated the map within the visualization.

**Comment by BridgeAR** [comment]
This is likely less of an issue as soon as we switch to the config based download functionality. Every change to the cc.json structure should be upwards compatible and thus, there should not be an actual need for this. If we ever encounter such need, let's do this on a case by case basis.
