### ISSUE TITLE
Delta View shows Deltas of itself as non-trivial if nodes have same name

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#89]
I'm using the delta view of the current (i.e. 1.9.3) visualization version with the attached data. There seems to be a bug, if two nodes have the same name (although in different parts of the directory tree): 
- If compared to itself it shows a delta for the bigger one of the nodes with values (bigger - smaller). I expected it to show no difference.
- If compared to a different file it still shows this difference, no matter if this file exists in the other version, if it has changes in the metric, etc. etc.

Maybe related to #60 ?

[nodesWithSameNames.txt](https://github.com/MaibornWolff/codecharta/files/1770579/nodesWithSameNames.txt)

**Comment by mrpatpat** [comment]
Hi, 

the first part of the question is propably related to [this line](https://github.com/MaibornWolff/codecharta/blob/master/visualization/app/codeCharta/core/data/data.deltaCalculator.service.ts#L36) and is clearly a wrong implementation. 
The second part of your question is a bit harder to solve. I think at some place the code does not reset these deltas correctly.

**Comment by mrpatpat** [comment]
The first part should be fixed. 

Used files: 

[filenameSample1.txt](https://github.com/MaibornWolff/codecharta/files/1772410/filenameSample1.txt)
[filenameSample2.txt](https://github.com/MaibornWolff/codecharta/files/1772411/filenameSample2.txt)

Resulting visualization: 
<img width="1061" alt="bildschirmfoto 2018-03-01 um 19 51 50" src="https://user-images.githubusercontent.com/2622069/36863509-2deccc82-1d8a-11e8-8c7d-380f2f008ca7.png">

**Comment by mrpatpat** [comment]
Does the second part of your question apply to the detailPanel in the lower left part of the screen or the 3d visualization ?

**Comment by ukinimod** [comment]
I refered to the 3D visualization, but it seems to be fixed by your patch.
