### ISSUE TITLE
Deselecting a building with edges will not de-highlight it's connected buildings until the mouse is moved

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#890]
# Bug

## Expected Behavior

When the user selects a building with edges that highlights some buildings connected to it as well and then deselects it, the buildings should be de-highlighted.

## Actual Behavior

When the user selects a building with edges that highlights some buildings connected to it as well and then deselects it, the buildings are not de-highlighted automatically. Instead moving the mouse is required.

This is because the hoveringRegistration is waiting for the mouse to move until a rayIntersection-check is triggered. Removing that mouse-requirement results in a broken distribution bar though.
This bug is minor and could be adressed when the hovering is refactored.

**Comment by JaiJoPa** [comment]
I got a quick fix for it, if needed. We could add threeSceneService.clearHighlight() to the onBuildingDeselected function in arrow service:
That way, when deselecting a building, instantly all buildings are de-highlighted.



![dehighlight](https://user-images.githubusercontent.com/50145538/94800496-f3a47400-03e4-11eb-9c12-120cb9037a74.gif)
