### ISSUE TITLE
Edges Metrices Labels 

### ISSUE THREAD

**Issue by cstanger** [MaibornWolff/codecharta#906]
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As a numbers-driven Software Architect, I want to use the Code Charta to illustrate the 'strength' of Entity-relationships and want to see the numbers. There for the Code Charta Tool should display the metric corresponding to an edge.

## Acceptance criteria
- All edges have a Labels, like the Buildings have. 
- The Edge Label displays the metric value of the selected Edge-Metric in the Menubar

## Assumptions & Exclusions
- 

## Development notes (optional Task Breakdown)
- reuse the existing Building Label Class

## Open questions

- As the edges itself, an edge-label can be displayed whenever the corresponding edge is displayed.

**Comment by BridgeAR** [comment]
Do you have a suggestion how this would be visualized? In case it's visualized for the whole map, the output would be very verbose and unreadable.

How would it be possible to hover to specific edges? That might not be trivial either. Overall, this sound like it requires a whole new view?

**Comment by BridgeAR** [comment]
Closing as won't fix due to missing feedback.
