### ISSUE TITLE
Delta view not working for bigger trees

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#91]
There seems to be a performance problem with the delta view (CC V 1.9.3), which prevents delta view from being usable on bigger trees. I would have liked to use the delta view on a node tree of size 4175. When loading multiple files (5) and switching to delta view the browser (chrome) hangs and times out. Using a different project with 15000 nodes it even doesn't work for one file loaded.

**Comment by mrpatpat** [comment]
Hi,

I am currently working on a branch where @xWorkerBeex and me solved many performance issues. I also could solve some angularjs related issues. It will be released as soon as we can confirm that it works correctly. The solution was to use a hashmap (path -> node) as an search index for data structure. I also refactored the map loading and processing which gave another performance boost.
The performance gains are huge and even maps like firefox are quickly loaded multiple times and delta calculation between them takes ~5-10secs.

**Comment by mrpatpat** [comment]
This is fixed in #98.
