### ISSUE TITLE
Identify a node by an artificial ID

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#923]
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As a developer, it might make sense to introduce an artificial unique property `codeMapNode.id` so that I can access a CodeMapNode/Node/CodeMapBuilding (that are our node interfaces) within a HashMap by it’s `id`.

This is related to a [comment](https://github.com/MaibornWolff/codecharta/pull/921#pullrequestreview-395926723) in #921 as a Node is unique only by the combination of its path and its type (folder or file).

A different approach could be to use the last character of a path to distinguish between file or folder:
- a folder always ends with a slash
- a file never ends with a slash

## Acceptance criteria
- Use **one** property (no matter which) that identifies a node uniquely
## Development notes (optional Task Breakdown)
- [ ] 
- [ ] 
- [ ]

**Comment by NearW** [comment]
@alschmut As far as I know the ids of the CodeMapBuildings change though when you exclude a building. Also when you exclude a building,it gets removed from the buildings-array, while we still have that building in our codeMapNode-structure. the codeMapNodes and the codeMapBuildings are not always of identical length.

When you have a folder structure such as /root -> /root/codecharta/ -> /root/codecharta/app and the codecharta folder does not contain anything besides the app folder, these folders get merged together as the app folder.

**Comment by alschmut** [comment]
@NearW true, I also wasn't actually talking about the already existing id (which is just the iterating number through the `nodes: Node[]` array). I was rather thinking about setting an id for each codeMapNode, straight after importing a file (like when preDecorating). This id could be used for every other node interface.

```
imported CodeMapNodes: CodeMapNode:
- root (id 1)
  - app (id 2)
    - codecharta (id 3)
      - file1 (id 4)
      - file2 (id 5)
```

```
- root/app/codecharta (id 3)
  - file1 (id 4)
  - file2 (id 5)
```

Nodes: Node[] (which are used for the codeMapBuilding right?)
```
- root/app/codecharta/file1 (id 4)
- root/app/codecharta/file2 (id 5)
```
