### ISSUE TITLE
Color range slider misbehaves when loading maps with blacklisted buildings

### ISSUE THREAD

**Issue by alexhunziker** [MaibornWolff/codecharta#926]
# Bug

## Expected Behavior

The color range slider should not change in size, and should be devided reasonably into 3 sections when loading a new map.

## Actual Behavior

It sometimes does not. (see screenshot)

## Screenshots

![image](https://user-images.githubusercontent.com/20796577/79995141-20a83e80-84b7-11ea-818f-9f412b5a0a8a.png)

## Steps to Reproduce the Problem
1. Load a map which has the buildings with the highest color metric values excluded
1. Open the color dropdown

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes 
- CodeCharta Version: 1.45.5
- OS: Windows
- Browser: Firefox

**Comment by alschmut** [comment]
this might be connected to #863?
