### ISSUE TITLE
Add a specialized symbol for newly added/removed nodes

### ISSUE THREAD

**Issue by mrpatpat** [MaibornWolff/codecharta#93]
As a result of #92 it would be good to visualize added/deleted nodes with a special, metric-less, symbol. This would make them always visible (not only with unary area) and create a clear distinction. Another problem is assuming that the metrics are 0. 0 is not a "non existant" value e.g. a new file would be very good in terms of "number of bugs".

**Comment by ukinimod** [comment]
Sorry, I did not realize you opened another discussion for this issue. Being able to use a different metric would be great. Special indication for the nodes should not be necessary.

**Comment by Richargh** [comment]
This issue has gotten stale. Maybe we'll get to this feature in 2018. Probably we'll tackle it next year and create a new issue then.
