### ISSUE TITLE
Duplicated NPM packages

### ISSUE THREAD

**Issue by thorsten** [MaibornWolff/codecharta#94]
Check https://www.npmjs.com/org/maibornwolff:

https://www.npmjs.com/package/@maibornwolff/codecharta-visualization -> v.1.8.2

vs

https://www.npmjs.com/package/codecharta-visualization -> v.1.9.3

**Comment by mrpatpat** [comment]
Hi @thorsten,
this is actually a kind of work in progress. I am already in contact with the npm support to fix this issue. The reason why it even exists is the strict npm unpublish policy to prevent missing dependencies.

**Comment by thorsten** [comment]
👍
