### ISSUE TITLE
Move unfocus button to the node context menu

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#948]
# Feature request

## Description

As a user, I want to easily find the unfocus button without it being placed on top of the 3d-scene.
A user would need to right-click a building and select focus. The user would assume that in order to revert this behaviour he can right-click the node again and instead of focusing, the user gets the option to unfocus the building again.

**Comment by alschmut** [comment]
If you decide to not remove the UNFOCUS button below the view cube, the button should be moved with the viewCube to the left, when the sidebar opens.
