### ISSUE TITLE
Project / Directory summary

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#95]
It would be Great to have some summary in the visualization concerning the number of Buildings in a package. The number of changed, added, deleted buildings in Delta mode. This would have helped with debugging. What do you think?

**Comment by mrpatpat** [comment]
I think this would be a nice feature with low implementation costs. The new algorithms used for #91  already have distinct branches for added/deleted/modified files. Adding flags to a node and counting them should be a rather simple implementation. 
You can expect it after the delta issues #91 #92 #93 are resolved.

**Comment by BridgeAR** [comment]
The number of total files is already included.

The delta mode does not yet show the number of deleted or added files. That would be a nice addtive.

It could roughly look like that: 
![image](https://user-images.githubusercontent.com/8822573/141840877-6cd00fbc-523e-4477-bcf3-cfa7cbfdea2f.png)
