### ISSUE TITLE
Selecting a building in chrome does not show the attributeSideBar

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#951]
# Bug

## Actual Behavior

![image](https://user-images.githubusercontent.com/8822573/81382362-8da21200-910e-11ea-818e-bf04e476901b.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- Browser: Chrome

@JaiJoPa 
> This is already fixed on master.

**Comment by alschmut** [comment]
@BridgeAR should we add the closing keyword for this issue into the description for #950?

**Comment by alschmut** [comment]
fixed by #950
