### ISSUE TITLE
Tech: Refactor Model Backend

### ISSUE THREAD

**Issue by RomanenkoVladimir** [MaibornWolff/codecharta#952]
# Issue

Right now model is used for everything that is shared by other components and is not a filter, importer or an exporter. This includes Project Serialization/Deserialization, the actual model and Metric Name Normalization and would include Issue#848 after implementation.

## Solution
Change project structure or refactor the current structure to increase readability.

**Comment by BridgeAR** [comment]
With the new parser strategy (having a single parser that is able to determine most metrics on it's own) we do not have to maintain lots of different parsers anymore. It would be easier to just let that parser do the work and ignore the old parsers. As such, I am going to close this as won't fix with the intention of deprecating multiple parsers at some point in the future.
