### ISSUE TITLE
Slow delta multiple and delta performance

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#955]
# Bug

## Expected Behavior

__GIVEN__: A big map is open in the visualizer

__WHEN__: Clicking from `Single` to `Multi` or `Delta`

__THEN__: It switches to the new mode

## Actual Behavior

It takes a significant amount of time to switch the modes. Most time is spend in two functions:
`decorateParentNodesWithAggregatedAttributes` and `decorateMapWithBlacklist`. These two functions are responsible for more than 2/3 of the total computation time. Another ~25% are spend in `getDeltaFile`.

It is likely that the computation is doing a lot of work that is not necessary due to the current data structure. It is probably the wrong algorithm complexity (Big-O-Notation).

## Steps to Reproduce the Problem
1. Load a big cc file.
1. Click on `Delta` or `Multiple

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.47.1
- OS: All
- Browser: Chromium

**Comment by BridgeAR** [comment]
This was recently fixed. Closing.

**Comment by NearW** [comment]
@BridgeAR The bottlenecks described in this issue aren't fixed I guess. We could check for bottlenecks again now, depending on how slow the performance still is for huge maps.
