### ISSUE TITLE
Dependency information in json schema

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#97]
Hi all.

I'd like to re-address our discussion about the dependency information in the json schema before we put more work into it.

I can think of two major ways to implement this:
1. Save it as edge information independent from node information.
2. Save it as part of the information of a node. 

Which way to implement this is probably dependent on the way we want to visualize the dependency. @silasg was suggesting a different visualization from that implemented now. I think there are some advantages to them and probably the second implementation for the schema is in this case preferable.

@silasg suggested having another independent view like the delta view that maps the dependency and weights on the dependency via the color of the nodes. Therefore the dependency could be modeled through another attribute on the node which is a hash map from selected incoming dependency and weight. I think this kind of visualization is more appropriate for our imminent use cases.

My intuition tells me that the second implementation for the schema perform better in the case we use this visualization and would also isolate the information for one node in one position. I this case dependency information is just a filter for the attributes. I think there could also be other attributes we could put a filter on.
On the other hand, if we want to have a visualization like now or some other that is concerned with the origin of the dependency, the first way to implement the schema is probably better. 

My question, especially to @mrpatpat: 
a) What's your opinion on the suggestion for a visualization of @silasg?
b) Using this visualization, do you think there is a measurable performance difference between the different implementations?
c) Is the implementation of the visualization easier using one or the other schema?

**Comment by mrpatpat** [comment]
Hi @ukinimod,

a) Personally, I think that putting dependency information into the regular view is too much information at once. In my opinion a isolated dependency view would clear up space for information that is actually related and important for the dependency visualization. 

b) Performance is not really a problem visualization-wise. If we decide to use arrows, then it is just a relatively small amount of 3D Objects more. If we decide to use a seperate view, then the Scene will be even more simple in terms of 3D. Performance problems could appear if we choose the wrong data structure for this problem. The running time of most algorithms is somehow dependent on the number of nodes in the structure. An extreme case of this is the delta calculation which needs to compare two trees. As far as I can see, dependency visualization needs to traverse a single tree ( cheap, O(n) ) and searching dependencies in the tree ( cheap, O(1) when using hash maps which are generated before this process ). Looking at the implementation mentioned in #91  I do not see any big running time issues. 
However, I do not know how memory usage will behave. Adding lists of data to every node could increase the memory usage significantly. According to [this stackoverflow answer](https://stackoverflow.com/questions/29620041/is-there-any-memory-limit-for-google-chrome-browser) there are browser tab memory limits. Currently a big map like firefox.json causes 780mb memory usage in the CC Tab (Chrome, Mac). On the over hand, I never profiled the usage and I am sure there are possible improvements. 

c) I would not say one or the other is really hard. It boils down to two different traversing and searching approaches. Both, tree traversal or list iteration, are very common practices. This is also true for searching, inserting, etc. Implementing a isolated 3D view however requires the definition of new 3D Objects, Colors etc. So implementing a new view takes more time (but it is not drastic). Attribute filtering could get a bit tricky, but I think it should just another "setting" which filters the tree before setting it as the selected one. Currently attributes are modeled as string => number pairs, but it should not be a big problem to generalize it to something like string => AttributeType.

I think we should meet up, discuss the visualization and make a decision. Currently my vote goes to an isolated view with lists as  part of the attributes.

**Comment by FernandoES** [comment]
I personally would suggest have a separate view for this information, since it would be too much with the other information.
As a suggestion for the new visualization I would still use the idea of buildings, but instead of the whole building with the same colour the different dependencies should be a part a of the building according to their weight ( something like every column here: https://beginnertriathlete.com/cms/articleimages/673/Total-Volume-graph.jpg ). 
The dependency links could be shown using arrows. ( black or weight-coloured? )
When it comes to the way we store the information I would suggest to add it to the nodes ( as long as it is not too much for the system limits ), since it is more intuitiv, at least for humans.

**Comment by mrpatpat** [comment]
As a visualization basis I would suggest one of those: 
* [Force-Directed Graph](https://bl.ocks.org/mbostock/4062045)
* [Hierarchical Edge Bundling](http://mbostock.github.io/d3/talk/20111116/bundle.html)
* [Adjacency Matrix](https://bost.ocks.org/mike/miserables/)

They should be pretty cheap to implement, since we already use d3 for calculation.

**Comment by ukinimod** [comment]
Having discussions in technical assessments in mind I would not introduce a completely new view. 

I look at this feature in the following mindset. I'm in an technical assessment with a customer. And would like to discuss about some file that is very big, changed very often. Now I would like to show if the file aligns to soc or if there are multiple reasons for the changes. It would break the discussion if in this context I would have to switch to a completely new visualization that display a lot of data that is actually not relevant for this use case.

Having thought about it this way, I would highly recommend @silasg idea for visualization.

**Comment by ukinimod** [comment]
I think, we can close this question, as it has moved from discussion to prototyping with branch https://github.com/MaibornWolff/codecharta/tree/feature/add-temporal-coupling-visualization
